### ISSUE TITLE
Issuer Dashboard State transition

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1006]
We have several states of ETO. (Ticket on-boarding required). 
One of the states require AGA approval. After this we show in dashboard new component. 
Compaing status (New)
https://invis.io/U8MLIP1VMBQ

Once you click on the widget. (Upload Term Sheet, Upload Prospectus, Upload Pampflet)
The user get redirected to Document section.
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37?seid=5b4dd4ae178d82a9aa495047

**Comment by SergejSoft** [comment]
Related to Bookbuilding and points: https://github.com/Neufund/platform-backend/issues/672

**Comment by Moejoe90** [comment]
@SergejSoft 
Missing `On-Chain` State
Missing `Date Picker`
