### ISSUE TITLE
Freshdesk URL

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#1030]
Hi @SergejSoft  I need your help with changing our freshdesk URL, its show now https://neufund.freshdesk.com/support/home, and Marketing want it to be Neufund.support without mentioning freshdesk 

You can use this article: https://support.freshdesk.com/support/solutions/articles/37590-using-a-vanity-support-url-and-pointing-the-cname

**Comment by pstroinski** [comment]
Done
