### ISSUE TITLE
To add on setting personal info

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#1051]
On the setting we should add another square showing his personal details which he provided, this a requirement also GDPR 
SEE MOCKUP:
![accoutninfo](https://user-images.githubusercontent.com/2290474/42824210-a312b2d0-89df-11e8-99bf-281e3e50ea5e.png)
On action: Hoover Over the panel the user would following info:
(Same as we have with ETO landings)

Full name 
Date of birth 
Address
Income above 5000 Euro - Yes/No
Design will be provided by @falinebambi or Mikolaj. 
´´´´´
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37?seid=5b72eb7f841d365393b6c911

**Comment by huesforalice** [comment]
@SergejSoft this is a frontend ticket, all the api endpoints needed for this are in place

**Comment by mpneu** [comment]
Added designs in Zeplin

**Comment by SergejSoft** [comment]
Please make sure this component is displayed only for individuals. We simply do not show this for companies. 
Ping Dave on slack to get API we connect to get data. (KYC API)
