### ISSUE TITLE
Issuer Dashboard. Document Section. IPFS

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1056]
Document Section has 3 elements. 
1. Template. (Not filled documents which users could always use as a reference.)
Functionality: Download only.

2. Prefilled template (We use ETO forms + KYC to prefill some forms)
Functionality: Download only.

3. Signed documents (pdf) where the user uses prefilled templates and sign and upload them. 
Functionality:
 Upload. (Notification in Back office that document is uploaded).  Admin can accept this document. 
Delete. In some states the user could have delete and re-upload the document. Once admin has review and confirm documents no changes possible. We simply hide delete button for these documents. 

Important! This is first version of document section. Some stuff is already done by @lizonp 
https://platform.neufund.io/documents

Pls. update with newest design and fuctionality. 

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37?seid=5b4dd4ae178d82a9aa495047

**Comment by Moejoe90** [comment]
Some changes 

1 - User cannot delete any file but can upload a file again at certain

**Comment by Moejoe90** [comment]
@SergejSoft Take note i added a small download header under the documents to download the document
