### ISSUE TITLE
Tooltip on mobile

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1065]
1. We need to align helper text on smal screens. 
Right now they are all a big ugly. 
Now:
<img width="671" alt="screen shot 2018-07-19 at 15 22 48" src="https://user-images.githubusercontent.com/2290474/42945169-eef3acde-8b67-11e8-8ecd-cf7e85780345.png">

New desing proposed from Kirstyn. @falinebambi pls. paste here. 

2.Pls. all add a space <br>
After the text highlighted. "valid documents must inlcude"
<img width="1043" alt="screen shot 2018-07-19 at 15 38 41" src="https://user-images.githubusercontent.com/2290474/42945909-ec68dad2-8b69-11e8-9f8f-87ae7b23de7d.png">

3. Change type in Date of Birth. It's different that the rest of the text. 
<img width="974" alt="screen shot 2018-07-19 at 16 06 47" src="https://user-images.githubusercontent.com/2290474/42947562-e040eeda-8b6d-11e8-8dd8-f5138e3ed497.png">

Proposed CSS from 
<img width="323" alt="screen shot 2018-07-19 at 15 58 30" src="https://user-images.githubusercontent.com/2290474/42947412-8f43040a-8b6d-11e8-95f6-86582e1a1e98.png">

**Comment by falinebambi** [comment]
Tooltip CSS to make it look like below: 

@media (max-width: 991.98px)
5ce0d9714f06cb0…b04.main.css:1
.Tooltip-module__tooltip-text___jFgq3 {
position: static;
opacity: 1;
 background-color: transparent;
 transform: none;
 color: inherit;
padding: 0;
box-shadow: none;
/* margin-top: .5rem; */
 /* padding-left: .5rem; */
text-transform: none;
 font-size: .575rem;
max-width: none;
width: 100%;
}

<img width="946" alt="screen shot 2018-07-19 at 16 31 56" src="https://user-images.githubusercontent.com/17235402/42949107-5287eea0-8b71-11e8-80e0-18949dbcf34b.png">
<img width="1710" alt="screen shot 2018-07-19 at 16 21 46" src="https://user-images.githubusercontent.com/17235402/42949111-553f6614-8b71-11e8-821f-13d6a11b91da.png">

**Comment by falinebambi** [comment]
DOB CSS header update: 

@media (min-width: 992px)
.FormFieldDate-module__date-field___1Yv7D .FormFieldDate-module__label___16a-n {
font-family: Lato,sans-serif;
    font-size: .75rem;
    letter-spacing: -.2px;
    line-height: 1.4;
    text-transform: uppercase;
    color: #4c4c4c;
    display: inline-flex;
    margin-bottom: .5rem;
