### ISSUE TITLE
Backoffice - File download failure

### ISSUE THREAD

**Issue by kelexa** [Neufund/platform-frontend#1076]
Hi,

This happened to us a couple of times already we get an error when opening an uploaded document. It can happen when the doc has been uploaded by the client or also when uploaded by us manually.

When I open the file it sends me to this:

![download blob](https://user-images.githubusercontent.com/40295416/43065089-0ad56d9c-8e61-11e8-87bd-a4e87466409b.jpg)

Thanks.

**Comment by huesforalice** [comment]
Prevent uploading of files other than the allowed ones
