### ISSUE TITLE
Backoffice - unprocessed documents modification

### ISSUE THREAD

**Issue by kelexa** [Neufund/platform-frontend#1101]
Hi,

Each time a client uploads a new document it should be able to be filtered on unprocessed accounts. 

We would like to have a drop down menu like this:

![unprocessed docs 2](https://user-images.githubusercontent.com/40295416/43255122-3ead5746-90c9-11e8-9bef-a0dc0aed24aa.jpg)

So that we can keep it as unprocessed selecting "New document" if other documents are still pending, or select "Reviewed" to take it out of the unprocessed list ourselves and finish the verification. The "None" option would be the default option if it's a Draft Account status.

On the main request page should look like this:

![unprocessed docs 1](https://user-images.githubusercontent.com/40295416/43254721-48b0d30e-90c8-11e8-9b81-b8cbac785ce7.jpg)

Under the unprocessed column instead of a tick we would see if it's "reviewed", "new upload", or "none" and be able to filter under each of those options.

Thank you

**Comment by shanile** [comment]
guys if this is too complex to design now in back office we can also, for now, just fix the logic by marking the account as has unprocessed documents everytime (regardless the account status) a new document was uploaded and not yet defined

**Comment by rudolfix** [comment]
Issue moved to [Neufund/platform-backend #1239](https://github.com/Neufund/platform-backend/issues/1239) via [**ZenHub**](https://www.zenhub.com/)
