### ISSUE TITLE
Page don't load

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1103]
To reproduce the bug:
Go to public view: https://platform.neufund.net/eto-public-view 
Than navigate to Dashboard or Doccuments. The page will not load. 
If you press Refresh the page loads. 
![Screen Shot 2018-07-26 at 14.24.38.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/712faef6-c7f1-4a9b-9cfb-2296567f6b1c)

**Comment by Moejoe90** [comment]
This is actually related with `PeopleSwiperWidget` not being used in the correct way

**Comment by Moejoe90** [comment]
Also in order to reproduce it correctly, you need to fill Team members and founders etc
