### ISSUE TITLE
Wallet Migrate. 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1141]
Wallet Upgrade and Wallet Update will be implemented after running all the test around Sep. But we must prepare view for this already now.

No feature flag neeed. Could go straign to production.

Check ballance box in settings could be visible for all type of users. 

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37?seid=5b61beade8872b396604aab0

To show the ICBM Balance and verify the ICBM Wallet adress we already have a function which you will need to connect the input field. 
Pls. ask @krzkaczor. He knows  where it is.

**Comment by Moejoe90** [comment]
@SergejSoft 
Visuals are not fully implemented
