### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1153]
User Dashboard. With Dave concept driver and Mostafa Commando Force.

We are not using Django for this Dashboard. Customly built simple dashbaord. 
Use ETO Dashboard as a point of refference. 

List of users which reads data via API. 
Feature list:
Search by: 
Filtr by:
User history log:
Update user type: Drop down switch.
Once we have a skeleton we could add features as needed. 
___________
Outdated ticket. 

We need a possibility for Customer Agent is able to change User type: Investor/Issuer.

Some people use a wrong login route and than not able to change it back. 

This feature is needed under business request:
https://backoffice.neufund.org/admin/kyc/businessrequest/68a3fc13-d252-4683-88ac-bfacf769be17/change/

I suggest a simple drop down with the possibility to edit the user type.
 ![investorissuer.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/051be085-80cd-47c2-b0d0-ddc78544bf53)

**Comment by rudolfix** [comment]
Issue moved to [Neufund/platform-backend #850](https://github.com/Neufund/platform-backend/issues/850) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rudolfix** [comment]
Issue moved to [Neufund/platform-backend #851](https://github.com/Neufund/platform-backend/issues/851) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rudolfix** [comment]
Issue moved to [Neufund/platform-backend #852](https://github.com/Neufund/platform-backend/issues/852) via [**ZenHub**](https://www.zenhub.com/)
