### ISSUE TITLE
Proposed changes to Project structure

### ISSUE THREAD

**Issue by huesforalice** [Neufund/platform-frontend#116]
After reviewing the existing project code, there are a few changes I would suggest making to the project structure, to clearer separate certain concerns. This should make it clearer where to put stuff and easier to find things. I'm happy to do this, but I don't want to mess up any other pull requests and branches you are currently working on.

### Extraction of "Services", e.g. parts of the code that have side effects
I would move all the code that interoperates with entities outside of the browser into their own top-level 'services' folder. Candidates for this are for example all the things that call out to our APIs (SignatureAuthApis.ts) or the stuff that deals with the Ethereum Connection (BrowserWallet.ts, PersonalWeb3.ts). The actions and reducer files should stay where they are, we are just aiming for a clean visible boundary between code that defines application flow/state and the external services which can be injected into this. Where something like 'notifications' goes is debatable, but probably not in the modules folder.

### Separation of re-usable components and one-time components
I would suggest having one folder for all the re-usable components like LoadingIndicator or HighRestImage and a different folder for all the top-level pagelike components, such as the WalletSelector. In the future the one-time components will most likely be dynamically loaded, so we can make use of speed improvements with code splitting.

### Proposed project structure

```
/assets # keep as is
/config # move all config (env variables) related code here
/components # have reusable components in here
/containers # have pages and all subcomponents in here, e.g. dashboard, login page etc, App and all its subcomponents could have a folder here too
/middleware # move all middleware here, this includes the injectify, but also the probably soon to come crash reporting etc.
/modules # have state and actions in here, move external services out of here
/services # have external services here, such as api access and ethereum connections
/styles # keep as is
/utils # keep as is, move utils that are only used by one service into a utils subfolder of that service
```
Apart from this, 'storeHelpers' are actually 'actionHelpers, and could be moved to the /modules or a /module/utils folder. 'getContainer', is actually the dependencyInjection config, so it probably should be named accordingly :).

**Comment by krzkaczor** [comment]
As we discussed IRL I am a little bit worried about low cohesion if we split project not by features but by type of a file. We did it in https://github.com/Neufund/commit.neufund.org/tree/master/app and I think we all agree that we hated it ( i mean ppl that worked on it :D) .

Let's discuss all these things IRL and then came up with exact plan.
