### ISSUE TITLE
Update API. CoinMarketCap

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1161]
CoinMarketCap - `The Public API will be taken offline on December 4th, 2018. Please migrate your application to the free tier of the Professional API.`

**Comment by banciur** [comment]
@SergejSoft this is not 2 hour task. It will require rewrite of our backend components and bigger change on neufund.org

**Comment by bobbyong** [comment]
You may consider CoinGecko free API - https://www.coingecko.com/api/

**Comment by banciur** [comment]
Thanks @bobbyong that's interesting service we will take a look.
