### ISSUE TITLE
Change Maximum ticket size: Unlimited

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1174]
![Screen Shot 2018-08-06 at 15.05.39.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/4bc173f1-423a-4434-a4e7-4d97a485c5b2)

Change 25000 to Unlimited.

**Comment by Moejoe90** [comment]
@SergejSoft This is already implemented I will close it
