### ISSUE TITLE
Breaking change in Metamask (will stop working) on November 2nd

### ISSUE THREAD

**Issue by banciur** [Neufund/platform-frontend#1199]
`On November 2nd, MetaMask and other dapp browsers will stop automatically injecting web3. Instead, dapps should request access using a new postMessage API.`

more info - https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

**Comment by rudolfix** [comment]
here's how to test it now. "Preparing your dapp" section in the link above

# this is important to be solved now

**Comment by glupiawymowka** [comment]
confirmed access for our platform, logged it, did a transaction, YAY

![image](https://user-images.githubusercontent.com/18315589/48135420-30b96780-e29d-11e8-9d01-c37259b82cd8.png)
