### ISSUE TITLE
Make action definitions less verbose

### ISSUE THREAD

**Issue by huesforalice** [Neufund/platform-frontend#120]
This is just a proposition. With the right type of type-inference, it is possible to define actions by just writing the action creator. This approach, when done right, will still retain fully typed actions, but with about half, or even a third of the code needed to define them.

**Comment by krzkaczor** [comment]
@huesforalice go ahead and show us some code! :D I am all for reducing boilerplate, even though I prefer that my function have explicit return types (I guess this is the source of boilerplate saving).
