### ISSUE TITLE
implement proper transaction signers for LightWallet and Nano Ledger

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1218]
transaction signer should parse transaction data and show similar information as Metamask. On top of that we should use Universe contract to check if "to" field is a known contract and display it's name. If not - a warning.
If we known name we also know ABI so we should decode "input" field and if it's a token transfer we should provide information: from to which token, amount etc.

This is good to have! Sooner or later our wallets will be more general purpose

**Comment by glupiawymowka** [comment]
this is just an idea that might not be valid anymore, but please check @andywalton
