### ISSUE TITLE
implement signTypedData for LightWallet and Ledger

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1219]
We should implement similar UI like Metamask
On top of that we should be able to detect if we are signing JWT from known service or it's something else. In second case we should display warning (or prevent signing altogether)

**Comment by rudolfix** [comment]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md

Please also note that metamask will soon switch to other standard of connecting

**Comment by pstroinski** [comment]
Do we still plan to implement it?
