### ISSUE TITLE
Bookbuilding

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1221]
Make sure we have START/STOP Book-building by end of SEP.

**Comment by falinebambi** [comment]
Start bookbuilding zpl.io/VxYmN0W
Stop bookbuilding zpl.io/V1qyE4w

@SergejSoft

**Comment by SergejSoft** [comment]
Updated design: https://zpl.io/a7Ed5eK
Once you ready with this ticket, I would love to call you to onboard with details of this functionality.
