### ISSUE TITLE
 Withdrawal Transaction with Ledger

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1227]
Pls. test in DEV environment withdrawal function of the wallet. 

We were testing this with Metamask and need to make sure it also works with Nano L.

Things to watch out. 

Pending transaction, 
Reverted transaction.
Successful transaction.

**Comment by banciur** [comment]
I tried to use ledger for withdraw on .io - it's not working correctly.
Generally transactions are sent but we are doing something wrong there maybe some race condition around ledger handling. Hard to tell without running it locally. 
- Amount to send shows placeholder 10.5 - that dosen't make sense to me
- Popup in amount to sent [eth] is empty
- I got some notices about loosing connection to web3 during process (red toast in top right corner)
- Once it showed me failure despite tx being sent
- Once it tried to send 
- Popup says "sign message" but we are not singing message but transaction
- Spinning ETH symbol is broken

some ideas
- We could add eth addres validation to "to" field 
- We could add ethscan link to "to" field
- We could add validation (positive number) to amount to send)
- We could add "send whole balance" functionality to amount to send. Remember we need to take into consideration gas amount and gas price
- We should not give ability to change gas limit or add some validation
- We could give ability to increase gas price.

**Comment by Moejoe90** [comment]
From a technical point, the ledger now is working all race conditions are solved. 
@banciur Can you raise a new ticket with you're suggestions as I will close this when the pr that handles technical side of sending transactions is solved.
