### ISSUE TITLE
 Bank Transfer Details

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1235]
Related to:#1212

https://zpl.io/aX4GyZM

The real banking details will be coming form config file so please put some rundom iban and bic. 

![screen shot 2018-08-17 at 12 58 39](https://user-images.githubusercontent.com/2290474/44263073-c5bc3f80-a21d-11e8-96a4-52b19266e8a3.png)

**Comment by rudolfix** [comment]
Guys we need to protect IBAN from any form of error when typing or setting textual data.
I will provide you IBAN in two forms:
1. a display form as above
2. a sha3 hash of it

before displaying IBAN calculate sha3 hash and it does not match the declared hash display "wrong IBAN" in red.

I'm assigning myself to this ticket as well. please make me to review PR

thanks!

**Comment by rudolfix** [comment]
Few explanations
1. the gas cost of direct bank transfer is 0 - for your calculations in the calculator
2. on the screen above user should see a checkbox information that says, "I Agree to add 10 EUR to investment amount that will be converted into ETH gas stipend for future transactions on the platform"

if checkbox is checked you add G to reference at the end. see later in the ticket

Then `Amount to Send` is investment value + 10 euro. the algorithm to compute reference number is described in here:
https://github.com/Neufund/platform-backend/wiki/5.4.-Use-Case-EUR-T-deposit#definitions

to convert ethereum address into base64 you need to convert it into bytes and then bytes into base64. do not encode hex string into base64. please refer to @huesforalice, he implemented it on the backend

**Comment by glupiawymowka** [comment]
*to recheck on stage due to bizzare results on .io*
