### ISSUE TITLE
Public View Design update

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1245]
@lizonp pls. wait till design are finished and passed as a link in the ticket.

Pls. use this link as a reference to work on ETO and Public View Fixes.

https://docs.google.com/presentation/d/1-BReyNlQlIGC5kH3DCvzt0XxcKf2goKse7lzYn4GhlQ/edit?usp=sharing

**Comment by falinebambi** [comment]
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5b7d8ac0bd131d7dc95ddbfb 

zpl://project?pid=5a8a92c89c1a166a6a6e8f37&seid=5b7d8ac0bd131d7dc95ddbfb
