### ISSUE TITLE
External widget for book building (3rd Party)

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1271]
We need a special widget that could be placed on public landing pages or website of the partners.

Strip View 3rd party *CTA "Register"> Public View *CTA "Register" > Registre> Platform use.

@falinebambi Please paste in this ticket invison link.

**Comment by mpneu** [comment]
https://projects.invisionapp.com/d/main#/projects/prototypes/15287103

**Comment by desfero** [comment]
@SergejSoft probably should be mo
