### ISSUE TITLE
High risk countries - Update list of countries to block account creation.

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#1275]
We have a new  High risk countries list which was published by FATF (The Financial Action Task Force), the list contain all the jurisdictions with strategic AML/CFT deficiencies that have not made sufficient progress in addressing the deficiencies or have not committed to an action plan, every 3 months they publish new list.

**KYC Flow**
The list: 
Democratic People's Republic of Korea (DPRK)	
Ethiopia		
Iran	
**Pakistan**	
Serbia		
Sri Lanka		
Syria		
Trinidad and Tobago		
Tunisia		
Yemen
USA 

Please make sure that these countries are being limited from opening an account. 
If one of this countries is selected we need to show alert preventing them to register.

**Comment by Moejoe90** [comment]
This is not a bug btw its a change

**Comment by shanile** [comment]
I tagged it as a bug because the current list is also not blocked from registration, we were able to registered
