### ISSUE TITLE
Portfolio View and User Behavior after investment. Connecting fields

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1276]
Final Design is done by @falinebambi 
Bookbild>Invest>Investment Flow>Potfolio

View are done. Need to connect al the fields. 
https://zpl.io/V1qn0Jm

**Comment by rudolfix** [comment]
![image](https://user-images.githubusercontent.com/17202864/46013042-47c83f80-c0cb-11e8-85a3-038ae7dc629d.png)

please diregard this one and create another ticket. this row is created from pending transactions endpoint from transaction of type INVESTMENT but you do not store additional metadata there so it will not work now

**Comment by rudolfix** [comment]
procedure to generate a list is as follows
1. use eto_listing endpoint to get a list of all ETOs that are in the on_chain state. for efficiency you can remove all etos that do not have a start date
2. for each `eto_id` obtain `ETOCommitment` instance and call
```
function investorTicket(address investor)
        public
        constant
        returns (
            uint256 equivEurUlps,
            uint256 rewardNmkUlps,
            uint256 equityTokenInt,
            uint256 sharesInt,
            uint256 tokenPrice,
            uint256 neuRate,
            uint256 amountEth,
            uint256 amountEurUlps,
            bool claimedOrRefunded,
            bool usedLockedAccount
        )
```

* BALANCE - take it from `equityTokenInt` , this is a token with 0 precision so you do not have to convert balance from wei. it's always integer as you get it
* VALUE EUR - equivEurUlps
* PRICE_EUR - BALANCE/VALUE EUR
* NEU_REWARD - rewardNmkUlps. it's just a number. not +-, just display the number.

now: if
claimedOrRefunded == true then display the row in YOUR ASSET list
false - display it in pending asset list

this parameter tells you if investor already claimed or refunded tokens.

3. PENDING ASSETS status: depends on the timedState() of ETOCommitment like on public profile
* Whitelist/Public - let's just display a countdown timer here to the end of public period. please disregard the green bar for now.
* in refund state display REFUND button. it should launch an ethreum transaciton `ETOCommitment.refund()`
* in claim and payout state display CLAIM TOKENS button and launch `ETOCommitment.claim()`

launching those transactions is secondary objective and I propose to split those into two separate tickets

![image](https://user-images.githubusercontent.com/17202864/46015822-8104ad80-c0d3-11e8-90be-f0c791d0202d.png)

**Comment by desfero** [comment]
@SergejSoft this issue is only about connection `Reserved Assets` and `Your Assets`?

**Comment by SergejSoft** [comment]
Reserved Assets - is the equity tokens that the investor paid for. The transaction is done, but the ETO campaign is still running. So we can't release this asset because we don't know if the campaign will reach the minimum threshold. 
So, in fact, it's a state of the equity token.
