### ISSUE TITLE
Backoffice - to show IP from registration on all applications

### ISSUE THREAD

**Issue by kelexa** [Neufund/platform-frontend#1284]
Hey,

At the moment we can only see the IP country from where they registered from on the clients that choose to do manual verification. We should be able to see it also on outsourced accounts, and drafts. 

Thanks.

**Comment by rudolfix** [comment]
Issue moved to [Neufund/platform-backend #1240](https://github.com/Neufund/platform-backend/issues/1240) via [**ZenHub**](https://www.zenhub.com/)
