### ISSUE TITLE
Add sentry to Frontend

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#1288]
Adding sentry reporting is a good start for error reporting. 

As a start it can be added only to our dev environment with a feature flag this will make it cheaper and also give a chance of good error reporting when a tester or a product owner breaks something and we need full information. 
also
Add ENV file for sentry 
```
NF_SENTRY_DSN=
```

**Comment by desfero** [comment]
The scope of this story is:
1) Add sentry reporting to a frontend
2) Report redux actions/state to sentry (https://docs.sentry.io/clients/javascript/integrations/react/#redux)
3) Catch saga errors and forward them to sentry (https://docs.sentry.io/clients/javascript/integrations/react/#redux-sagas-middleware)
4) Implement react error boundaries and display a friendly error message in case of any error during react render phase (example: https://github.com/desfero/beer_guru/blob/master/packages/beer_guru/src/components/App.js#L22, docs: https://reactjs.org/docs/error-boundaries.html)

**Comment by desfero** [comment]
@rudolfix can you please create two projects (dev+staging and production) for frontend on sentry? (or give an access to do that to @Moejoe90 or me :))
