### ISSUE TITLE
Implement visual regression on full views with Cypress 3

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#1290]
Cypress 3 has a good feature of screenshotting full views, this can be the bases for a good visual regression tool that.

`Edit:`
After the initial merge with code checks implement an initial test that uses screenshotting with cypress and code checks

**Comment by desfero** [comment]
@Moejoe90 that make sense and it will really help with changing any kind of styles. 
We need to think about all the problems that can arise. For e.g. using fixtures in tests can break visual regression as wallet amount will not always be the same.

**Comment by Moejoe90** [comment]
This should be easy now after migrating to codechecks 
Mostly will be done by chris

**Comment by Moejoe90** [comment]
@desfero Good that you mentioned this point. as per the meeting we will use component blacking to hide any components that would change due to fixtures or anything

**Comment by Moejoe90** [comment]
This is an example of how how to implement this feature 
https://github.com/codechecks/vis-reg-cypress-example
