### ISSUE TITLE
Nominee field

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1296]
There is now a ethereum adress in the Neuminee field. 

<img width="566" alt="screen shot 2018-09-05 at 18 09 51" src="https://user-images.githubusercontent.com/2290474/45106426-f44f7b00-b136-11e8-97ee-8254763f466c.png">

**Comment by lizonp** [comment]
@banciur Please make that `nomenne` field as a full name accessible for us.

**Comment by lizonp** [comment]
@SergejSoft It's hardcoded for now
