### ISSUE TITLE
Better design for message signing

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#1299]
![image](https://user-images.githubusercontent.com/23242822/45148850-7f2c8600-b1c8-11e8-871a-fae5d231b107.png)
![image](https://user-images.githubusercontent.com/23242822/45157642-06d2be80-b1e2-11e8-9415-a6d2079820b2.png)

Do we have designs for this view?
@SergejSoft @falinebambi

**Comment by falinebambi** [comment]
zpl.io/b6vKgQW 
zpl://screen?sid=5ba3a725983644a999cb33c6&pid=5a8a92c89c1a166a6a6e8f37
![signing_transaction](https://user-images.githubusercontent.com/17235402/45823676-7a9abe00-bcee-11e8-99d8-07f71e2e1a92.png)

**Comment by falinebambi** [comment]
zpl.io/b6vKgQW
zpl://screen?sid=5ba3a725983644a999cb33c6&pid=5a8a92c89c1a166a6a6e8f37
![signing_transaction_error](https://user-images.githubusercontent.com/17235402/45823951-280dd180-bcef-11e8-8054-dd18ddccac6d.png)

**Comment by falinebambi** [comment]
@Moejoe90 @SergejSoft please see above. Let me know if you have any questions.

**Comment by SergejSoft** [comment]
@lizonp, did you use the fixed component of ETH spinner. It's also related to: #1362
