### ISSUE TITLE
Register Button Doesn't disable when when the process is Active

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#1308]
![image.png](https://images.zenhubusercontent.com/5a71a3454b5806bc2bc504bf/8164b7c9-7ff3-4e9a-a239-0623239b353a)

Button should be disabled and `Restore` instead of `Register`

Note: Take caution that this element is shared with Register Flow so the button should be register when in register flow and recover when in recover flow

Please rename the URL ROUTE to restore/seed

Locale heper text to rewrite by Marlene @meneramandarin 

Page title: Restore you Light Wallet.

**Comment by meneramandarin** [comment]
does the text need to get shortened or what's the issue? @Moejoe90

**Comment by meneramandarin** [comment]
got it. how does the flow for the user look like? they provide their email and then we send them a link or anything else they need to know?
