### ISSUE TITLE
Renable visual regression - Fix Storybook

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#1324]
Storybook is having problems with screenshots again and timeout. It's failing at some component 
Check storybook more specifically 
` yarn storybook:screenshots `
Once it runs re-enable visuall regression via Danger CI. 

Take into note there is a step that needs to be done in the end where only a user with Admin role on github can do. 

Go to Branches and re-enable danger

**Comment by trival** [comment]
visual regression can be reenabled after https://github.com/Neufund/platform-frontend/pull/1327 is merged
