### ISSUE TITLE
Transaction Status Icon. Header

### ISSUE THREAD

**Issue by falinebambi** [Neufund/platform-frontend#1326]
We need to design an icon that would always show last-current transaction which would open transaction dialog (Pending, Revert, Success).

#1957 

**Testing notes**
This under the hood use exactly the same modals that you already tested on #2610. So you can limit to a couple of transactions there is no need to test again all cases.

**Comment by falinebambi** [comment]
@Moejoe90 Designs Ready as per discussed: https://github.com/Neufund/platform-frontend/issues/1326

**Comment by glupiawymowka** [comment]
- [x] overall data visible when the user clicks on the rotating icon is correct 

![image](https://user-images.githubusercontent.com/18315589/55145695-8951aa00-5143-11e9-8ff2-7573f581ca05.png)

- [ ] when the pending transaction summary popup was open for a couple of seconds, the whole page throwed a fatal error. 
What exactly I did: 
 * logged in with a fixture, where all the transactions were unsuccessful and no signature request was sent to metamask 
* restarted metamask while logged in to this account
* moved to SPARE_1 fixture account
* did an investment 
* transaction was pending, when I clicked on the pending icon, the correct summary was shown
* after a couple of seconds, the page crashed and I can't login with this fixture anymore 

![image](https://user-images.githubusercontent.com/18315589/55148153-f8c99880-5147-11e9-952f-3699e3e4aecb.png)
![image](https://user-images.githubusercontent.com/18315589/55148183-08e17800-5148-11e9-931b-4dbcfffaa45e.png)

**Comment by glupiawymowka** [comment]
this is not happening again both on stage and dev. 
*feature ok to be released*
