### ISSUE TITLE
Hide TEST form Caree pages

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1349]
https://neufund.org/cms_resources/react-front-end-developer.pdf
and this https://neufund.org/cms_resources/back-end-developer.pdf

In the last paragraph we need to drop the test and have only this text:

**Simply apply by email to: jobs@neufund.org**

**Comment by banciur** [comment]
@SergejSoft It should be done by person that has original of this document. Then we could generate new document and reupload it.
