### ISSUE TITLE
Spinning ETHER logo is broken

### ISSUE THREAD

**Issue by falinebambi** [Neufund/platform-frontend#1362]
Spinning ETHER logo is broken on here and other places where we used it https://platform.neufund.io/

https://codepen.io/PalmBeachagency/pen/VdzQRN

![screen shot 2018-09-17 at 17 33 39](https://user-images.githubusercontent.com/17235402/45633348-da4f5a00-ba9f-11e8-802f-82366472c569.png)

**Comment by Moejoe90** [comment]
When testing with production build you can run it locally via
```yarn build:prod```
to build the production bundle then
```sh ./scripts/prod-like-srv.sh``` 
to run the server , ill add it to the ticket as well
