### ISSUE TITLE
[ETO TERMS] min value failure if below 500

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1363]
How to reproduce: 
1. Open the ETO terms form
2. Put the minimum value below 500€
3. Both on .io & .net it's failing and not saving the given values 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/83c88a6b-b402-4dd1-8003-952b947a2e9f)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/66688f16-6905-4820-b156-98ce27a415bc)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/77efe470-5846-4a98-b9fc-bdceea77697c)

**Comment by rudolfix** [comment]
Backend does not allow pledges below minimum ticket and above maximum

**Comment by SergejSoft** [comment]
I suggest to have an alern message if the user puts a value less then 500euro.
"The minimum ticket size accepted at the moment is 500 Euro"

**Comment by glupiawymowka** [comment]
It's 100 now, the message is correct and prevents saving with invalid value 
![image](https://user-images.githubusercontent.com/18315589/47917008-75fa2580-dea8-11e8-9382-9bc09a92c78a.png)
