### ISSUE TITLE
check node status on transaction submit

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1364]
in `sendTxSubSaga`
please check error cases returned by the node (Parity)
- you are out of gas
- you submitted same transaction twice
- you submitted incorrect nonce
- take other error cases from ESOP-ui and Commitment page

**Comment by Moejoe90** [comment]
@rudolfix 
I have checked btw both ESOP and commitment 

Commitment
https://github.com/Neufund/commit.neufund.org/blob/68997f767fb36095ef78dabb15f80c9f3cc645d2/app/web3/web3ErrorHandler.ts

ESOP
https://github.com/Neufund/ESOP-ui/blob/master/src/ContractComService.js#L576

They mostly deal with `Ledger` `Metamak` Errors and don't have as much other edge cases as i hoped
