### ISSUE TITLE
Implement individuals panel for 1/2 people

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1367]
Background:
On the ETO view we miss correct layout for individuals component where only 1/2 people are added.
![Screen Shot 2018-09-18 at 13.01.14.png](https://images.zenhubusercontent.com/5b8cc0d2afc56b36f3abe65a/20d2718a-fc95-4269-a181-eaea64197aa7)

Zeplin: zpl://screen?sid=5b7c2f346d8b230e716f04cf&pid=5a8a92c89c1a166a6a6e8f37

**Comment by glupiawymowka** [comment]
This is the current look. I mark is as done 
![image](https://user-images.githubusercontent.com/18315589/47439689-1e273480-d7ad-11e8-8c2b-ccb332ed525e.png)
