### ISSUE TITLE
[ETO foms] Legal info form - unclear error message + bug when saving empty form

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1370]
1. Go down till "Current share capital" field and add some values

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/ad8a9c09-560a-483f-a964-65682481b69c)

2. delete the number of %

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/bbfdf6c1-ff98-4128-ba18-dce79850e690)

3. Click "Save" when this input is empty. 
The following error will appear

![image](https://user-images.githubusercontent.com/18315589/45685634-3cfd3000-bb4a-11e8-9eed-a6ca74bb60c0.png)

**Comment by AlexeyTuboltsev** [comment]
this is connected to #2153
