### ISSUE TITLE
Manual verification first option 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1373]
Hi Kirstyn, we need to make apeling KYC page to give the user more options. 

Option 1: Choose Full VideoIdent accessible via Browser (Chrome & Firefoc) or App (Android & iOS). You will be connected to a identification specialist who will guide you through the process. This process takes about 5-6 Minutes

Option 2: Self-Service Auto Identification via App (Android & iOS). You will undergo an automated identification in about 2 Minutes

Option 3: Manuel verification. You will upload your proof of residency and ID. Could take up to 24Hours. 

<img width="1440" alt="screen shot 2018-09-18 at 16 39 02" src="https://user-images.githubusercontent.com/2290474/45695387-94f36100-bb61-11e8-810b-5c080e75419c.png">

Manual is free, so we kind of wanna make manual more appealing 
Second option cost us circa 2 euro per verification. 
1st. Option cost us circa 8euro.

**Comment by shanile** [comment]
this is my ticket that I opened yesterday and I asked the manual to be upfront can we decided on this 

Manual verification first option #1632

**Comment by SergejSoft** [comment]
@Dave for now. Let's put manual verification as the first step. and IdNOW below, so that users could pick manual verification as the default option.
