### ISSUE TITLE
KYC Beneficial owner should have validation for `Percentage Held` field

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1386]
Background:
It's possible to save ownership field as an incorrect percentage value.
![image](https://user-images.githubusercontent.com/7031578/45867355-93a17e80-bd83-11e8-8ef9-277de2e4a85f.png)

**Comment by glupiawymowka** [comment]
fixed

![image](https://user-images.githubusercontent.com/18315589/48557175-4e627e80-e8e6-11e8-9052-3ac48f33505e.png)
*tested on .io*
