### ISSUE TITLE
Fix performance problem on ETO Key Individuals form

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1391]
**Background:**
There is a noticeable performance issue on Key Individuals form when there are a lot of individuals.

**Technical notes:**
I can see that there are a lot of repeating each time input change is triggered. Need to play for `shouldComponentUpdate` or `FastField` from formik.

**Comment by Moejoe90** [comment]
As mentioned before the first step to solve any performance issue is updating formik

For example this problem
https://github.com/jaredpalmer/formik/issues/430

**Comment by SergejSoft** [comment]
@desfero  is this solved? If yes, pls. close this ticket

**Comment by andywalton** [comment]
Hi @desfero - I assume this is still a problem?

Alexey, I've added this to the Neufund Platform Multi-Product / Jurisdiction epic, will aim to plan for this time permitting in a future sprint before 15 May 2019's release. 👍

**Comment by desfero** [comment]
@andywalton it's still a problem. 
Just try to submit all fields inside key individuals form and you will see how slow UI respond to keyboard events while typing.

**Comment by andywalton** [comment]
Okay thanks for the update @desfero and for noting it's blocked. We can work on this as a nice to have in future sprints (if possible before we go live with the Multi-product / jurisdiction ETO offering).
