### ISSUE TITLE
Add percentage validation to `CURRENT SHARE CAPITAL/SHAREHOLDER STRUCTURE / CAPTABLE` fields on `Legal Information` ETO form

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1393]
**Background:**
It's possible to provide invalid percentage value and those get an API error during saving.
![image](https://user-images.githubusercontent.com/7031578/46367706-9ef78280-c67e-11e8-83f3-97baa5aabcd6.png)

**Technical notes:**
Please think about building something reusable to validate percentage value (as we don't have anything right now :( ). Keep in mind that there should be an ability to provide different valid percentage values (for e.g. from 1 to 99% or 0-100%).

**Comment by trival** [comment]
I enabled customization of yup validators with additional test in the upcomming withdraw validation PR, so this should be trivial to do
