### ISSUE TITLE
Investment flow: ICBM Wallet.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1397]
Please make nEUR wallet value inactive. (disabled) So people don't get consused. 
I will onboard you about this ticket.

**Comment by rudolfix** [comment]
Locked Account wallets are visible if investor has balance in them. The responsible contracts are:
1. `ContractsService.euroLock` for  euro locked account
2. `ContractsService.etherLock` for ether locked account

on both you call `transfer` function exactly as with the token. (three argument one). everything works like as with the token.

for testing we have a fixture with both locked accounts. the address of the use fixture user `0xDf5F67E6e4c643a2ceD1f9De88A5da42E1507eFD`

**Comment by rudolfix** [comment]
You can also re-ping backend to the newest build to have tested locked account code.
