### ISSUE TITLE
small fix. Public view

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1402]
1. Logo got narrowed.  Equity token logo looks fine. But General logo view got squashed. 
2. Youtube preview image is still not appearing. 

![Screen Shot 2018-09-24 at 15.50.32.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/5939d0f9-76a9-4686-9f10-8e398085906d)

**Comment by lizonp** [comment]
@SergejSoft that logo image has to bo square. I've checked it, it has wrong size
