### ISSUE TITLE
new updates are erased when there is backend error when saving

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1411]
We should not close the form view before it's saved correctly on backend. Right now form is closed and we go to dashboard then it's saved and we've got an error message.

This is bad UX and needs to be fixed ASAP

**Comment by glupiawymowka** [comment]
Reopening this issue as happened to me again (tested with Metamask)

1. Went to "investment terms" 
2. entered "1" in all obligatory fields
3. saved

there is a popup that saving my ETO data failed, throwing me back to forms. Entered data is gone
![image](https://user-images.githubusercontent.com/18315589/48126936-ceec0400-e282-11e8-9518-99dde0848919.png)
