### ISSUE TITLE
Key Individuals

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1414]
https://platform.neufund.io/eto/registration/key-individuals)

The forms is not saving without all required fields to be filled. 
Now, most of the offered fields don't have individuals and only offered as on option. 

Solution: Show team and the rest of the form by clicking (+).

TODO: make sure the form is saving partially even if users made mistake in the following steps.
Example: Team if filled, users clicks (+) to add some Partners but decide to save the form. 
We could show an error, but Team members need to be saved.  This prevents users from filling the form again form the beginning.

**Comment by rudolfix** [comment]
Please also note that `role` field is optional. What we need is an avatar and a name

**Comment by desfero** [comment]
@rudolfix  ok, so need to change validation as the role was set to `required`. So an avatar should be also as a required field?

**Comment by desfero** [comment]
```
TODO: make sure the form is saving partially even if users made mistake in the following steps.
Example: Team if filled, users clicks (+) to add some Partners but decide to save the form.
We could show an error, but Team members need to be saved. This prevents users from filling the form again form the beginning.
```
@SergejSoft it will add additional complexity as we then filter and save only individuals with `name` and `avatar`. I don't think it's worth to add it as it's not something we usually do on any web forms. If there is an error user will be notified through error message where he can decide whether to remove individual or fill required data for that individual.
