### ISSUE TITLE
INVESTOR SETTINGS - show "your identity on Ethereum" badge

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1424]
we have KYC finalization done on blockchain. this is one of the coolest features we have. we should Ethereum Identity of the user in the same box we show KYC status

@falinebambi you can surely thing about smth cool. blockchain state has 4 flags we maybe can use some icons?
- verified (or nor)
- qualified investor (or not)
- verified bank account (or nor)
- account frozen (or not)

![image.png](https://images.zenhubusercontent.com/5a72da804b5806bc2bc52ecc/fcd358d9-ffa8-4122-9142-16b3c5cb7dad)

the main are is typically occupied by verification data (for individual investor), but we have a whole top

**Comment by pstroinski** [comment]
Do we plan to present status on the dashboard? If yes we need some designs

**Comment by Moejoe90** [comment]
We need to check if we will implement this ticket otherwise we should close

**Comment by Moejoe90** [comment]
Discussed with @andywalton closing for now
