### ISSUE TITLE
KYC Treshholds and Investment Logic

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#143]
User logic required for KYC flow.

For ETO below 2.5M (Crowdinvestment)
KYC form question: User needs to confirm that they earn 5K or have asset 100K. (I hereby confirm that I have 5K Netto income or 100K in assets)
If the user confirms he is able to invest up to 10K in ticket side. (Equity token value). 
If not user can invest than 1K (Equity token value).

For ETO above 2.5M
Users are not limited to any limits.  (Prospectus needs to be downloaded)

**Comment by huesforalice** [comment]
The KYC part of this is done, that means the question is asked
