### ISSUE TITLE
wallet recovery phrases are not checked on "SEND WORDS"

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1432]
![image](https://user-images.githubusercontent.com/17202864/46111336-e6958e80-c1e6-11e8-8760-21892c84a255.png)

phrases are checked when I already enter e-mail and password which is way too late.

see #970

**Comment by Desperado** [comment]
add proper bug description @Desperado @glupiawymowka

**Comment by pstroinski** [comment]
Related to #970

**Comment by pavelneu** [comment]
Tested on Chrome, Firefox, Safari.

Checked:
recovery wallet with right seed phrase,
wrong seed phrase,
changing wrong words to the right ones.

**Comment by glupiawymowka** [comment]
tested on stage (we will need to change the message but besides it works fine)
