### ISSUE TITLE
possible race condition on permission escalation

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1436]
in documents view. I upload termsheet. There's permission escalation. New JWT is obtained. HOWEVER: in ~50 cases the call to upload document is done on not updated JWT. I can provide backend log.
It basically says that required permission is not in JWT

I think we do not wait for new JWT to be written to storage before api call is done to upload

**Comment by Moejoe90** [comment]
@rudolfix 
Can you add steps to approx reproduce this bug? 
I'm having a hard time reproducing this
