### ISSUE TITLE
UI for reverted transaction modal not implemented!

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1440]
![image](https://user-images.githubusercontent.com/17202864/46172745-954bd480-c2a4-11e8-93f7-ee2658c6672c.png)

where is our animation???

**Comment by rudolfix** [comment]
![image](https://user-images.githubusercontent.com/17202864/46174785-528cfb00-c2aa-11e8-92d5-8f6e77c5324b.png)

**Comment by trival** [comment]
@AlexeyTuboltsev this can be done in the component. The case for the REVERTED_TX error needs to be enhanced! the screen with the layout can be found on zeplin

**Comment by AlexeyTuboltsev** [comment]
This can only be done after #1526 is merged

**Comment by Moejoe90** [comment]
@AlexeyTuboltsev There is no need for merging #1526 it's not connected to this task really. The error case is already there you just need to show this case when an error occurs

**Comment by AlexeyTuboltsev** [comment]
somebody fixed it already
