### ISSUE TITLE
Transaction metadata is not submitted to backend - UI implementation impossible

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1443]
for WITHDRAW we have all data already in transaction (where we send and the value)

for INVESTMENT
* eto address
* amount
* currency

must be stored so we can implement this
![image](https://user-images.githubusercontent.com/17202864/46174876-87994d80-c2aa-11e8-8908-0d7a273245f5.png)
and this
![image](https://user-images.githubusercontent.com/17202864/46174988-c62f0800-c2aa-11e8-9594-9852fe7bf4bc.png)

**Comment by desfero** [comment]
I'm closing this one as this a generally duplicated issues
