### ISSUE TITLE
Create a general gasEstimation utlity method

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#1448]
**Background**
Estimating 

**Todo**
The method should take a transaction as input and the percentage of gain
```
contractsService.icbmEuroLock.migrateTx() 
``` 
For example and then add a specified percentage to the estimated gas cost as

**Comment by trival** [comment]
I am adding configurable gas cost percentage in https://github.com/Neufund/platform-frontend/issues/1475

**Comment by Moejoe90** [comment]
Ok then @trival I assigned you to this since you are already working on it. 
close it if you think it should be closed

**Comment by Moejoe90** [comment]
@trival This will be closed as is the same ticket
