### ISSUE TITLE
INVEST button should be only visible for users with valid on-chain KYC claim

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1459]
This ticket has two parts (and you can split it):

- [x]  PART 1
1. add new singleton contract to `ContractsService` instantiated at startup. The artifacts is `IdentityRegistry` and you can find it here
2. add a method to obtain identity claim for currently logged on user and deserialize it
https://github.com/Neufund/platform-contracts/blob/master/contracts/Identity/IdentityRegistry.sol#L36

and deserialize it into following record
https://github.com/Neufund/platform-contracts/blob/master/contracts/Identity/IIdentityRegistry.sol#L15
we have deserialization procedure in our test suite:
https://github.com/Neufund/platform-contracts/blob/master/test/helpers/identityClaims.js

- [x]  PART 2
Show INVEST button only if the claim `isVerified` IS set and claim `isAccountFrozen` IS NOT set

when to load claims? we should probably load ethereum claims together with checking backend claims (even in the same saga....)
it's also connected to this ticket #1422 #1423 #1424

**Comment by glupiawymowka** [comment]
looks good
![image](https://user-images.githubusercontent.com/18315589/48912303-87b26580-ee75-11e8-9323-353544c26bf8.png)
