### ISSUE TITLE
when estimating gas add configurable overhead

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1465]
in transactions for which we estimate gas, make sure that it goes through one saga so we have one place where gas is estimated.

please implement configurable overhead that we always add to estimated gas. keep it in ENV

let's say if GAS_OVERHEAD is 0.5 we add 50% to estimated gas and this value is returned

**Comment by rudolfix** [comment]
also connected to #1448

**Comment by trival** [comment]
adding this while working on https://github.com/Neufund/platform-frontend/issues/1475
