### ISSUE TITLE
Investment flow fixes

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1473]
- [x] hide ICBM wallets with zero balance. 
![image](https://user-images.githubusercontent.com/2290474/46348271-bfa7e400-c64e-11e8-8152-ecc2d7d8f7a5.png)

- [x] Vertical scroll bars. ??? let's think what  could be an option here.

- [x] Number formating.
![image](https://user-images.githubusercontent.com/2290474/46348440-4eb4fc00-c64f-11e8-99df-7e6133620c95.png)

- [x]  Remove helper text:
![image](https://user-images.githubusercontent.com/2290474/46348530-90de3d80-c64f-11e8-9578-81abbfbbeb29.png)

- [x] Make error message orange like everything else. 

- [x]  gas handlign to enable transaction,. 

1. 1.	I spent all my funds from Investment ETH Wallet
2. 2.	Now I select ICBM Wallet. There is no money for gas
3. 3.	No error message is displayed! 
However INVEST button is inactive so you probably detect this situation but do not show it

- [x] Direct Bank Transfer does not require gas! But you are blocking me: INVEST button is gray and you say I do not have ETH

**Comment by glupiawymowka** [comment]
Invest entire wallet balance
1. When I click the button first, it wants to literally send the whole amount (I guess the button is inactive as there's nothing left for gas)
2. only when I click on Invest entire balance button again, the proper amount shows up and I can invest

1. 
![image](https://user-images.githubusercontent.com/18315589/49162216-b3789400-f32a-11e8-83cf-9b032e76904c.png)

2. 
![image](https://user-images.githubusercontent.com/18315589/49162853-174f8c80-f32c-11e8-8fdb-0bd32a75ccc2.png)

**Comment by glupiawymowka** [comment]
this problem doesn't repeat now, solved
