### ISSUE TITLE
Refactor Forms

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1484]
Background:
There are places in forms that need to be refactored so forms error messages/validation can be reused.

- [ ]  Create `FormRadioGroupField` that can be used to generate radio groups so we can stop repeating each time the same code (for e.g. `Eto Terms` form `enableTransferOnSuccess` can be used as a base implementation)
- [x]  Replace all error messages by `FormError` component (like I did in `FormField` here https://github.com/Neufund/platform-frontend/pull/1487/files#diff-898555fd97cfc464d7f31f650ee2c78cR113)
- [x]  `FormLabel` should use `label` tag for correct usability / semantic / accessibility
- [x]  Create own version of `MaskedInput` that will provide thorough `render` prop our `Input` component so any change to `Input` styles change `MaskedInput` style 
 - [ ] `FormRangeBase` add label and error message https://github.com/Neufund/platform-frontend/blob/99cc39929cdb0e6b8fc1090d931aaba2c068370c/app/components/shared/forms/form-field/FormRange.tsx#L96
 - [ ] Refactor `FormFieldDate` to only call `onChange` when all values where provided correctly (date, month, year) (see https://github.com/Neufund/platform-frontend/pull/3147#discussion_r296647689)

**Comment by pstroinski** [comment]
To verify with the formik PR

**Comment by Moejoe90** [comment]
This is done in theory with the Formik PR
