### ISSUE TITLE
Calculate timeline pointer in campaigning state

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1497]
Background:
Currently, ETO timeline campaigning state day pointer is always set to a constant value.
![image](https://user-images.githubusercontent.com/7031578/46521098-bb620d80-c87e-11e8-90b7-8068f26668e4.png)

But if the dates are know we can correctly calculate date pointer.

**technical details**
* We can calculate the pointer only when we know start date (returned by the contract)
* We known the whole span of the ETO in seconds and also in pixels
* We can calculate the visible span before the WHITELISTED starts in pixesl and we know how many seconds it covers
* If current date < start of WHITELISTED - calculated span then we display as on the image above (initial position)
* if we are in range we start to move the cursor

This is rough idea implement something akin to this. The cursor starts moving when we are in displayed range

**Comment by SergejSoft** [comment]
is it still relevant?

**Comment by desfero** [comment]
probably yes, campaigning pointer position is still hardcoded on timeline

**Comment by rudolfix** [comment]
here's test case on `io` where indicator should not be "parked"
https://platform.neufund.io/eto/view/LI/ce390a89-be03-45a6-9360-af7d1e019085

**Comment by glupiawymowka** [comment]
tested on stage
