### ISSUE TITLE
replace fufu on bank transfer investment summary with aquisition document download

### ISSUE THREAD

**Issue by trival** [Neufund/platform-frontend#1511]
The link should be the same as in the normal investment summary dialog. Title should be also: "Download Reservation Agreement"

**Comment by Moejoe90** [comment]
@trival this is a replica of this 
https://github.com/Neufund/platform-frontend/issues/1365

**Comment by trival** [comment]
> @trival this is a replica of this
> #1365
> No need for this ticket

It is new, the other ticket is already closed
