### ISSUE TITLE
investment flow - when converting from one currency to another - mind the roundings

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1515]
per ticket #1514 we should always convert currencies with wei precision. please make sure you call all smart contracts methods with wei precision. examples
1. someone enters ETH amount and you call `calculateContribution`
2. someone enters EUR amount and you call `transfer` on an Ether token

however we should not display wei precision: no one will understand values with 18 digits after dot.

1. display EUR with two digits precision
2. display ETH with four digits precision

**always round up to the required precision to be on a safe side**

this is particularly important for direct bank transfer where amount will be copied to clipboard and we need to make sure that required number of tokens will be bough

**Comment by trival** [comment]
done, all the rounding is done as suggested.
