### ISSUE TITLE
[BUG - IMPORTANT] invest entire balance - gas cost incorrectly added ^

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1517]
Please follow the same rules as with the investment calculation

1. when investing from any of ICBM Locked Accounts - you SHOULD spend entire wallet balance up to a wei precision: all the gas costs will come from ether balance

2. when investing from ether/ether token - only in that case you should SUBSTRACT gas cost from the total eth balance and the remainder should be spent.

mind wei precision as per #1515 

also when there is 0 balance on ether/ether token I see something like below which looks like you actually ADD the gas cost not SUBSTRACT?

![image](https://user-images.githubusercontent.com/17202864/46695250-5b1cf400-cc0f-11e8-9471-89b281534479.png)

**Comment by rudolfix** [comment]
@rudolfix bug is still there - entire investment balance of Investmwnt Wallet is set and then gas cost is added on top - and your balance is exceeded

also button INVEST stays grey and no error message is displayed until you actually change the amount

**Comment by glupiawymowka** [comment]
done
