### ISSUE TITLE
"Sorry your wallet does not contain enought ether to cover gas for the transaction" - still not like other error messages

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1518]
can we have this below
![image](https://user-images.githubusercontent.com/17202864/46695584-4a20b280-cc10-11e8-92f2-51d7e5dcff0f.png)

displayed as other error messages: in red below the amount? it's really hard to spot. looks more like information

**Comment by trival** [comment]
@rudolfix I removed it completely into a general transaction error that is used generally in all transactions here: https://github.com/Neufund/platform-frontend/pull/1526

**Comment by glupiawymowka** [comment]
the message is gone. now we have usual "The amount exceeds your wallet balance"
