### ISSUE TITLE
undeletable zeros when providing ETH amount and other weirdness

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1519]
1. type 250 in ETH then delete it with backspace. you see number below which cannot be deleted but can be navigated with arrows
![image](https://user-images.githubusercontent.com/17202864/46695950-3a559e00-cc11-11e8-99f9-7044c71b5301.png)

2.  when you press any character which is not a digit the cursor goes right but the character under it stays

3. type 121.7652 and then start deleting with backspace. when you reach the decimal dot, the number morphs into 1210000.000 why?

do you convert ETH back to EUR then set EUR and then convert it back to ETH. it's hard to understand what is wrong here

**Comment by glupiawymowka** [comment]
also video added by Marta, when she wrote 0.99999... it increases the value by 0.0001: 
[https://drive.google.com/open?id=1rZ0SU5IpxoOyuK--jcaW18NYfgDsUgTf
](https://drive.google.com/open?id=1rZ0SU5IpxoOyuK--jcaW18NYfgDsUgTf)
