### ISSUE TITLE
[ISSUER] FormTransformingField works incorrectly

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1520]
when you enter a value in the form it is transformed into value and then transformed back and displayed again.

try to type 7 when transform ratio is 0.01 (for example whitelist discount on Investment Terms)

you'll get some crazy value due to rounding errors

![image](https://user-images.githubusercontent.com/17202864/46702870-1b610700-cc25-11e8-8cd1-455e8118ff28.png)

what is stored must be decoupled from what is displayed

**Comment by rudolfix** [comment]
sorry for giving it to you after the YupTS but here we have serious problems with forms - seems like implementation went in wrong direction and now we have to replace this component

**Comment by glupiawymowka** [comment]
Entered 7 there, still getting the same result 

![image](https://user-images.githubusercontent.com/18315589/48002926-439d3200-e10d-11e8-905f-a09fae5f5650.png)
