### ISSUE TITLE
Portfolio overhaul and fixes

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1528]
- [x] hide NEU panel
![image](https://user-images.githubusercontent.com/17202864/46762105-8a4a6880-ccd6-11e8-8cbe-5f34cd3ef2a1.png)
Please hide this for now. We’ll not make it for first ETO. Instead we’ll add NEU to YOUR ASSETS!
- [x] simplify DIVIDENDS FROM NEU
![image](https://user-images.githubusercontent.com/17202864/46762154-ac43eb00-ccd6-11e8-8cbc-c84921346e4f.png)
Please rename it to OUTSDANDING PAYOUTS (this will be changed by lawyers anyway ;>). Here you will see not only payouts coming from NEU, but also from other tokens
Also table is wrong and we need to work on it after fist ETO.
You can just use “MY PROCEEDS” from Manage Wallet here. And change the title to the above. Will be good for now
- [ ] List NEU in YOUR ASSETS
![image](https://user-images.githubusercontent.com/17202864/46762224-d5647b80-ccd6-11e8-8ce0-8eeb7b18c140.png)
Fill columns as follows
•	BALANCE: on Neumark.balanceOf(user id/wallet address). If balance == 0 then row is not displayed
•	PRICE – it’s available in price feed, we already have it in state
•	VALUE EUR – multiply balance * price
•	NEU REWARD – empty
•	DOCUMENTS – (temporarily): link to page (open in new tab): https://commit.neufund.org/commit/status?address=<user_id> (example of working address: 0x430513b91748d977Aa38e4db691764a97Fe28236)

NEU is a token as any other so later we'll fully unify it with listing. Now you need probably need to hack this component. Up to you how you add this "outstanding data"

**Comment by glupiawymowka** [comment]
checked

1. case 1 - no assets (.net)
![image](https://user-images.githubusercontent.com/18315589/48556210-9cc24e00-e8e3-11e8-9a5a-71001b429981.png)

2. case 2 - existing assets (.io)
![image](https://user-images.githubusercontent.com/18315589/48556397-1eb27700-e8e4-11e8-91aa-e5f6fafe2c96.png)

**Comment by glupiawymowka** [comment]
@SergejSoft or @rudolfix  please let me know what do you think. Currently, there is an information "There is nothing to show" for reserved assets, but no such information for "Your assets"
Should it be changed? 

![image](https://user-images.githubusercontent.com/18315589/48556769-1eff4200-e8e5-11e8-8658-bfc6227323e3.png)

**Comment by SergejSoft** [comment]
@drakkein Pls. change the text in RESERVED ASSETS  to: "You have currently no reserved assets in your Portfolio."
and add text to YOUR ASSETS: "You have currently no confirmed assets in your Portfolio."
