### ISSUE TITLE
Transaction signer (wording + align)

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1535]
As @rudolfix  said, we need a new wording for this as nothing is signed here!

Then, everything should be centered. This is how it looks now: 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/f371e84d-611a-4801-bd39-3001a6c7fab7)

This is how it should look:

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/29cf8483-9375-4bfc-8020-a83a74465d92)

Code from Kirstyn: 

.Message-module__title___28Wmn {
    text-transform: uppercase;
    margin-bottom: .5rem;
    text-align: center;
}

**Comment by desfero** [comment]
@SergejSoft ```As @rudolfix said, we need a new wording for this as nothing is signed here!```
what working should we use here?

**Comment by SergejSoft** [comment]
Transaction Verification
Pls.verify your transaction by confirming this in your wallet.
