### ISSUE TITLE
Widget. ETO Striped View

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1537]
<img width="1258" alt="screen shot 2018-10-11 at 16 15 53" src="https://user-images.githubusercontent.com/2290474/46810453-07c2b700-cd71-11e8-9fcf-c8541556be21.png">
We need to make a responsive widget for neufund.org with ETO Fifth Force and Founders Bank.
I want to give it as start project to Wiktor Furman.

Specification:
1. Responsive ETO strip view (widget) for neufund.org
2. iFrame with the specific size for partner pages that shows striped ETO view. (not responsive)

Design for the responsive view. 

This needs to be finished by 22 Oct.

**Comment by falinebambi** [comment]
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5bc4b545e2c97b18e1648348
