### ISSUE TITLE
[KYC] low  prio | inadequate informations after KYC is submitted

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1539]
Fill KYC data
Submit KYC data
Go back to settings
Click "add additional documents" in KYC box
You see this:
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/fede6a5b-30b2-4b42-a8c3-76beecb41701)

What is wrong here:
- Verification process is not completed yet. It is in progress!
- No information that you can actually add more documents by clicking on document icon. 

Action link after KYC data is submitted does not make sense (Marcin)
Current link says "GO TO WALLET", but there is nothing new in the wallet in that case.
 Please change to "GO TO SETTINGS"

**Comment by SergejSoft** [comment]
@glupiawymowka  is this still on. I was thining it's done??
