### ISSUE TITLE
[investor wallet] tool tips for Gwei & Gas price needed - important!

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1545]
We received lots of feedback that the terms Gwei & Gas price are unclear
We could add the tooltips similar to the ones used in KYC for PEP and US citizens.

Pls. add a tooltip with helper texts and localization key in the locale file. 

They both can be found, among others, in the withdraw feature
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/8174dd0b-2b67-46af-bd3b-3364e265aace)

**Comment by desfero** [comment]
@SergejSoft what help text should we put there?

**Comment by rudolfix** [comment]
I will reasign to @Moejoe90 which does refactor of this. also I think designs changed

**Comment by Moejoe90** [comment]
Indeed designs changed for this

**Comment by Moejoe90** [comment]
@glupiawymowka 
Good question I have no clear idea on what should happen to investment. 
@trival is handling investment related stuff
