### ISSUE TITLE
Bug list.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1549]
https://docs.google.com/presentation/d/1-BReyNlQlIGC5kH3DCvzt0XxcKf2goKse7lzYn4GhlQ/edit?usp=sharing
there are 3 tickets assigned to you. Pls. mark as done one in review

**Comment by glupiawymowka** [comment]
all fine EXCEPT one thing: 
lines below key problem solution and key benefits for investors are missing if rolled up

![image](https://user-images.githubusercontent.com/18315589/48133548-73784100-e297-11e8-9b26-025fdbede946.png)

all fine when unrolled 
![image](https://user-images.githubusercontent.com/18315589/48133632-bfc38100-e297-11e8-8f7c-061932b56ab0.png)
