### ISSUE TITLE
[ETO PUBLIC VIEW] - automatic quotes should be deleted for Investor Quote, low prio

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1557]
The quote should be added manually in the forms, to avoid double quotes 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/d3fcd867-beb8-43c0-bcab-3a52264016b0)

**Comment by SergejSoft** [comment]
@glupiawymowka I was under the impression this quote is coming from the company description?

**Comment by glupiawymowka** [comment]
it's fixed already
