### ISSUE TITLE
[ETO OPPORTUNITIES] wrong time zone used

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1559]
note from @Vanilizer : 
Countdown to ETO should be displayed in UTC

design: 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/d83b46c5-84c0-4326-a7a0-bdee0a2a82c0)

actual countdown: 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/c2456389-6120-4003-bddf-bd9cde5b2787)

**Comment by rudolfix** [comment]
no bug here. it's in UTC - it says that ! closed
