### ISSUE TITLE
[ETO PUBLIC VIEW] - Legal company name not displayed + wrong brand name - IMPORTANT

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1560]
1. In Legal information, legal company name is not displayed as it should

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/5fa2de15-17b0-4f14-9c1f-db4b2023dac8)

2. In the given example, Quintessence is the brand name, so the "About" section shouldn't be "Neufund" but "Quintessence" (design here : https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5b7c2efb28ae9b21e6fbc305 )

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/0486fa94-481a-4bc5-b19b-bbe48b8a60e8)

**Comment by rudolfix** [comment]
@glupiawymowka legal information is taken from KYC data and displayed as is. same data goes to legal documents... what is wrong here? I do not see anything wrong here

**Comment by rudolfix** [comment]
please re-check on stage, io data is maybe too shitty?

**Comment by rudolfix** [comment]
@glupiawymowka @Vanilizer until you confirm this on stage, this issue is on hold

**Comment by glupiawymowka** [comment]
@rudolfix verified with both companies on stage, works fine there. closing
