### ISSUE TITLE
Remove No. and add placeholder "amount"

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1570]
![Screen Shot 2018-10-16 at 12.40.16.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/1726b860-07d4-4da0-aa7c-84f29b6731a7)

/Users/soft/platform-frontend/app/components/shared/forms/formField/FormCategoryDistribution.tsx
line:139

**Comment by glupiawymowka** [comment]
"No" is gone correctly, but "Amount" cuts strangely when the window gets smaller

![image](https://user-images.githubusercontent.com/18315589/48002374-ae4d6e00-e10b-11e8-9ad2-d51b72f05037.png)

**Comment by SergejSoft** [comment]
Please break the input fields in two lines in the smaller screen sizes. XS, S.

**Comment by glupiawymowka** [comment]
done
