### ISSUE TITLE
Slide Deck Ifame integration

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1576]
Please look at ETO forms for media because we have youtube and twitter working, but only for some cases. 
But @Vanilizer reports it does work with Firth Force ETO, and Twitter page of Foudner Bank.
<img width="1021" alt="screenshot 2018-10-16 at 16 43 55" src="https://user-images.githubusercontent.com/2290474/47024812-b7799980-d162-11e8-9a9e-5e16127a9fe3.png">

It was done by Patryk, and he said it will only work if you placed embedded code, but our form doesn't accept this:) LInk only So this needs to be fixed.

**Comment by desfero** [comment]
@SergejSoft i checked what happens here and you need to copy and paste embedded url link.
![image](https://user-images.githubusercontent.com/7031578/47100346-8f0f9f00-d237-11e8-83b3-431f687fa26b.png)

But that can be very confusing for a user :(

We can fix it by using OEmbed slideshare api (https://www.slideshare.net/developers/oembed)
after that it should be possible to simply pass slideshare link.

@SergejSoft should i continue work and connect with slideshare api?

**Comment by desfero** [comment]
@SergejSoft talked with @rudolfix and we are going to fix that on backend side as it's more appropriate way to deal with that issue. So, for now, I'm going to move it to 'Backlog' and assign to you and @rudolfix
