### ISSUE TITLE
Backoffice - Changing status of document after it's accepted

### ISSUE THREAD

**Issue by kelexa** [Neufund/platform-frontend#1588]
Hi,

To be able to modify status of document back (to rejected, pending or ignored) after we accepted and saved it. This should work in any **Account Status**. Not only on Pending accounts.

Now we get this message:

![image](https://user-images.githubusercontent.com/40295416/47080264-d847fa80-d207-11e8-8478-7bbcee9c8b55.png)

**Comment by rudolfix** [comment]
Issue moved to [Neufund/platform-backend #1137](https://github.com/Neufund/platform-backend/issues/1137) via [**ZenHub**](https://www.zenhub.com/)
