### ISSUE TITLE
Investor| Investment summary| Tooltip 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1590]
<img width="765" alt="tooltiop" src="https://user-images.githubusercontent.com/2290474/47082224-375c3e00-d20d-11e8-9f03-bb01856a725d.png">
If ICBM Wallet selected in the investment flow pls. add a generic tooltip with the text: "As an ICBM investor you have already received a NEU reward for your commitment, therefore you won't get rewarded again."

Make sure the test ist than saved in locale file so we could edit this any time later.

**Comment by glupiawymowka** [comment]
I guess it's fine like this
![image](https://user-images.githubusercontent.com/18315589/49163601-c2ad1100-f32d-11e8-88bf-595fb87141f0.png)
