### ISSUE TITLE
Min ticket size

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1592]
If a user makes more than one investment we should check the total value of his investment. 
So if he invested 5000Euro and than only 50Euro. The validation should still allow him to invest. 
<img width="1225" alt="screen shot 2018-10-17 at 15 33 52" src="https://user-images.githubusercontent.com/2290474/47090032-52857880-d222-11e8-9f4a-6245fc451aed.png">

Example: Minimum Ticket Size = (SUM of all investments)

**Comment by rudolfix** [comment]
I reviewed the ETO Contract and it will not allow for that. You need to always send at least min ticket to it. So I put it on hold - we can implement it differently on next ETO
