### ISSUE TITLE
bring back original NEU widget

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1594]
![image](https://user-images.githubusercontent.com/17202864/47091758-c5dcb980-d225-11e8-8e8c-792cc5e17d0e.png)

1. please format NEU as currency (decimal separators)
2. provide NEU/EUR price
3. provide total NEU value in EUR

there are designs

**Comment by glupiawymowka** [comment]
1. second point (Neu/EUR price) is missing, @rudolfix please confirm that it should look like in this old design below
2. please center "Welcome to the Neufund Platform" and "My Neumark" regarding whole container, not only the widget itself 

Current view
![image](https://user-images.githubusercontent.com/18315589/48500918-451cd780-e83c-11e8-80eb-e9665ba74c60.png)

Design (ignore the colors and wording)
![image](https://user-images.githubusercontent.com/18315589/48501023-7a292a00-e83c-11e8-884c-cb94063c84e9.png)
