### ISSUE TITLE
[WITHDRAW] no ETH address validation - IMPORTANT

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1603]
Whatever address can be entered here, there is no error message: 

Case 1:
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/d5957737-3eea-410e-b9fd-f0b77a6d6268)

What is this address? 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/03d5d0a4-bb1c-4c2a-a87f-7eb4bf9503db)

Transaction is confirmed, ETH is correctly gone, but where? 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/44982b34-2f2f-4857-a1c2-e853f2e2f772)

CASE 2: 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/9b88d7b3-da18-465c-865a-268c49779c8e)

"Address" is correct in this case
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/a041565c-01bc-4992-8d26-8c3c6fc35b62)

No info what happened, no option to correct 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/92c6c349-3818-46dc-a5b5-baa28eef5700)

**Comment by rudolfix** [comment]
@Moejoe90 here you have a few test cases for withdraw. i think we have it covered so close if so

**Comment by Moejoe90** [comment]
@rudolfix 
This ticket is being handled as part of #1475 so i will close

**Comment by Moejoe90** [comment]
This will be added as a test case so i will close this for noe
