### ISSUE TITLE
Add loading indicator for ETO OPPORTUNITIES

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#1622]
**Background** 
Currently, when the eto's are loading there is no indicator  that makes me wait simply from nothing there is a list 
![image](https://user-images.githubusercontent.com/23242822/47225719-120f3180-d3bf-11e8-9819-7b871cd8d06f.png)

**Task** 
Investigate if all states are there as in `loading` state and add a loading indicator

**Comment by falinebambi** [comment]
https://codepen.io/PalmBeachagency/pen/GXJLom
![screen shot 2018-10-23 at 17 47 57](https://user-images.githubusercontent.com/17235402/47373291-cffe2c80-d6eb-11e8-80b2-1b09e1e50978.png)
