### ISSUE TITLE
implement ETO progress in Eto Overview widget

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1630]
![image](https://user-images.githubusercontent.com/17202864/47313595-9b349b80-d63f-11e8-9d85-4ba437ff3b55.png)

 - visible in whitelist (pre-eto) only when investor can participate! see above. otherwise countdown
- visible in public phase

Data sources
- number of investors: from `etoCommitment::totalInvestment()`
- ETH: etherToken.balanceOf(etoCommitment.address)
- EUR: euroToken.balanceOf(etoCommitment.address)

green/gray progress bar is constructed from following data:
- starts at 0%
- ends at calculated percentage > 100% which we compute as follows
new_shares_to_issue / minimum_new_shares_to_issue * 100
- green vertical bar at 100% - place it proportionally to the value above.

now where green bar ends calculate from proportion totalTokensInt/(new_shares_to_issue*equity_tokens_per_share)
totalTokensInt you get from `etoCommitment::totalInvestment()`

**Please note that we show percentages on the green bar, not amounts**

**Comment by glupiawymowka** [comment]
Ok, after a talk with Paweł, I guess I understood wrong and there is no plan to add a current percentage on the progress bar. 
1. pre-eto is only visible for the investors that can take part - CORRECT
2. number of investors change correctly (doesn't count double if invested many times from 1 account)
3. 100% bar placed proportionally
4. progress bar is moving with invested amount
