### ISSUE TITLE
Translocation history for Euro users 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#1633]
we should somehow display all the user money in Money Out transaction including the rejected ones, will be easier for them to track it and also they might need it for tax authority
You can see an example from eToro (they also shows decline withdrawals and deposits)- this can be also for ETH deposits which are simpler as we can show it from ETH scan

![image](https://user-images.githubusercontent.com/36156487/47297205-bd64f400-d614-11e8-967d-e90fd7fad5f4.png)

**Comment by rudolfix** [comment]
Issue moved to [Neufund/platform-backend #1108](https://github.com/Neufund/platform-backend/issues/1108) via [**ZenHub**](https://www.zenhub.com/)
