### ISSUE TITLE
Eto Status Widget - additional state when max cap reached

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1635]
This applies both to `Whitelist` and `Public` states. State is detected by calling `calculateContribution` on `EtoCommitment` where in `newInvestorContributionEurUlps` parameter you provide minimum ticket value from EtoData.

If `maxCapExceeded` is set it means that more investment in eto is impossible and we should show:

1. When in Whitelisted state
"Presale cap reached"  and then counter to public ETO

2. When in Public state
"Maximum cap reached" (and nothing else)

*We can re-use our mechanism to detect who can participate in pre-eto which already calls `calculateContribution`*

**Comment by falinebambi** [comment]
![image](https://user-images.githubusercontent.com/17235402/47564726-3f5f6080-d926-11e8-9373-3e7d4eb71090.png)

**Comment by rudolfix** [comment]
@falinebambi what about when we reached max cap of the whitelist? should we just switch back to bare counter?

**Comment by falinebambi** [comment]
Those design are on ticket: https://github.com/Neufund/platform-frontend/pull/1644

**Comment by rudolfix** [comment]
I will again reiterate:
1. If we are in public phase we show image below. it's 100% correct
![image](https://user-images.githubusercontent.com/17202864/48129642-66a12080-e28a-11e8-852b-ebce356f1512.png)
2. If we are in pre-eto (whitelist phase) and investor CAN INVEST IN WHITELIST
we show the same widget with following wording changes
ETO SUCCESSFUL = PRE-ETO SUCCESSFUL
MAX CAP REACHED = PRE-ETO CAP REACHED
and instead of green bar we show the counter until public phase
3. If we are in pre-eto and investor cannot invest then we just show counter as we do now
