### ISSUE TITLE
ISSUER DASHBOARD - simple implementation of bookbulding pledges download

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1638]
This is simplified implementation before we implement a full thing

1. Add another box to issuer dashboard which is available when there are any pledges made (use `/etos/{id}/bookbuilding-stats` to get stats)
2. Display stats below on the block
![image](https://user-images.githubusercontent.com/17202864/47308257-628dc580-d631-11e8-99e1-8ddaab729bf1.png)
3. Add "DOWNLOAD AS CSV" button which will emit csv file. use `/etos/me/pledges` to obtain list of Pledge objects (see swagger)
CSV format should be
address,e-mail,currency,amount_eur,inserted_at
----------------------------------------------
UPDATE: `/etos/me/pledges` is implemented and deployed on io. re-pin backend to have it in e2e tests

**Comment by mpneu** [comment]
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5be96d3f072fb97e8f12a835

https://invis.io/PCP29ZSWHXK

**Comment by glupiawymowka** [comment]
![image](https://user-images.githubusercontent.com/18315589/53170675-fc19b380-35e0-11e9-9b14-8e5140bb41fa.png)
done and works fine!
