### ISSUE TITLE
ISSUER DASHBOARD - implement set start date widget

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1639]
This widget is used to set ETO start date on-chain. It should also allow to change the start date. As this action is critical we should also have confirmation dialog.

*Widget visibility*
Widget is visible once in on-chain state and when ETO contract is in `Setup` `timedState`

*What should be visible on the widget*
If current start date is set - it should be displayed (UTC) `startOfStates[1]`
If date can be changed/set - a date pickup widget and SET DATE button (we have it already)

*When date can be changed/set*
See `setStartDate` implementation of ETOCommitment contract. There are two cases
- date is not yet set in smart contract (check `startOfStates[1]` to contain 0 value)
- if date is set, it may be changed only when
```
uint256 startAt = startOfInternal(ETOState.Whitelist);
require(
            startAt == 0 || (startAt > block.timestamp && startAt - block.timestamp > PLATFORM_TERMS.DATE_TO_WHITELIST_MIN_DURATION()),
            "ETO_START_TOO_SOON");
```
so startOfStates[1] - now() > PLATFORM_TERMS.DATE_TO_WHITELIST_MIN_DURATION()

*Date validation before submission*
Following condition must be met
```
require(
            startDate > block.timestamp && startDate - block.timestamp > PLATFORM_TERMS.DATE_TO_WHITELIST_MIN_DURATION(),
            "ETO_DATE_TOO_EARLY");
```

*when to hide it*
when smart contract `timedState` is `Whitelisted`

*Confirmation modal should show*
1. New start date in UTC
2. Time span to start date from now (double confirmation)
3. ETO Commitment Contract address with link to Ether Scan
4. ETO Terms Contract address with link to Ether Scan
5. Equity Token address with link to Ether Scan
6. `equityToken.currentAgreement()` as a link to IPFS gateway to obtain legal agreement independently from Neufund Platorm
6. `etoCommitment.currentAgreement()` as a link to IPFS gateway to obtain legal agreement independently from Neufund Platorm

**Comment by rudolfix** [comment]
QA review done! Flow itself works but UI needs improvements

1. When setting the ETO start date please allow to set time as show in date pick up widget here https://zpl.io/29oWjvB
2. Please make calendar icon clickable -> shows widget
![image](https://user-images.githubusercontent.com/17202864/51318799-9bd0a880-1a5b-11e9-838e-0d38a615c060.png)
3. On the widget
![image](https://user-images.githubusercontent.com/17202864/51319203-b7887e80-1a5c-11e9-815f-a5c953ac5b94.png)
If start date is already set
- please show countdown and current start date (with time) in UTC
- entry to select new date below
3. Please change information on the following:
- new start date must be in **UTC** and must show time
- below information in your local time zone (which will be good to name explicitely)
- fix UI per design here [Kirstyn please provide)

You can test this flow on io by logging with Metamask account 0x74180B56DD74BC56a2E9D5720F39247c55F23328

**Comment by AlexeyTuboltsev** [comment]
there should be two areas in the widget
1: (if presale date already set) current presale date (utc) and a counter of time left
2: (only if change is still possible) change date button and a counter counting time it's possible to change the date.

**Comment by glupiawymowka** [comment]
*tested on .io*
This is working correctly, but a review of logics and designs is needed 

- [x] the widget allows date change when the conditions are met
- [x] there is a contract sent to be signed (and paid) in the wallet
- [x] states of the widget: 

date chosen, change still possible - CORRECT
![image](https://user-images.githubusercontent.com/18315589/53164883-940fa100-35d1-11e9-8228-10098071408f.png)

ETO in CLAIM, PAYOUTS state - @falinebambi @rudolfix should this still be visible? There is a past date (Jan. 21)
![image](https://user-images.githubusercontent.com/18315589/53165369-d4235380-35d2-11e9-9e64-26dbdb17b5cf.png)

same for the unsuccesfull ETO (Refund) 
![image](https://user-images.githubusercontent.com/18315589/53166144-d090cc00-35d4-11e9-9244-29780f2f8edf.png)

The most important point is that there shouldn't be any "Time left" header if we're not counting anymore. We can show the date in the past, but the header's wording should change

**Comment by falinebambi** [comment]
I'll test it today and give you some feedback on designs.

**Comment by Louisswryan** [comment]
Here are the updated issuer dashboard states without the 'TIME LEFT' and without the graphic.

ISSUER_DASHBOARD_CLAIM
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c8660e68bd661197caf0d4d

ISSUER_DASHBOARD_REFUND
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c8660e6512e0a38963e5c9c

Apologies for the time taken. From the ticket I understood this to be a much bigger task than it actually was.

**Comment by glupiawymowka** [comment]
*tested on .io*
current view for the presale that cannot be added or changed now: 
 
![image](https://user-images.githubusercontent.com/18315589/55158869-2f131200-5160-11e9-8f91-06c27d38b4f9.png)
seems correct
