### ISSUE TITLE
ISSUER DASHBOARD - implement uploading and signing investment agreement

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1641]
Following process should be implemented.

1. We show new widget in Dashboard when eto enters signing state (`timedState`), the widget says "Download and Sign Paper Investment Agreement". The button below downloads `Investment and Shareholder Agreement` from TEMPLATES collection (same thing we do in Documents section)
2. In documents section we already have a place to upload signed investment agreement. However document type changes from `signed_investment_and_shareholder_agreement` to `investment_and_shareholder_agreement`. Signed template will be provided by Ethereum network event!
3. When `investment_and_shareholder_agreement` is in the documents collection the widget from (1) changes state and says `Sign Investment and Shareholder Agreement on Ethereum. Only announced agreement can be confirmed by Nominee"`. The button below says "Sign Agreement". When pressed we make `etoCommitment.companySignsInvestmentAgreement(agreementUrl)` where `agreementUrl` is `ipfs_hash` taken from document collection with `ipfs:` prefix (example: `ipfs:QmcVyJXxGqkv7ucZGXTtzxAb95TYz5nPnRt1uVDWe31miG`)
--> add ipfs link to signing modal 

4. If `etoCommitment.signedInvestmentAgreementUrl()` == `ipfs:` + ipfs_hash from documents collection, the widget says "Waiting for Nominee to confirm investment agreement` and that's it. If the condition below is not met widget goes to state in (3) - issuer can upload Agreement many times and offer it to Nominee to confirm
5. Widget changes state again when `timedState` is in Claim or Payout - in that case it says "ETO Completed Succesfully" and button below says "GO TO WALLET"
6. if state is "Refund" hide the widget

**Comment by Louisswryan** [comment]
1. ISSUER_DASHBOARD - ETO signing state widget
--LINK: https://zpl.io/aBy7QKm

2. ISSUER_DOCUMENTS - signed investment and shareholder agreement upload prompt
--LINK: https://zpl.io/andMnjJ

**Comment by Louisswryan** [comment]
(user required to download, sign and upload a signed paper investment agreement)

-- https://zpl.io/aBy7QKm

(DOWNLOAD AND SIGN link downloads document and links user to LEGAL DOCUMENTS where they are prompted to upload signed agreement)

-- https://zpl.io/andMnjJ

(once document is uploaded, user needs to sign on ethereum but is currently in LEGAL DOCUMENTS so module is needed with link to ethereum)

-- https://zpl.io/bJ9Pwyn

(should user leave module without signing on ethereum, DASHBOARD needs to update with status and link)

-- https://zpl.io/aMKM8e3

(once signed on ethereum, user must wait for response)

-- https://zpl.io/VQKrOkR

(if response positive, user gets a success message and invitation to go to wallet)

-- https://zpl.io/bABjMzo

(if user has navigated away from DASHBOARD, maybe a module with success message and invitation to wallet is a good idea)

-- https://zpl.io/VQBmk0A

(if user unsuccessful, repeat the SIGN ON ETHEREUM widget but with status updated to invite user to try again)

-- https://zpl.io/29O4LZw

**Comment by AlexeyTuboltsev** [comment]
blocked by https://github.com/Neufund/platform-frontend/pull/2499

**Comment by AlexeyTuboltsev** [comment]
FOR QA: this pr is the first take on the download/upload/sign IA flow. This flow didn't exist before and there are many edge cases that we couldn't anticipate. Please report not only bugs but also everything that you find not user friendly or else not good enough so that we could continue designing it  😍

**Comment by glupiawymowka** [comment]
*tests are ongoing for this ticket (need to wait for the fixture restart)* 

- [x] if the user leaves the flow before signing, there is a link to continue on the dashboard\

- [ ] "sign the agreement" module doesn't contain this text: 
This is the final step! Announced agreements can only be confirmed by the nominee. Click below to sign the agreement on Ethereum.  
design - https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c642ea84b2e42463425f70a

Also, the picture is not centered 
![image](https://user-images.githubusercontent.com/18315589/55409289-10e35280-5562-11e9-84ee-339d5261a4a4.png)

- [ ] I did sign already, but the module still invites me to do it (success status in metamask and transaction summary). 
If I click on it, I can go through the full process again
![image](https://user-images.githubusercontent.com/18315589/55409587-936c1200-5562-11e9-87c2-a673a5d7d7c9.png)

- [ ] I went throught the process again, then refreshed and now the module informs me, that I've re-uploaded my agrement and therefore I need to sign again. But I did not upload anything in the meantime. I tried once again **and I can't reach the "success" status** 
![image](https://user-images.githubusercontent.com/18315589/55409877-1beab280-5563-11e9-9500-e1755cbc82f8.png)

**Comment by shanile** [comment]
I had this ticket on QA I test it with wallet 9 and I created this document which describes the flow I have my comment there @Vanilizer @falinebambi please check https://docs.google.com/document/d/1uFGbpIrDMiwQVsAqd3TGeJVMe5OFnJGlqDKnUQaKjW4/edit

**Comment by shanile** [comment]
Test comment: it was tested and I added share document https://docs.google.com/document/d/1uFGbpIrDMiwQVsAqd3TGeJVMe5OFnJGlqDKnUQaKjW4/edit taking screenshots of the whole flow, Aga reviewed it and beside one comment everything is working well.

When the user going back to dashboard after he successfully uploaded the investment agreement the message is still the same and he is still required to upload the document - we should change it to ISHA successfully uploaded, or the box should disappear.

**Comment by AlexeyTuboltsev** [comment]
looks like you didn't wait until the transaction was finished...

**Comment by glupiawymowka** [comment]
@AlexeyTuboltsev please read my comments from before. They are all still valid, plus one thing I re-tested now: 
 
- [ ] this file is downloaded by deafult in .doc BUT then I cannot upload the file in the same format. Anyways, I've uploaded some pdf instead

![image](https://user-images.githubusercontent.com/18315589/56143482-e9987680-5fa0-11e9-9992-ce35fb6d89a2.png)

- [ ] successful "sign investment agreement on ethereum" 
![image](https://user-images.githubusercontent.com/18315589/56198024-5a3fa180-603a-11e9-9bec-7a70e343adca.png)

- [ ] I did NOT re-upload anything, so why do I have to sign again what was just confirmed to me as signed? this is a serious bug that makes completing of this process impossible. 

![image](https://user-images.githubusercontent.com/18315589/56198248-d639e980-603a-11e9-9ab4-a6922f2bd3d9.png)

**Comment by glupiawymowka** [comment]
- [ ] I have no mean to check if the success modal is appearing (I can't sign as the nominee...)
- [ ] this is how the "success" widget looks on the platform vs designs

platform
![image](https://user-images.githubusercontent.com/18315589/57311172-6f649900-70eb-11e9-8bfc-231545b5a849.png)

design
![image](https://user-images.githubusercontent.com/18315589/57311203-7c818800-70eb-11e9-8b7e-120f8e6cdc12.png)

**Comment by glupiawymowka** [comment]
tested on stage (till signature in ETH network)
