### ISSUE TITLE
PUBLIC PROFILE - INVESTMENT TERMS - change data shown

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1643]
We do not show essential data there!

Here is data that we should show in the sections
**Equity**
PRE-MONEY VALUATION - stays
EXISTING SHARES - stays
NEW SHARES TO ISSUE (range) - we show a range like 1281 - 277128. range `minimum_new_shares_to_issue` - `new_shares_to_issue`
NEW SHARES TO ISSUE IN PRE-ETO (displayed if defined and > 0) `new_shares_to_issue_in_whitelist`
NEW SHARE PRICE - stays
PRE-ETO DISCOUNT (if defined - in %) - `whitelist_discount_fraction` (currently we have discount scheme there - drop it)
INVESTMENT AMOUNT - stays

**Token Sale**
TOKENS PER SHARE - stays
TOKENS TO ISSUE - drop it
TOKEN PRICE - stays
TICKET SIZE is a range (`min_ticket_eur` - `max_ticket_eur` | "Unlimited") - max ticket may be undefined in that case it means there is no upper limit
CURRENCIES: always `ETH` and `nEUR`
PRE-ETO DURATION - stays
PUBLIC ETO DURATION - stays

**Token Holder Rights**
*no changes*

**Comment by glupiawymowka** [comment]
"unlimited" ticket - correct
NEW SHARES TO ISSUE IN PRE-ETO - missing in public view if not filled, ok
