### ISSUE TITLE
[light wallet, recovery phrase] unclear instruction (wording change)

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1658]
The wording here suggests that there is an instruction to see. 
In fact, the instruction is only on the first step of the process

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/25c0120a-3add-408f-8b02-9d1c1ede38c1)

Please change wording from "Please make sure to follow the instructions." to "Please note all the phrases down including numbers."

**Comment by meneramandarin** [comment]
done
