### ISSUE TITLE
[KYC] country of residence wording

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1659]
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/456f3024-6600-4155-bd98-6d4eb4aba4d8)

Since we don’t ban investors because of where they’re coming from, rather than residence country, this should be clearer.
Please change to  “Unfortunately we do not accept investors or companies with residency in your country due to regulatory restrictions”.

**Comment by meneramandarin** [comment]
i cannot find an entrance for this in the locals file. anywhere else i can change it @desfero?

**Comment by desfero** [comment]
@meneramandarin they were not placed in locales file. Btw i moved then to locales file and also fixed that working change

**Comment by meneramandarin** [comment]
okay, thanks.
