### ISSUE TITLE
[bookbuilding] more user-friendly descriptions for min & max pledges 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1682]
1. Minimum pledge should say like other similar messages.
For example - "The amount is below the minimum pledge size of €500"!
![image](https://user-images.githubusercontent.com/18315589/47622069-bf412280-db00-11e8-875d-8578bb27f6ea.png)

2. When €1000000000000 was entered, an unclear message appeared
![image](https://user-images.githubusercontent.com/18315589/47622065-b0f30680-db00-11e8-946c-a201f93a1088.png)

**Comment by glupiawymowka** [comment]
1. Minumum pledge looks good now
2. Max pledge looks good until this point (1000000000): 

![image](https://user-images.githubusercontent.com/18315589/48012752-0479db80-e123-11e8-9a6f-af4ef5dfd15b.png)

3. Above this point it's still the same (10000000000)
![image](https://user-images.githubusercontent.com/18315589/48012845-38ed9780-e123-11e8-905b-d2187fd2cbc2.png)
It should be impossible to enter more digits OR the message about max amount should stay. 
@SergejSoft please advise

**Comment by SergejSoft** [comment]
@glupiawymowka @desfero guys, I suggest limiting the pledge amount to 10000000 (8) Digits.

**Comment by desfero** [comment]
@glupiawymowka `Must be a whole number` is a `yup` library bug, i will try to fix it when have some time (https://github.com/jquense/yup/issues/50). 
@SergejSoft so i will limit to 8 characters, after that input is blocked, so it's not possible to provide more than 8.

**Comment by glupiawymowka** [comment]
(stage)
still possible to add more than 8 characters
![image](https://user-images.githubusercontent.com/18315589/48501700-156ecf00-e83e-11e8-937d-a9f09b3d9480.png)

**Comment by glupiawymowka** [comment]
*tested on .io*
