### ISSUE TITLE
Implement correct behaviour for page titles

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1683]
*Background:*
Right now every page on the platform is with the same title "Neufund Platform". 
![image](https://user-images.githubusercontent.com/7031578/47639980-34e1d880-db6b-11e8-8629-77ea03f1ef25.png)
This raises several problems:
- Product looks like not a finished one,
- Usability is not quite good as when use has opened a few tabs he doesn't know which one is showing what,
- Accessibility is bad as any users with disabilities are going to hear every time on each page "Neufund Platform" without any information at first what this page is about.
- Without correct titles, we are not going to progress with SSE/PRERENDERING for sharing a meaningful link on social media portals (like for e.g. we want to share eto public view link on facebook)

Technical notes:
We can reuse my https://github.com/desfero/beer_guru/blob/master/packages/beer_guru/src/hocs/withSceneTitle.js hoc that was built on top of `react-helmet`

**Comment by rudolfix** [comment]
OK. who sets the titles? Some of the titles should be dynamic like should have a name of the ETO (when looking at public profile). Are we associated with the routes?

**Comment by SergejSoft** [comment]
Whatever improves our UX this year I wanna push out of the backlog. So mark this as ready for dev.

**Comment by glupiawymowka** [comment]
*this is already live and working correctly. additionally, fix of one remaining header was tested on .io*
