### ISSUE TITLE
change max persons age

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#1690]
<img width="813" alt="screen shot 2018-10-27 at 18 55 00" src="https://user-images.githubusercontent.com/14041336/47654870-0de7ce80-db8c-11e8-994b-8eb02dcf9cc5.png">

rudolfix [1:44 PM]
@alexey.tuboltsev :slightly_smiling_face: please find age of the oldest living person in wiki add one year and put in the validator. then we are safe for one year ;> I think it's cool so let's simply do it

**Comment by glupiawymowka** [comment]
it's 125 now! :D
