### ISSUE TITLE
[staging, account details] incorrect full name shows

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1692]
1. Light wallet, KYC is done (1 was entered everywhere)
2. This is what shows as Full Name in "Account Details" (Settigns)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/d114f6cc-4dbf-4c06-b237-27a2e737fe6e)

**Comment by drakkein** [comment]
I'm unable to reproduce this issue, also there is no any signs of code problems.

**Comment by glupiawymowka** [comment]
let's reopen it if happens again
