### ISSUE TITLE
Equity Token Offering Terms -> ETO is not under crowdfunding regulations is without any required error message

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1693]
Because of that user don't know why it's not possible to submit form.
![oct-29-2018 20-39-34](https://user-images.githubusercontent.com/7031578/47672531-f411b000-dbba-11e8-8ace-2454b83ffc8c.gif)

We need to add a proper error message

**Comment by rudolfix** [comment]
OK let's add error message "Crowdfunding based ETOs are not supported right now"

**Comment by glupiawymowka** [comment]
done
![image](https://user-images.githubusercontent.com/18315589/49595835-31ffb200-f979-11e8-9548-45279a2e5e03.png)
