### ISSUE TITLE
change how light wallet secret data is processed

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1712]
- [x]  do not store vault in local storage, you can store just salt and e-mail

- [ ] when logging out, please delete vault and salt from storage, you can keep e-mail for UX. the consequence of that is that you need login link to log in, not just password which is what we want [Seperate ticket]

- [x]  ask for the password every time we sign anything. do not store decrypted keys or vault anywhere. for each signing retrieve vault from the storage, use password and salt to decrypt, sign what you have to sign and destroy all the data

**Comment by Moejoe90** [comment]
Point 2 taken to a separate ticket
