### ISSUE TITLE
Portfolio Payout flow.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1733]
There is a new design for Portfolio functions that reached the stage of PayOut. 

User case: User invested in the ETO and after a successful campaign, the user is able to claim equity tokens and rewards in NEU.

**Desings**:
List: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c51c8019c3e07307b056e1a
No payouts: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c5320a1881152354d831cb7
Accept All Summary: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c4eff5466e3b3bee976ec3f
Accept nEur summary: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c4eff5487c26e79e4575c65
Accept eth summary:
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c4eff56c50a21377f681154
Accept success: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c51c8029c3e07307b056f3e
Redistribute summary: zpl.io/b6jWdEN
Redistribute confirm: zpl.io/VkwPLm5
Redistribute success: zpl.io/V1zLg8Z

**Progress:**

- [x] Display payout
- [x] Approve payout
- [x] Redistribute payout
- [x] Add NEU icon to header (would be done as a part of #2411)
- [ ] E2E tests for accept payout
- [ ] E2E tests for redistribute payout

**Testing notes**
Please refer to the above progress checklist to see what's already merged to master (`.io`).
To test payout you need to have some payouts so correct fixture should be used. Fortunately, a lot of fixtures are already with available payouts like INV_ICBM_EUR_M_HAS_KYC, INV_HAS_EUR_HAS_KYC and INV_EUR_ICBM_HAS_K.

**Comment by rudolfix** [comment]
Attaching UI to smart contracts:
You can find full information in **FeeDisbursal** contract with source code here: https://github.com/Neufund/platform-contracts/blob/master/contracts/FeeDisbursal/FeeDisbursal.sol
It's pretty well documented.

1. our proRata token is always NEU (Neumark). you can assume proRataToken with NEU address everywhere. We'll have bigger redesign of all dashboards so I would not waste time for anything universal.

2.
![image](https://user-images.githubusercontent.com/17202864/51907752-08d32f00-23c8-11e9-9178-8f2a44839219.png)

you obtain all necessary data by calling `claimableMutipleByToken`
```
const paymentTokens = [euroToken.address, etherToken.address];
const claimables = await feeDisbursal.claimableMutipleByToken(paymentTokens, neumark.address, investors[0]);
```
you receive array of arrays where internal array is
`(amount that can be claimed, total disbursed amount, time to recycle of first disbursal, first disbursal index)`

you will always receive as many lines as tokens requested even if there's nothing to claim
if `amount that can be claimed` is 0 then you do not display line for ether/euro on the right. if both ether and euro are empty, you do not display any payouts

**Comment by rudolfix** [comment]
![image](https://user-images.githubusercontent.com/17202864/51909609-5900c000-23cd-11e9-8ab5-3f01092623b5.png)

nEUR is coming from euroToken line, ether is coming from etherToken line

in ACCEPT ALL PAYOUTS you invoke Ethereum transaction
`feeDisbursal.acceptMultipleByToken()`

**Comment by rudolfix** [comment]
![image](https://user-images.githubusercontent.com/17202864/51910024-4dfa5f80-23ce-11e9-96fe-8cc9e51e8c32.png)

Each line represents nEUR or ETH payout from NEU token

you accept by
`feeDisbursal.accept()`
you rejet by
`feeDisbursal.reject()`

**Comment by rudolfix** [comment]
Action button should be disabled and text changed to "USER NOT VERIFIED" (temporary, we need better texts). feeDisbursal kicks out not verified users.

**Comment by rudolfix** [comment]
**TESTING**
newest backend image contains fixtures to test disbursals
1. account 0x0020d330ef4de5c07d4271e0a67e8fd67a21d523
2. ETO in payout state (`ETOInPayoutState`) already distributed proceeds

please never hardcode eto address, always take it from `eto_fixtures.json`

**Comment by desfero** [comment]
@rudolfix do you have for testing also account with only one token to payout?

**Comment by Desperado** [comment]
Neu Token Holder agreement - to be opened in the new window, not in the same one.

**Comment by glupiawymowka** [comment]
1. NEU token holder agreement fixed (opens in new tab now)
2. This **redistribute** button doesn't give an impression that it's clickable at first sight @falinebambi @desfero 
![image](https://user-images.githubusercontent.com/18315589/52484367-6df00700-2bb6-11e9-9f3d-85b79b04dfd6.png)
3. Total Payout can be a bit confusing. Maybe we could have a tooltip explaining what exactly is this amount there? 
4. @rudolfix is it correct that we are charging people if they actually don't want to profit from NEU? Is it charged from the redistributed amount, or from the user's wallet? 
What happens after 4 years? Are they charged anyway for not getting money? 
![image](https://user-images.githubusercontent.com/18315589/52484846-96c4cc00-2bb7-11e9-805a-3dc34a810386.png)

5. Both accept and redistribute works fine on .io <3 
![image](https://user-images.githubusercontent.com/18315589/52487062-0d17fd00-2bbd-11e9-89b6-03165c234d63.png)

**Comment by Desperado** [comment]
@glupiawymowka 
2. What does it mean? That is is black? But hovering and clicking obviously works well.

**Comment by Desperado** [comment]
4. Was wondering the same actually. It feels this action should be free for the user.

**Comment by desfero** [comment]
@glupiawymowka @Desperado so this redistribute is a little bit tricky and is only need for accountancy of dividends as if there is no option to reject dividends than tax office can claim tax immediately after receiving the payout. The investor needs to pay for ethereum transaction cost to as it's the usual transaction that goes do ethereum node to be mined.

**Comment by glupiawymowka** [comment]
2. There is any other button on the platform that looks like this one, also looks a bit like normal text.

**Comment by glupiawymowka** [comment]
Ok, let's drop it for now. I'll create another ticket in case of tooltips or wording change
