### ISSUE TITLE
fix when UPDATE YOUR SETTINGS is shown

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1734]
per #1459 we should force user to complete all settings before investment is available. Currently it looks like this
![image.png](https://images.zenhubusercontent.com/5a72da804b5806bc2bc52ecc/fa41ec68-5898-4d48-a841-286ccfafee40)

what to fix:
1. this is visible when **user is not logged in**. this should not affect state of the widget in any way when user is not logged in (obviously)
2. when user is logged in **only INVEST NOW button should be replaced**. all rest stays the same (all counters, ETO progress etc.)

**Comment by glupiawymowka** [comment]
Verified, works fine: 
1. User not logged in - can preview the investment status but can't invest
![image](https://user-images.githubusercontent.com/18315589/48516370-7e1c7280-e863-11e8-9cc4-1be05f758ba4.png)

2. User logged in, no KYC - can preview, is redirected to settings
![image](https://user-images.githubusercontent.com/18315589/48516424-a015f500-e863-11e8-81fc-0d8ccc4ace38.png)
