### ISSUE TITLE
Rename Document Names. Logic Part.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1741]
We need to rename documents. pls. see the image attached. 

The section with templates on the right should have "template" in each document. 
The section below should have "signed" in each name. See the emage below. 

One more template to be added: "Investment Memorandum Template".

@AGA to provide the template for Investment Memorandum. 

<img width="1111" alt="screen shot 2018-11-06 at 14 40 12" src="https://user-images.githubusercontent.com/2290474/48068019-0353b780-e1d2-11e8-910e-5476e429b262.png">

Logic part:

In the ETO investment terms. User could select two types of investment.
 HNWI ETO or RETAIL ETO

Depends on which option is selected we need to show and require different documents. 

For HNWI (High Net Worth Individual) we need to show "Investment Memorandum Template" and 
"Signed Investment Memorandum" See mock up below.
<img width="1045" alt="screen shot 2018-11-06 at 14 45 44" src="https://user-images.githubusercontent.com/2290474/48068296-bc19f680-e1d2-11e8-8c4a-6262e4dec2e2.png">

If Retail ETO is selected no changes. We show same as before in the doc. section.

**Comment by rudolfix** [comment]
@Moejoe90 let's talk before you start implementation. this requires changes on the backend and in data schema

**Comment by rudolfix** [comment]
All new document names and types are added. Backend is also changed properly. Now we are generalizing prospectus and memorandum to Investors Offering Document which has a type `approved_investor_offering_document`, this is the document that investor uploads here:
![image](https://user-images.githubusercontent.com/17202864/48315831-7f3b6e80-e5db-11e8-8a7e-50312b6f74bb.png)

name should be different depending on `allow_retail_investors`:
- if true then "Approved Prospectus" - so the old name!
-if false then "Signed Investment Memorandum"

Second thing to improve:
![image](https://user-images.githubusercontent.com/17202864/48315862-f244e500-e5db-11e8-8384-4b4bcf6ac8b8.png)
Here `Prospectus Approved` is hardcoded. We should change the tag name with the same name and logic as above
