### ISSUE TITLE
Account details. Align text fields.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1750]
Account details. down right info box has ugly aligned text. I suggest to change the grid.  Looks ok on Tablet size screen. on small size gets broken. 
<img width="1322" alt="screen shot 2018-11-06 at 17 14 23" src="https://user-images.githubusercontent.com/2290474/48077381-803d5c00-e1e7-11e8-97a6-67fbe0d20b80.png">

**Comment by glupiawymowka** [comment]
pretty 

![image](https://user-images.githubusercontent.com/18315589/48661664-f9557280-ea75-11e8-9621-e3c935ddd133.png)
