### ISSUE TITLE
Discount Field. Investment Terms. ETO

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1757]
User story: We are offering new type of campaigns with 100K ticket size and for this, we need to create a new campaign type. (HNWI) High Net Worth Investor. So in the Equity Token Offering Term we need to create a new radio button so that ETO user could select which campaign he will be running. 

<img width="845" alt="screen shot 2018-11-07 at 12 17 37" src="https://user-images.githubusercontent.com/2290474/48128599-41f77980-e287-11e8-839c-549a536d996e.png">

- [x] Select button HNWI <> Retail ETO

- [x] Move the Box "ETO is not under Crowdfunding Reg.." up right under the radio button.

Here is proposed design, but we could go with your idea. selector. 
https://zpl.io/agr0gmM

Pls. ping Marcin to get corresponding Swagger Fields. 

- [x]  Add Discoutn (%) field which is optional. (not required). 
<img width="867" alt="screen shot 2018-11-07 at 12 22 59" src="https://user-images.githubusercontent.com/2290474/48128820-f1cce700-e287-11e8-83c6-ef5eca41849b.png">
So the ETO user will have an option to fill White List Discount and Public Sale Discoutn. 

- [ ] If Public Sale Discount is applied we need to display the percentage and discounted price in all places the Investor see the token price. 
-Public View
-Widget (Stripped View)
-Investment summary. 
![neufund_platform_2018 preview mode invision](https://user-images.githubusercontent.com/2290474/48128981-6f90f280-e288-11e8-9443-040b57c9bf5e.png)

Here how we show discoutn in Zeplin.  https://zpl.io/agr8LrQ

**Comment by rudolfix** [comment]
**how to wire new fields**
Select button HNWI <> Retail ETO into `allow_retail_investors` which is a bool. HNWI is mapped into `false`, Retail is mapped into `true`
Public sale discount into `public_discount_fraction` that has type `number` and works exactly like whitelist discount

**Comment by rudolfix** [comment]
**additional validations**
1. if HNWI selected then minimum ticket must be > 100000
2. if Retail selected then trade must be DISABLED
3. there are validations on discounts, see below

```python
        if self._dict["allow_retail_investors"] and self._dict["enable_transfer_on_success"]:
            raise InternalEtoListingValidationException(
                "For retail (prospectus based) ETO, transfers must be disabled", self.eto_id)
        if self._dict.get("whitelist_discount_fraction", 0) < self._dict.get("public_discount_fraction", 0):
            raise InternalEtoListingValidationException(
                f"whitelist_discount_fraction must be greater or equal public_discount_fraction", self.eto_id)
        if self._dict.get("fixed_slots_maximum_discount_fraction", 0) < self._dict.get("public_discount_fraction", 0):
            raise InternalEtoListingValidationException(
                f"fixed_slots_maximum_discount_fraction must be greater or equal public_discount_fraction", self.eto_id)
        min_non_retail_ticket = terms_constants["MIN_QUALIFIED_INVESTOR_TICKET_EUR_ULPS"] / 10**18
        if not self._dict["allow_retail_investors"] and min_ticket_eur < min_non_retail_ticket:
            raise InternalEtoListingValidationException(
                f"For non retail ETO, min ticket is {min_non_retail_ticket} eur", self.eto_id)
```

**Comment by rudolfix** [comment]
**when and how to show discounted tickets**
coming soon!

**Comment by SergejSoft** [comment]
Pls. add another ADD A NEW TAG:
“INVESTMENT MEMORANDUM”
(IT WILL BE DISPLAYED INSTEAD OF “PROSPECTUS APPROVED”

ALSO ADD A NEW TAG:
“INFOBLATT APPROVED”
(IT WILL BE DISPLAYED INSTEAD OF “PROSPECTUS APPROVED”

see mock up:

IF DISCOUNT FOR PUBLIC SALE ENTERED - SHOW DISCOUNT ON PUBLIC PAGE


<img width="878" alt="screen shot 2018-11-13 at 12 05 13" src="https://user-images.githubusercontent.com/2290474/48409601-88901c80-e73c-11e8-8030-4e5018145b50.png">

**Comment by SergejSoft** [comment]
As discussed with @Vanilizer, let's comment out part of the code that shows the discounted price in the striped view. 
So we will show the full price.

**Comment by glupiawymowka** [comment]
done
