### ISSUE TITLE
[landing page] lower registration/newsletter option not visible

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1758]
This is how the lowest part of the landing page looks. 
input for newsletter is barely visible

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/8b27735a-50e1-4d07-a817-c6d6b78fac25)

**Comment by desfero** [comment]
@glupiawymowka @mpneu BTW the same issue is also in documents section 
![image](https://user-images.githubusercontent.com/7031578/48304197-f4447080-e515-11e8-9a78-16b48d891984.png)

We can increase bottom padding if everyone agrees 
![image](https://user-images.githubusercontent.com/7031578/48304238-cad81480-e516-11e8-9585-d160d745df85.png)

**Comment by SergejSoft** [comment]
Fully agree!

**Comment by glupiawymowka** [comment]
looks fine now 

![image](https://user-images.githubusercontent.com/18315589/48499222-3f24f780-e838-11e8-8b8d-d5ddbc358b6e.png)
