### ISSUE TITLE
Fix false positives during visual regression

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1770]
**Background:**
There are some false positives during visual regression check:
- https://s3.eu-central-1.amazonaws.com/neufund.visual.regression/b69900a859064af31957527769a19e837867e293/report/index.html
- https://s3.eu-central-1.amazonaws.com/neufund.visual.regression/24e45da9220f0d9c7220b31f694a7fd53cedf18e/report/index.html

Please investigate and try to fix them.

**Comment by Moejoe90** [comment]
How do you know they are positives this is dangerous. It would be great to add more info regarding this
