### ISSUE TITLE
please fix! you should not be able to start verification without backup codes!

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1778]
![image](https://user-images.githubusercontent.com/17202864/48267596-0a2d3500-e433-11e8-9215-43c50cbb9bf3.png)

If backup codes are not verifies you should not be able to start verification process!

**Comment by glupiawymowka** [comment]
FIXED 

![image](https://user-images.githubusercontent.com/18315589/48343247-2c60c600-e672-11e8-9a7a-d3417f5e6226.png)
