### ISSUE TITLE
[KYC] PEP tooltip fix

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1797]
This is the current look of the PEP tooltip

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/e15882c0-508e-4b6f-bc6f-05cf5b962791)

The US Citizen tooltip to compare

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/83e0df69-c4b7-4c2d-8594-0cfd71cef496)

Please make them similar, I also think there is no need to put "1." if there is only one point

**Comment by shanile** [comment]
We already have a ticket on this topic https://github.com/Neufund/platform-frontend/issues/995 please check

**Comment by glupiawymowka** [comment]
checked
