### ISSUE TITLE
Add transactional emails

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1815]
We need to add this email for transactional email.

The one we definitely need is Whitelist email. LIne 23. 
The text and scenario for each email.

https://docs.google.com/spreadsheets/d/1DriOB6fv_asroBbVdJsz8A48Lbk936PE9UMO3lMjTdU/edit?usp=sharing

**Comment by glupiawymowka** [comment]
whitelisting email works, cool
![image](https://user-images.githubusercontent.com/18315589/48939204-c26adb00-ef13-11e8-8bf6-efacaaaf8b41.png)
