### ISSUE TITLE
Place Widget (ETO) on neufund.net

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1816]
Ticket assigned is addigned to Wiktor, with Tomek and Thomas to support or communicate. 

Place Firth Force Widget (The one you were making) on a staging of a corporate website. www.neufund.net  Pls. talk to Tomek as he knows how this needs to be deployed. 

Pls. talk to Thomas, because he is updating some fields and new tag which will be displayed in ETO Widget.
Ticket that Thomas is working: https://github.com/Neufund/platform-frontend/issues/1757

**Comment by banciur** [comment]
@SergejSoft Work on neufund.net is mainly done by Andy and it's overseen by Ula. She is setting priorities etc there.
