### ISSUE TITLE
Sign In |Registartion fixes

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1827]
1.Make "Help" and "Register" bold. <strong>
![Screen Shot 2018-11-14 at 12.02.49.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/142f1425-2119-4eb0-bea0-c54cbde84b3a)
2. Llink button "View Tutorial" to https://support.ledgerwallet.com/hc/en-us/articles/360000609933-Lost-device-PIN-code-or-recovery-phrase
![Screen Shot 2018-11-14 at 12.11.28.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/3fe3fb5b-4c6c-4709-923a-17b3cc72cdcf)

**Comment by glupiawymowka** [comment]
This is fixed, but something else seems to get broken on the same screen: 
1. This is the view from .net env
![image](https://user-images.githubusercontent.com/18315589/48661742-3b32e880-ea77-11e8-91e2-716601e61e90.png)

2. This is the view from .io
![image](https://user-images.githubusercontent.com/18315589/48661751-70d7d180-ea77-11e8-9dcc-67bf66deda40.png)

* please make sure that the placeholders stay grey
* please remove underline from "Help" button on the left, to make it consistent with "Login" buton on the right
