### ISSUE TITLE
Platform Landing. New Box

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1830]
We need to add one more box and circle to https://platform.neufund.org/

Mockups below:
![Screen Shot 2018-11-14 at 14.41.18.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/23816e79-df84-4cdc-bad4-c480dc800534)![Screen Shot 2018-11-14 at 14.41.03.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/c4dd3340-524b-45c6-b15e-5da592c83917)

Design and souce file will be pasted in the ticket by @mpneu Mikolaj.

Text to add to locale files: 
"Neufund provides an end to end solution for asset tokenization and issuance. Our set of protocols for enhanced ownership allows anyone to give real-world assets a representation on the Ethereum Blockchain in form of legally-binding security tokens."

"Driven by the idea of making the investment world more inclusive, Neufund has already shaped a better future of fundraising. Looking at their progress over the last 2 years, I’m excited for what's to come" – Frank Thelen, Freigeist Capital

@drakkein pls. use the other boxes as an example.

**Comment by mpneu** [comment]
Updated mockup:
https://drive.google.com/file/d/1CGgkCAGxpaDcjXNjmsRMw_A8jLz2wUR5/view?usp=sharing

/eto-card/ Banner:
https://drive.google.com/file/d/1s-0K0-60sGwcUqG2w__kN1ZJiRivSdxO/view?usp=sharing

LandingHeader-module__company-image__ circle logo: 
https://drive.google.com/file/d/1CffGtkV8LNmaelUI0trpjb1hUu16jnW5/view?usp=sharing

EtoOfferingCard-module__image-wrapper___ image on which quote lands:
https://drive.google.com/file/d/183cec-QCg6Xi7mJdEqTrdwmVY9IyCKjv/view?usp=sharing

Below all text that needs to be added:
Tag-module__tag___29ist ghost-bold white ml-2

BLOCKCHAIN

Tag-module__tag___29ist ghost-bold white ml-2

GERMANY

EtoOfferingCard-module__name___13Or_

NEUFUND

EtoOfferingCard-module__description___3yAhR

Neufund provides an end to end solution for asset tokenization and issuance. Our set of protocols for enhanced ownership allows anyone to give real-world assets a representation on the Ethereum Blockchain in form of legally-binding security tokens.


EtoOfferingCard-module__round-label___2JhoY

<span> SERIES B </span>


EtoOfferingCard-module__quote___yJ17M

<p>
“Driven by the idea of making the investment world more inclusive, Neufund has already shaped a better future of fundraising. Looking at their progress over the last 2 years, I’m excited for what's to come.”
</p>

<p>
Frank Thelen, Freigeist Capital
</p>
