### ISSUE TITLE
Remove deprecated React lifecycle hooks

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#1837]
**Background:** 
Due to the async rendering feature that is going to be shipped with React 17 a couple of hooks are deprecated (`componentWillReceiveProps`, `componentWillMount` and `componentWillUpdate`). Please refer to docs (https://reactjs.org/docs/react-component.html) for details.

**Comment by drakkein** [comment]
Automated tests are passing, but would be nice to verify if there is no any strange behaviour across platform pages.
