### ISSUE TITLE
[stage, withdraw] please fix the error message when transaction was rejected

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1838]
I'm sure it worked before, but now rejecting a transaction on ledger/Metamask results with the followig message: 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/48a3bc6c-bb09-493c-859b-a8a6d6c0f3b9)

**Comment by desfero** [comment]
Was already changed by @Vanilizer
