### ISSUE TITLE
PItch form bug

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1842]
<img width="871" alt="screen shot 2018-11-15 at 15 20 39" src="https://user-images.githubusercontent.com/2290474/48558632-0e04ff80-e8ea-11e8-9a85-828795b66418.png">

**Comment by glupiawymowka** [comment]
done
![image](https://user-images.githubusercontent.com/18315589/48945167-a83bf780-ef29-11e8-8d46-1c2788fd9d74.png)
