### ISSUE TITLE
Public View|Investor section 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1848]
<img width="1008" alt="screen shot 2018-11-16 at 14 39 18" src="https://user-images.githubusercontent.com/2290474/48624779-98626780-e9ad-11e8-9334-883e8ca195c6.png">

**Comment by glupiawymowka** [comment]
works now
![image](https://user-images.githubusercontent.com/18315589/49453586-bc161200-f7e3-11e8-94c0-3c04be4c0a83.png)
