### ISSUE TITLE
ETO. Field formatting| Investment Terms.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1849]
Pls. only change number format with a gap between thousends. 4 800 instead of 4888. 
So we would have 459 000
https://stackoverflow.com/questions/16637051/adding-space-between-numbers

For now ingnore the comments with million. >M.  

<img width="1012" alt="screen shot 2018-11-16 at 14 44 50" src="https://user-images.githubusercontent.com/2290474/48625000-40783080-e9ae-11e8-850d-7794fee07af1.png">

**Comment by glupiawymowka** [comment]
the point about spacing is done:
![image](https://user-images.githubusercontent.com/18315589/48909896-d0b2eb80-ee6e-11e8-83c6-2355bb2e1412.png)
