### ISSUE TITLE
Pledging returns 400. Staging.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1850]
@rudolfix, pls. detele max pledging amount. Now it's 5000. 

@SergejSoft commented on [Fri Nov 16 2018](https://github.com/Neufund/platform-backend/issues/1206)

Maximum pledging size dosn't return an error. 
MInimu Pledging 500 gives an error, but maximum dons't show user any error. 

@desfero I suggest adding the same logic we have for the minim pledging. Now allow the user to enter an amount higher than max. pledging amount. 

<img width="1261" alt="screen shot 2018-11-16 at 15 04 03" src="https://user-images.githubusercontent.com/2290474/48626003-0b211200-e9b1-11e8-99c0-3e16d812c126.png">

---

@banciur commented on [Fri Nov 16 2018](https://github.com/Neufund/platform-backend/issues/1206#issuecomment-439407889)

@huesforalice @rudolfix 
 Around moment when ticket was created there was sentry exception
`PledgeNotWithinBoundsException: Pledge with amount 8000 is not within bounds of 500.000000 and 4999.875003 for eto id 0x0F232924f...`
https://neufund.slack.com/archives/CB2B616SG/p1542376941000800

I cannot login into vpn now to copy paste whole information. But it suggests that error might be on frontend

---

@SergejSoft commented on [Fri Nov 16 2018](https://github.com/Neufund/platform-backend/issues/1206#issuecomment-439410341)

Yes, I guess it's front end. Will move to front.

**Comment by Moejoe90** [comment]
@drakkein 
I think you have an idea maybe about this since its related with 
https://github.com/Neufund/platform-frontend/pull/1754

**Comment by rudolfix** [comment]
that was edge case where ETO max cap was below max ticket

**Comment by Desperado** [comment]
Can't reproduce this now.
