### ISSUE TITLE
Widget: new state

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1851]
Widget: Add a new state for presale investors only with the text:
“Pre-sale cap reached, public eto starts in” and show the Countdow
related to: #1635

<img width="449" alt="screen shot 2018-11-16 at 15 45 36" src="https://user-images.githubusercontent.com/2290474/48628122-b1bbe180-e9b6-11e8-9322-96a63fab4a1a.png">

**Comment by Vanilizer** [comment]
Hey, everything is done, BUT the widget should be clickable on its full length.

Currently I can only click around ELDO TOKEN to go to listing page. 

(Despite the "More details" link - this is implemented correctly and is for the ultra stupid)
