### ISSUE TITLE
[ALL ENV] "Error while trying to get pending transaction" - recurring error bar

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1861]
I couldn't reproduce it on master, but received the screen with this problem appearing there too.
Both on .io and .net I could reproduce it (mainly by leaving an open, logged in platform tab for a couple of hours, but sometimes the error bar showed up earlier ).

This problem occurred for different wallets, different account states (verified, unverified etc)

1. Sometimes it's only a single appearance, but anyway please let us know what is the nature of this problem, so some clearer wording can be prepared dor the error bar

2. sometimes, as you can see in the screen below, this bar shows up exactly every 60 seconds

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/8282f222-937d-4c2f-88b2-f52930f1b696)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/b55a6afc-d2eb-4557-a68e-6fb598f57013)

https://platform.neufund.net/api/user/pending_transactions/me shows: 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/f42144ad-2b5d-4c1e-8532-7f34421197fb)

**Comment by Moejoe90** [comment]
After research, I found the reason 
This happening when you open two browser pages and log out from one of the open browser sessions. 
The way to deal with this basically adds an event listener or a channel listener that listens to events.

**Comment by rudolfix** [comment]
will be fixed in #1942 also error message is hidden now

**Comment by glupiawymowka** [comment]
This seems to be solved for now
