### ISSUE TITLE
[USABILITY FIX] REGISTER | Ledger - add paragraph 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1867]
Under "Select your wallet for registration" headline, add the following paragraph and format with current styling:

“Your Ledger Nano has many addresses. Your ETH and NEU balance is displayed next to each address. Please choose the one you want to register with.”

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/5306e3a6-d09f-484d-a208-96dc7707214a)

**Comment by AlexeyTuboltsev** [comment]
also solves #1870

**Comment by glupiawymowka** [comment]
done <3
