### ISSUE TITLE
[USABILITY FIX] KYC CONFIRM - add paragraph 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1885]
below the header, please put the following paragraph:

"To submit your identity verification request, please provide your signature on your Ledger Nano or on MetaMask."

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/e9869511-66c5-48c6-8848-36b380e53aac)

**Comment by AlexeyTuboltsev** [comment]
duplicate of #1901
