### ISSUE TITLE
[USABILITY FIX] KYC WIDGET - new wording + link

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1899]
Aga wanted to change the text, but I still can't see it. 
If there is another text than given below, please change it into this one: 

1. PENDING VERIFICATION - 

"Thank you for submitting your identity verification request! We will review your documents within 1 business day and contact you if we require further information. Otherwise, we will notify you by email once your account has been successfully verified.

To contact support, please click here.” ---> link to freshdesk ticket

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/c83ab6da-ac71-4455-b459-5a6da7f80da3)

2. REJECTED VERIFICATION
“We regret to inform you that after careful review, your identity verification request has been rejected. To contact support, please click here” ---> link to freshdesk ticket

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/f89324de-5c8f-4cf1-bf4c-7138ad25ca98)

In both cases, please make "HERE" clickable, and link it to : https://support.neufund.org/support/tickets/new

**Comment by SergejSoft** [comment]
TEST rejected Verifications.
