### ISSUE TITLE
[USABILITY FIX] LOGIN & REGISTER WITH LEDGER - visual fixes

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1904]
1. Please remove “Ensure you enable “Browser support” on your ledger” 
2. Always show all 6 steps as deafult
3. DESIGN - we need an icon with "Contract Support", similar to the current one

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/c2cfbe20-c2ce-49df-8241-037748cf98fd)

**Comment by glupiawymowka** [comment]
please pause this ticket for now

we need the design though

**Comment by mpneu** [comment]
@glupiawymowka 

icon with "Contract Support":

https://drive.google.com/file/d/1ibdPt5PmkzdiDxXG9BSffyLgYqxW77wS/view?usp=sharing
