### ISSUE TITLE
[USABILITY FIX] NAVIGATION BAR - visual fixes 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1905]
1. Please bold the active tab (make the green bar ~3xbolder + bold the module name when active)
2. Hide Identity tab for now 
3. Take the fingerprint-icon from Identity and use it for Settings (currently named "Profile") 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/4fe6c7f1-ce2e-4cec-9739-63bb1dfe4eae)

**Comment by desfero** [comment]
Double left border twice and bold active text

**Comment by desfero** [comment]
@glupiawymowka discussed with @mpneu and we will change background color without making text bold

**Comment by glupiawymowka** [comment]
looks sooo pretty now! closing
