### ISSUE TITLE
[USABILITY FIX] DASHBOARD - add "coming soon" placeholder

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1907]
Below the ETO Opportunities section, please add the following placeholder :

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5bf2f66b072fb97e8f6925e8

so it looks like here : 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/07c70ae0-22b2-4a1c-9e09-b32702c3dd91)

**Comment by mpneu** [comment]
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5bf3d72e9befb87e83dda862
