### ISSUE TITLE
Backoffice/Platform - Unable to upload .pdf file

### ISSUE THREAD

**Issue by kelexa** [Neufund/platform-frontend#1915]
Hi,

I get this message when trying to upload a normal pdf file

![image](https://user-images.githubusercontent.com/40295416/48770538-f00b1680-ecbe-11e8-824f-9712d2741fe8.png)

The client is not being able to upload it from platform either. He was however able to upload a different .pdf file before.

**Comment by kelexa** [comment]
this only seems to happen with account with wallet address 0x689764c4070B804a5d019267DE06b9A92e2F2809

**Comment by rudolfix** [comment]
Issue moved to [Neufund/platform-backend #1336](https://github.com/Neufund/platform-backend/issues/1336) via [**ZenHub**](https://www.zenhub.com/)
