### ISSUE TITLE
[USABILITY FIX] PROFILE - widgets need to fit new contents - important

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#1930]
longer content caused the issue when it's overlapping the widget area, please see the examples: 

![image](https://user-images.githubusercontent.com/18315589/48782692-088b2900-ecdf-11e8-873f-10589864039e.png)

![image](https://user-images.githubusercontent.com/18315589/48782737-22c50700-ecdf-11e8-98c6-42b6f12bc914.png)

also, lower widgets are now bigger  and look a bit empty

(.net)

![image](https://user-images.githubusercontent.com/18315589/48782527-adf1cd00-ecde-11e8-8234-c56885aa4d77.png)

(.io)
![image](https://user-images.githubusercontent.com/18315589/48781877-34a5aa80-ecdd-11e8-8f3d-28e7c1cc1d83.png)

please fit the widgets to the new contents

**Comment by SergejSoft** [comment]
pls. drop the last sentence in the box. IDENTYTI verification.

**Comment by glupiawymowka** [comment]
Better. Can we also do something with the buttons on different height? 

![image](https://user-images.githubusercontent.com/18315589/48913312-4c656600-ee78-11e8-833e-29f402b87e12.png)
