### ISSUE TITLE
Text formating.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1949]
TEXT in emial verificaiton is ""strong"" Please make same size and format as all oher boxes.
<img width="823" alt="screen shot 2018-11-20 at 21 37 37" src="https://user-images.githubusercontent.com/2290474/48801495-ce388080-ed0c-11e8-9e98-3bec96820253.png">

Once verified. the text is normal. 
<img width="409" alt="screen shot 2018-11-20 at 21 42 19" src="https://user-images.githubusercontent.com/2290474/48801656-3a1ae900-ed0d-11e8-9495-2020cd111d39.png">

**Comment by glupiawymowka** [comment]
done
