### ISSUE TITLE
KYC form - Validation on required field

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1952]
"Date of birth" in KYC forms is a required field. It  currently has no validation when empty and no "*".

Please add "*" (make required field on the front end)
And validate when user clicks - "continue"

![image](https://user-images.githubusercontent.com/26923972/48823137-03ba8980-ed60-11e8-8a20-3840524a29ec.png)

**Comment by huesforalice** [comment]
The validation works correctly. I have only added the star for now.
