### ISSUE TITLE
Investment Widget fixes

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1969]
- [x] 1. Please change the percantages "100%" and "500% into "Min. Investment Amount" and "Max. Investment Amount"
- [x] 2. Please remove "0%"
On all versions of the widget.
![image](https://user-images.githubusercontent.com/26923972/48853761-81a68100-edb0-11e8-90e8-77d998c21371.png)

- [x] 3. Please add a headline "Key investment terms:" in the same style as "Pre-money valuation" and center the whole section vertically
![image](https://user-images.githubusercontent.com/26923972/48853861-b74b6a00-edb0-11e8-9a98-11f80cc9a589.png)

**Comment by rudolfix** [comment]
those are not investment amounts but amounts of tokens. that will be mixed up with the data on the left. ticket postponed until we clean it up.

**Comment by mpneu** [comment]
Desktop / tablet / mobile views

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5bf6b92096cd6f1246247991

**Comment by falinebambi** [comment]
<img width="757" alt="screen shot 2018-11-30 at 12 29 47" src="https://user-images.githubusercontent.com/17235402/49286860-bc3ca780-f49b-11e8-937e-bbcbdb4c0361.png">
@desfero here are the designs for with the min / max investment amount update

**Comment by glupiawymowka** [comment]
done
![image](https://user-images.githubusercontent.com/18315589/49453283-1a8ec080-f7e3-11e8-94a8-aba6c79de8ff.png)
