### ISSUE TITLE
Bookbuilding tool - fixes

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1971]
1. Add headline "Subscribe to the whitelist" in the bookbuilding tool - pledge state
2. Change "€_____BACK NOW" to
"Indicate your commitment <br>
€___________ COMMIT"
3. Add a tooltip (same as next to "reveal my email") next to headline "Subscribe for the whitelist"
--> Content of the tooltip:
"The whitelist is available to a limited number of investors on a first come first serve basis. Whitelist participation grants investors access to the typically more favorable investment terms of the presale.   

Please note that the whitelist is merely for informational purposes. It does not create any legally binding obligation for you. Accordingly, you are not bound to your whitelist commitment and may change your commitment at any time. However, if your whitelist commitment is at any point changed to 0, you will be removed from the whitelist and unable to access the investment terms of the pre-sale. "

![image](https://user-images.githubusercontent.com/26923972/48854317-e7dfd380-edb1-11e8-9d07-342127fbb7b7.png)

4. Once investor enter amount and clicked "back now/commit" headline should change to "Congratulations! You’re on the whitelist"

![image](https://user-images.githubusercontent.com/26923972/48854400-24133400-edb2-11e8-8ba7-5ed65e39c8cb.png)

5. Once investor deletes his commitment change headline to: "You have been removed from the whitelist"

**Comment by mpneu** [comment]
Desktop / tablet / mobile views

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5bf6b92096cd6f1246247991

**Comment by glupiawymowka** [comment]
done
