### ISSUE TITLE
Bookbuilding tool - errors in logic

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1972]
1. At the moment when you enter a pledge in the bookbuilding tool, if you have 0 ETH in the wallet you receive a message that you have not enough funds to bookbuild. This is an error. Pledging is for free and independent of wallet balance. 
USER shoudl be able to bookbuild regardless of wallet balance. 

2. Whitelisting (bookbuilding) should be only visible to kyc’ed (Verified) investors.

**Comment by rudolfix** [comment]
ad 2. why? it's impossible to invest less so there's no point of pledging less. I will postpone this ticket until we clear that up

**Comment by Vanilizer** [comment]
Ok we can postpone ad. 2 BUT we have to do 1 and 3. This is priority for 27th of Nov.

**Comment by glupiawymowka** [comment]
both points fixed
