### ISSUE TITLE
Investment flow - wallet selector

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1973]
Wallet selector:
Now:
Active state black text+green bar, inactive state grey text, no bar

Please change to:
Active state: black text + green bar
Inactive state: black text + no bar

![image](https://user-images.githubusercontent.com/26923972/48854975-76a12000-edb3-11e8-85e6-06b5030adbea.png)

**Comment by glupiawymowka** [comment]
text is black, active tab gets green bar + black currency icon. Looks good for now
![image](https://user-images.githubusercontent.com/18315589/49023035-93b06700-f196-11e8-95ba-0cc142d42e57.png)
