### ISSUE TITLE
ETO TIMELINE tweak on public view

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1978]
Move "ETO start" flag between pre-eto and public eto phases.

![image](https://user-images.githubusercontent.com/26923972/48856372-7f472580-edb6-11e8-8d48-b6691993830d.png)

**Comment by glupiawymowka** [comment]
done
![image](https://user-images.githubusercontent.com/18315589/48914627-5be6ae00-ee7c-11e8-980f-215e30bfc38b.png)
