### ISSUE TITLE
Change wording for error message

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1979]
Change "Error while trying to get pending transaction" to "Please try again later. We cannot process this action while a transaction is pending. "

I coulnd find it in the file.

![image](https://user-images.githubusercontent.com/26923972/48856462-bae1ef80-edb6-11e8-8c09-cb934b9ca7ac.png)

**Comment by rudolfix** [comment]
another wrong ticket

**Comment by rudolfix** [comment]
no prosze was, przeciez nowy komunikat nie ma sensu. czemu zdejmowac postponed z rzeczy ktore chce przedyskutowac? @Vanilizer @SergejSoft

**Comment by Vanilizer** [comment]
So either we fix the error or change the error message to something totally generic, so it does not confuse a user. If it stays like this is confuses users too.
