### ISSUE TITLE
Investment Flow - handle cases when investor invests for a second time

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#1987]
If investor already participated and is topping up over previous investment we need a few additional things:
1. we already have investor ticket in state, ask @desfero where is it. but this state should be reloaded when investment window is opened. (`IInvestorTicket`)
2. take existing equity tokens and NEU from (1) and put them into green part as initial values:
![image](https://user-images.githubusercontent.com/17202864/48865885-3b154e80-edd1-11e8-8f05-515934b86385.png)
leave empty if initial values are 0 in the ticket or ticket does not exist in the state
3. when calculating new ticket, add it to initial values to simulate total amount of NEU and tokens
4. on the summary show just new values

5. now we need to modify minimum and maximum ticket values you get from `calculateContribution`. 
- find invested euro equivalent `IInvestorTicket::equivEurUlps`
- actual min amount = calculateContribution::minTicketEur - equivEurUlps. cannot be less than token price! (you can take non-discounted one)
- actual max amount = maxTicketEur - eurEquiv. if < less than token price then set it to 0
- note than max amount can be less min amount (when investor invested full max ticket the max amount will be 0)

remember to show this correctly:
 
![image](https://user-images.githubusercontent.com/17202864/48874015-36f92900-edf1-11e8-863d-6c94fd87c58d.png)
rename MIN. TICKET SIZE to MIN. AMOUNT

it's all a little bit crude but I do not see better quick solution for that

please remember to update artifacts and backend hash for tests!

**Comment by falinebambi** [comment]
@trival lets do logic like this for now and redesign for on the next round.

**Comment by trival** [comment]
after discussion with @rudolfix @falinebambi we decided to not implement (2) and (3), but instead display the text "You already invested in this ETO. The current investment will be added to your previous one. See your portfolio for more details."

**Comment by rudolfix** [comment]
@trival please implement the warning text. see comments in pr #2141 

also warning text for ICBM wallet (taht you do not get new NEU) disappeared

**Comment by glupiawymowka** [comment]
min ticket changed correctly
![image](https://user-images.githubusercontent.com/18315589/49529456-56468a80-f8b6-11e8-9855-5b23a7beb2c6.png)

but as @rudolfix said, I see no warning about no NEU reward for using ICBM wallet 

![image](https://user-images.githubusercontent.com/18315589/49529382-2d25fa00-f8b6-11e8-81a1-18e7e5615707.png)
