### ISSUE TITLE
WORDING Error messages to change

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1991]
1. Please change "Recovery phrase entered is not correct" to "Something went wrong. Please enter your 24 word recovery and try again." I could not do so myself

![image](https://user-images.githubusercontent.com/26923972/48892341-2622d480-ee3e-11e8-805a-a7d37274f26e.png)

2. Please also change "Timeout when signing message" to "Oops! Looks like the request timed out. Please try again."

3. Please change "Our server is experiencing..." to "We were unable to confirm your ownership due to a connection error. Please try again or contact support."
![image](https://user-images.githubusercontent.com/26923972/48892808-2a9bbd00-ee3f-11e8-9999-fb7d516292cc.png)

**Comment by glupiawymowka** [comment]
done
