### ISSUE TITLE
Reset Password Step - Fixes

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#1992]
Please delete headline "Reset your Password" and add a text in a bigger font: "A new access link has been sent to your email. <b>Please save this link.</b> You will need it to access your account."

![image](https://user-images.githubusercontent.com/26923972/48892586-b234fc00-ee3e-11e8-89b5-3957250c7184.png)

**Comment by glupiawymowka** [comment]
yay!
![image](https://user-images.githubusercontent.com/18315589/49029329-9dd96200-f1a4-11e8-9091-45a0c6875221.png)
