### ISSUE TITLE
KYC flow. Production.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2007]
On the PRODUCTION environment. When KYC is done for ISSUER.
Ledger walet. 
The user skips first two steps and lands in the Beneficial Owners. 
![image 10](https://user-images.githubusercontent.com/2290474/48915794-38256700-ee80-11e8-8752-93596638b650.png)

**Comment by glupiawymowka** [comment]
goes to step 2 now, which seems correct
