### ISSUE TITLE
URGENT - PUBLIC VIEW - wrong ISHA displayed in listing page

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2008]
![image](https://user-images.githubusercontent.com/26923972/48917508-8853f780-ee87-11e8-93a9-b2fbc4debd69.png)

The public view shows the "Signed ISHA". It should show the "ISHA"

This is a serious bug.

**Comment by Moejoe90** [comment]
@Vanilizer 
I tested now on master it is currently the unsigned ISHA

**Comment by glupiawymowka** [comment]
I also see the correct one now on .io
