### ISSUE TITLE
BUG in whitelisting process

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2014]
Once you click "delete my commitment" in the whitelisting tool you receive a popup to "confirm your pledge" - this is wrong. 

Please change the wording of this popup to:

Headline: "Remove my commitment"
text: "Please confirm that you would like to remove your commitment and therewith be removed from the whitelist of this ETO."

![image](https://user-images.githubusercontent.com/26923972/48934188-554f4980-ef03-11e8-8dd2-22dfd2bbaf79.png)

**Comment by glupiawymowka** [comment]
done 

![image](https://user-images.githubusercontent.com/18315589/49458756-bb827900-f7ed-11e8-8b52-478ef3caf9ad.png)
