### ISSUE TITLE
BUG in widget behaviour

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2015]
As a verified and not ICBM user I should be able participate in any public sale listing on Neufund. 

Eldo Token is in PUBLIC SALE STATE. However I see the progress bar and the button asking me to verify

This must be a bug. 

![image](https://user-images.githubusercontent.com/26923972/48934302-b7a84a00-ef03-11e8-9180-0b6ff8af83a4.png)

**Comment by Moejoe90** [comment]
@rudolfix 
I just checked this ticket it appears to me that there might be some difference between the back-office KYC approval and on Chain Claim approval

**Comment by rudolfix** [comment]
it's related #1424 - we react to onchain status here not to the backend. we should possibly return verified when both backedna and on-chain say so

**Comment by Moejoe90** [comment]
@rudolfix can you check 
https://github.com/Neufund/platform-frontend/pull/2061
This does exactly that

**Comment by rudolfix** [comment]
#2061 would solve temporarily our problem
