### ISSUE TITLE
BUG Widgets have different heights

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2016]
Hey,

yesterday you said all widgets have to have a specific height, do to external implementation. 

In the whitelisting stage the widget is higher than in the invest now state. 

I believe this is a bug.

![image](https://user-images.githubusercontent.com/26923972/48934558-d3f8b680-ef04-11e8-8430-dbffcf44bdb2.png)

**Comment by Vanilizer** [comment]
The widget height also varies on public view vs. dashboard  - result: text and icon on public view is centered vertically and on dashboard it is not. 

Please center vertically the text on dashboard and unify the height of widget.

![image](https://user-images.githubusercontent.com/26923972/48980422-e7547f00-f0c8-11e8-94fa-b28a14c62c80.png)

**Comment by glupiawymowka** [comment]
*tested on .net*
