### ISSUE TITLE
Widget- display info

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2018]
Currently we display:
<TOKEN NAME>
<TOKEN SYMBOL>

please change this to:

<BRAND NAME>
<TOKEN NAME> (<TOKEN SYMBOL>)

E.G.

Instead of 

FORCE
FTH

show

NEUFUND
FORCE (FTH)

@trival we discussed this but I dont want to loose it;)

![image](https://user-images.githubusercontent.com/26923972/48934698-69944600-ef05-11e8-8787-89cd53630b5e.png)

**Comment by glupiawymowka** [comment]
done
