### ISSUE TITLE
Change "Your Reference Number" in Direct Bank Transfer

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2021]
Hey Marcin,

as discussed we need to adjust the reference number for the Direct  Bank  Transfer

Currently: NF <wallet address>

Would be easier for the bank if it would be:
Investment Amount, Reservation and Acquisition Agreement from <date>

![image](https://user-images.githubusercontent.com/26923972/48935615-80886780-ef08-11e8-9c44-4a932f2a093a.png)

**Comment by huesforalice** [comment]
I'm not sure what exactly I should write there. Could you give me an example of the whole subject that should go there?

**Comment by huesforalice** [comment]
@Vanilizer @rudolfix

**Comment by Vanilizer** [comment]
"Investment Amount, Reservation and Acquisition Agreement from 27.11.2018, NF <number>"

**Comment by Vanilizer** [comment]
what changes everytime is the "date" and the "number after NF"
