### ISSUE TITLE
Investment Flow - Direct Bank Transfer

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2022]
If user chooses Direct Bank Transfer

Make the "ETH input field" grey and read only. It should not be editable. This confuses the user.

![image](https://user-images.githubusercontent.com/26923972/48935677-c2191280-ef08-11e8-9860-bb26b662efda.png)

If the Gas Cost is 0 for a Direct Bank Transfer please hide it.
![image](https://user-images.githubusercontent.com/26923972/48935739-f55ba180-ef08-11e8-93f7-b27ae4a0b145.png)

**Comment by rudolfix** [comment]
1. OK to make ETH field gray
2. OK to hide gas costs
3. why? why should I not be able to see how much I'm investing in ether?

**Comment by Vanilizer** [comment]
ok lets do 1. and 2.

3. is confusing for a EUR transfer investor. but if you think it should be there, leave it :) Can you assign this ticket?

**Comment by glupiawymowka** [comment]
done

![image](https://user-images.githubusercontent.com/18315589/49453707-f4b5eb80-f7e3-11e8-8564-a490c9412adf.png)
