### ISSUE TITLE
[IMPORTANT USABILITY] when countdown is at 0 it just stays there - please refresh state ^

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2029]
!We need to improve this: it's a kind of thing that looks LAME (not doing anything bad btw.)
People often wait to invest first to get best NEU price or cheap slots and wait for the counter to count to zero. If we got stuck they will be extremely disappointed. 

When counter goes to zero we should refresh ETO state. This will however work only if the client clock is in perfect sync with Ethereum network clock. otherwise we can still land in the same state.

This may create crazy refresh loop so we may beed a wait time before the refresh

**Comment by glupiawymowka** [comment]
@rudolfix to test this properly, @Desperado and I need to know if/how we can get an ETO in such state (without waiting for a month :D)
