### ISSUE TITLE
URGENT: Update of platform.neufund.org landing page

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2032]
We have update the landing page for investors for our ETO

We are only changing the header, hiding the middle section of the page, adding the widget and changing the wording.

Please see design in zeppelin: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5bfbff1ea6dc504991a06ade

![platform update](https://user-images.githubusercontent.com/42346526/49019873-45e43080-f18f-11e8-8be9-be804878e97d.png)

**Comment by rudolfix** [comment]
@drakkein mind that contracts are not initialized on landing page yet. so this change may require a refactor of app init

**Comment by mpneu** [comment]
Updated the Zeppelin link in ticket

Please to replace the ETO card img with this one:
https://drive.google.com/file/d/1bMM0xsv22yXuh_4jgDtcdswAQDsPoBUH/view?usp=sharing
