### ISSUE TITLE
Investment flow - Change "Direct Bank Transfer" to "Direct Bank Transfer (EUR)"

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2034]
Investment flow - Change "Direct Bank Transfer" to "Direct Bank Transfer (EUR)"

![image](https://user-images.githubusercontent.com/26923972/48951135-b431b480-ef3d-11e8-9e3b-a7ab62d23348.png)

**Comment by glupiawymowka** [comment]
done
