### ISSUE TITLE
Add a tooltip in Direct Bank Transfer Popup

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2035]
Please add a tooltip with following text to the check box text:

"Transaction fees are necessary to process transactions on the Ethereum Network. These fees are paid in ETH. For your convenience, we convert your 10 EUR to ETH to cover your initial transaction costs. Please keep in mind that you may need to deposit further ETH at a later point depending on your transaction activity."

![image](https://user-images.githubusercontent.com/26923972/48951285-45a12680-ef3e-11e8-99e5-6b61f7291e4b.png)

**Comment by glupiawymowka** [comment]
*tested on .io*
![image](https://user-images.githubusercontent.com/18315589/49159188-33e7c680-f324-11e8-9354-f236348188ff.png)
