### ISSUE TITLE
Fix modals usability issues

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2043]
**Background:**
Current modal implementation has a couple of usability issues. 
To improve it we need to:

- [ ] On Dialog Open, Set Focus
- [ ] On Dialog Close, Return Focus to Last Focused Element
- [ ] While Open, Prevent Tabbing to Outside the Dialog

Less problematic but also need to be fixed
- [ ] Markup the Dialog and Dialog Overlay Appropriately

**Techical notes:**
There is nice article that explains each of problems above https://bitsofco.de/accessible-modal-dialog/.

**Comment by AlexeyTuboltsev** [comment]
we'd better do it in course/after moving to design system

**Comment by desfero** [comment]
Seems to be fixed already
