### ISSUE TITLE
Direct bank transfer popup - wording + tooltip

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2046]
Alexey, 

as we suspected copy cannot handle too many "bolds" in the text. As you can see in the screenshot (this is on production by today) In the first text paragraph you can see <STRONG> in text. 

Could you fix it the way that anything marked STRONG should be bold and orange? 

This is also connected to adding a tool tip to the check box: https://github.com/Neufund/platform-frontend/issues/2035

![image](https://user-images.githubusercontent.com/26923972/48980395-8af15f80-f0c8-11e8-8734-cdc5ff8b868c.png)

**Comment by glupiawymowka** [comment]
*tested on .io*

![image](https://user-images.githubusercontent.com/18315589/49159042-dce1f180-f323-11e8-9cd3-822daaa75f9d.png)
