### ISSUE TITLE
KYC Forms - wrong link

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2048]
On the view "Submit more documents" the link "Go to my profile" should lead to "profile". Currently it leads to Dashboard. Please change.

![image](https://user-images.githubusercontent.com/26923972/48980485-f1c34880-f0c9-11e8-9fa4-1e3687292c88.png)

**Comment by huesforalice** [comment]
It looks like this is already correct on the master branch

**Comment by Vanilizer** [comment]
I just tested on staging and it is not correct. 

![image](https://user-images.githubusercontent.com/26923972/49034537-8f924280-f1b2-11e8-84ad-4184ec0404d5.png)

**Comment by glupiawymowka** [comment]
*fixed on .io*
![image](https://user-images.githubusercontent.com/18315589/49160911-14529d00-f328-11e8-9a08-c4f9a20f6df2.png)
