### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2050]
Please add a tooltip with following content:
"The Initial Capital Building Mechanism (ICBM) was a one-time event that took place from 17 November - 17 December 2017, where investors were rewarded with NEU in exchange for putting aside ETH and committing to invest it in ETOs on Neufund." in two places:

1. Profile - ICBM Migration Tool (next to the headline)
![image](https://user-images.githubusercontent.com/26923972/48981428-9f882480-f0d5-11e8-9384-a6d48b3217ed.png)

2. Dashboard - next to the link "Can't see your ICBM wallet?..." 
![image](https://user-images.githubusercontent.com/26923972/48981452-f1c94580-f0d5-11e8-8004-bd8a72eed496.png)

Both tooltips shall have the same content.

**Comment by glupiawymowka** [comment]
The tooltip on the dashboard is crashing when you try to read it for >15sec
![image](https://user-images.githubusercontent.com/18315589/49082066-0f6aec00-f249-11e8-987e-71067d2569e6.png)
![image](https://user-images.githubusercontent.com/18315589/49082084-1a258100-f249-11e8-8e19-c09ed99d88c0.png)
*tested on stage*
