### ISSUE TITLE
Update positioning of tabs in navigation

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2068]
Current navigation:
Dashboard
Portfolio
Wallet
Help
Profile

Please swap places of  Help+Help ICON & Profile + Profile ICON 

New order:
Dashboard
Portfolio
Wallet
Profile
Help

![image](https://user-images.githubusercontent.com/26923972/49024969-ed1a9500-f19a-11e8-917f-5d430e28b87c.png)

**Comment by glupiawymowka** [comment]
done
![image](https://user-images.githubusercontent.com/18315589/49595892-565b8e80-f979-11e8-9787-1b022cf7c87c.png)
