### ISSUE TITLE
ETO FLOW - Submitting documents - Popups

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2069]
1. ETO FLOW - When you upload a document and have to confirm it, you receive this popup.
![image](https://user-images.githubusercontent.com/26923972/49025126-484c8780-f19b-11e8-8154-6219151ab5bd.png)
This is incorrect.
Please change Headline to:
“Confirm document upload”
And text below:
“Please confirm that you would like to upload this document.”

2. ETO FLOW - When you enable whitelist, you receive this popup.
![image](https://user-images.githubusercontent.com/26923972/49025215-73cf7200-f19b-11e8-9c5b-9fd02889b704.png)
This is incorrect.
Please change Headline to:
“Confirm begin of your whitelisting period”
And add text below:
“Please confirm that you would like start your whitelisting period.”

**Comment by glupiawymowka** [comment]
- [x] whitelist start popup (metamask)
![image](https://user-images.githubusercontent.com/18315589/52574064-c1af5a00-2e1b-11e9-8c4e-e430ec086039.png)
- [x] document upload popup
![image](https://user-images.githubusercontent.com/18315589/52574160-f58a7f80-2e1b-11e9-9b7d-96b16f06dd48.png)
