### ISSUE TITLE
ETO FLOW - New state before whitelist enabled

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2076]
ETO states

Add a new state when ETO listed but has no whitelisting enabled called:

“Coming soon”

Please implemented it on ETO Timeline (State Whitelist should display “Coming Soon” until Whitelist enabled)

Please implement it in the Widget as a new state before whitelist.

**Comment by glupiawymowka** [comment]
this was done as a part of the referenced ticket
