### ISSUE TITLE
Global - Update header formatting in boxes on profile

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2077]
Update every header to:
Font size 0.825rem 
Color #4c4c4c

here example for "identity verification"
![image](https://user-images.githubusercontent.com/26923972/49031634-d419e000-f1aa-11e8-8e9b-3b93010d3f63.png)

please also add a space between text and "go to my dashboard"

**Comment by desfero** [comment]
@Vanilizer space between text and GO TO MY DASHBOARD is already there

**Comment by desfero** [comment]
Probably not needed anymore
