### ISSUE TITLE
[trezor] missing translations

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2087]
![image](https://user-images.githubusercontent.com/14041336/49073517-eb9cab80-f232-11e8-9b72-c0d88094698a.png)

.

**Comment by glupiawymowka** [comment]
a full setup of trezor is needed to test. will do in some free time

**Comment by glupiawymowka** [comment]
There is another problem that needs a separate problem. 
Trezor + metamask simply don't let user login on the platform, no message
