### ISSUE TITLE
Widget - ETO not found state

### ISSUE THREAD

**Issue by drakkein** [Neufund/platform-frontend#2088]
Instead of redirecting user to the index page we should display error message on the widget page.

Example: 
![image](https://user-images.githubusercontent.com/10601291/49074844-dd9c5a00-f235-11e8-8471-ed607bd9e924.png)

**Comment by glupiawymowka** [comment]
@drakkein could you give me a hint on how to recreate this?

**Comment by drakkein** [comment]
I guess the easiest way is to visit widget url with wrong id, ex: `https://platform.neufund.org/embed/eto/widget/totally-wrong-id`.
The other option is to create iframe in condepen or some similar sandbox with this url

**Comment by glupiawymowka** [comment]
merci, it works :)
