### ISSUE TITLE
Claim for Pending Assets

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2102]
The ETO is successfully finished and users who invested in the campaign.
Button Claim 
Summary
Transaction 
Success
Portfolio

**Comment by falinebambi** [comment]
Design in Zeplin: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5c10fc41fde4d550a21760d4
zpl://project?pid=5a8a92c89c1a166a6a6e8f37&seid=5c10fc41fde4d550a21760d4

**Comment by mpneu** [comment]
Invision clickthrough: https://projects.invisionapp.com/prototype/claim-cjpl6qwo00015xt01wa1od3im

**Comment by mpneu** [comment]
Invision clickthrough: https://projects.invisionapp.com/prototype/claim-cjpl6qwo00015xt01wa1od3im/play/f4bd4fe9

**Comment by Moejoe90** [comment]
@rudolfix 
I also need the transaction that should be made in order to conduct a claim

**Comment by rudolfix** [comment]
In MY ASSETS we should be able to download same agreements we have in confirmation dialog and we download them in the same way:
![image](https://user-images.githubusercontent.com/17202864/50969366-82b97c00-14de-11e9-932e-e6e31daa7376.png)

We can reuse same procedure we had in investor dashboard - template download

1. first we need to resolve to obtain placeholders, example call to eto listing api
```
inputs = {"token_holder_ethereum_address": investor_ethereum_address}
    inputs_enc = quote(json.dumps(inputs))
    result = fixture_wallet.client.get(TEMPLATE_ETO_URL % (eto_address, template_type) + "?inputs=" + inputs_enc)
```
where `TEMPLATE_ETO_URL ` is `etos/%s/templates/%s`

2. then we need to download (providing the placeholders) as pdf from immutable storage
```
immutable_storage_api_client.download(
        doc_info["ipfs_hash"], mime_type=doc_info["mime_type"], placeholders=placeholders, as_pdf=True)
```
where `doc_info` is taken from templates collection and placeholders you take from previous call

**Comment by glupiawymowka** [comment]
1. The "transaction cost" line looks different indesigns
![image](https://user-images.githubusercontent.com/18315589/51316364-b81d1700-1a54-11e9-80c1-9f549f174177.png)

actual look 
![image](https://user-images.githubusercontent.com/18315589/51315060-966e6080-1a51-11e9-9357-9e8b25705c22.png)

2. I'm unable to finish the transaction, getting the following error message each time: 

![image](https://user-images.githubusercontent.com/18315589/51315090-a71ed680-1a51-11e9-89ad-9a7d05dc5016.png)

Link to the errors appearing in the console: 
https://pastebin.com/Mscr1tzr

**Transaction succeed for @Desperado**

3. I had to try many times before (only 2, reservation agreement and company token holder agreements) documents, started downloading 
![image](https://user-images.githubusercontent.com/18315589/51315618-d5e97c80-1a52-11e9-97cb-ad764196e758.png)

![image](https://user-images.githubusercontent.com/18315589/51315749-32e53280-1a53-11e9-9fa9-ed6edf95cd5b.png)

4. "SIGNED INVESTMENT & SHAREHOLDER AGREEMENT" not downloading at all for both of us

**Comment by Moejoe90** [comment]
@SergejSoft @glupiawymowka 
Regarding all the points:
1 - This change can be easily added but please then align this between all the review components `investment`,`withdraw`,`upgrade`. 

2 - This is actually a problem related to Metamask there is an edge case where sometimes Metamask crashes. The way to test this is to when this error happens to try a safe bet transaction like withdraw. 
The solution as I explained to Disable/Enable Metamask

3 - This is specifically for `.io` environment. The ETO fixtures are there but the ISHA document is not uploaded @rudolfix @banciur I can't do much from my side to solve this

**Comment by glupiawymowka** [comment]
Ok, with Moe's help it worked. We just need to observe if it will also happen on staging, nothing else can be done for now. 

Regarding designs, I agree that the current version is consistent, let's keep it 

The output is as follows, so I mark it as ready 
![image](https://user-images.githubusercontent.com/18315589/51329948-ced46580-1a76-11e9-8cc1-bfeddf2df0e1.png)
