### ISSUE TITLE
[ETO PUBLIC] distinct People swiper state

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2103]
People swipers are always black. Please make them grey when they're not active

Here an example when there's nothing more to show on both sides 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/8a9946fc-a4f8-4589-baa9-3cb492939a01)

**Comment by AlexeyTuboltsev** [comment]
visual regression is ok. Screenshots of slider are wrong cause it's only slider here, without the whole layout. This should be fixed too but in a separate ticket. I checked all states of slider in a real layout, it's all fine
