### ISSUE TITLE
Profile Icon. Hooverover

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2108]
All Icon is fine, except Profile. Once hoovered over the icon is turning same color as the background. Tested on Production.
![Screen Shot 2018-11-28 at 11.56.19.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/c724411b-dda5-4f34-9e36-5465d7e9201f)

**Comment by AlexeyTuboltsev** [comment]
can't reproduce, all looks fine...
