### ISSUE TITLE
URGENT for 2.12 - REMOVE MAX NIEDERHOFER FROM LANDING PAGE

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2125]
Please remove Max&Alina Niederhofer from the slider on landing page platform.neufund.org
![image](https://user-images.githubusercontent.com/26923972/49280061-6c54e500-f489-11e8-9ab6-eed4924063ab.png)

**Comment by glupiawymowka** [comment]
removed
