### ISSUE TITLE
ETO DASHBOARD LOGIC AMENDMENTS regard. ETO type

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2130]
IF HNWI ETO (chosen in ETO Terms Form)
→ Change “Upload prospectus” to “Upload signed Investment Memorandum”
→ Change “Please go to the documents section and upload your prospectus” to “Please go to the documents section and upload your signed Investment Memorandum. This will enable you to start your ETO fundraising on the platform.”
→ Change link label “UPLOAD PROSPECTUS” to “UPLOAD INVESTMENT MEMORANDUM”
IF RETAIL ETO (chosen in ETO Terms Form)
→ Change “Upload prospectus” to “Upload approved Prospectus” and add a box “Upload approved Pamphlet”
→ Change “Please go to the documents section and upload your prospectus” to “Please go to the documents section and upload your approved Prospectus. After that will need to upload the approved Pamphlet to enable your ETO fundraising on the platform.
IF CROWDFUNDING ETO (chosen in ETO Terms Form)
→ Change “Upload prospectus” to “Upload approved Pamphlet”
→ Change “Please go to the documents section and upload your prospectus” to “Please go to the documents section and upload your approved Pamphlet. This will enable you to start your ETO fundraising on the platform.”
→ Change link label “UPLOAD PROSPECTUS” to “UPLOAD PAMPHLET”

![image](https://user-images.githubusercontent.com/26923972/49289186-52c09700-f4a3-11e8-8de2-7000ec7e8ac3.png)

**Comment by Moejoe90** [comment]
@Vanilizer this will be postponed for now as we don't support Crowdfunding ETO
```
IF CROWDFUNDING ETO (chosen in ETO Terms Form)
→ Change “Upload prospectus” to “Upload approved Pamphlet”
→ Change “Please go to the documents section and upload your prospectus” to “Please go to the documents section and upload your approved Pamphlet. This will enable you to start your ETO fundraising on the platform.”
→ Change link label “UPLOAD PROSPECTUS” to “UPLOAD PAMPHLET”
```
