### ISSUE TITLE
ETO FLOW - DOCUMENTS SECTION

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2131]
Here again the description of document section logic:
1. Section "All Legal Document Templates"
--> Here we show ALL document templates we have regardless of ETO type chosen
--> All documents should have "Template" in their name and be empty templates
2 Section "Generated documents" 
-> Here we have generated documents for the specific company that is logged in (which means we take specific templates and prefill them with data from the forms and kyc)
--> These documents should be called by their name (no template, no signed, no approved) - plain name.
3. Section "Upload section"
--> here we show what kind of documents the company has to upload depending on the ETO type
--> names of documents should indicate the kind of document:
- Signed ISHA
- Signed Term Sheet
- Signed Investment Memorandum
- Approved Prospectus
- Approved Pamphlet

TASK 1: The screenshot below shows already correctly implemented sections 2 and 3. Section 1 is not yet fixed.
TASK 2: Add the following to the logic:
- If RETAIL ETO show both "Approved Prospectus" AND “Approved Pamphlet” in Document upload section
- If CROWDFUNDING ETO  - show just “Approved Pamphlet” in Document upload section

![image](https://user-images.githubusercontent.com/26923972/49289275-95826f00-f4a3-11e8-905f-9ab98f251d7f.png)

**Comment by Moejoe90** [comment]
@Vanilizer 
```
TASK 2: Add the following to the logic:

If RETAIL ETO show both "Approved Prospectus" AND “Approved Pamphlet” in Document upload section
If CROWDFUNDING ETO - show just “Approved Pamphlet” in Document upload section
```
Will be postponed for later
