### ISSUE TITLE
ETO Form - ETO Terms - ETO Type

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2132]
We have to allow CROWDFUNDING ETO - therefore please make three check boxes (excluding each other):
o ETO is for tickets above EUR 100 000 (HNWI ETO)
o ETO is under prospectus regulations (RETAIL ETO)
o ETO is under crowdfunding regulations (CROWDFUNDING ETO)

![image](https://user-images.githubusercontent.com/26923972/49289607-95cf3a00-f4a4-11e8-9b21-5475798a0644.png)

IF HNWI ETO checked:
- Min. Ticket size by default 100 000 EUR and add validation that cannot be smaller than that
- Max. ticket size Unlimited

IF RETAIL ETO checked:
- Min. Ticket size by default 500 EUR and add validation that cannot be smaller than that
- Max. ticket size Unlimited

IF CROWDFUNDING ETO checked:
- Min. Ticket size by default 500 EUR and add validation that cannot be smaller than that
- Max. ticket size by default 10 000 EUR and read only.
- Add Validation on Max. Investment amount  - it cannot exceed 2.5M in total (--> This is dependent on Pre-Money Valuation and Max. new shares to issue)

**Comment by pstroinski** [comment]
view is already different
