### ISSUE TITLE
INVESTMENT WIDGET - New tag: Approved Pamphlet

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2133]
If ETO chooses to do a CROWDFUNDING ETO, then in the investment widget we should show a tag called "Approved Pamphlet" instead of "Approved Prospectus" or "Investment Memorandum"

![image](https://user-images.githubusercontent.com/26923972/49289864-6bca4780-f4a5-11e8-9498-797fd10906c0.png)

**Comment by rudolfix** [comment]
we need to implement CROWDFOUNDING type of ETO
