### ISSUE TITLE
ETO FORMS - Success percentages adjustments

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2134]
All forms that have all fields by default optional should always show 100% at the beginning. 

e.g.  Key individuals show 100% but Pitch does not

![image](https://user-images.githubusercontent.com/26923972/49289925-a7651180-f4a5-11e8-8141-5d122a959913.png)

Adjust progress calculation with 100% progress if all fields optional.

**Comment by AlexeyTuboltsev** [comment]
need to talk to aga about it

**Comment by pstroinski** [comment]
We should rethink how it should be presented
