### ISSUE TITLE
convert all strings to transaltions

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2143]
there are many texts still left in sagas etc, that are static strings, not translations. After #2087 got merged we can  convert them to Enums -> FormattedMessage. Aim: get rid of all strings and all injected intl in sagas.

**Comment by AlexeyTuboltsev** [comment]
blocked by https://github.com/Neufund/platform-frontend/pull/2273

**Comment by Desperado** [comment]
moving to Staging, as it is not really possible to test it by hand. this is technical issue.
