### ISSUE TITLE
Upgrade tool - BUG FIX

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2161]
Important!! Don't update just locale strings. We need special locale key for only this case.

Currently we show the "Withrawal transaction summary" when an investor is using the migration tool. This is confusing for the user. 

Please have a seperate popup  summary with the following wording for the migration tool:
![image](https://user-images.githubusercontent.com/26923972/49435155-362fa200-f7b6-11e8-8b08-5a10c334c9a0.png)

**Enable your ICBM wallet**
**To Address**
**Amount Sent**

**Comment by Moejoe90** [comment]
ACTUALLY WALLET UPGRADE

**Comment by glupiawymowka** [comment]
Done
![image](https://user-images.githubusercontent.com/18315589/52645469-24b6f480-2ee1-11e9-99ed-4a48dc3fd645.png)
