### ISSUE TITLE
INVESTOR |Stat View

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2174]
Adding a tab with "FUNDRAISING STATISTICS  " in the public View:
If the users click it is redirects to ICO Monitoring page:
 Here is the test link for our FORCE campaign. https://test.icomonitor.io/#/0x01A1f17808edAE0B004A4F11a03620D3d804b997
stage/ICO

This tab/button is visible after Presales starts.

The mockup:
https://zpl.io/V1lDPeZ

**Comment by glupiawymowka** [comment]
*option hidden for now*
