### ISSUE TITLE
REFUNDED flow including ETO timeline, summary, pending transaction and refund complete

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2195]
hey! we have smth like this on stage now
![image](https://user-images.githubusercontent.com/17202864/49608815-f7f2d800-f999-11e8-89f7-b4f5ecaa5fb0.png)

Can we have a design for what to do on REFUND?

**Comment by falinebambi** [comment]
Overview of changes:
- Claim Refund State in the last section of widget 
- Status changed to 'Refund' with red dot
- Timeline in Refund state 

Zeplin link: 
https://zpl.io/a7OqW3K

Designs: 
![ETO_refund](https://user-images.githubusercontent.com/17235402/55711840-deb47380-59ed-11e9-9324-a228bdd755f6.png)

**Comment by rudolfix** [comment]
@falinebambi transaction modal design

**Comment by glupiawymowka** [comment]
hey @desfero here I can clearly see, that you've fixed the timeline for REFUND state, and also hid it for mobile. 
However, both of these are happening again

**Comment by glupiawymowka** [comment]
no fixture with refund state on stage.
