### ISSUE TITLE
Adjustments capital raised

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2196]
￼In widget hide “by 3 investors”

![image](https://user-images.githubusercontent.com/26923972/49641910-ddf4dc00-fa11-11e8-8777-107967516167.png)

Hide “3 investors”
![image](https://user-images.githubusercontent.com/26923972/49641915-e1886300-fa11-11e8-9ac3-76f3a9f9ad86.png)
￼
Hide the button Fundraising statistics. 
![image](https://user-images.githubusercontent.com/26923972/49641922-e51bea00-fa11-11e8-8027-88275852f0a7.png)

Important, do not delete this only hide. We will enable this after Fin.Authorities will give us a green light to show this stats.

**Comment by glupiawymowka** [comment]
*tested on production*
![image](https://user-images.githubusercontent.com/18315589/49811559-d1e78200-fd63-11e8-9684-e9aa2c6d168e.png)
