### ISSUE TITLE
Terms of Use. Updated

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2197]
Problem: Since we updated terms of use users will see it again. 
<img width="1234" alt="screen shot 2018-12-07 at 11 26 36" src="https://user-images.githubusercontent.com/2290474/49642323-00d3c000-fa13-11e8-8a6a-4b349be86bbc.png">

The mission: if users have already read T&C once, to show the same modal with the different text:

"Please read our updated Terms of Use" and pls. make the word updated <strong>

**Comment by glupiawymowka** [comment]
*tested on .net*
It's correct (title with "updated" for old users, without it for new ones), but why is the document's name [object Object] now? 
Please fix it 

![image](https://user-images.githubusercontent.com/18315589/51542100-bbe8d900-1e5a-11e9-8bb1-273396f1eeb3.png)
