### ISSUE TITLE
[USABILITY] show not enabled ICBM wallets in investment flow but disabled

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2221]
Out ICBM investors that didn't upgrade are getting lost by not seeing their funds from non enabled/upgraded ICBM wallets in investment window. so

- show non upgraded wallets, they are disabled and display "~UPGRADE~/ENABLE" button
- when clicked we go to wallet view and start upgrade saga on clicked wallet

that's a quick fix. what we should do is to make transaction in place but our workflow does not support that

**Comment by Louisswryan** [comment]
Currently ICBM investors can not see disabled wallets at the start of their investment flow:

![Screenshot 2019-03-19 at 09.25.15.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/1c1dcb2c-7e39-4158-bb91-68f183981657)

We need to show that these wallets exist but are disabled and offer a CTA to upgrade the wallet and enable.

https://zpl.io/VkGg6pZ

When the user clicks UPGRADE, they will be taken to WALLET and upgrade process begins.

Thanks :)

**Comment by glupiawymowka** [comment]
*tested on .io*

**Comment by glupiawymowka** [comment]
hey, we don't have any test ICBM wallets on stage, so I can't really test much more here...
