### ISSUE TITLE
BUG: THA error for not ICBM investors

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2224]
Hi,

so Ula is NOT an ICBM investor. 
However she did buy NEU on the secondary market. 

After that she invested in our ETO EUR.

In her portfolio now she has:
- FORCE tokens
- NEU (NEU from secondary market + NEU from FORCE investment)

On the portfolio next to NEU she has a link to Token Holder Agreement. 

If she clicks on it she is redirected to ICBM page (which is incorrect in first place) and then when she clicks to download THA on commit.neufund.org/commit/status she gets an error (which is a second bug - but understandable - somehow she should have two THA for both purchases) 

Please find the flow in the video attached. 

[THA error.mov.zip](https://github.com/Neufund/platform-frontend/files/2663259/THA.error.mov.zip)

**Comment by rudolfix** [comment]
@Vanilizer can you do the same process but once you are on commit page, do the full refresh in the browser and download agreement again. does it work? if so, this is not backend probelm

**Comment by glupiawymowka** [comment]
The agreement worked multiple times for me (not even refresh needed).
Indeed, you're forwarded to the commit page though.

**Comment by glupiawymowka** [comment]
We discussed with Marcin, that a space to hold all the documents is needed, but as we don't have one yet and it's a massive amount of work, we can leave it in the commit page for now. 
The most essential thing is that the document download works
