### ISSUE TITLE
Research topic related to server side rendering / prerendering

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2233]
***Background:***
Server-side rendering is not that easy to turn on an existing project. As a part of this issue, we need to investigate what should be done exactly and all pitfalls that wait for us.

The biggest pitfall that comes to my mind is that full server-side rendering is not possible to achieve for blockchain application as on the server we are not allowed to access user wallet.

Also please consider prerendering, maybe it's more appropriate in our case than server-side rendering.

**Comment by pstroinski** [comment]
Not needed now. When we have a requirement to implement such functions we will re-open
