### ISSUE TITLE
KYC upload multiple files

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2243]
we should upload all files dropped in the dropzone. Now we only take the first one and silently ignore the others
related: #1884

**Comment by Louisswryan** [comment]
I think the solution to multiple files is to have a specific drop zone for each file. I am currently working on our new file upload component so this can be used in response to this ticket.

Upload component:

https://zpl.io/bWXYJ4p

**Comment by andywalton** [comment]
Hey for this specific case, we don't need to redesign this component. It currently allows you to upload 1 file/image at a time. Please do the dev work to allow this to upload multiple files.

Should there be a problem with one file say if you upload more than 1, highlight the error for this file but don't block the one that can be uploaded. So if a file type or file size requirement for one of the files in the list or more, please highlight these errors.

We're doing improvements to KYC in the next 3 weeks and we'll address this issue further during that. For now, the task should be to allow multiple file types, validate this correctly and block file types that aren't supported and to do this using our current component.

^ @AlexeyTuboltsev

**Comment by pavelneu** [comment]
Tested on Chrome and Firefox, 
ready to be merged on master.
