### ISSUE TITLE
LightWallet Upgrade - migrate and deactivate option

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2259]
We should offer migration option from LightWallet to nano ledger (and metamask - why not?)

1. user enters backup codes into nano ledger. we've already made sure that standard derivation path is used
2. user signs message with ledger. we can do via login procedure/backend signing api
3. we check is message was signed by the same ethereum address that is migrating
4. **we delete light wallet key blob from backend** this deactivates salt and password. they cannot be used to recover key anymore
5. we log out current user

as a minimum we should offer a "deactivate" button. in that case we simply delete blob and log out. that deactivates current salt and password so (1) restore is needed or (2) login via nano/metamask with key imported

**Comment by Moejoe90** [comment]
@rudolfix 
If you have already implemented a `delete` `me` endpoint then it can be implemented

**Comment by pstroinski** [comment]
@andywalton Do we plan to implement it still with the new user flow and the app?
