### ISSUE TITLE
Fix fatal `TypeError: Cannot read property 'getItem' of null`

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2260]
***Background:***
Some environments (like `WebView`) do not provide `window.localStorage`, if such happens frontend throws a fatal error during rendering (sentry report https://sentry.neusrv.net/sentry/production/issues/3090/?referrer=slack). Under the hood, we use our own class-wrapper for localStorage called `Storage`. 
To fix this we need to implement `ObjectStorage` with the same API as `Storage` and base this new class on a plain old javascript object.

**Acceptance criteria**
[ ] -

**Comment by Moejoe90** [comment]
Additionally, care should be taken when writing this store as in to test the side effects of storing inside a simple object.

**Comment by Moejoe90** [comment]
Take into note this ticket will get a bit more complicated after https://github.com/Neufund/platform-frontend/pull/1942
Since now you will need to implement an EventEmitter and a listener that listens for storage clearance events
