### ISSUE TITLE
Display Private KEY in addition to SEED

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2270]
**Design:**
Pls. make sure we use the current design. 
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5c35d15e88a77b4ba9e4dd45

**Testing notes:**
For now, seed view after 3 minutes will ask a user to confirm permission again for security reasons.

**Comment by Desperado** [comment]
Hi @desfero , this feature is not yet in Staging. we just checked it.

**Comment by glupiawymowka** [comment]
design 
![image](https://user-images.githubusercontent.com/18315589/51313711-899c3d80-1a4e-11e9-8a82-24963d7f6c88.png)
actual look
![image](https://user-images.githubusercontent.com/18315589/51313786-b94b4580-1a4e-11e9-849c-a3e4f1c76b32.png)

Private key copied & shown correctly
Password requested again after 3 minutes

**Comment by SergejSoft** [comment]
Pawel, thsi little design change is not that critical.  Let's marked thsi tickets as staging. Once I deploy this to production we will close it.

**Comment by glupiawymowka** [comment]
on stage
