### ISSUE TITLE
Add error message for deprecated browsers

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2275]
**Background:**
Neufund support only greenfield browsers therefore we need to add a meaningful error message for users with really old browsers to make the web better! 👨‍💻👩‍💻  
Currently, after sentry errors observations, a couple of checks need to be done. 
1) We need to check es6 support (https://gist.github.com/JoeyBurzynski/1351acd30656870f22ab9e1bd4e62896). Related sentry error https://sentry.neusrv.net/sentry/production/issues/3175/?referrer=slack.
2) We need to check `Intl` support, related sentry error https://sentry.neusrv.net/sentry/production/issues/3256/?referrer=slack

As an error page reuse current error page design but with the new header and description.
**Zeplin**: zpl.io/V0JlnWE
**Component**: `CriticalError` 

Use the following text:
header: Oops... it looks like you use an old browser
description: @SergejSoft @Moejoe90  **TODO**

### Acceptance Criteria

- [ ] Given user with old browser that do not support `Intl` (check support here https://caniuse.com/#search=intl) when he visit platform then critical error page should apprear with meangfull messag about outdated browser
- [ ] Given user with old browser that do not support `es6 features` (check support here https://caniuse.com/#search=es6) when he visit platform then critical error page should apprear with meangfull messag about outdated browser

### Testing notes
For first AC you can use UC Browser (avaialble on android)
For second AC you can use IE11

**Comment by pstroinski** [comment]
To be moved to asana @andywalton
