### ISSUE TITLE
Introduce new components by refactoring existing code

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2288]
**Background:**
This is a general issue to track/discuss components that we can create by refactoring existing code.
So in long term, this will reduce the maintenance cost of our design system and speed up with new features.

**Components that we can create:**

- [ ] We can extract documents to a new section layout 
![image](https://user-images.githubusercontent.com/7031578/50761062-b8096400-1269-11e9-9f65-a991d0abd7cb.png)
- [x] Extract `CurrencyIcon` component, so it's not only used in `AssetPortfolio`

**Comment by pstroinski** [comment]
We clean on the go...
