### ISSUE TITLE
User Dashboard |Bank Details

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2289]
The basic user flow:
We display nEUR proceeds in the Wallet.
User click REDEEM> User get a modal with info about depositing 1.00EURO
User makes a manual transaction to the details provided in the modal.
Shani gets the transfer and manually verify the account. 
When confirmed, user gets a confirmation email.

The user can click Withdraw entre the amount. Done!

We need to add validation for ETH, if the user doesn't have enough ETH user should get an alert message that there is not enough ETH to complete this transaction. 

We need to type version (text) one for bank verification and another for investment flow. 

@falinebambi to provide design and place in the ticket.

**Comment by rudolfix** [comment]
done!
