### ISSUE TITLE
Fix Transaction Flow Edge Case

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2297]
**Background**
There are two types of transactions 
1 - One Time transactions, for example, Upgrade, claim etc
2 - Recurrent transactions for example  Withdraw . Invest

This edge case affects only one-time transaction. If you conduct an upgrade transaction continue until the transaction is sent then close the transaction dialogue box. The app will be in a state where the transaction is still not mined hence you can try to do upgrade again. Once you click upgrade you will wait until the transaction is done. And end up into upgrade summary. 

This is not the correct behavior. There should be an extra view that indicates the transaction is already done. Or show failed dialogue directly @SergejSoft @rudolfix what is the best approach. 

**Task** 
1- Implement Initial Condition check mechanism that checks if the conditions are met after the last transaction being mined. This should only effect flows where there is already a transaction before

2- Add a new TxSender State where it indicates to the user that this transaction is already done

**Testing notes**
To fix this edge case now we don't allow to progress with transaction flow if there is already a pending platform transaction in progress. In case there is one already in progress we just show success modal for this pending transaction when it's done and user should again initiate the transaction process. If there is external pending transaction then after it's done we allow user to progress with initiated transaction flow.

**Comment by rudolfix** [comment]
This is "transaction status indicator" I'm begging for months. We have all support on the backend for this. See also epic #1957 

1. statuses: no transaction being mined, transaction being mined, transaction OK, transaction reverted, OOO transaction
2. clicking on status brings back correct mining dialog!

**Comment by falinebambi** [comment]
@Moejoe90 Designs Ready as per discussed: https://github.com/Neufund/platform-frontend/issues/1326

**Comment by glupiawymowka** [comment]
*this was tested during the overall transaction statuses check on .io and partly on .net*
