### ISSUE TITLE
nEUR Deposit flow UX

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2298]
All changes will be done on the front end. 

nEUR deposit flow should be clear for the user the nEUR is bridge currency used for investment provided by Quintesence (Sister company responsible for nEUR issuance and withdrawal)

We have 2 type of user action.

connected to top-up (In-going money transfer).
Redeem or Return token or (burning nTokne and outgoing money transfer. or withdraw)
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?tag=quintessence

The whole process is explained in the google document.
https://docs.google.com/presentation/d/1Eo3wljeJ7tPxuva7dRAJdOF8JSIHHjlrebxBONTj9xY/edit?usp=sharing

**Comment by Desperado** [comment]
Missing "Acceptance criteria" and "Testing notes"
