### ISSUE TITLE
(WIP)Deposit Flow UX change

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2302]
We have 2 type of user action. 
1. connected to top-up (In-going money transfer).
2. Redeem or Return token or (burning nTokne and outgoing money transfer. or withdraw)

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?tag=quintessence

The whole process is explained in the google document. 
https://docs.google.com/presentation/d/1Eo3wljeJ7tPxuva7dRAJdOF8JSIHHjlrebxBONTj9xY/edit?usp=sharing

**Comment by desfero** [comment]
Will split by smaller issues and attach them to the epic #2298. Description was moved to https://github.com/Neufund/platform-frontend/issues/2298
