### ISSUE TITLE
Scroll and focus first invalid input

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2307]
**Background:**
It's a usual behavior that UI scroll and focus first invalid input for better usability/accessibility.

**Comment by glupiawymowka** [comment]
*tested on .io, ISSUER FORMS*

focus correctly moves to the first invalid input 
![image](https://user-images.githubusercontent.com/18315589/51915296-0af2b900-23db-11e9-89e7-ad6c8a177b58.png)
