### ISSUE TITLE
Ledger when locked allow to sign message without proper approval on device

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2319]
**Steps to reproduce:**
1. Login with ledger 
2. Wait for ledger to be locked
3. Try to submit/update email 

After that for a small amount of time popup is shown, and email is sent without any approval on the device.

**Interactive demo:**
![jan-16-2019 11-07-10](https://user-images.githubusercontent.com/7031578/51241830-edefcc00-197e-11e9-9899-e0af03ba6997.gif)

**Acceptance  criteria:**

- [ ] Given a user with a not approved email when he is submitting an email then he should click approval on ledger device to sign the email change message

**Comment by rudolfix** [comment]
yeah that's because in fact we didn't put permission escalation on the backend api. could you please tell me what permission do you sign? we'll add backend constraint and you will receive 401 when you try to hack like this.

**Comment by Moejoe90** [comment]
The problem actually comes from the fact that we store all escelated permissions and the tokens can be used more than once

**Comment by Moejoe90** [comment]
I confirm that this was fixed in a previous pr

**Comment by glupiawymowka** [comment]
*tested on stage*
