### ISSUE TITLE
Remove bluebird from dependencies

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2322]
**Background:**
We load whole `bluebird` to only use `promisify` function. 
We should create our own `promisify` and those save around 21kb gzipped.

**Comment by Moejoe90** [comment]
Please take into note that the new method or library should be well tested when it comes to changing callbacks to promises there are a couple of edge cases. It's really not easy to write a custom wrapper.  

Have a look at these tests and implement them to whatever custom function you end up choosing to use
https://github.com/petkaantonov/bluebird/blob/master/test/mocha/promisify.js
