### ISSUE TITLE
app tries to fetch pledges even if bookbuilding is empty

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2323]
_request 1_: https://localhost:9090/api/eto-listing/etos/\<etoId\>/bookbuilding-stats.
returns zero bookbuilding ({investors_count: 0, pledged_amount: 0})
nevertheless app tries to fetch pledges:
_request2_: https://localhost:9090/api/eto-listing/etos/\<etoId\>/pledges/me
and the backend returns an error document not found

**Comment by desfero** [comment]
There is nothing we can do with this, so closing this issue
