### ISSUE TITLE
pending/my assets portfolio UI and UX cleanup

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2340]
We have a few simple fixes that we'd like to implement

1. We link pending and my assets to company public profile. Kirstyn please tell us should we use a link or the whole area is clickable?
2. We drop the NEU Reward column from MY ASSETS. REWARD applies only to pending assets
3. We rename column DOCUMENTS to INVESTOR AGREEMENTS. In this column we have a single button/link to download documents
4. When link/button is clicked
- in case of NEU we go to commitment page (as it is now! - we do not have NEU documents download implemented yet)
- in case of any other (equity) token we show a modal where you can download all three investor documents separately (so the links you see now are going to this modal).

Steps
1. @falinebambi  does the designs
2. @drakkein will do implementation

deadline on production is 2nd of Feb

**Comment by falinebambi** [comment]
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5c49eda033fdc7bf07c0e0b6
![portfolio document download](https://user-images.githubusercontent.com/17235402/51694527-4b2ff100-2001-11e9-9163-177ce4410d8d.png)
![updated portfolio](https://user-images.githubusercontent.com/17235402/51694528-4bc88780-2001-11e9-995e-bda1f795f8b6.png)

**Comment by rudolfix** [comment]
I've just noticed that we never defined what should go into MY ASSETS so let's reiterate
QUANTITY - token.balanceOf(user wallet address)
CURRENT PRICE
- for NEU we take it from price oracle - this is already implemented OK
- for equity token we need to take current market price from the token controller (right now we use same price as in RESERVED ASSETS which is wrong)
CURRENT VALUE
- multiply QUANTITY * CURRENT PRICE

How to get market price from token controller:
- instantiate IEquityToken artifact from equity token address (alternatively you can use EquityToken which implements this interface)
- get two values: IEquityToken::tokensPerShare() and IEquityToken::tokenController()
- instantiate IControllerGovernance artifact from token controller address
- call IControllerGovernance::shareholderInformation() which returns
```
function shareholderInformation()
        public
        constant
        returns (
            uint256 totalCompanyShares,
            uint256 companyValuationEurUlps,
            ShareholderRights shareholderRights
        );
```
now the market token price is (market valuation / existing shares) / tokens per share
please use big number for calculations. final price is in wei (10**18) EUR

check platform-contracts repo for all the smart contracts mentioned above
