### ISSUE TITLE
Issuer ETO forms - bug when deleting Key individuals

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2347]
When you delete a position in the key individuals form after 1 click on"x" the form reloads back to dashboard. There is no way to delete more positions in the form without going to dashboard first
![image](https://user-images.githubusercontent.com/26923972/51662191-59572080-1fb3-11e9-9536-a10209d8af93.png)
.

**Comment by glupiawymowka** [comment]
Confirmed that this bug still exists. It's hard to reproduce as it looks that is appearing randomly, so more than one try on deleting all the key individuals, not saving, deleting again may be needed. 

**Steps to reproduce**
1. You can use the following fixture on .io:
0x0015650359daf66f6633deeb490a059027b0e396
2. Login, go to Key Individuals form
3. For the given fixture, a few team members are already added - try deleting all of them one by one
4. At some point, deleting a key individual should redirect you to the dashboard (once it happened at the first try, the other time I had to refresh and try again)
5. From the console: 

![image](https://user-images.githubusercontent.com/18315589/53811435-b43c4a00-3f59-11e9-9cf9-3b9b1881f3fa.png)

**Comment by andywalton** [comment]
I've checked this and the behaviour still happens on .io - I spoke with @Moejoe90 and he seems to think this might be a result of the way the fixture is being setup. I'm therefore adding Moe to this ticket as well.

When you pick it up... come chat to me if this is unclear but see Nikola's comment regarding how to replicate. It's very random and sometimes it happens after 1 click, another time it will happen after 2 clicks when deleting items.

**Comment by AlexeyTuboltsev** [comment]
solved with https://github.com/Neufund/platform-frontend/pull/2675

**Comment by glupiawymowka** [comment]
for now it's not saving anything but uploaded picture :D waiting for the review of the mentioned PR
