### ISSUE TITLE
[RECOVERY PHRASE] empty popup appearing 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2380]
Last step of verification - recovery phrase is broken on all env (also live)

1. Create a light wallet account
2. Go through the recovery phrase steps
3. When you put all the words correctly, "continue" button should appear. click it
4. The folowing window should pop up:

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/9e76ec9b-2529-4705-af7d-3a1d66cd5fa6)

 I guess this text was somehow lost (title "Your Recovery Phrase", rest as in the picture)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/2ae24f39-d1d8-4323-86cb-f3c5efb5bd9c)

**Comment by Desperado** [comment]
Confirmed on Live. Ouch :(
