### ISSUE TITLE
Check Issuer Login

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2384]
**Describe the bug**
Some issue with issuer login
**To Reproduce**
Login as issuer
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
@Vanilizer if you have more comments to add

**Comment by Vanilizer** [comment]
Agora Trade ha ssuccessfully registered on the platform, they had the same problem with kyc - when they uploaded more docs they got an error, it was resolved because kyc department just accepted them. But now she tries to login again and gets the error.

**Comment by Moejoe90** [comment]
This is related with opening the wrong link
