### ISSUE TITLE
[QUICK FIX] when downloading personalized agreements in token claim we wait too long without indication

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2403]
related to https://github.com/Neufund/platform-frontend/issues/2102

when user clicks to download document: both when claiming tokens and then in MY ASSETS we make two calls to backend: resolve placeholders and then generate personalized PDF.

on the backend there's libre office doing word -> pdf. it's slow. user waits for 2-3 seconds without a clue what is going on so the user clicks again.

quick fix:
* change mouse cursor to WAIT
* prevent clicks until document starts downloading (or error!)

**Zepplin**
Quick fix - not needed

**Component**
Portfolio - Token Claim process

**Acceptance criterea**
- cursor changes or other indication making user wait when request is being processed
- cannot download same document when request is being processed

**Testing notes**
First click makes you wait for a long time. next clikcs on the same documents are cached. we need branch testing

**Comment by glupiawymowka** [comment]
the cursor indicates now, that some action was taken and the user should wait.
