### ISSUE TITLE
Past investments in Portfolio

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2405]
when tokens are claimed, investment line disappears from RESERVED ASSETS **forever**, we need to show those somewhere probably where history of transactions was supposed to be shown

See below

**Comment by Desperado** [comment]
@rudolfix do we need some investigation for this, or it should be proper story?

**Comment by andywalton** [comment]
We met and it was agreed we'll do the following:

1) In Wallet - we will have a platform history of transactions (we might need to create a Transaction detail view but we'll see about this when designing it and if we can delay this for simplicity for a later stage).
2) In Portfolio - we'll have a new Past Transactions list in chronological date order (it's basically a timeline feed)

See a working PRD here: https://docs.google.com/document/d/1ileQzHNis9RBHmZc6bHE2cF9kj7PCyUXAZEFYXSQpnY/edit?usp=sharing

**Comment by falinebambi** [comment]
We are splitting this ticket into 2 parts. This ticket will concentrate only on the listing of the 'Past Investment' in the Portfolio view. This solves the problem of the Reserved Assets such as unsuccessful but refunded Tokens disappearing from record. 

The Past Investments are sorted by Date. 
If a field in not applicable leave it blank in the table 

Order of table: 
Date
Token 
Profile 
Quanity
Amount Invested 
Purchase Price 
Neu Reward
Status 

List of Status:
Claimed
Refunded 
No status 


![image.png](https://images.zenhubusercontent.com/57c01da2e40e5714b16dddf9/07ac1347-8bf5-4085-8e09-35788e15a132)

Zeplin link: https://zpl.io/boDnAmg

**Comment by rudolfix** [comment]
**tech details**
this is basically different on the same data you have in RESERVED ASSETS with the following exceptions:
* ETO is in on chain state of REFUND, CLAIM or PAYOUT (so goes out of reserved assets, goes in here)
* we order those by date

Please also note "View Profile" in MY ASSETS, which is active only for Equity Token, not NEU  and leads to public profile of company

**Comment by falinebambi** [comment]
@rudolfix updated to remove view profile on NEU

**Comment by glupiawymowka** [comment]
*this was tested on .io and will be tested live again*
