### ISSUE TITLE
[KYC] fix logics of dropped IDnow verification flow

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2408]
When the user stops IDnow verification for some reason and goes back to the platform, he'll see the widget in a state that is normally connected to submitted process

1. Register on the **platform.net** or use any unverified account
2. Start verification process for personal account

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/7fa8649d-fead-4970-af52-8b192bd61de1)

3. Begin **video** verification
4. Reenter platform.net address in the URL bar and go to profile
5. You'll see the widget in the given state, with correctly working buttons, but totally invalid message shown
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/52df3776-93c3-42d9-8f48-429c49c4bedb)

This is wrong because the user did not submit verification here, he actually is still in the middle 

Expected behavior would be that :
a) profile tab would be in the "unverified" state as the user dropped the process
b) There would be another widget state for this cause, with the given text (agreed with taskforce) 

```Thank you for starting your identity verification request with IDNow. It looks like your request was unable to be processed. You may either restart the process with IDNow, or start over and select manual verification. When you select manual verification, an agent will review your request within 1 business day.```

c) Buttons could be more informative. Please replace the wording according to Shani's comment

**Comment by shanile** [comment]
@glupiawymowka I suggest instead 
LEFT: RESTART VERIFICATION PROCESS
RIGHT: CANCEL AND START OVER

LEFT: CONTINUE WITH INSTANT VERIFICATION 
RIGHT: MANUAL VERIFICATION

**Comment by glupiawymowka** [comment]
@Desperado

**Comment by glupiawymowka** [comment]
@Moejoe90 I have assigned you for now as you were working on this  before

**Comment by glupiawymowka** [comment]
*tested on .io*
