### ISSUE TITLE
Change email feature

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2414]
**Background**
Change email widget is an already working. Now its time to finalize it. Maintaining separate widget does not make sense anymore. Merge it into `EMAIL VERIFICATION` widget
- [x] if there's verified e-mail, add button 'CHANGE EMAIL ADDRESS`
- [x] when clicked allow to enter new e-mail, we have state for it
![image](https://user-images.githubusercontent.com/17202864/54088326-59419300-435d-11e9-8203-3fd7655a5d0e.png)

- [x] If the `new email` equals `current email` verified and unverified show error toast component with user has the same email.
- [x] If entered email is unavailable return an error [ALREADY DONE]
- [x] If entered email is available add new email [ALREADY DONE]
- [x] change existing toaster text after adding e-mail from `Your email address has been successfully added.` to `Activation link was sent to your email.`
- [ ] cleanup code, remove change e-mail widget and `PERSONAL SETTINGS` section, remove setting to show e-mail widget `NF_FEATURE_EMAIL_CHANGE_ENABLED`
- [x] Add e2e tests for all flows

All calls are done via `user` api 

**Zepplin**
not needed
**Component**
VerifyEmailWidget
**Acceptance criteria**
* initial e-mail activation must work correctly and without any changes - we are adding a new state after it's completed
* flow above must work. user should be able to change -> enter -> activate e-mail
* user should be able to cancel verification ONLY if there's already verified e-mail
* in case of LightWallet, **login link must be sent to new e-mail**
* all e-mail templates must make sense so full test on stage is required

**Testing notes**

**Comment by glupiawymowka** [comment]
- [ ] the buttons should be aligned (means, "update email address" should go lower)

![image](https://user-images.githubusercontent.com/18315589/55330470-6439a000-5491-11e9-8da3-472ac71a9d98.png)

- [ ] this is the email that I get when I change the address using light wallet. Things that are wrong here: 
- I didn't use the recovery phase, a separate template is needed here 
- The same sentence used twice (before each button) @vizmab please also take a look 

![image](https://user-images.githubusercontent.com/18315589/55330838-57697c00-5492-11e9-8a63-27f1c33166d2.png)

- layout used for buttons is different from the one we have when we register with light wallet 

![image](https://user-images.githubusercontent.com/18315589/55331231-1de54080-5493-11e9-8046-65d918f94d38.png)


- [ ] popup was supposed to be changed from sentence 1 to sentence 2, but it's merged instead. 
This is not valid, as the email was not added yet, it needs to be confirmed by clicking a link sent to user first. 
Please change to "Activation link was sent to your email address." 

![image](https://user-images.githubusercontent.com/18315589/55326396-ecb34300-5487-11e9-9da5-5aceaf46cc79.png)

- [ ] email that comes when Metamask or Ledger was used: 
no link to support added, @vizmab will check/change the copy 

 
![image](https://user-images.githubusercontent.com/18315589/55326953-48ca9700-5489-11e9-8d32-d8cee53fbccd.png)

WHAT IS CORRECT: 
- [x] for Lightwallet, new and working login link is coming
- [x] email requesting address change confirmation arrives to the new address 
- [x] transaction emails are being sent to the new email address

**Comment by glupiawymowka** [comment]
buttons, copy and links were fixed by Vizma. 
Popup and buttons on the platform still need to be changed
