### ISSUE TITLE
nEUR Step 3 - Purchase flow

### ISSUE THREAD

**Issue by falinebambi** [Neufund/platform-frontend#2415]
Background
nEUR Step 3 - Purchase
The user by our platform should be able to but nEUR tokens from Quintessence PLC

PRD https://docs.google.com/document/d/1tNrQGkVPDdSbSDaoJMNevPfQQtLjXc8l8Z_MZYA8MYo/edit

Zeplin

https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/dashboard?seid=5c586dc8ad117f42241edc39

Component

Acceptance criteria
- [x] Only the user with a verified account should be able to get nEUR
- [x] Every nEUR purchase should start with accepting ToS
Testing notes

**Comment by rudolfix** [comment]
## Technical notes

Please take a look in investment flow: invest with bank account on how to create reference/purpose line (starting with `NF`

it also contains code to print from modal

remember to check amount via `EuroTokenController` contract
```
function minDepositAmountEurUlps()
        public
        constant
        returns (uint256)
    {
        return _minDepositAmountEurUlps;
    }
```

**Comment by glupiawymowka** [comment]
1. I think my comment here got lost, but from the design I see that all the purchases should also start with accepting ToS
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c586d5c9022ce4290ddf6ba

2. There is a typo in the design, that appears also on stage now. It should always be nEUR if not in the header. Pease change to "To receive nEUR in your wallet..."
![image](https://user-images.githubusercontent.com/18315589/53402271-b9295880-39b1-11e9-9310-991f855b529b.png)

3. As we are not sending any email with transaction summary, We need to add PRINT button (@falinebambi )that would print all the given data. 
Next, please drop the last line
![image](https://user-images.githubusercontent.com/18315589/53403119-52a53a00-39b3-11e9-9e7b-1dd88ab3a826.png)
