### ISSUE TITLE
Unsuccessful login and registration on iOS 12 / Safari

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2425]
**Description**
It is not possible to register or sign-in with iOS 12 and 11

**Environment**
Use physical device or browserstack, both Safari and Chrome 

**Expected behaviour**
Normal ability to login and signup (at least on iOS12) 

**Screenshots**
![bs_realios_Mobile_iPhone XS-12.0 (2).jpg](https://images.zenhubusercontent.com/5c3ddac32c893f1dad8d7a9a/eb7205ed-022b-42fc-bd78-456ad571fd5a)

ios 12 
![image](https://user-images.githubusercontent.com/18315589/58802234-f6cefa80-860c-11e9-9039-3f7c568dfbb3.png)

ios 11 
![image](https://user-images.githubusercontent.com/18315589/58802379-53321a00-860d-11e9-84d9-88cf86a7ca51.png)

**Inspect**
Network: 

headers: 

Request URL:https://platform.neufund.io/api/user/user/me
Request Method:GET
Status Code:401
cf-ray:4e12203b3f6ba6c3-DUB
Content-Length:2517
Content-Type:application/json
Date:Mon, 03 Jun 2019 13:48:39 GMT
expect-ct:max-age=604800, report-uri=“https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct”
Server:cloudflare
X-XSS-Protection:1; mode=block
Provisional headers are shown
Accept:application/json, text/plain
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJzdWIiOiIweGZBZjdBMEVGMUU4NTVDNzBhM0VFYjQ4RDM5NEQxMzY4YTdBMUQwNGQiLCJ1aWQiOiIweGZBZjdBMEVGMUU4NTVDNzBhM0VFYjQ4RDM5NEQxMzY4YTdBMUQwNGQiLCJ1aWRfdHlwZSI6IndhbGxldF9hZGRyZXNzIiwiZXhwIjoxNTU5NjU2MTE5LCJpc3MiOiJuZXVmdW5kIiwiYXVkIjoiZXh0ZXJuYWwiLCJpYXQiOjE1NTk1Njk3MTkuNDkwNzgyNywianRpIjoiYTgxZDNlZTEtY2YwOS00OGE2LWI2NTAtOTk4ZmI4ODU3YWIwIiwicGVybWlzc2lvbnMiOnsic2lnbi10b3MiOjE1NTk1NzAzMTl9fQ.AElxTCasQTXEshHA4cl1ASq5rABdSZyn-Z2H3FHdwBtY8CRxPRjvl-fNL6mpsQ4EnxIqxAAtUSy4ObB2nBX8D539AKbd0rykqergIW-KyZCnFXrlfoeDyIC4WgYCJ-GD6hjCaP6Ky8qLq6wRend43yg9CIF6JBf6L7KuJW0EO7yHDD2-
Content-Type:application/json
Referer:https://platform.neufund.io/register/light
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

debug
:
“Exception type#<class ‘platform_common.jwt_validation.JwtPermissionRequiredException’>#Traceback (most recent call last):↵  File “/usr/lib/python3.6/site-packages/py_platform_common-0.0.4-py3.6.egg/platform_common/jwt_validation.py”, line 137, in validate_request_header_jwt_token↵    raise KeyError(“Bearer not found in Authorization”)↵KeyError: ‘Bearer not found in Authorization’↵↵During handling of the above exception, another exception occurred:↵↵Traceback (most recent call last):↵  File “/usr/lib/python3.6/site-packages/flask/app.py”, line 1813, in full_dispatch_request↵    rv = self.dispatch_request()↵  File “/usr/lib/python3.6/site-packages/flask/app.py”, line 1799, in dispatch_request↵    return self.view_functions[rule.endpoint](**req.view_args)↵  File “/usr/lib/python3.6/site-packages/flask_injector.py”, line 89, in wrapper↵    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)↵  File “/usr/lib/python3.6/site-packages/injector/__init__.py”, line 782, in call_with_injection↵    return callable(*full_args, **dependencies)↵  File “/usr/lib/python3.6/site-packages/connexion/decorators/decorator.py”, line 73, in wrapper↵    response = function(request)↵  File “/usr/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py”, line 117, in wrapper↵    response = function(request)↵  File “/usr/lib/python3.6/site-packages/connexion/decorators/response.py”, line 104, in wrapper↵    response = function(request)↵  File “/usr/lib/python3.6/site-packages/connexion/decorators/decorator.py”, line 44, in wrapper↵    response = function(request)↵  File “/usr/lib/python3.6/site-packages/connexion/decorators/parameter.py”, line 207, in wrapper↵    return function(**kwargs)↵  File “/usr/lib/python3.6/site-packages/py_platform_common-0.0.4-py3.6.egg/platform_common/jwt_validation.py”, line 174, in _wrap↵    check_permissions_as=check_permissions_as)↵  File “/usr/lib/python3.6/site-packages/py_platform_common-0.0.4-py3.6.egg/platform_common/jwt_validation.py”, line 145, in validate_request_header_jwt_token↵    raise JwtPermissionRequiredException()↵platform_common.jwt_validation.JwtPermissionRequiredException: Authorization failed due to missing permission(s): None with check of type all for uid None↵”
status
:
401
title
:
“Authorization failed due to missing permission(s): None with check of type all for uid None”
type
:
“platform_common.jwt_validation.JwtPermissionRequiredException”
**Version/screen**
Release2018, September
OS iOS, v12.1.3
Browser Safari
Screen Size 5.8 in - 2.79 x 5.65 in
Resolution 1125 x 2436 px
Viewport 375 x 812 dp
Aspect Ratio 19.5 : 9

**Comment by glupiawymowka** [comment]
still getting error when trying to register on .net

**Comment by Moejoe90** [comment]
What about `io`?

**Comment by glupiawymowka** [comment]
it's fine on .io
fine on .org
not working on .net

**Comment by Moejoe90** [comment]
I'll move this to the backlog then

**Comment by glupiawymowka** [comment]
hey, this got quite urgent as we started to focus on mobile a lot. 
Not having it fixed prevents me from testing the mobile view on all the environments

**Comment by pstroinski** [comment]
Seems that the problem here is with the basic auth. 
Platfom that has basic auth set (dev/stage) are not working, prd and demo are ok

**Comment by pstroinski** [comment]
@desfero: Seems to be a Safari/Edge and mobile browsers bug. When we use basic auth it’s not possible to overwrite Authorization header with our custom Bearer token.
The workaround is to not use Authorization header for JWT token but rather some custom one (like Authorization-JWT).
Some discussion is here https://github.com/axios/axios/issues/1469

**Comment by rudolfix** [comment]
when merged alt header will be recognized as per description
https://github.com/Neufund/platform-backend/pull/2049

still my proposition is to set both Authorization and X-NF-Authorization headers, Authorization is differently treated when caching etc.

`X-NF-Authorization` has precedence so combination of working `X-NF-Authorization` and broken `Authorization` will work

**Comment by glupiawymowka** [comment]
tested on stage
