### ISSUE TITLE
send NEU and equity tokens tokens from Portfolio

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2437]
**Background**
We want to enable sending tokens from Portfolio, see epic for rationale

**Designs**
See #3311 

**Acceptance criteria**
* [x] we provide "SEND" action for any token in MY ASSETS in protfolio (NEU and any equity token)
* [x] action is enabled only if token is transferable (see below), alternatively, as such check is expensive we can do it in transfer modal and provide explanations there (@Louisswryan we would need a desgin in that case)
* [x] withdraw modal should observe `decimals()` value of ERC20 standard and use ERC20 standard for token name and symbol
* [x] withdraw all is supported as usual with all the rounding tricks we use. we should be able to withdraw up to the wei as gas is not impacting the token value
* [x] we should detect all edge cases ETH withdraw is detecting (smart contract withdraw, new user, verified neufund user etc.)
* [ ] in case we send to smart contract we should detect if ERC223 transfer is supprted by the withdrawing contract and display proper information

**Technical notes**
1. you should obtain precision of the token by getting `decimals()` and use it in all calculations. NEU has 18 decimal places (standard). equity token has 0 decimal places. but please do not hardcode, take it from token contract
2. if tokens are transferred to smart contract we should check if ERC20 transfer is supported. this can be done in two ways
- doing estimate gas on `transfer(to, amount, data)` 
- doing a eth_call on `transfer(to, amount, data)` and see if it reverts or not.
if we can use it, we should use it.
if not we use normal transfer. we should provide info that smart contract will be notified/not notified
3. how to check if token is transferable. there are (unfortunately) two ways
- for NEU there's `transferEnabled()`
- for any other tokens on our platform we provide standard means of checking transferability
call `tokenController()` on a token. then on token controller (which has artifact of name `ITokenController`), call `onTransfer`. see definition in `platform-contracts`
if any of those calls revers, we are using foreing token, then just assume it's transferable
4. method above requires to know `to` address and `amount` so if we want to check it before we know it
then
- choose `to` address randomly
- choose `amount` to be single unit of `decimals()`
5. we do not have any tokens that require KYC for transfers (except nEUR for which we'll not provide UI)

**Testing notes**
* [x] we have fixtures with NEU that can be used for NEU transfer
* [x] we have fixtures with equity tokens that can be used for transfer
* [x] we have fixtures for equity tokens that are not transferable

**Comment by rudolfix** [comment]
there's a standard to add token to web3 wallets, we should expose it for compatible wallets like Metamask
https://github.com/estebanmino/EIPs/blob/master/EIPS/eip-747.md

**Comment by andywalton** [comment]
@Louisswryan Will you focus on transferring a token "out" ie. sending a token from Neufund to another wallet address.

Please will you add a "trigger" call to action to the Portfolio view - ie. per Token you own. It could be a <- -> icon that when clicks allows you to send a token. We later can consider how we add a token via a transfer in (receiving a token from another wallet you have)

**Comment by Moejoe90** [comment]
**Technical notes**
1. you should obtain precision of the token by getting `decimals()` and use it in all calculations. NEU has 18 decimal places (standard). equity token has 0 decimal places. but please do not hardcode, take it from token contract
2. if tokens are transferred to smart contract we should check if ERC20 transfer is supported. this can be done in two ways
- doing estimate gas on `transfer(to, amount, data)` 
- doing a eth_call on `transfer(to, amount, data)` and see if it reverts or not.
if we can use it, we should use it.
if not we use normal transfer. we should provide info that smart contract will be notified/not notified
3. how to check if token is transferable. there are (unfortunately) two ways
- for NEU there's `transferEnabled()`
- for any other tokens on our platform we provide standard means of checking transferability
call `tokenController()` on a token. then on token controller (which has artifact of name `ITokenController`), call `onTransfer`. see definition in `platform-contracts`
if any of those calls revers, we are using foreing token, then just assume it's transferable
4. method above requires to know `to` address and `amount` so if we want to check it before we know it
then
- choose `to` address randomly
- choose `amount` to be single unit of `decimals()`
5. we do not have any tokens that require KYC for transfers (except nEUR for which we'll not provide UI)

**Comment by glupiawymowka** [comment]
tested on stage
