### ISSUE TITLE
Mobile View. Hide Ledger and Metamask button on sign in. 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#2438]
Pls. provide designs for the front end that hides Metamask and Ledger sign in on mobile views. 

It's UX case to see. 

User might skip wallet selector. 
@andywalton to research.

---
Tasks for this:
- [x] Review how it currently works. Confirm the situations where MetaMask and Ledger don't work - ie. is this only a mobile situation or do specific browsers not support this type of logins.
- [ ] Wireframe out a revised solution for this
- [ ] Test internally to verify it's okay
- [ ] Document for handover (see if additional design is require or if this can go straight to dev)

**Comment by andywalton** [comment]
Hello, I'm busy looking at this today. I've added a small task list to show what I'm busy with.

**Comment by falinebambi** [comment]
Linked to this ticket: https://github.com/Neufund/platform-frontend/issues/688 Designs are there
