### ISSUE TITLE
Remove EIP55 package and use web3-utils to get checksummed eth address

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2448]
**Background**
We can get rid `eip55` by using https://web3js.readthedocs.io/en/1.0/web3-utils.html#tochecksumaddress. Fewer dependencies mean lower maintenance cost and fewer bugs/security vulnerabilities 

**Acceptance criteria**

**Technical notes**
Probably we need to update `web3-utils` to the latest version to have `toChecksumAddress`.

**Testing notes**
The platform should work exactly as previously. This issue affects how we internally generate a checksummed address (see EIP55) but it should not change anything from a visual point (we have e2e tests for this so probably manual testing is not needed here)

**Comment by Moejoe90** [comment]
I suggest we take out web3-utils completely 
honestly, both packages can be taken out, these are just utility functions so I don't think there would be much code to add

**Comment by desfero** [comment]
ok, we agreed to remove both `web3-utils` and `eip-55`

**Comment by Moejoe90** [comment]
- [ ] Remove EIP55 
- [ ] Remove Web3-utils
- [ ]
