### ISSUE TITLE
Update the nEUR emails

### ISSUE THREAD

**Issue by huesforalice** [Neufund/platform-frontend#2455]
There are 4 new emails in Sendgrid:

NEUR_PURCHASE_SUCCEEDED
NEW_BANK_ACCOUNT
NEUR_REDEEM_REQUEST_RECEIVED
NEUR_REDEEM_REQUEST_APPROVED

There are a few tasks to be done
* Create the right header images
* Make sure the formatting of the text looks good
* Make sure that the links contained in the text point to the correct url
* Make sure that someone from marketing reviews the copy

**Comment by huesforalice** [comment]
PS: This feature will be released in the first week of March, the sooner you can get the wording done the better.

**Comment by glupiawymowka** [comment]
Hey, I guess this is already live. 
However, there are some differences between emails (see the links format, buttons, etc.)
I guess that in general, we need to overview all the emails we send: 

1. BANK VERIFICATION
![image](https://user-images.githubusercontent.com/18315589/53642393-fdc32700-3c31-11e9-9dc2-e1cf5ce2a504.png)

2. nEUR PURCHASE
![image](https://user-images.githubusercontent.com/18315589/53642470-26e3b780-3c32-11e9-86f8-300dadffb70a.png)

3. KYC SUCCESS
![image](https://user-images.githubusercontent.com/18315589/53642609-7cb85f80-3c32-11e9-8dac-bff4bdf452ad.png)

4. Payout accepted
![image](https://user-images.githubusercontent.com/18315589/53642673-9bb6f180-3c32-11e9-8959-e0bdcbb011a1.png)
5. NEWSLETTER
![image](https://user-images.githubusercontent.com/18315589/53643249-e2591b80-3c33-11e9-9bd0-7a44ed39d6a1.png)

**Comment by andywalton** [comment]
Ula and Vizma cleaned up these emails + header images on Thursday. They all seem to be working fine but let me know if anything isn't working and we can open a new ticket to fix.
