### ISSUE TITLE
Transaction complete pop-up shows incorrect link for the ether transaction

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2460]
**Description**
On the success screen of transaction complete we have incorrectly formed link where transaction hash should link to the etherscan, so  it's not clear it a link! 
It may be that the whole flow is like that.
The same situation we have on transaction reverted state.

**Environment**

**Steps To Reproduce**
Make a sending transaction

**Actual behaviour**
https://etherscan.io/address/0xb8abbe330e6bd917b1027f4a1e080903871d90f9055686ce87d25f338e3a0e8d - WRONG

**Expected behavior**
https://etherscan.io/tx/0xb8abbe330e6bd917b1027f4a1e080903871d90f9055686ce87d25f338e3a0e8d - GOOD

**Comments, context, logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/195594/52784395-3b7e5800-3055-11e9-9668-47c703a45091.png)

**Comment by glupiawymowka** [comment]
*tested on .io and .net*
