### ISSUE TITLE
Issuer Dashboard - templates cannot be downloaded when ETO in on-chain state

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2470]
**Description**
When trying to download Reservation And Acquisition Agreement when ETO is in on chain state: `payout` or `claim`, backend refuses to resolve placeholders for this document.
The cause is that we pas 0x0 address to the resolver. 
```
https://platform.neufund.org/api/eto-listing/etos/me/templates/reservation_and_acquisition_agreement?inputs=%7B%22token_holder_ethereum_address%22%3A%220x0000000000000000000000000000000000000000%22%7
```

**Environment**
Issuer dashboard with ETO in payout or claim states

**Steps To Reproduce**
Login on io environment with 0x007D45D94368AE57ac8351604dC1cB3236150727 (ISSUER_CLAIMS).
go to:
![image](https://user-images.githubusercontent.com/17202864/52884045-2563bb00-316d-11e9-9ef2-04d64a0c1b5b.png)
Click on Reservation and Acquisition Document

**Actual behaviour**
Download document fails

**Expected behavior**
Download of unresolved template as docx happens

**Comments, context, logs**
To fix please do not resolve any of templates if eto is in on chain state (`eto.state`). Instead download directly from immutable storage api

**Comment by glupiawymowka** [comment]
*tested on .io*
