### ISSUE TITLE
Issuer Dashboard - old start date widget displayed on production

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2471]
**Description**
On FORCE eto old widget is displayed - without a sheep

**Environment**
production

**Steps To Reproduce**
Ask @Vanilizer to log in and show you issuer dashboard for FORCE

**Actual behaviour**
Shows old ugly widget

**Expected behavior**
Show sheep

**Comments, context, logs**
This is ok on io environment. use ISSUER_PAYOUT metamask account

**Screenshots**
![image](https://user-images.githubusercontent.com/17202864/52884652-da4aa780-316e-11e9-8f22-831ba96f1f73.png)

**Comment by AlexeyTuboltsev** [comment]
@Vanilizer can't check it on .net because of a bug related to ledger

**Comment by glupiawymowka** [comment]
now, when ledger is fixed, I'll ask @Vanilizer to check this problem again

**Comment by shanile** [comment]
@Vanilizer please provide a screenshot of the FF ETO widget and see if the sheep is there

**Comment by shanile** [comment]
Test note:

here you can see the outside widget on platform.org

![image](https://user-images.githubusercontent.com/36156487/55549760-e9fa5d00-56d6-11e9-8c13-de70937cc249.png)

which still don't have the sheep @Vanilizer to provide with screenshot from the FF account

**Comment by Vanilizer** [comment]
As an issuer on the ETO preview page i do not see the bouncing sheep:
![image](https://user-images.githubusercontent.com/26923972/55550502-9e48b300-56d8-11e9-9f5e-c041d5e439a4.png)
