### ISSUE TITLE
[LOGIN] - double Signature Request is sent to Metamask 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2493]
**Description**
There is a specific edge case when the user is not logged into Metamask, wants to login/register on the platform, enters his password in MM and ends up having two Signature Requests in MM.

**Environment**
all. Kirstyn and Marcin also confirmed it on Opera Mobile

**Steps To Reproduce**
1. Make sure you're logged out of MetaMask plugin 
2. Go to "Login" or "Register" and choose MetaMask
3. When MetaMask plugin will ask you, enter your password
4. Next, a Signature Request will appear, but on the plugin icon you will see 2 popups (red square)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/219a703e-9156-4d5c-b37e-c40583cae568)
5. Sign the request
6. You will be logged in, but the second request will appear
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/45ae8096-d2aa-4667-a6b7-1f403d5b9333)

**Actual behavior** 
If you click "Sign" - nothing specific happens
If you click "Cancel" - you're logged out of the platform
**Expected behavior**
User should not get the second popup that logs him out of the platform

**Comments, context, logs**
You can use any MetaMask account to check it
**Screenshots**

**Comment by Desperado** [comment]
I have tried in Opera for Android and it was not exactly double signature request, but 4 or 5 signature requests

**Comment by glupiawymowka** [comment]
*tested on .io*
Both for chrome and chrome incognito mode, no multiple signature requests were sent. 

@Desperado please check with Opera mobile on .io

**Comment by Desperado** [comment]
@AlexeyTuboltsev 
 testing on platform.neufund.io with Opera Mobile and can't somehow see how can I sign any transaction. Everything is turned on. Page pops me up to reload the browser.
![Screenshot_20190320-115110_Opera](https://user-images.githubusercontent.com/195594/54679092-c47e2880-4b06-11e9-8ede-5ed640e6c276.jpg)
Also the layout seems to be shifted
![Screenshot_20190320-115121_Opera](https://user-images.githubusercontent.com/195594/54679094-c516bf00-4b06-11e9-91eb-2560aa1bde5f.jpg)

**Comment by glupiawymowka** [comment]
@Desperado please check with Opera Mobile on .net 

Web version is fine on stage

**Comment by glupiawymowka** [comment]
@Desperado said he checked it on stage, so I'll move it
