### ISSUE TITLE
Upgrade Ledger provider to use LedgerHQ provider 

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2497]
**Background**
Its time to upgrade our ledger provider to use the latest LedgerHQ provider
**Designs**
N/A
**Acceptance criteria**
Everything should work normally after the upgrade
**Technical notes**

**Testing notes**

**Comment by glupiawymowka** [comment]
current status on .net: 
no matter which derivation path is chosen, user is logged into the first one

**Comment by Moejoe90** [comment]
good catch @glupiawymowka

**Comment by glupiawymowka** [comment]
*tested on .net*
the login screen was loading a bit slow for 2 out of +10 tries
- [x] incoming transactions are visible on the accounts
- [x] outgoing transactions are correctly sent
- [x] different derivation paths are opening correct accounts
