### ISSUE TITLE
JWT expiring too soon

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2500]
**Description**

https://sentry.neusrv.net/sentry/production/issues/843/
https://sentry.neusrv.net/sentry/production/issues/3209/
https://sentry.neusrv.net/sentry/production/issues/3986/
https://sentry.neusrv.net/sentry/production/issues/3206/
https://sentry.neusrv.net/sentry/production/issues/4179/
https://sentry.neusrv.net/sentry/production/issues/3782/
https://sentry.neusrv.net/sentry/production/issues/1889

**Environment**
MacOsX 10.14 Chrome 72.0.3626

**Actual behaviour**
Sentry messages

**Expected behavior**

**Comments, context, logs**

JWT expiring too soon

logger |  
-- | --
0 | Getting key: NF_JWT from storage

Error while loading GAS api data.
--

**Screenshots**

**Comment by Desperado** [comment]
also has a corresponding backend issue on sentry 
https://sentry.neusrv.net/sentry/backend-python-production/issues/299/?query=is:unresolved

**Comment by Moejoe90** [comment]
@Desperado @glupiawymowka 
I will move this to QA directly 
the only way to make sure this is working is that we stop getting these errors from sentry 
If these errors still persist then please raise a new ticket and we will look at the options

**Comment by Desperado** [comment]
Ok @Moejoe90 
We should be able to observe it when it will go to production

**Comment by Desperado** [comment]
Resolved issue in Sentry
