### ISSUE TITLE
If node fails, other requests also fail.

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2501]
**Description**
When we have invalid JSON rpc response, we need to ignore it. Make sure that the process will retry the request.

**Environment**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Steps To Reproduce**
Sentry issue

**Actual behaviour**

**Comments, context, logs**
Error: Invalid JSON RPC response: ""
https://sentry.neusrv.net/sentry/production/issues/3052/

**Screenshots**

**Comment by Moejoe90** [comment]
This Ticket will be split into two tickets 

- [ ] Add retry on RPC fail for Batched methods 

- [ ] Assert that if a web3 method is not using batch if yes inject a separate retry on rpc layer abstraction

- [ ]

**Comment by pstroinski** [comment]
Will be fixed with the web3 upgrade
