### ISSUE TITLE
Cannot read property 'timedState' of undefined

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2502]
**Description**
A clear error state should be implemented on the component level.

**Environment**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Steps To Reproduce**
Sentry Issue

**Actual behaviour**

**Comments, context, logs**
https://sentry.neusrv.net/sentry/production/issues/1880/

**Screenshots**

**Comment by desfero** [comment]
@Desperado I'm not able to find how this can happen now and from what I see this issue happens last time 3 months ago so maybe it was somehow fixed between.
I marked all issues related to `timedState` as resolved for now on sentry so we get a notification when this appears again.

Let's close this issue for now?

**Comment by Desperado** [comment]
Yes, if it is unclear and not happenning again, we can close it @desfero
