### ISSUE TITLE
Cannot read property 'web3' of undefined

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2503]
**Description**
ETO contract data could not be loaded
Cannot read property 'web3' of undefined

**Environment**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Steps To Reproduce**
Sentry Issue

**Actual behaviour**

**Expected behavior**

**Comments, context, logs**

**Screenshots**
https://sentry.neusrv.net/sentry/production/issues/1879/

**Comment by drakkein** [comment]
This error seems to be really old, last reported failure is from 2nd December. Ticket should be reopened if failure occurs again.
