### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2504]
**Description**
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Environment**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Steps To Reproduce**
Sentry Issue  

**Comments, context, logs**
https://sentry.neusrv.net/sentry/production/issues/923/

A critical error occurred NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. [object Object]
--
logger | console
extra | {"arguments":[{"message":"Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.","name":"NotFoundError","stack":"Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.\n    at Eo (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:280:68414)\n    at Ra (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:280:87804)\n    at Pa (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:280:85182)\n    at Ia (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:280:84527)\n    at ka (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:280:83548)\n    at Qo (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:280:82451)\n    at Object.enqueueSetState (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:280:47379)\n    at t.w.setState (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:272:1669)\n    at https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:16:7667\n    at m (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:106:14170)\n    at a (https://platform.neufund.org/0f1108222b8c0d3074ce.main.min.js:1:1267118)\n    at https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:49:132297\n    at https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:155:94140\n    at Object.submitForm (https://platform.neufund.org/0f1108222b8c0d3074ce.main.min.js:1:982991)\n    at Object.handleSubmit (https://platform.neufund.org/0f1108222b8c0d3074ce.main.min.js:1:981681)\n    at Object.t.handleSubmit [as onSubmit] (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:125:56896)\n    at t.n.executeSubmit (https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:125:49458)\n    at https://platform.neufund.org/fd263fecd24786b4fd15.vendors~main.min.js:125:49362"},{"componentStack":"\n    in div\n    in button\n    in div\n    in form\n    in Unknown\n    in Form\n    in t\n    in Unknown\n    in t\n    in Unknown\n    in t\n    in WithFormik(Function)\n    in div\n    in Me\n    in div\n    in Se\n    in Unknown\n    in Connect(Component)\n    in Unknown\n    in Connect(Component)\n    in section\n    in Unknown\n    in Connect(Component)\n    in t\n    in t\n    in Connect(t)\n    in Unknown\n    in div\n    in Me\n    in div\n    in Se\n    in div\n    in _e\n    in Unknown\n    in Unknown\n    in div\n    in Unknown\n    in Unknown\n    in Connect(Component)\n    in w\n    in Connect(w)\n    in s\n    in Unknown\n    in Unknown\n    in t\n    in w\n    in Connect(w)\n    in t\n    in Connect(t)\n    in Unknown\n    in w\n    in Connect(w)\n    in T\n    in Connect(T)\n    in w\n    in Connect(w)\n    in Unknown\n    in t\n    in t\n    in a\n    in Connect(a)\n    in IntlContainerInjector\n    in Unknown\n    in InjectIntl(Component)\n    in IntlProvider\n    in Unknown\n    in Unknown\n    in t"}]}

**Screenshots**

**Comment by desfero** [comment]
I don't see how we can reproduce this one. It's also not reported to the sentry last 3 months so let's close it.
