### ISSUE TITLE
Start using new block feature from Provider Engine

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2508]
**Background**
Provider Engine has a callback function for new blocks. This feature can be used to emit `NEW_BLOCK_MINED` events to the app. All previous calls that depend on timely delay for polling can actually get triggered by `NEW_BLOCK_MINED`. 

Advantages: 
 - This will minimize the number of redundant requests to the eth node
 - All direct polling requests can be batched into one request

Provider Engine is currently outdated. 

Please update Provider Engine to the latest version 
Things to get taken into account is:

Bundle Size if its too big we won't add it

Check with @rudolfix the issue he wanted to solve  
https://github.com/Neufund/platform-frontend/pull/3848
**Designs**
N/A
**Acceptance criteria**
 - All three wallets should Emit `NEW_BLOCK` event while the app is running. 

 - Replace all polling mechanism with new block trigger

Good to have: 
 - All polling calls should be batched

**Technical notes**

**Testing notes**

**Comment by rudolfix** [comment]
please note that we should have only one provider that can generate this event at a time. 
what about unlogged state? should our "read only" provider by used to generate new block events? wallet providers are only in context of logged on user

**Comment by Moejoe90** [comment]
I will update the ticket so that it uses `https://github.com/MetaMask/eth-block-tracker`
With this we only need to wrap a web3 object with the tracker then events will happen automatically
