### ISSUE TITLE
nEur Balance description text copy change (Wallet View)

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2523]
Our customers will soon navigate to their Wallet and see a new nEur Balance component, see the below screenshot.

![image.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/14f37a55-aadb-4f80-b8cb-ff6c8561d02f)

This ticket is for a minor copy update to the description of this balance.

**What's currently on the platform:**
This is your nEUR balance which you may use to invest in opportunities on the platform. nEUR tokens are stable coins provided by Quintessence PLC that mirror euro investment on the platform. You can purchase nEUR from Quintessence PLC via bank transfer. In order to receive funds you will be asked to return the nEUR token. Go to you dashboard to view available investment opportunities.

**Needs to change to this:**
This is your nEUR balance. You can use it to invest through Neufund or redeem to your bank account. nEUR represents a Euro equivalent and is issued by Quintessence PLC.

* Note the word Quintessence PLC needs to link to https://quintessence.global/ in a new browser tab.

**Acceptance criteria**
This copy change has been completed, tested and pushed with the next available release.

**Comment by glupiawymowka** [comment]
*tested on dev and stage*
