### ISSUE TITLE
Redeem Flow - if there is incorrect number input, don't calculate the other fields

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2526]
**Description**

**Environment**
INV_ICBM_EUR_M_HAS_KYC

**Steps To Reproduce**
1. Go to your wallet
2. Click Redeem. 
3. Use input field.

**Actual behaviour**
a) when input very big number, other feilds like bank transaction fee and total, are also calculated
b) when input something like 015 as a sum to redeem, it is accepted and forwarded later

**Expected behavior**
a) we should lock the other fields if the input is incorrect
b) we should cut unnecessary zeroes along the result of the input, as this number may be saved incorrectly later.

**Comments, context, logs**

**Screenshots**

![selection_030](https://user-images.githubusercontent.com/195594/53505489-35a46000-3ab4-11e9-811f-f413ce3e1ada.png)
![selection_031](https://user-images.githubusercontent.com/195594/53505488-35a46000-3ab4-11e9-8080-1180d4e31719.png)
![selection_032](https://user-images.githubusercontent.com/195594/53505486-35a46000-3ab4-11e9-8d59-df4083c92ca4.png)
![selection_033](https://user-images.githubusercontent.com/195594/53505484-350bc980-3ab4-11e9-86a6-70c9d34efb25.png)

**Comment by glupiawymowka** [comment]
this is already implemented to production
