### ISSUE TITLE
adding more restricted countries 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#2531]
Please block those countries from investors flow 

Afghanistan
American Samoa
Guam
Iraq
Libya
Nigeria
Pakistan
Panama
Puerto Rico
Samona
US Virgin Islands

If any questions please contact me

**Comment by Moejoe90** [comment]
There is no country with the name `Samona`

**Comment by shanile** [comment]
@Moejoe90 its part of US so ignore it, sorry

**Comment by glupiawymowka** [comment]
*TESTED all countries on .io*
