### ISSUE TITLE
[nEUR Redeem] - prevent users from entering characters other than numbers

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2534]
**Description**
Currently, we allow the users to enter all the signs they want in the "Amount to Redeem" input. 
However, this ends up with a strange error label below. Also when they use a coma for amounts. 

We have this case solved well in investment flow, where user can only enter numbers or " . ". 
 
**Environment**
All, this is also live.

**Steps To Reproduce**
1. on .net, you can use this fixture with a verified bank account:
0xE6Ad2CdBA2FB15504232eBFa82f64c06c87F9326

2. Go to wallet
3. Try to enter special signs, letters, comas, negative values

**Actual behaviour**

errors when coma is a decimal separator
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/05fb765d-89b5-4b7a-9fee-900ab02847e6)

all kinds of characters are allowed

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/82d59cad-f462-4809-94f6-99483469769e)

**Expected behavior**

It would be perfect to have the same solution as in investment flow (you can see it on .io with the same fixture as above). 
Here, I can only enter dot or numbers and entering a dot automatically pushes "0" in front. 

![investment.gif](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/defec127-2b47-44c5-b602-5fde4726ec2e)

**Comment by drakkein** [comment]
Connected to #1484. Will require to create proper masked input component

**Comment by glupiawymowka** [comment]
*tested on .io*

**Comment by glupiawymowka** [comment]
*tested on .net*
