### ISSUE TITLE
Issuers ETO Forms - update ETO Terms forms with new multi-jurisdiction product types

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2548]
### Background
The "Taskforce Legal Product Design" is exploring how we might offer multiple products via multiple different jurisdictions to our customers. This change to the platform has many legal and product considerations.

_For more information please refer to the Epic description: #2546_

---

### Context

This ticket describes the changes required to allow an Issuer to successfully setup an ETO campaign now that we offer multiple ETO products in two different jurisdictions.

**This ticket focusses on the ETO form: ETO Terms. Therefore, as an Issuer user I can...**

1.0) Login to Neufund to my Dashboard view.

2.0) I will see a list of ETO form cards that have been sectioned into two groups, namely: 1) Company Information and Marketing Content and 2) ETO settings. For this change, please see this ticket: #2633

3.0) When I click on the ETO Terms card I will see the following form. 

![image.png]
(https://images.zenhubusercontent.com/57c01da2e40e5714b16dddf9/6c43b216-97f3-4ce2-932f-1e523d0e3a0d)

3.1) I will see a radio list of 6 available ETO Types. The default ETO type is already selected for me (the first item - MINI ETO in Lichtenstein. 

![Screenshot 2019-04-01 at 14.07.15.png](https://images.zenhubusercontent.com/57c01da2e40e5714b16dddf9/1d2f7cd5-edd3-4043-8fa3-3c067a70c7ff)

When I hover over on ETO Type in this list it will show a tooltip for that product details. Each will display 5 bullet points namely:

- Max investment amount (Unlimited EUR raise / Maximum 5M EUR raise)
- Min. ticket size (10 EUR minimum ticket size / 200k EUR minimum ticket size)
- Asset type (Security / Investment Asset)
- Document type (Security / Investment Memorandum)
- Transferability of token (ie. Token is transferable / Token isn’t transferable)

![Screenshot 2019-04-01 at 14.11.12.png](https://images.zenhubusercontent.com/57c01da2e40e5714b16dddf9/29574bc2-c2e6-48ec-8814-d49ff7044531)

These bullet values should be pulled directly from the API on a per product basis, you would need to correctly word them as per the examples given above.

Note the order for these ETO Types is:
1. Mini ETO in LI (Maximum 5M EUR raise, 10 EUR minimum ticket, Security, Investment memorandum, Token is transferable)
2. High Net Worth Individual ETO in LI (Unlimited raise, 100k EUR minimum ticket, security, Investment memorandum, Token transferable)
3. High Net Worth Individual ETO in DE (Unlimited raise, 200k EUR minimum ticket, Investment asset, Investment Memorandum, Token not transferable)
4. Retail ETO in DE (Unlimited raise, 10 EUR minimum ticket, Investment asset, Investment Prospectus, Token not transferable)
5. Retail ETO in LI (Unlimited raise, 10 EUR minimum ticket, Investment asset, Investment Memorandum, Token not transferable)
6. Retail ETO in LI (Unlimited raise, 10 EUR minimum ticket, Security, Security prospectus, Token is transferable)

3.2) I am able to change my ETO Type selection from the default one selected (provided by the API) to one of the other 5 options.

3.3) Changing the selected ETO Type will change the fields in the gray box below. These items aren’t editable and they will be pulled in directly from the API for this phase of the project.

![Screenshot 2019-04-01 at 14.17.17.png](https://images.zenhubusercontent.com/57c01da2e40e5714b16dddf9/5c6d16de-d44e-42a8-abbc-eea36c791753)

3.4) Below this gray box, not the text below the ETO selection highlighting your minimum ticket size based on your ETO Type selection.

![Screenshot 2019-04-01 at 14.45.25.png](https://images.zenhubusercontent.com/57c01da2e40e5714b16dddf9/d7a8a1c0-d5d2-4a64-9efb-43d4dd00d8bf)

3.5) All the other fields that aren’t in the gray box are editable. The validation for these fields should be handled by the API.

3.6) The user should be able to save their changes and exit back to the Dashboard.

---

### Designs

https://zpl.io/Vk58WN5

---

### Acceptance & testing criteria
- [x] As a user I can hover over each ETO Type radio item and view a tooltip showing the correct 5 bullet items pulled from the ETO product type API.
- [x] As a user I can only select on ETO Type (ie. I can’t select multiples).
- [ ] As a user, when I select an ETO Type, the gray box below displays my ETO settings which are not editable by myself. ~~It displays a disabled cursor icon~~ (moved to #2722 ).
- [ ] As a users, after saving my ETO Terms changes, when I save and revise the page these changes have been saved.
- [ ] As a user, I cannot enter incorrect values into fields constrained by the product definition: ticket sizes, offering periods and other validations for whose constraints are provided by the backend. see below (in essence we remove hardcoded validators by ones that backend provides)
- [ ] As a user, I'm warned in the "Investment Terms" form, in the calculator section, when the Maximum Investment amount is higher than those in the product definition, but still I can set such higher amount
- [ ] As a user, I do not see "WHEN THE TOKEN IS TRADABLE" selection if the asset type is investment asset (`vma`). The token tradeability is in that case set to later
---

### Technical notes
The backend now provides two new endpoints you can use for managing the eto products. You can find them on the eto_listing_api (see swagger ui)

1) Endpoint **/products** will return a list of all products available on the system. An example product looks like this:
```
  {
    "asset_type": "vma",
    "available": true,
    "can_set_transferability": false,
    "has_nominee": true,
    "id": "0000000000000000000000000000000000000000",
    "jurisdiction": "de",
    "max_claim_duration_days": 30,
    "max_investment_amount": 0,
    "max_offer_duration_days": 90,
    "max_public_duration_days": 60,
    "max_signing_duration_days": 60,
    "max_ticket_size": 0,
    "max_whitelist_duration_days": 30,
    "min_claim_duration_days": 7,
    "min_investment_amount": 0,
    "min_offer_duration_days": 1,
    "min_public_duration_days": 0,
    "min_signing_duration_days": 14,
    "min_ticket_size": 200000,
    "min_whitelist_duration_days": 0,
    "name": "hnwi eto de",
    "offering_document_type": "memorandum"
  }
```
Only Products that are "available" can be used. All other values should be pretty self-explanatory. Only in the case of "max_ticket_size" and "max_investment_amount" please note, that a zero value is equal to infinity, so there will be no restrictions on those values.

2) Endpoint **/etos/me/product** can be used to change the current product for the Eto. The payload for the request is {"product_id": 0x0000000000000000000000000000000000000001}. If the current values in the ETO conform to the product constraints, no changes will be made to the eto data. If the current values in the ETO do not confirm to the product constraints, defaults which are inside the constraints will be set.

**Comment by andywalton** [comment]
AGA has provided a printout of all the ETO setup wizard and the changes that are expected due to this multi-jurisdiction / multi-product type change. We now just need to document and designed if needed.

**Comment by Vanilizer** [comment]
please do this order and preselect MINI ETO:

MINI ETO in LI (max. 5M EUR, security, investment memorandum, token tradable)
HNWI ETO in LI (100k minimum ticket, security, investment memorandum, token tradable)
HNWI ETO in DE (200k minimum ticket, investment asset, investment memorandum, token not tradable)
RETAIL ETO in DE (investment asset, investment prospectus, token not tradable)
RETAIL ETO in LI (investment asset, investment memorandum, token not tradable)
RETAIL ETO in LI (security, security prospectus, token tradable)

**Comment by falinebambi** [comment]
Designs updated: ![image.png](https://images.zenhubusercontent.com/57c01da2e40e5714b16dddf9/69f01f2c-2fe3-43d3-a929-76b3bdcd4179)

Zeplin link: https://zpl.io/Vk58WN5

Preselected toggle for calculator shows active but user can not change: 

![toggle preselected.svg](https://images.zenhubusercontent.com/57c01da2e40e5714b16dddf9/9e37f5fd-27c6-4b5a-8abc-8d9795452186)

Screenshots above also updated

**Comment by desfero** [comment]
@falinebambi @andywalton can we move design related changes like removing background as a separete ticket? It would be then hard to review this as design changes touch more than a single place in the code. And generally it's a good practice to split this two always as a separate tickets to speed up with development, review and qa.

**Comment by glupiawymowka** [comment]
**This is a draft, please leave for now** 

Andy, Kirstyn please mind the guidelines while preparing / accepting the designs (we wanted to completely get rid of "€" on the platform and replace them with EUR)

*  MAXIUM TICKET SIZE input 
- [ ]  "Must be a 'number' type is not the user friendly copy, this should be changed here and globally @andywalton please propose a copy 
![image](https://user-images.githubusercontent.com/18315589/56224404-de604c00-606f-11e9-893a-c483e994788e.png)
- [ ] see the screen above. In the Investment flow, we will now automatically change commas into dot separators, and also actually not let people input the incorrect values (to check, PR #2747 )

**Comment by glupiawymowka** [comment]
1. This part is still true for all the ETO types that are not mini ETO: 

![image](https://user-images.githubusercontent.com/18315589/56746830-405e3700-677d-11e9-832c-de0963a6b00a.png)


2. There is no way to add a ticket higher than 5000000 for mini ETO, this is correct. 
But if I delete the value, the placeholder will still say "unlimited" 
Also, the minimum ticket placeholder is 1 instead of 10 
![image](https://user-images.githubusercontent.com/18315589/56747100-a8ad1880-677d-11e9-87fb-1644b0cc71fc.png)

**Comment by desfero** [comment]
@glupiawymowka 
1. We are going to move it to @AlexeyTuboltsev ticket about number formatting as agreed on a grooming one week ago
2. Fixed in https://github.com/Neufund/platform-frontend/pull/2826.

**Comment by glupiawymowka** [comment]
I confirm that the placeholders were fixed
