### ISSUE TITLE
Transaction email update - nEUR_redeem_request_received 

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#2550]
**Background**
When the user initiates nEUR redeem, they receive a transaction email (SendGrid - Platform - NEUR_REDEEM_REQUEST_RECEIVED), which should also include:
 
Bank account details: -bank_account_number-
Reference number: -purpose-
 
**Designs**
![redeem received](https://user-images.githubusercontent.com/48217191/53747813-64e81200-3ea4-11e9-898a-f7051dbd8cdf.png)

**Acceptance criteria**

**Technical notes**

**Testing notes**

**Comment by Moejoe90** [comment]
As per discussion with @vizmab this is done
