### ISSUE TITLE
hide payout announcements and payouts list when low amounts are redistributed

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2555]
**Background**
In case when low amounts of ETH or nEUR are distributed to token holders, we should not bother them with those. This applies both to announcements in Dashboard and payout table in Portfolio view.

**Designs**
No changes - we just hide parts of interface

**Acceptance criteria**
* in the announcement (dahsboard) - we do not display values below 100 nEUR or 1 ETH.
* in the payouts (portfolio) - we do not display values below 1 nEUR or 0.01 ETH
* if there's nothing to display we do not display widget.

**Technical notes**
technically: currently we have threshold to show widget and payout amounts at 0 now the threshold is as below.

**Testing notes**
With current fixtures it's very hard to test manually. There's already announcement on large amount created - this I do not know how to test. You can request fixture from @Exef for a user with very small amount of NEU that would produce such small values.

**Comment by shanile** [comment]
we are not sure how to test it

**Comment by drakkein** [comment]
@shanile this is not ready yet. There will be fixture that will have incoming payouts below display values, so you will be to test it using this fixture.

**Comment by rudolfix** [comment]
@drakkein @glupiawymowka we have an idea how to test it in e2e:

1. make all threshold configurable (they should be anyway)
2. mock high values for all thresholds at the beginning of e2e tests. like we do not show above 1000 EUR and 127 ETH (the same for announcement)
3. make sure elements are hidden accordingly for user that has payouts below this threshold etc.

we often test our configurations this way on backend and this works pretty well
