### ISSUE TITLE
[redeem flow] please add info about transaction fee to error message

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2556]
**Description**
We currently have this message if the user wants to redeem 5 > nEUR. 
However, it's said nowhere what is this "minimum fees amount" (and also it's not true as min. fee is 0.05)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/415d196c-b3f7-4001-8bea-764c6c1d0d6d)

Maybe we could simply change this text (that's why I've assigned you @andywalton) into something like "Please note that the minimum redeem amount is 5 EUR" (to discuss/rethink)

**Comment by rudolfix** [comment]
"Redeem amount should be 5 nEUR or more" where 5 is from smart contract minimum withdraw

**Comment by shanile** [comment]
tested and working
