### ISSUE TITLE
incorrect rounding of amounts in the wallet

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2557]
**Description**
Amount in nEUR wallet is weirdly rounded, possibly other wallets as well. My exact balance is 29.083350986799034666 but the displayed balance is 29.09 so it seems we *rounded up* which will always overstate holdings.

**Environment**
Production environment - my address 0x64Be85331949105Eb0459B936abF474710B4601b

**Actual behaviour**
Wallet is rounding up or inconsistently rounding.

**Expected behavior**
Please fix rounding in all wallets as follows:
1. nEUR wallets (nEUR + LockedAccount nEUR) - **round down** to two decimal places
2. ETH wallets (ETH + LockedAccount ETH) - **round down** to four decimal places

If you use same rounding function for NEU, you can also round them down to 4 decimal places

**How to test**
Please write unit test with a few cases. You can use 29.083350986799034666 which should round to 29.08 in case on nEUR and to 29.0833 in case of ETH and NEU

**Comment by glupiawymowka** [comment]
*tested on .io*
