### ISSUE TITLE
nEUR REDEEM - balance check incorrect

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2559]
**Description**
My actual holding of nEUR is 29.083350986799034666. Now I want to withdraw below that amount but application does not let me. Examples of amounts below that do not work:
29.080000001
29.083
29.081

**Environment**
Production - 0x64Be85331949105Eb0459B936abF474710B4601b

**Actual behaviour**
Hard to guess. It compares with something but hard to say what is this value or if we compare string or numbers

**Expected behavior**
All values below or equal actual balance with full precision should work. So in my case I should be fully able to withdraw 29.083350986799034666

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a72da804b5806bc2bc52ecc/f177c802-ef3f-4d6d-9a3c-7d8053cda565)

**Comment by Desperado** [comment]
tested on .io with other fixes.
