### ISSUE TITLE
[REDEEM] please add a tooltip to bank transaction fee

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2570]
**Background**
We have a bank transaction fee, but it's nowhere said how big it is and why.
Let's add a tooltip explaining it to the user. 

**Designs**

This is how the popup looks atm, we could add a tooltip as in some other places, or design it differently 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/0af2bba6-3809-43c1-8470-c0faa9a9bb8d)

**Wording**

When you redeem nEUR, a 0.5% transaction fee is charged by our banking partner. This fee will be deducted from the amount you've requested to redeem.

**Comment by falinebambi** [comment]
![Redeem](https://user-images.githubusercontent.com/17235402/54127309-c6aafd80-4409-11e9-924f-9dac8ad2ccd9.png)

Updated Design: https://zpl.io/bLKkY4YThis is also a universal styling change to Tooltips which will now be signified by a dotted underline. 

We will follow Material Design logic for the behaviour or tooltips.  
https://material.io/design/components/tooltips.html#behavior
![Screenshot 2019-03-11 at 14 29 17](https://user-images.githubusercontent.com/17235402/54127502-34efc000-440a-11e9-9870-b21e9cfb99df.png)

**Comment by glupiawymowka** [comment]
*tested on stage*
