### ISSUE TITLE
make ledger support great again

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2573]
We need several improvements to our ledger support

- [ ]  we need to bring back instruction to click OK on the ledger when signing transaction or message. currently it shows for split second or not at all (and you are in standard transaction modal). something hides it
- [ ]  we need to detect new firmware and setting to confirm each parameter of transaction individually.  `[NOT POSSIBLE NOW]`
- [ ]  if setting above is enabled we should modify instruction from point 1 to show that multiple clicks are required (you can compute number of clicks: it's number of parameters to the transaction + 2). if we can track clicks then track them `[NOT POSSIBLE NOW]`
- [ ] if firmware does not support `browser enabled` remove this step from the tutorial
- [ ] if settings from point (2) are enabled we can show to disable them instead of `browser enabled` step
`[NOT POSSIBLE NOW]`

3 and 4 will require simple design changes

**Comment by banciur** [comment]
@rudolfix regarding point 2 and 3 there is no way to detect this setting using documented features of ledger libraries. 
I created issue with question about this topic in ledgerjs github - https://github.com/LedgerHQ/ledgerjs/issues/321

Some extra remarks.
- Current ledger libraries implementation is much better than last one but there is one thing. Most of functions have 30s timeout. So for example we can detect device disconnection after 30s. 
- Another thing to concern here is that for example if user won't sign tx in 30 seconds promise will reject and from browser point of view it's timeout  but you will still see this tx on ledger.
- If you issue few tx's it will create queue of tx's to sign. So if we would introduce some race condition or allow user to click very fast on send button we could end in sending more transactions. To be tested is how web3 with ledger subprovider will behave. Will it set nonce correctly or not. Anyway user will see multiple tx's to sign.
- it works on firefox if user would set `security.webauth.u2f` config flag so we can think about adding 
- It didn't work on opera for me despite in theory it should (https://caniuse.com/#feat=u2f). Maybe I did something wrong around babel and code transpiling

**Comment by Moejoe90** [comment]
@Louisswryan 
![image](https://user-images.githubusercontent.com/23242822/54607360-7a397080-4a4e-11e9-9c6d-11edd2f21d48.png)

**Comment by Moejoe90** [comment]
@rudolfix 
just like @banciur said 
step 2,3 can't be done at the moment you only have `arbitrary contract` and `version`

**Comment by Moejoe90** [comment]
The flow was already changed by @desfero
