### ISSUE TITLE
use short nEUR purchase references

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2576]
**Background**
long references in form of `"NF"<space>Ethereum Address<space>REF<space>20 chars random string[<space>][G]` do not work correctly, they are often cut by banks or by bank apps UI. we'll switch to backend generated short references that are acquired each time reference is being displayed

**Acceptance criteria**
1. Each time user enters nEUR purchase/verification dialog new reference is obtained from the backend and displayed in `` field
2. when dialog is closed, e-mail notification is sent containing reference from (1)
3. reference is 10 random upper case letters and digits starting end ending with NF
4. if deposit is received with this reference it's attributed to the correct user in backoffice app

**Technical notes**
You can obtain reference via `neur-purchase-request-preparation` of `kyc_api`, see swagger
You need newest backend SHA

**Testing notes**
please also test the following
1. two deposits on the same reference with different amounts - should be visible in backoffice separately
2. deposit with old reference format (take something from backoffice or fake it) should be correctly processed

**Comment by glupiawymowka** [comment]
*tested on .io*

**Comment by glupiawymowka** [comment]
*tested on .net*
