### ISSUE TITLE
[redeem, metamask] transaction error while trying to redeem 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2583]
**Description**
Our user trying to redeem neur from his metamask wallet and getting this error constantly. 
I wasn't able to reproduce it on stage, but it's visible in sentry 
**Environment**
production
**Steps To Reproduce**
I wasn't able to reproduce it on stage, but for the user steps should be: 
1. Login to an account with a verified bank account and some nEUR on the platform
2. start redeem process, choose the amount
3. Continue 
4. Sign the transaction on Metamask
5. Here is where the error pops out 

**Actual behaviour**
Transaction in Metamask is not signed, so no nEUR are being redeemed. 
No entry about redeem request in backoffice (all the other requests are working fine) 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/d3e6e2f8-9868-4ff4-99f0-409667a84c50)
**Expected behavior**
Redeem request is signed and sent  to back-office for processing
**Comments, context, logs**
sentry error 
https://sentry.neusrv.net/sentry/production/issues/4678/?query=is:unresolved%20user:id:0xfc32Bb5207f058AD1c4F45a36f325BE5D47Bd03c

**Comment by desfero** [comment]
@glupiawymowka i'm really not able to reproduce in any way this error. Do you have any thoughts on how we can try to reproduce it on dev?

**Comment by glupiawymowka** [comment]
I also wasn't able to reproduce it. Will contact Customer Support to figure out if this still happens
