### ISSUE TITLE
Remove the graphic pattern from the background of the platform

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#2586]
Hi,

This is a change to be made across the board on both issuer and investor side.

Let's remove the graphic that sits towards the bottom of the background of the platform.

This has been signed off by all designers. We will be introducing more of our unique Neufund graphics into the platform and this background will make it too visually complex.

![Screenshot 2019-03-12 at 13.31.47.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/83137078-e7b3-44ce-86d3-b6d410ef490e)

**Comment by glupiawymowka** [comment]
*tested on .io*
as agreed with Louis, this is only about the dashboard. 
The pattern on the landing page can stay
