### ISSUE TITLE
[Investor flow] please adjust investment module visually to the current needs

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2587]
**Background**
@falinebambi I'm adding you so you can update the designs as well. 
We agreed to drop all the € symbols to be consistent with all the  money/token values in the future, as some of them don't have symbols. Also, "Eth Wallet " and "nEuro Wallet" is not consistent with any name that we use on the platform. 

**Designs**
This whole view needs fixes. What is wrong: 
- header, "SELECT YOUR WALLET TO INVEST" => "Select which balances you’d like to use" (also capital)
- to be consistent : "Invest Your Entire Wallet Balance" => first, it's the normal sentence, no need to start every word with a capital letter, second, "Invest your entire balance"
- Eth Wallet & nEuro Wallet => ETH balance & nEUR balance
- The same here
![image](https://user-images.githubusercontent.com/18315589/54371741-39221480-467a-11e9-87ad-ccbb1d0626e5.png)

- min. amount is 0.43 **EUR** 
![image](https://user-images.githubusercontent.com/18315589/54204031-b52e2800-44d3-11e9-9c4d-227b746bbbe7.png)
- The € symbol in the input should be changed to EUR
- the same problem in the estimated gas footer 
![image](https://user-images.githubusercontent.com/18315589/54204525-ab58f480-44d4-11e9-90ee-bb95a0f931a2.png)

**Acceptance criteria**
- [x] "select your balance" header is updated
- [x] "Invest your entire balance" button is updated
- [ ] balances to choose are named correctly (ETH balance t + nEUR balance) 
- [ ] no € symbol to be seen in the investment module

**Testing notes**
Can be tested on .io with 
INV_HAS_EUR_HAS_KYC fixture
0x0009c1d95c547d53e3b962059be11802b5e85ba3

**Comment by falinebambi** [comment]
@glupiawymowka We are updating designs for this in another ticket, will make sure that those above changes are applied.

**Comment by falinebambi** [comment]
@andywalton can you make phrase app text changes please. @Louisswryan can you double check the copy against the new designs for the enable ICBM wallet ticket

**Comment by Louisswryan** [comment]
This is how the investor flow appears now

Zeplin: https://zpl.io/VkGg6pZ

Every change must be made. They are listed above and below is a screenshot outlining them.

![INVESTOR_MODULE.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/d1554ca9-a06f-42ff-9e4f-96838f6f8acd)

Also the new disabled ICBM wallets with the UPGRADE option are included. From ticket:
https://app.zenhub.com/workspaces/nf-platform-5a620eae4604395352a06fdb/issues/neufund/platform-frontend/2221

Note the word UPGRADE may change but this will be confirmed by tomorrow.

Once completed, can we please have this sent back to design for a final check?

Any questions just ask

Thank You!!

**Comment by Louisswryan** [comment]
This design has been updated to reflect recent decisions about how we present information.

'UPGRADE' is now 'ENABLE'

Commas separating 1000s of values are now spaces.

The link is below.

https://zpl.io/VkGg6pZ

Thanks!

**Comment by glupiawymowka** [comment]
- [ ] Available balances should be renamed accordingly (Wallet -> **balance**, also please mind it's nEUR, as in the design) https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c8fcd5d4b61e52507a37abc
current (**incorrect**) view:
![image](https://user-images.githubusercontent.com/18315589/55335550-918b4b80-549b-11e9-94f3-32e6069dbe07.png)

- [ ] there should be no € symbol in the placeholder nor in the GAS cost
current (**incorrect**) view:
![image](https://user-images.githubusercontent.com/18315589/55336609-7faaa800-549d-11e9-89e6-474366ef9ea4.png)

![image](https://user-images.githubusercontent.com/18315589/55336658-9bae4980-549d-11e9-9ae0-5755677f0a4d.png)

- [ ] as per design, both Equity **tokens** and NEU **tokens** should start with small letters, not the capital ones.
current (**incorrect**) view:
![image](https://user-images.githubusercontent.com/18315589/55336954-15dece00-549e-11e9-8a08-e9699da2728b.png)

**Comment by shanile** [comment]
we tested and its OK
