### ISSUE TITLE
Fix ledger usage in ESOP-ui application

### ISSUE THREAD

**Issue by banciur** [Neufund/platform-frontend#2596]
It will require more changes to whole application as subproviders have a bit different API and are used differently. Also code there wasn't properly finished and there are some hacks. Because of that it will require a bit bigger overhaul and to decrease amount of work I will drop some features. 

List of dropped features:
- Metamask support
- ledger connection detection
- checking of required app version (that wasn't finish)
- waiting for tx to be mined

Basically after changes app will work like this.
When you open page it will try once to connect to ledger. If ledger won't be connected you will see page as it is now.
If ledger is present it will automatically request your account (no popup and confirmation requirement) and display page same way as you see it now after accepting address.

If you connect ledger after opening page you will simply have to reload page.

Signing transaction will be similar you just won't see spinner with blocks it will just show link to etherscan transaction.

## Testing
Admin for stage nano is one with address `0xe802ed697bdd7dcd452cddd42dfd7b1d3fc5ec10`
first one from here (https://neufund.atlassian.net/wiki/spaces/TEC/pages/57999361/Development+Nanos+keys+and+phrases). Currently it is on dev ledger marked with `new firm.` label.

With it you can test admin functionalities. My suggestion is that to test ability to send, confirm / reject transactions is to use `suspend` / `resume` functionalities as this operation is reversible and you can do it as many times as you want.

Also my suggestion would be to not use private nanos here. Page is using standard derivation path and writes data into public blockchain so your address will become publicly visible.

**Comment by glupiawymowka** [comment]
- [x] contract data ok 
- [x] adding new user 
0xE6Ad2CdBA2FB15504232eBFa82f64c06c87F9326

**TO DO**
- [ ] Cannot use "show paper copy" when signing ESOP en the employee ledger (DEV)

**TO TEST: **
- [ ] when fixed, test SIGN ESOP as an employee

**Comment by glupiawymowka** [comment]
this is tested on stage
