### ISSUE TITLE
Make CTAs in INVESTOR and ISSUER WALLETS the same size and weight as DASHBOARD

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#2598]
Hello,

Can we please have a visual fix on the CTAs in Investor and Issuer Wallets.

font-size: .8125rem
font-weight: 600

So we go from this:

![Screenshot 2019-03-19 at 09.05.43.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/46b2439b-4376-458f-af38-2cbcd0303491)

To this:

![Screenshot 2019-03-19 at 09.04.53.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/7224ac2c-62bf-46fe-92e3-49441735fcdb)

The background image is also removed but do not do anything to this as this job is on another ticket.

Thank you!

**Comment by glupiawymowka** [comment]
Fonts are correctly changed. There is a spacing difference explained below, but I've discussed it with Louis and he agreed it's fine 

In the design, the spacing between Account Balance buttons is not wider than the account balance 

![image](https://user-images.githubusercontent.com/18315589/55170732-56290e00-5177-11e9-96c9-f47ff1a76fd9.png)

on the platform, it's actually a bit wider
![image](https://user-images.githubusercontent.com/18315589/55172512-6f7f8980-517a-11e9-8e8c-8ef203a237bf.png)
