### ISSUE TITLE
Change background-colour that sits behind platform

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#2599]
Currently, we have a transparent background-colour that sits behind the body of the platform that is revealed in the animation when the user over-scrolls upwards.

The animation is nice, the background-colour is not.

![MAKE WHITE BACKGROUND SAME COLOUR AS HEADER.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/f7b88b66-12fd-43c4-81ab-99fcc40da35a)

Can we please make the background-colour the same dark blue colour as the header so it looks more like this?

![BACKGROUND-COLOUR BLUE.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/f60f6b9b-34a9-443c-a133-583a39f71862)

The header colour is: #414f5b

When I tried to use this, it did not give the desired result.

For my example, I used: #3a4752. This is fine too but perfectly matching is best.

Thanks :)

**Comment by glupiawymowka** [comment]
*tested on .net and .io*
