### ISSUE TITLE
REDEEM FLOW - withdraw entire balance if user types visible balance

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2601]
**Background**
We round down wallet balances. When user types such balance in the redeem modal, we currently will withdraw amount typed so the remainder will still be in the wallet. Example
visible balance: 345.21 nEUR
entire balance: 345.2189721982793232 nEUR
remainder 0.0089721982793232 nEUR

**Acceptance criteria**
After typing visible balance, entire balance is withdrawn and new nEUR balance is exactly 0

**Testing notes**
Best way to test is of course to use etherscan and just see the account. Alternatively you can see nEUR token balance in the Metamask when you add it as a token. Please ask any developer to find nEUR address for you. it will be in transaction posted to pending pool

**Comment by glupiawymowka** [comment]
this is also testable by checking the redeemed amount in the backoffice (it should be higher/full despite the rounding-down visible for the user)

*tested on .io*
