### ISSUE TITLE
Remove Neufund-Green Line Marker from Off-Card Titles

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#2602]
This is a platform-wide change.

If this cannot be implemented in one go, that is ok. I will identify instances for it to be changed.

In some cases, the Neufund-Green Line appears next to titles that are not on cards such as the below example.

![OPPORTUNITIES PAGE.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/6f7f6f77-292b-48aa-a406-dce5e5438417)

 This indicator should just be used within cards and not on the light blue background.

The goal is to make all of the off-card titles look basically the same but without the line and the text justified left within the same content margin. Something like the below.

![OPPORTUNITIES NO LINE.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/6031350b-d4fb-46fd-8e4c-d78cfc26ed0e)

Thanks :)

**Comment by glupiawymowka** [comment]
*tested on .net*
