### ISSUE TITLE
Issuer Dashboard layout misalignment

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2605]
**Description**
Seems like a minor fix.

When you login as an Issuer on the Dashboard view the Enable Whitelisting and Presale Date cards don't line up next to each other on desktop. Something is up with the grid layout.
 
See attached screenshot. I can see via the code inspector that there is an empty `<div class="col-12 col-lg-6"></div>`

Please check this for other dashboard cards in the code base. It might be when we're hiding the cards that we aren't removing the wrapping div from the DOM.

![Screenshot 2019-03-19 at 16.00.27.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/9dd4c2bc-925c-426c-a343-879fe7e38d36)

<img width="1566" alt="Screenshot 2019-03-20 at 10 53 14" src="https://user-images.githubusercontent.com/609657/54675324-a280a800-4afe-11e9-957b-8e7e2a73ac8c.png">

**Environment**
IO -> https://platform.neufund.io/dashboard

Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Steps To Reproduce**
Login using the fixture for 
Wallet: WALLET_18
Name: ISSUER_SETUP_NO_ST
Address: 0x0015650359DaF66f6633DEeb490a059027B0e396

**Actual behaviour**
The Enable Whitelisting and Presale Date cards don't line up next to each other on desktop.

**Expected behavior**
Cards should line up and only collapse to a single column for breakpoints smaller than 992px.

**Acceptance criteria**
-> Layout looks like the attached screenshot.

![Screenshot 2019-03-19 at 16.32.57.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/e2d87a39-b30e-4d15-8eba-7d44ad038b50)

**Comment by glupiawymowka** [comment]
no changes visible atm, but we should re-discuss it as the designs show all the boxes in 1 line
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5b1e26c8b35ead8b15991dea

**Comment by shanile** [comment]
I tested it with wallet 18 and this is how the dashboard looks like now 

![image](https://user-images.githubusercontent.com/36156487/55548188-3a6fbb80-56d3-11e9-82d7-c83db7fda221.png)


seems that it was not fixed yet
