### ISSUE TITLE
Issuer ETO forms - Reordering of Key Individual list items

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2606]
**Background**
Currently there is a usability issue on the Issuer ETO forms. For example, when adding Key Individuals, you can reorder the individuals added to the various sections without a) editing the fields to correctly represent the order you want or b) deleting them and then adding back information in the order you want. This is tedious and frustrating.

A better solution would be to allow a user to reorder. The simplest solution is to use some reordering arrows up and down arrows.

**Designs**
See attached a screen design. Note to the right of the list item cards there would be a reordering up down arrow. When clicking either direction it should change the order, ie. either up or down.

_Please ask Kirstyn for the vector svgs for the arrow icons if they aren't attached to this ticket before you pick it up_.

**Acceptance criteria**
As a user, I can reorder the following items in the Issuer step Key Individuals sections:
* TEAM
* ADVISORS
* KEY ALLIANCES
* BOARD MEMBERS
* NOTABLE INVESTORS
* KEY CUSTOMERS
* PARTNERS

Reordering will be limited to inside the section. Ie. you won't be able to reorder an item from one section into another (Team to Advisors).

**Technical notes**
If you feel we should use drag and drop for reordering, let's chat then about specific additional designs you'd need. You'll probably need a placeholder card and a drop zone. But I'd recommend do the simplest and for now use the up down arrows to reorder.

**Testing notes**
After reordering. If you revisit the page the order should remain. If you reorder it should update immediately and shouldn't require a page save. The reason, that's how it is when you delete. It deletes an item immediately and you don't need to press save for it to finalise the deletion.

**Attachments**
![Screenshot 2019-03-19 at 17.33.21.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/d9190378-64c8-482c-9a50-5ea37bb206b8)

**Comment by andywalton** [comment]
Hey @AlexeyTuboltsev - let me know if you want to talk through this before you start. 👍

**Comment by shanile** [comment]
Tested and it's working
