### ISSUE TITLE
Pre-mask validation

### ISSUE THREAD

**Issue by drakkein** [Neufund/platform-frontend#2608]
**Background**
The validation schema should be fulfilled before any masking
this means if we enter an invalid input we should have a red text saying this is invalid input

So the first step is we conduct validation on the Form Level Which means `0-9 , .`  anything else should be red.

Also we should introduce localized mask to support american number format. 

More will come after tomorrows meeting. @AlexeyTuboltsev please add what will come after.

**Comment by AlexeyTuboltsev** [comment]
fixed with https://github.com/neufund/platform-frontend/issues/2747
