### ISSUE TITLE
Value is not converted to EUR after you login but then is present after refresh

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2612]
**Description**

**Environment**

**Steps To Reproduce**
1. Login to the platform with investor type fixture.
2. See the dashboard.
3. Refresh. Compare the results.

**Actual behaviour**
Currency values are not converted but then onverted after refresh

**Expected behavior**

**Comments, context, logs**

**Screenshots**
![image (1).png](https://images.zenhubusercontent.com/5c3ddac32c893f1dad8d7a9a/2d9e6c49-dc3d-4ba4-a78b-eb4341b643fc)

**Comment by glupiawymowka** [comment]
*tested on .io with 3 different fixtures*
