### ISSUE TITLE
[transactions, platform]  add a button to reset pending transactions

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2614]
**Background**

On .io, some transactions are pending forever, blocking the fixtures for everyone who needs to use them. 

Please add a button to reset them easily each time it happens. 

**Acceptance criteria**
- [x] a pending transaction can be reset
- [x] new transaction can be started 

**Technical notes**

**Testing notes**
This can be tested with many transactions, like Redeem flow

**Comment by banciur** [comment]
In following link you will find some notes regarding this problem - https://neufund.atlassian.net/wiki/spaces/TEC/pages/585728013/Troubleshooting

**Comment by rudolfix** [comment]
@glupiawymowka flag addes - can be tested

**Comment by glupiawymowka** [comment]
works on io <3
