### ISSUE TITLE
Add e2e tests for investment flow when there is not enough eth for gas during neur investment

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2616]
**Background**
We should add a test for a case when there is not enough eth for gas while investing with neur

**Technical notes**
Use `Wallet 6` from https://github.com/Neufund/platform-contracts/issues/237

**Testing notes**
It's only e2e test so if build is green issue can be closed

**Comment by desfero** [comment]
`INV_ETH_EUR_ICBM_M_HAS_KYC_DUP_HAS_NEUR_AND_NO_ETH` is not implemented correctly (there are some ETH's there)

**Comment by rudolfix** [comment]
@desfero could you just send this eth to address(0)? 
```
const balance = await promisify(web3.eth.getBalance)(fas[f].address);
        const valueToSend = balance.minus(2100000);

        await promisify(web3.eth.sendTransaction)({
          from: fas[f].address,
          to: DEPLOYER,
          value: valueToSend,
          gasPrice: 100,
          gas: 21000,
        });
```
and then do the test. problem is because of gas stipend that user gets after valid KYC... and it happens already on CI
