### ISSUE TITLE
Issuer ETO forms - Investment Terms page doesn't display

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2631]
When I login as an Issuer and visit the Dashboard page and I click on Investment Terms the view doesn't load and shows an error.

This ticket is two fold:
1. We need to fix this bug and figure out why the Investment Terms view isn't displaying. 
2. We need to design a better error page as explain the reason for the error.

I'd run the ticket as follows - fix the bug first, then run it through QA and release the fix. Then move it back into design for the error screen designs.

**Acceptance criteria:**
When I browse to Investor Terms I can view the forms for this view and it doesn't show an error.

**How to reproduce:**
Login as an issuer using the fixture: **WALLET_18** on .io. The error shows for me in Chrome.

Speak to @andywalton should you have any questions.

**Screenshot:**
<img width="1552" alt="Screenshot 2019-03-20 at 11 20 43" src="https://user-images.githubusercontent.com/609657/54910932-9ecd9680-4eed-11e9-8ca4-9dfbd877b26f.png">

**Comment by shanile** [comment]
@AlexeyTuboltsev the form is OK and now we can see it however the save bottom is not there

**Comment by shanile** [comment]
Tested and the form is visible
