### ISSUE TITLE
Metamask double-signature again

### ISSUE THREAD

**Issue by Desperado** [Neufund/platform-frontend#2632]
**Description**
After testing metamask new signing methods there are again problems with repeated signatures. I think it happens when backend lags a little bit. it's higher prob if account is new. you login with new account it asks to sign on metamaks. you click yes. then you downloads ToS go to dashboard and then it asks again. if you cancel the second one you are logged out
and reverse is true. you cancel the first one, you go to main page and then after few seconds another signature request pops up. if you sign you get logged it

**Environment**
Current dev env

**Steps To Reproduce**
Login to dev using metamask

**Actual behaviour**
As per desription

**Expected behavior**
Signature through metamask should happen  just once
**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
*tested on .io*
- [x] tos signature request is not being sent multiple times to metamask 
- [x] when there is an active session, user is automatically redirected to the dashboard (instead of the landing page) 

Looks like it's done (and let's hope it will stay this way :D)
