### ISSUE TITLE
Issuer ETO Forms - reordering form cards on Issuer Dashboard

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2633]
When you login as an Issuer, you're able to view a list of the ETO campaign cards as per this screenshot below:

![Screenshot 2019-03-25 at 11.34.35.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/ff1eab72-11ac-4c39-8790-f6ae399d1315)

This ticket is about reordering these cards into two new sections as follows:

**COMPANY AND MARKETING INFORMATION**
1. About
2. Legal Info
3. Key Individuals
4. Pitch Deck
5. Marketing & Media

**ETO SETTINGS**
1. Equity Token Info
2. ETO Terms
3. Investment Terms
4. Token Holder Rights

Please hide the card **Risk Assessment** for now.

### Designs
<img width="516" alt="Screenshot 2019-03-25 at 15 58 50" src="https://user-images.githubusercontent.com/609657/54930104-f7655980-4f16-11e9-98f5-5fbc559e4390.png">

@falinebambi please add the designs in Zeplin and provide a link here.

### Acceptance & testing criteria
- [x] The cards have been reordered as per the designs and description.
- [x] You can't view the card **Risk Assessment** in the UI.

### Technical notes
- These cards already exist. This is purely a UI change.

**Comment by glupiawymowka** [comment]
This is done correctly, but I've almost missed the section titles as they're too small comparing to the form icons. 

Current font-size: .875 rem
![image](https://user-images.githubusercontent.com/18315589/55175762-3813db80-5180-11e9-9c3a-d4138d7af507.png)

Please change to: 
1.1 rem
This was discussed with @falinebambi and will be consistent with upcoming issuer flow designs 

![image](https://user-images.githubusercontent.com/18315589/55175665-069b1000-5180-11e9-8fcd-8f26c3233a22.png)

**Comment by glupiawymowka** [comment]
we agreed that the font size can be changed later, during the overall flow re-design
