### ISSUE TITLE
Handle the case where Ledger requires more than one click

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2639]
**Background**
we need to bring back instruction to click OK on the ledger when signing transaction or message. currently, it shows for a split second or not at all (and you are in standard transaction modal). something hides it
**Designs**
N/A atm
**Acceptance criteria**
The UX should prompt a couple of times for confirmation
**Technical notes**

**Testing notes**

**Comment by Moejoe90** [comment]
I haven't been able to reproduce @glupiawymowka

**Comment by glupiawymowka** [comment]
not able to reproduce it either. I'll reopen the ticket if needed
