### ISSUE TITLE
Investors multi-jurisdiction ETO preview cards

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2653]
**Background**
For more background information please refer to the Epic description: #2546 

As part of the Neufund multi-jurisdiction ETO epic we need to develop a new ETO preview card to be used on the Investor Dashboard.

These cards will be under the section titled _Current investment opportunities_.

Each preview card will have the following fields:

* Thumbnail image
* Company name
* Company token name
* Company headquarters country
* Company funding round
* ETO status
* ETO jurisdiction
* ETO categories
* ETO status by timeframe - ie. 10 days till ETO starts, ETO ends in 2 days etc.

_WIP - we then also need to confirm the below__
We then might also show a graph that shows the current status of how much has been raised in both EUR and ETH and also what the soft/hard caps are together with the # of investors so far.

These cards have different states and adapt based on ETO status variable. See designs for all possible states that include:

- Coming Soon
- Whitelist
- Presale
- Public sale
- In Signing
- Claim your tokens
- Refund
- Closed
- Successful

**Designs**
![etostates](https://user-images.githubusercontent.com/609657/55560916-8a5d7b00-56f1-11e9-9926-d61bd27a498a.png)

Please see designs on Zeplin: https://zpl.io/bWqvBMP

**Acceptance criteria**
- [x] As an Investor I can login to Neufund and view a list of ETO investment preview cards.
- [x] The ETO preview cards adapts to all possible ETO states.
- [x] Clicking any preview card will open the ETO company page and display the ETO jurisdication disclaimer when necessary.

**Technical notes**
- We need to consider how we can get reuse out of these preview cards and how it might be possible to for instance display the available investment opportunities on our website. 

**Testing notes**
Your context is that you're an Investor. Please ensure the card adapts to all possible ETO states as per the designs.
There are two leftovers:
1. ETO status change is moved as a separate ticket (#2786).
2. It's not possible to use keyboard navigation (#2787).

**Comment by rudolfix** [comment]
please use feature flag to replace cards on the dashboard

**Comment by rudolfix** [comment]
@glupiawymowka @desfero eto grid is enabled on io and you can test. I already see a few problems
1. on chain state + start data not set -> shows counter to unix epoch (01.01.1970) - I'm sure we handled that correctly on normal cards
2. pre-onchain: LISTED and PROSPECTUS APPROVED - no information show at all

also we should add some backgrounds to those tickets and replace NEUFUND as company name with something menaingful. I will add backend ticket

**Comment by rudolfix** [comment]
@glupiawymowka also it shows `WHITELIST` status in case bookbuilding is disabled. who is giving names to states now? could you ask what to do in that case?

**Comment by desfero** [comment]
@rudolfix 
1. Do we have any fixtures for this or to test this case we should go through all eto steps until whitelist?
2. This is because we don't have any `keyQuoteFounder` set for this etos.

**Comment by glupiawymowka** [comment]
@rudolfix @desfero 
The statuses were wrong already before this ticket was merged. Can we agree that it's being solved in #2786 ? 
I also see #2076 in "ideas".

1. The fixture for this ETO is 
WALLET_18 | ISSUER_SETUP_NO_ST

**Comment by glupiawymowka** [comment]
@rudolfix @pstroinski Can't test jurisdiction disclaimer on stage as it's not requested for inactive ETO's

other points tested on stage
