### ISSUE TITLE
ETO jurisdiction disclaimer modal

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2655]
**Background**
For more background info see here: #2546 

With the multi-jurisdiction ETO product offering we have a situation where we need to display a new disclaimer modal which looks as follows:

![jurisdiction-disclaimer-popup](https://user-images.githubusercontent.com/609657/55157306-5bc52a80-515c-11e9-865c-8d83e7b7ad0f.png)

Note: DE stands for Germany and LI stands for Lichtenstein

Current user scenarios we need to consider:

1. If **investor is not logged in** on the platform and clicks a DE-offering (ie. an ETO preview card that is listed on our website) they are **shown a modal** with the jurisdiction disclaimer: This offering is not for Liechtenstein-based investors. Please confirm that you are not from Liechtenstein.
2. If **investor is logged in** on the platform and they aren't KYC'd and they then click on a DE-offering they are **shown a modal** with the jurisdiction disclaimer: This offering is not for Liechtenstein-based investors. Please confirm that you are not from Liechtenstein. 
3. ~~If **investor is logged in** on the platform and KYC shows that **they are from LI**, we hide the DE-offers for him all together and **no jurisdiction disclaimer modal** required.~~ (moved as a separate ticket)
4. If **investor is logged in** on the platform and KYC shows that **they are not from LI**, we do **not need any modal** if investor clicks DE-offering.
5. When the ETO is Refund or Claim/Payout we do not show any modals.

The copy for the modal is:
*Headline:* Following ETO is not for Lichtenstein-based investors
*Body:* Please confirm that you are not based in Liechtenstein to see this ETO.
*Buttons:* Return / Confirm

**Designs**
@falinebambi to add the designs with a Zeplin link here and please update the screenshot above.

**Acceptance criteria & Testing notes**
- [x] Jurisdication disclaimer modal shows based on the scenarios described above.
- [x] It looks like the designs and the copy is correct.

**Technical notes**
- We need to check if the user is logged into the platform to determine their KYC status and nationality in order to determine jurisdiction.
- There is no need to store this popup confirmation or rejection. Until we know their KYC status, we'll keep showing it if the user isn't logged in. Secondly, if the person has logged in and they aren't KYC'd we could store the disclaimer modal result as part of the session and adapt the experience accordingly. This is a nice to have and I'd be open to chat about this further if we have time.

**Comment by andywalton** [comment]
NB extra info: Legal popup - we show it every time for the user that is not logged in, is only registered, has only the email verified but not yet KYC’ed

**Comment by falinebambi** [comment]
![Legal Pop Up](https://user-images.githubusercontent.com/17235402/55708480-59799080-59e6-11e9-94cc-24aaac19a955.png)

Zeplin Link: zpl.io/VYKjkrd

Copy Approved by marketing

**Comment by rudolfix** [comment]
@andywalton please provide rules to filter cards in dashboard in separate tickets. we expect those rules will be the same as for the modal

**Comment by glupiawymowka** [comment]
@andywalton @vizmab   I know that copy was confirmed, but do you really think this is not confusing? 
I honestly didn't know if an answer for
"please confirm you are NOT from Lichtenstein" is Yes or No :D  No I'm not? Yes I am? Yes I confirm?  This is confusing. 
![image](https://user-images.githubusercontent.com/18315589/56802142-91266c00-681f-11e9-9134-6bdf5baecffb.png)
