### ISSUE TITLE
ETO Forms - Add a label to Add category field in Company Information

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2659]
With our new ETO preview cards, we only have space for the two (2) company category tags. These tags are pulled through from our are going to be display on Preview card.

If you login as an Issuer and browse to: https://platform.neufund.io/eto/registration/company-information

Scroll down until you see:

<img width="799" alt="Screenshot 2019-03-29 at 17 00 10" src="https://user-images.githubusercontent.com/609657/55246311-4415a100-5245-11e9-82a2-96fe751a922e.png">

Please add the following HTML above the Add category select input field:
```
<label for="companyCategories" class="FormFieldLabel-module__form-label">Company categories</label>
<p>Add up to 6 tags that best describe your company. The first two will appear on your ETO preview card and all tags will be displayed on your ETO detail page.</p>
```

**Designs**
Screenshot of what this will then look like:
<img width="821" alt="Screenshot 2019-04-08 at 12 19 07" src="https://user-images.githubusercontent.com/609657/55717041-c26a0400-59f8-11e9-8ddb-cd25be6112a1.png">

**Acceptance criteria**

- [ ] Label and helper text has been added.

**Technical notes**
None

**Testing notes**
* You'll need to login as an Issuer.

**Comment by glupiawymowka** [comment]
this is done, but text informs about 6 fields, and only 5 can be added. 
@andywalton please decide if we should allow 6 or change the text 
![image](https://user-images.githubusercontent.com/18315589/56153566-c5e02b00-5fb6-11e9-9107-7008e37b6360.png)

**Comment by andywalton** [comment]
Hello, please change 5 to 6 tags.

**Comment by kelexa** [comment]
tested on staging - OK
