### ISSUE TITLE
Terms of use change

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2663]
Don't start on this ticket until it's assigned to you and the blocked label is removed. If in doubt, please ask Andy. 👍  
---

**Background**

The day we go live with the first multi-jurisdiction ETO offering (est. 15 May 2019) we'll need to have our _Terms of use_ online with that release.

This ticket's primary task is to update our Terms of Use that we display in app via a modal when you login to the app (first time) and each time we change our terms and you login the next time thereafter.

* Please ask Andy or Dialika for the latest terms pdf.

<img width="1260" alt="Screenshot 2019-03-29 at 11 26 24" src="https://user-images.githubusercontent.com/609657/55226635-bd959b00-5215-11e9-8413-25e04121d2dd.png">

These terms are also visible on our website via a link in the footer of the site. The Marketing Team will be responsible for getting this file online but feel free to help if you can.

<img width="1469" alt="Screenshot 2019-03-29 at 11 33 39" src="https://user-images.githubusercontent.com/609657/55227885-e9fee680-5218-11e9-838f-286d812d1bf1.png">

**Acceptance criteria & Testing notes**
- [ ] The new Terms of use are downloadable via the Please read our terms modal. They display for all new customers and will display again to existing customers when you login again after the terms have be updated. (If not Moe, see @Moejoe90 comment below).
- [ ] Please check with Marketing if they've updated the terms on our website.

**Comment by Moejoe90** [comment]
@andywalton 
this is taken directly from the smart contract 
from frontend we take the current hash agreement from the smart contract and check if the user signed this hash

**Comment by andywalton** [comment]
@Moejoe90 --> thanks for the extra info!

**Comment by falinebambi** [comment]
![image](https://user-images.githubusercontent.com/17235402/56123799-82190180-5f75-11e9-8044-f9ae9563c8a5.png)

**Comment by glupiawymowka** [comment]
For the new users that did not see any other ToU than the updated ones, please keep the new design and translations for buttons, but use the following header and paragraph: 



> PLEASE READ OUR TERMS OF USE
> 
> We would like you to read and confirm that you agree with our Terms of Use. This is an important step for you to understand our product.

**Comment by glupiawymowka** [comment]
Please use a better image quality so it won't look like that when enlarged
![image](https://user-images.githubusercontent.com/18315589/56904363-64cc5300-6a9e-11e9-8185-15a852695ae0.png)

**Comment by glupiawymowka** [comment]
No new Tos document was attached. 
I got the correct file and I'll create a backend ticket for @rudolfix when Dialika will confirm some details.

**Comment by glupiawymowka** [comment]
tested on .net but @rudolfix the new document is not there yet
