### ISSUE TITLE
Change platform selectors so that they use the full state

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2671]
**Description**
As per Meeting in Retro
There are some selectors currently that return a full updated object this is causing problems for React to conduct render optimization as components are getting updated without the need for updating them.
**Environment**
All
**Steps To Reproduce**
N/A
**Actual behaviour**
Components are being updated without the need for an update
**Expected behaviour**
Only components that are touched should be updated
**Comments, context, logs**

**Screenshots**

**Comment by pstroinski** [comment]
To be done case by case
