### ISSUE TITLE
Sidenav to Topnav

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#2685]
This is a big ticket but these changes must be made at the same time otherwise it will not work.

UI changes:

1. Contain the content of the following Nav States to 1140px in width

    INVESTOR_DASHBOARD
(we need to remove the Neumark logo so that the information collapses properly)
![INVESTOR_DASH_1140px.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/07b96562-451e-401a-a91d-f6193215cba2)

    INVESTOR_PORTFOLIO
![INVESTOR_PORT_1140px.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/73791dac-493f-4691-9c95-f866d51a2780)

    ISSUER_DASHBOARD
![ISSUER_DASH_1140px.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/0bc085d4-fcc8-405c-81b2-99e9659af743)

    ISSUER_WALLET
![ISSUER_WALLET_1140px.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/9102b72e-3a39-44ce-bf32-d2dd880e0250)

The content of all other states sit within this so do not need to be changed

EXCEPT for ISSUER_ETO... This is the one state that will remain larger than 1140px for now (just leave the current width)

Also disregard the SUPPORT state for these changes

2. Center the content of ALL states (except support) to sit in the middle of the screen

3. Change Sidenav to Topnav with icons in place of state titles and titles revealed on hover.

4. PROFILE Navigation moves to the right side of the screen with a profile icon for Lightwallet users and a Metamask icon for Metamask users

5. make SUPPORT nav state a static widget that sits in the bottom right of the screen

6. Drop the NEUFUND logo on the header so it is just the title (I know this might be too much. Maybe we can have logo and no title)

So similar to the following:

Metamask https://zpl.io/anp0B1O

Lightwallet https://zpl.io/2Gy6PzY

All states are accounted for, just rearranged

![NEW_STATE_POSITIONS.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/d3991a74-ca32-4612-b346-55b43f8c4f43)

NOTE: As the ISSUER_ETO state is still larger than 1140px, it will be the only state without the support widget as there is no space (yet)

These changes allow for a smooth transition to mobile and a native app in the future

Maybe like this https://zpl.io/2Gy6q7r

Any questions, just ask

Also this will need to come back to design for a check as it is a big (but very nice) shift in our UI

Thank You!!

**Comment by andywalton** [comment]
We need to add to this ticket before being able to hand it over.

**Comment by glupiawymowka** [comment]
hey, topnav is done and waiting for release. 
I'm putting it back to DESIGN as requested, so you check what is still to be done
