### ISSUE TITLE
Investment flow - masked input strips a dot at end of input

### ISSUE THREAD

**Issue by drakkein** [Neufund/platform-frontend#2688]
**Description**
Masked input strips a dot at end of input. If you write down a number and then you add dot in a middle it will work correctly.

**Environment**

**Steps To Reproduce**

**Actual behaviour**
Should not strip dot at any position. 

**Expected behavior**

**Comments, context, logs**
It is stripped by value conversions inside sagas. 
```
        yield put(actions.investmentFlow.setEthValue(ethVal.toFixed(0, BigNumber.ROUND_UP)));
        yield put(actions.investmentFlow.setEurValue(bignumber.toFixed(0, BigNumber.ROUND_UP)));
```

**Screenshots**

**Comment by AlexeyTuboltsev** [comment]
a duplicate of and will be sold with #2687
