### ISSUE TITLE
[CLAIM TOKENS] documents to download are gone

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2689]
**Description**
We had this done correctly, but somehow the documents to download while the user claims equity tokens are now gone. Please fix this flow to have them back 

**Environment**
.io (I had no way to check it on production yet) 

**Steps To Reproduce**
To test this, you can use the following fixture: 

INV_ICBM_EUR_M_HAS_KYC
0x0020D330ef4De5C07D4271E0A67e8fD67A21D523

1. Login with the given fixture and choose "Claim your Quintessence token"

2. There will be a checkbox to select that you've downloaded the above agreements, but there are no agreements to download 

![image](https://user-images.githubusercontent.com/18315589/55393152-fc409380-553c-11e9-9c17-8070a55a5294.png)

**Expected behavior**
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c10f7ac2e3f28242462d1bf

according to designs, there should be 3 agreements to download at this point 
![image](https://user-images.githubusercontent.com/18315589/55394492-b33e0e80-553f-11e9-994e-7a72e35ae585.png)

**Comment by shanile** [comment]
Tested and working
