### ISSUE TITLE
cancel pending e-mail verification

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2701]
**Background**
If users start new e-mail verification via `change e-mail` feature, there's no way to cancel it and widget will have intermediary state forever. When reviewing this we discovered with @glupiawymowka that we could do cancel if we simply accept already verified e-mail as new e-mail - which would be natural for the user. We want to restore cancel option this way.

**Designs**
Change
![image.png](https://images.zenhubusercontent.com/5a72da804b5806bc2bc52ecc/d2907f1f-f222-4880-9c8f-969843903e31)
UPDATE EMAIL ADDRESS -> CANCEL EMAIL ADDRESS

**Acceptance criteria**
[ ] if there's no pending verification and user enters already verified address we have a friendly frontend side validator that will prevent that - see existing toaster error. backend will ignore this silently
[ ] ~~if there's pending verification and user enteres already verified address, we cancel pending verification~~ --> this point is not needed as, after replacing the button, there will be no way to do so
[ ] if there's pending verification and user clicks CANCEL VERIFICATION, we cancel pending verification

**Technical notes**
See https://github.com/Neufund/platform-backend/issues/1526 on how to cancel pending verification (check `new_email` field)
Please wait for this ticket to be merged into master

**Testing notes**
See acceptance criteria

**Comment by glupiawymowka** [comment]
wording for some specific steps of the flow: 
*this was proposed and language-checked by the Marketing*
1. 
![image](https://user-images.githubusercontent.com/18315589/56200143-7e9d7d00-603e-11e9-89a2-eed13255bee1.png)

The line just below "Update email address" should be dropped as it's wrong

The line above password input should say : 
"Please enter your password to update your email address."

2. 
![image](https://user-images.githubusercontent.com/18315589/56200354-ebb11280-603e-11e9-8388-cc018c2affb3.png)

New translation here would be: 
"Please check your inbox to verify your new email address (sometimes it lands in spam folder). Verification was sent to: < new email address > 

3. In case of an already started verification, the user should see the following buttons

![image](https://user-images.githubusercontent.com/18315589/56200522-40ed2400-603f-11e9-8230-8f413b51311a.png)

so "Cancel pending verification" is the translation that should be used in this case

4. NOTIFICATIONS: 

![image](https://user-images.githubusercontent.com/18315589/56200686-86a9ec80-603f-11e9-8974-910a4e060af9.png)

"Verification sent to new email address"

OR, in case of canceling: 

"Updated verification canceled"

**Comment by glupiawymowka** [comment]
- [ ] If I cancel my pending verification, this email comes to the original email address
![image](https://user-images.githubusercontent.com/18315589/56964313-3c565e80-6b5b-11e9-9ea7-0a501198bb91.png)
We talked with @vizmab that user should simply not get an email at this point. 
The request to switch it off will be in the different ticket

**Comment by vizmab** [comment]
We should link the following emails:

- Cancel email verification - no email needed;
- Wallet recovery -on Sendgrid the name of the email is "Old - Platform - LOGIN_EMAIL"
- Email changed - on SendGrid the name of the email is "Platform - ACTIVATION_LOGIN_EMAIL"

Could we please do it as soon as possible so that users wouldn't get the wrong emails by accident?
