### ISSUE TITLE
cannot REDEEM 5 EUR

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2708]
**Description**
When I type 5 EUR to redeem, validator kicks in. 5 EUR is a valid REDEEM value

**Environment**
All environments - it's in production now.

**Steps To Reproduce**
Any fixture with more than 5 nEUR balance. Use REDEEM and type 5 in the amount.

**Actual behaviour**
Validator kicks in when amount 5

**Expected behavior**
Should accept 5 EUR, but not accept ~~5.01~~ 4.99

**Screenshots**

**Comment by glupiawymowka** [comment]
this one is correct on .io, we can merge it to stage
