### ISSUE TITLE
KYC Business form not saving details

### ISSUE THREAD

**Issue by kelexa** [Neufund/platform-frontend#2710]
**Description**
KYC Business forms don't save the information you filled out properly

**Environment**
.org

**Steps To Reproduce**

1. Start KYC verifying as a company
2. fill out the company details 
3. click save and add documents
4. click on continue to go to the next page
5. click on back to go back to the previous page
all information you previously saved will be  gone 

**Actual behaviour**

not saving form information

**Expected behavior**
to save information in case someone needs to modify something without filling out all of the infromation again 

**Comments, context, logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/40295416/55548769-82dba900-56d4-11e9-8d27-12cd4b6390c6.png)

**Comment by desfero** [comment]
Tested on stage, OK
