### ISSUE TITLE
ISSUER DASHBOARD - "go to wallet" link does not work

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#2711]
**Description**
If you log in onto a issuer dashboard with successful eto, you see "eto completed successfully" module and it has a link "go to wallet" . if i click on the link it does not work.

**Environment**
ledger
chrome
production

**Steps To Reproduce**
1. login as issuer
2. have an eto completed
3. go to dashboard

**Actual behaviour**

**Expected behavior**

**Comments, context, logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/26923972/55550233-06e36000-56d8-11e9-99c3-f4414ef99f16.png)

**Comment by glupiawymowka** [comment]
no fixture in such state, but tested on .io
