### ISSUE TITLE
Issuer ETO Settings Forms don't save details (missing save button)

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2716]
**Description**
Issuer ETO forms should submit on pressing the Save button. Currently this isn't happening consistently across the existing ETO forms.

**Environment**
.io

**Steps To Reproduce**
* Login to the Dashboard as an Issuer - use fixture wallet 18
* When on the Dashboard - scroll down you'll see the "ETO application" section.
* Scroll further down until you see the section titled ETO Settings.
* Each of these 4 cards (Equity Token Info, ETO Terms, Investment Terms, Token Holder Voting Rights) are missing a Save (submit) button.

**Actual behaviour**
* There isn't a save button, there should be one.

**Expected behavior**
* The ETO settings cards should each have a Save button that correctly submits the views form data on clicking the button.
* The button should be while the company during the ETO application process. As soon as they submit their ETO application for review, these Save buttons should be hidden (as per current expected functionality).

**Comments, context, logs**
None

**Screenshots**
Equity Token Info
![Screenshot 2019-04-04 at 17.31.03.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/ae0c3ba3-5b8f-498e-8eeb-522b884fe3de)

ETO Terms
![Screenshot 2019-04-04 at 17.31.22.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/88fc1776-612c-43c8-a69c-ba471fb6ba74)

Investment Terms
![Screenshot 2019-04-04 at 17.32.19.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/a03e106b-eb77-4020-8334-261bc530805f)

Token Holder Rights
![Screenshot 2019-04-04 at 17.32.46.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/e5c3c697-8337-4239-904a-b2895b558b9f)

**Comment by AlexeyTuboltsev** [comment]
fixed with #2631
