### ISSUE TITLE
Add disabled cursor for all readonly/disabled input types

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2722]
**Background**
All disabled inputs should have the cursor set to disabled `not-allowed`.

**Designs**
not needed

**Acceptance criteria**

- [x] **Given** i'm inside form with disabled fields (like `EtoTerms`) **when** i hover over disabled input type **then** my cursor is changed to `not-allowed`.

**Technical notes**
none

**Testing notes**

**Comment by glupiawymowka** [comment]
*this works both for forms and other inactive buttons on stage and live*
