### ISSUE TITLE
Tooltips overlaps when placed close to each other

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2723]
**Description**
See steps to Reproduce and actual behavior. Also please fix Tooltip design to the latest one (zpl://screen?pid=5a8a92c89c1a166a6a6e8f37&sid=5b69bdacc25b0c12e7b6f3a6).

![Apr-08-2019 13-09-04](https://user-images.githubusercontent.com/7031578/55702213-1a583900-5a00-11e9-8bec-da28e351a8ea.gif)

**Environment**
-

**Steps To Reproduce**
Go to Eto Terms and hover over Eto types.

**Actual behavior**
A couple of tooltips opened at the same time overlaps when placed close to each other.

**Expected behavior**
Force close Tooltip when another one is going to be opened

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
*tested on stage*
