### ISSUE TITLE
display nominee name as provided in the backend

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2737]
**Background**
We have hardcoded nominee name in the frontned: `Neumini UG`. with the backend SHA available the nominee address may be changed and we need to display correct nominee name. See more info here
https://github.com/Neufund/platform-backend/issues/1133

**Acceptance criteria**
* [x] everywhere we display hardcoded nominee name now you take it from `nominee_display_name` field of `eto_data`
* [x] if nominee is successfully changed in backoffice app, the displayed nominee name should change to selected nominee in backoffice

**Technical notes**
Please note that **all ETO fixtures coming from backend have the same nominee** with the name `Neumini` so update your e2e tests where you have `Neumini UG` hardcoded

**Testing notes**
Nominee may be changed only in DRAFT/PREVIEW so use ISSUER_DRAFT for manual testing

**Comment by glupiawymowka** [comment]
*tested on .io and stage*
