### ISSUE TITLE
handle transferability and tradeability correctly everywhere

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2741]
**Background**
We split "transferability" - is token technically p2p transferable from "tradeability" - does company intent to put equity tokens on secondary market and trade it publicly. See backend https://github.com/Neufund/platform-backend/issues/1562 for background details

**Designs**
No need designs required see acceptance criteria where changes apply

**Acceptance criteria**
* [ ] set "IS THE TOKEN TRANSFERABLE" to `enable_transfer_on_success` from `eto_data`
![image](https://user-images.githubusercontent.com/17202864/55887750-62b55980-5bae-11e9-8068-3dcf651bb186.png)
* [x] show "WHEN IS THE TOKEN TRADEABLE" only when `enable_transfer_on_success` is true
![image](https://user-images.githubusercontent.com/17202864/55888162-30f0c280-5baf-11e9-8af5-7d5acc421ed7.png)
* [x] when shown, field is editable by the user, see how it's bound to data below
* [x] set  `token_tradeable_on_success` as follows: if "WHEN IS THE TOKEN TRADEABLE" "ASAP" to **true**, if "LATER" to **false**
* [x] values above are correctly displayed on public profile of company.
* [x] tradeablity is hidden from public profile if  `enable_transfer_on_success` is false

**Technical notes**
Blocked by backend ticket 1562

**Testing notes**
* all the products that have asset type "VMA" should have "WHEN IS THE TOKEN TRADEABLE" hidden
* if visible "WHEN IS THE TOKEN TRADEABLE" changes are correctly saved to backend

**Comment by glupiawymowka** [comment]
*tested on stage*
