### ISSUE TITLE
Issuers - Add Rich Text Editor support for some Issuer textarea fields

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2756]
**Background**
<img width="1112" alt="Screenshot 2019-04-14 23 07 17" src="https://user-images.githubusercontent.com/609657/56099198-12216180-5f0a-11e9-9ffd-b29044e49e28.png">

On our Issuer company pages under the Pitch section we need to allow better formatting of the content. Currently it only allows you to insert a single paragraph of text, not even multiple paragraphs or line breaks. This makes it very difficult to read  and rather unusable when this content runs long.

To fix this we should add rich text editor functionality to the necessary textarea input fields that will allow Issuers to format their long form content.

The rich text functionality required is:
- [x] Bold, italic, paragraph and line break spacing, add a heading (ie. add h3 - similar to Github Markdown editor), adding an ordered and unordered list and the ability to add an external links.
- [x] The pitch fields (textarea fields) this should work with are:

1. COMPANY STORY
1. COMPANY MISSION
1. PRODUCT VISION
1. KEY PROBLEM SOLUTION
1. TARGET CUSTOMERS
1. TARGET MARKET AND INDUSTRY
1. KEY COMPETITORS
1. UNIQUE SELLING PROPOSITION
1. KEY BENEFITS FOR INVESTORS
1. MARKET TRACTION
1. ROADMAP
1. BUSINESS MODEL
1. MARKETING APPROACHf

For example:
<img width="1119" alt="Screenshot 2019-06-03 at 11 55 11" src="https://user-images.githubusercontent.com/609657/58793477-7e5d3f00-85f6-11e9-8ff1-0330ec349c48.png">

- [x] Also, under About company the `Company description` field should allow rich text editing.

<img width="796" alt="Screenshot 2019-06-06 at 10 28 27" src="https://user-images.githubusercontent.com/609657/59260527-0c12dd00-8c3c-11e9-8692-b50c5d33ce93.png">

**Technical aspects we leave up to the developer:**
- [ ] Researching and choosing a rich text editor library? CKeditor, TinyMCE, QuilJS, Markdown etc.
- [ ] Further development considerations such as lazy loading packages only when we need to use them.
- [ ] Storing the rich text to the backend.

**Designs**
- [ ] Do we require design work? When you choose a library, please speak with Andy and we can agree on designs if required.

**Acceptance criteria**
- [x] Pitch ETO forms via PITCH textareas allow you to do rich text editing.
- [x] These fields correctly display this rich text on the company listing page.

**Technical notes**
See above.

**Testing notes**
Same as acceptance criteria.

**Comment by glupiawymowka** [comment]
*tested with codechecks*

**Comment by glupiawymowka** [comment]
on .net, there is a Text Editor issue that moves editing buttons to the footer. 

**Steps to reproduce**
1. As a fresh issuer, go to _About_ or _Pitch_ forms. 
2. Click on the input that should support Text Editor. The tools are not there
![image](https://user-images.githubusercontent.com/18315589/60543154-d8e0dc80-9d15-11e9-8fee-389871924eb1.png)
3. Try to manually edit text by using cmd+i or cmd+b, the text will change accordingly
4. Save
5. Go back to the form
6. Scroll to the footer
![image](https://user-images.githubusercontent.com/18315589/60543961-f9119b00-9d17-11e9-8e7a-9cc99c6f0d29.png)

7. Try to use the buttons. They will work if you hit the right one (not so easy)
![image](https://user-images.githubusercontent.com/18315589/60544247-b00e1680-9d18-11e9-99c4-2aa45ea793dd.png)

**Console**
![image](https://user-images.githubusercontent.com/18315589/60544382-f6fc0c00-9d18-11e9-9b65-45b683f19069.png)
