### ISSUE TITLE
ETO company page fixes

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2759]
New ticket to address things missed from #2654

- [x] Banner at top of page detailing ETO Jurisdiction 

![Screenshot 2019-04-18 at 17 17 23](https://user-images.githubusercontent.com/17235402/56371691-db936180-61fd-11e9-81e1-d6c61a623a29.png)

- [x] Reorder, reformat numbers and put in additional information from ETO forms.  

![Screenshot 2019-04-18 at 17 11 17](https://user-images.githubusercontent.com/17235402/56371517-8bb49a80-61fd-11e9-9a7f-20e2e31fa921.png)

- [x] if a value for any of the points is 0.00, leave an empty space 

![image](https://user-images.githubusercontent.com/18315589/56808875-d86a2800-6832-11e9-909d-8fe1ef58ec3f.png)

- [x] ETO Overview widget - there is a comma in ETO token price, that is not taken from the ETO investment terms table, please change to a decimal point

![image](https://user-images.githubusercontent.com/18315589/56809418-1156cc80-6834-11e9-9700-b9ac5b136b0a.png)

**Comment by Moejoe90** [comment]
@AlexeyTuboltsev 
The new requirement is like this 
If the user is an investor then we will keep the banner like in the top 
If the user is an issue we will display this information instead 
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cdd6dc414c8f21d4a706b1f 

It should contain only a simple copy text and a link, in the end, the link should point to 
`http://platform.neufund.org.io/eto/view/{$preview-code}`
the link should open in a new tab completely 
where the `preview-code` is the preview code of the eto

**Comment by glupiawymowka** [comment]
tested on stage
