### ISSUE TITLE
Prompt Ledger Nano users with older firmware to upgrade to our supported firmware version

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2760]
**Background**
After the latest Chrome update version `73.0.3683.103` to be precise the old Ledger support was again broken and therefore connecting to the platform with these older Ledgers isn't possible.

We will need to prompt old firmware users to update their Nano Ledgers to the latest version.

We can do this by adding a new check to see if the Ledger firmware matches what we support, which is currently version 1.5.5.

If it doesn't pass this check, we need to display an upgrade your firmware message as per the design below.

**Designs**

<img width="1774" alt="Screenshot 2019-04-17 at 10 54 48" src="https://user-images.githubusercontent.com/609657/56587185-6353e400-65e1-11e9-839c-c5b5f596ff14.png">

__The copy is as follows:__
> Ledger Nano firmware is unsupported

> Looks like you are using a Ledger Nano with outdated firmware. For security reasons we only support devices with the latest firmware version. Please update your Ledger Nano to access Neufund.

> For update instructions, visit Ledger.com.

The Ledger.com text should open in a new tab the following URL: https://support.ledger.com/hc/en-us/articles/360002731113-Update-device-firmware

**Acceptance criteria & testing notes**
- [x] You can connect to the platform with a Ledger Nano that has our supported firmware version (version 1.5.5).
- [x] You are told to upgrade your firmware if your Ledger fails the firmware check (less than version 1.5.5).

**Technical notes**
We need to write a function that checks the users firmware version is supported as part of the check that verifies a Ledger is connected.

If it's not supported, we should prevent them from connecting to the platform and display a view that prompts them to upgraded.

We need to add a regression test to check any link we point externally to Ledger.com doesn't return a 404.

Note the container for the content above is set to `.col-md-9` and the row class that wraps it is set to `.justify-content-center`. If you zoom in on that screengrab you'll see the `html` used to achieve the layout.

**Comment by andywalton** [comment]
![IMG_0241](https://user-images.githubusercontent.com/609657/56204960-d80aa980-6048-11e9-89aa-318ed3a0b684.JPG)
![IMG_0243](https://user-images.githubusercontent.com/609657/56204961-d80aa980-6048-11e9-87b1-11551525d8a4.JPG)
![IMG_0244](https://user-images.githubusercontent.com/609657/56204962-d80aa980-6048-11e9-8ee2-51e347746353.JPG)

Going to add to this ticket to get copy written and some designs.

**Comment by andywalton** [comment]
Guys, I just spoke with Vizma, she'll write the copy for this.

**Comment by shanile** [comment]
I recommend to add this link https://support.ledger.com/hc/en-us/articles/360002731113-Update-device-firmware where the user can find full instructions on how to do it

**Comment by Moejoe90** [comment]
@andywalton I don't think it's correct to say we support the latest version but we need to specifically say `1.5.5` as latest version can change with time

**Comment by andywalton** [comment]
@Moejoe90 okay, happy with that. 

I've updated the copy in the ticket above to read:

> Looks like you are using a Ledger Nano with outdated firmware. For security reasons we support devices with firmware version 1.5.5 and later. Please update your Ledger Nano to access Neufund.

**Comment by glupiawymowka** [comment]
hey, this is still working well, but the conversation here was all the time about the acceptable firmware (which is 1.5.5) and now we're showing acceptable ETH app version (1.2.4) while still informing about "firmware" which I would understand as device firmware. 
It's just a copy @andywalton change as Moe said ETH app version comes with the firmware update anyways

![image](https://user-images.githubusercontent.com/18315589/56897490-f92eb980-6a8e-11e9-89ad-4c37d7591512.png)

**Comment by andywalton** [comment]
Hello, I'd update the copy to the following:

**Connection status: Ledger Nano firmware is unsupported**

Looks like you are using a Ledger Nano with outdated firmware. For security reasons we only support devices with firmware version 1.5.5. Please update your Ledger Nano to access Neufund.

For update instructions, visit [Ledger.com](https://support.ledger.com/hc/en-us/articles/360002731113-Update-device-firmware).

---

My question is, should I make this copy update?

Also, I think the container in your screengrab above @glupiawymowka @Moejoe90 is a bit too wide. If you can, I'd recommend this change - see in the ticket to the screengrab referencing the design + html:

> Note the container for the content above is set to `.col-md-9` and the row class that wraps it is set to `.justify-content-center.` If you zoom in on that screengrab you'll see the html used to achieve the layout.

**Comment by andywalton** [comment]
Hi @Moejoe90 @glupiawymowka 

I've taken a look and the version number for the firmware we support is pulling through from a variable.

See line 18 in: `/app/lib/web3/ledger-wallet/ledgerUtils.ts`

![image](https://user-images.githubusercontent.com/609657/57081052-38aa0f80-6cf4-11e9-9e23-237d3ff70915.png)

I've updated this to 1.5.5, pushing this now Moe, please will you take a look.

**Comment by glupiawymowka** [comment]
new copy is tested on .io and needs a stage deploy to retest

**Comment by glupiawymowka** [comment]
*tested on .net*
