### ISSUE TITLE
Make toggle background colour always green

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2767]
**Background**
Currently, toggle background is gray in case slider is on the left side. This is not correct from the ui/ux as we often use the toggle to represent values that are not simple ON/OFF. 
For e.g. `When is the token tradable` inside ETO terms:
![image](https://user-images.githubusercontent.com/7031578/56273453-f21ab980-6126-11e9-8d0f-83f94c3015e3.png)

**Acceptance criteria**
- [ ] Given toggle is not disabled then background should be always green regardless of the slider position.

**Technical notes**

**Testing notes**

**Comment by pstroinski** [comment]
To be moved to asana
