### ISSUE TITLE
Change global font color

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2778]
**Background**
Font default color is not the same as on designs. Now it's set to `#656b72` but if you look closer to all new zeplin designs default color is `#4c4c4c`.
Please note the same applies to headings. Current heading color is `#2b2b2b` but should be also set to `#4c4c4c`.

**Designs**

**Acceptance criteria**

- [ ] Given I'm on an investor dashboard when i inspect the color of `TOKEN NAME` on thumbnail widget it should be set to `#4c4c4c` on `body` level.
- [ ] Given I'm on an investor dashboard when i inspect the color of ETO name on thumbnail widget it should be set to `#4c4c4c` on `body` level.

**Technical notes**
Bootstrap provides a special variable for `headings` color, we should set to `inherit` so `body` style applies to all headings and paragraphs by default.

**Testing notes**
This will affect colors everywhere.

**Comment by pstroinski** [comment]
To be moved with the design tickets that are unifying the platform with the designs
