### ISSUE TITLE
[URGENT] Banned countries at KYC registration update

### ISSUE THREAD

**Issue by kelexa** [Neufund/platform-frontend#2779]
**Description**
at KYC registration form, we should add Cambodia to the list of countries that are not allowed to proceed with the verification.

**Environment**
production

**Expected behavior**
Countries that should be on the list are now:

Bahamas, Botswana, Democratic People's Republic of Korea (DPRK), Ethiopia, Ghana, Iran, Pakistan, Serbia, Sri Lanka, Syria, Trinidad and Tobago, Tunisia, Afghanistan, Guam, Iraq, Libya, Nigeria, Panama, Puerto Rico, Yemen, **Cambodia** and the United States of America.

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
reviewed on .io

**Comment by glupiawymowka** [comment]
tested on stage
