### ISSUE TITLE
masked money input rounds up if investing the whole balance

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2781]
**Description**
maskedMoneyInput  rounds up if investing the whole balance. Previously it simply chopped of the excessive digits

**Environment**
wallet_4 or any other that allows to invest

**Steps To Reproduce**
login with wallet_4 fixture, try to invest from ICBM_balance the whole amount (218.1289 eth ).  

**Actual behaviour**
Amount appearing in the input will be 218.1290, not  218.1289

**Expected behavior**
to have the same figure i the input as in the wallet balance

**Comments, context, logs**

**Screenshots**

**Comment by AlexeyTuboltsev** [comment]
https://github.com/Neufund/platform-frontend/pull/2768 will solve it

**Comment by glupiawymowka** [comment]
it was solved with the mentioned ticket
