### ISSUE TITLE
Update status component to show more states

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2786]
**Background**
This is a leftover from #2772. 
Our generic status component should be updated to handle all new states (for e.g. `Countdown to Presale`). This states should not only be calculated base on ETO status and ETO contract status keys but also take into consideration ETO properties like `isBookbuilding` and more.

**Designs**
zpl://screen?pid=5a8a92c89c1a166a6a6e8f37&sid=5ca235f479733c07fcbb4341

**Acceptance criteria**

- [x] Correct ETO status is shown on eto widget
- [x] Correct ETO status is shown on eto thumbnail widget
- [x] Correct ETO status is shown on issuer dashboard

**Technical notes**
We should refactor to keep all logic in one place (either selector or util) that will calculate correct ETO state and then use it inside status and also inside ETO widget and ETO thumbnail widget

**Testing notes**

**Comment by glupiawymowka** [comment]
Ticket #2076 can be closed when this one will be done.
It should be a part of it

**Comment by glupiawymowka** [comment]
tested on stage
