### ISSUE TITLE
Dashboard filtering rules for ETO preview cards

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2789]
**Background**
This ticket describes a couple of filtering rules for our new ETO preview cards that are displayed on our Dashboard view when logged in as an Investor on the platform.

An investor will see ETO preview cards from two jurisdictions. We need to filter these preview cards as follows:

1. If an investor **has not completed KYC**, we show all ETO cards  on the Dashboard.
2. If an investor **has completed KYC** and they **are not permanent residents of Li**, we **show all the preview cards** on the Dashboard.
3. If an investor **has completed KYC** and they **are permanent residents of Li**, we **hide all DE ETO preview cards** from them on the Dashboard. 

**Designs**
Not required

**Acceptance criteria**
- [x] Cards filter as per the requirements above.

**Technical notes**
- [x] We are going to probably need a new fixture that will allow us to test this as an investor that is has Li residency status as part of their KYC information.

**Testing notes**
None

**Comment by Moejoe90** [comment]
@andywalton 
We do not have in KYC anything that mentions `permanent residents` we have the country of birth and Nationality. 

Currently, the logic is as this 
```
KYC 
-> Individual -> Check Nationality 
-> Businuss -> Check jurisdiction
```
Please confirm if this is ok

**Comment by andywalton** [comment]
@Moejoe90 

Ah yes, we don't have a specific field called `permanent residents`.

I'd keep the KYC for Business as suggested in your comment.

For Individuals I'd rather use `address.country` to determine their jurisdiction as that address will be verified as where they're living (ie. where they reside).

I also agree that if a user is in a Draft State and they are `LI` via KYC then we filter the ETO list.

**Comment by rudolfix** [comment]
@andywalton @Moejoe90 I think we discussed the following critera: if eto is in ('claim', `refund` or `payout') states we can show those freely without any restrictions because they are not offers anymore! we confirmed this with legal, so there will be two more conditions

* [ ] ETOs that are finished are always shown to all users without restrictions
* [ ] ETOs that are finished do not need additional modal both for logged and unlogged users

**Comment by kelexa** [comment]
tested on .io - OK
not enough ETO listings (no ongoing DE, or LI) on staging to test properly
