### ISSUE TITLE
Platform landing page changes

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2790]
**Description**

On `platform.neufund.org` under the section:
MEET OTHER COMPANIES TOKENIZING THEIR SHARES SOON

Remove the coming soon preview cards from the page:
1. Next Big Thing
2. Curf

Then reorder the remaining cards as follows:
1. Emflux
2. My Swoop
3. Founders Bank
4. Air Profile
5. Agora Trade
6. Ngrave

**Acceptance criteria**

- [x] Next Big Thing and Curf have been removed.
- [x] Preview cards have been reordered as per above.

If you have any questions speak to Andy or Aga.

**Comment by glupiawymowka** [comment]
@andywalton please note that Next Big Thing is also visible here (right corner) and this ticket doesn't cover adding some other company instead
![image](https://user-images.githubusercontent.com/18315589/56670064-6f5ba680-66b2-11e9-8168-96702e138cf5.png)

**Comment by glupiawymowka** [comment]
*tested on stage*
