### ISSUE TITLE
[Dashboard, my wallet] different total values in the widget 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2792]
**DESCRIPTION** 
 When the users head to the dashboard/ My wallet page, they can easily count that the total given is not the actual sum of the visible amounts

**ENV**
all, this is live

**STEPS TO REPRODUCE**
1. You can login with any fixture that has some ETH, like this one 0x429123b08DF32b0006fd1F3b0Ef893A8993802f3 (INV_ICBN_NO_KYC) (nEUR are not needed as the problem seems to by caused by ETH roundings) 
2. The "my-wallet-widget-total" will show the value 1-2 euro cents higher than my-wallet-widget-eth-token.value

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/a3a26698-c678-4eb4-bbb5-f51750bda311)

**COMMENTS** 
This is connected to #2742 but needs a bit more attention as it's publicly visible 

**TECHNICAL NOTES**

**Comment by rudolfix** [comment]
Please round down everywhere
