### ISSUE TITLE
Update Ngrave image on platform landing page

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2794]
The Ngrave has brand recently changed and they have asked us to update this on our website.

On `platform.neufund.org` please replace the Ngrave card background image from:

![Screenshot 2019-04-23 at 16.19.45.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/5ce004db-d294-4210-89c4-100e35fdca60)

With this new image:

![ngrave_banner_20190415@2x.jpg](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/c1d42bc4-8f99-4539-a7b2-ee0e4e453c2e)

The above image is saved at the correct size of 1050px by 522px as currently used.

**Comment by glupiawymowka** [comment]
*tested on stage*
