### ISSUE TITLE
Please make all the tooltips consistent 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2795]
**Background**
We have some new designs for the tooltips, but the old ones should also be changed accordingly

These can still be found all over the platform (whitelisting here)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/ac76236a-0793-4395-a46d-b38914784ae5)

**Designs**
Example of a tooltip that is being implemented for redeem flow (same for ETO forms) 
https://zpl.io/bLKkY4Y

**Acceptance criteria**
The following tooltips are aligned to the new designs **(also in zepplin, please move to "backlog" when done)**:
- [ ] whitelisting (both tooltips) 
- [ ] ICBM migration tool 
- [ ] KYC (US citizenship and PEP) 
- [ ] ~~MyWalletWidget-module__icbm-wallet___1dar3~~ this element is simply gone now
- [ ] Issuer forms, Media 
![image](https://user-images.githubusercontent.com/18315589/58106525-88d80b80-7be8-11e9-846a-17766521fe9d.png)

and others, if I overlooked something :) 
**Technical notes**

**Testing notes**

**Comment by pstroinski** [comment]
General changes to the whole platform - currently in design in the Product Improvements project
