### ISSUE TITLE
[ETO page] add bottom margin for the unverified user notification module 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2807]
**Description**
In an unverified user opens an ETO page, the banner asking for verification looks like it's glued to the company photo. 

To see this, you only need to open ETO page with any unverified account

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/4c86d81f-f884-4955-9116-458b7f6d3c75)

Please add some margin-bottom so the notification is separated from the picture

**Comment by andywalton** [comment]
Hello, simple fix here. Please add the class `mb-3` to the notifications module. Assuming they consistently have this problem throughout the app?

**Comment by glupiawymowka** [comment]
*tested on stage*
