### ISSUE TITLE
new eto card layout broken after panel switched to grid

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2809]
**Description**
after merging grid panel layout new eto cards layout is broken
**Environment**

**Steps To Reproduce**
set `NF_ETO_LIST_GRID=1`, login as wallet_4, go to dashboard
 
**Actual behaviour**
eto card layout has a large white margin on the right

**Expected behavior**
eto cards should look as designed (https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5ca235f479733c07fcbb4341)

**Comments, context, logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/14041336/56855798-5e32c400-6956-11e9-9f35-c94804358e8d.png)

**Comment by glupiawymowka** [comment]
*tested on io*

**Comment by glupiawymowka** [comment]
*tested on .net*
