### ISSUE TITLE
Trans-History #5. Fit ICBM Balance card on top row in INVESTOR WALLET (only for ICBM Investors)

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#2820]
To create the necessary space for the Transaction History, we cannot have the ICBM balance sitting below the nEUR and ETH balances.

Can we move this card from sitting below like here:

![INV_WALLET.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/fda9702a-a847-4509-9bde-8fc440355d1c)

To sitting along the top like here:

![Screenshot 2019-04-29 at 16.31.01.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/c351a0ab-6040-4467-8012-b258d584dc5c)

Zeplin link: https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5cc70347e2e4482d1317594f

The content should squeeze into these spaces but can we please run this back past product when done to check it looks ok.

It is ok if they still stack vertically when the screen size is compressed like below but we need a better solution in the long run:

![Screenshot 2019-04-29 at 16.43.35.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/e2af331e-2eac-4496-b8e6-4037cf0b6b83)

Much appreciated :D

**Comment by desfero** [comment]
Closing, we will do some redesign on the wallet page soon
