### ISSUE TITLE
Investor dashboard grid refactor

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2827]
**Background**
follow up on https://github.com/Neufund/platform-frontend/pull/2561
change investor dashboard to grid layout to make use of widget automatic placement etc

**Designs**

**Acceptance criteria**
everything should looks as before, storybook reports no substantial changes

**Technical notes**

**Testing notes**

**Comment by glupiawymowka** [comment]
#2896 this is also connected

**Comment by AlexeyTuboltsev** [comment]
done in https://github.com/neufund/platform-frontend/issues/3033
