### ISSUE TITLE
Transaction email flow errors

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#2830]
**Description**
We have certain emails on Sendgrid that are triggered at the wrong time.

When email address is updated on platform and when users recover wallet they receive the same email:
![2222222](https://user-images.githubusercontent.com/48217191/56970347-3d8d8880-6b67-11e9-9b66-5fb057cd096b.png)

When user cancels pending email verification they get this email:
![33333](https://user-images.githubusercontent.com/48217191/56970464-762d6200-6b67-11e9-87c9-4b27d56e232f.png)

**Environment**
Sendgrid + Platform
**Steps To Reproduce**

Nikola already tested and discovered this issue.

**Actual behaviour**

**Expected behavior**
The emails should be linked the following way:

Cancel email verification - no email needed;
Wallet recovery without changing email address -on Sendgrid the name of the email is "Old - Platform - LOGIN_EMAIL"
Email changed or wallet recovery with changing email address - on SendGrid the name of the email is "Platform - ACTIVATION_LOGIN_EMAIL"

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
Issue moved to [Neufund/platform-backend #1641](https://github.com/Neufund/platform-backend/issues/1641) via [**ZenHub**](https://www.zenhub.com/)
