### ISSUE TITLE
refactor bankTransferRedeemInit to use maskedMoneyInput

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2831]
**Background**
after this `https://github.com/neufund/platform-frontend/issues/2747` has been merged,
- refactor redeemInit component to use the new masked input

**Designs**

**Acceptance criteria**
everything should work as before :))

**Technical notes**

**Testing notes**

**Comment by AlexeyTuboltsev** [comment]
let's wait for https://github.com/Neufund/platform-frontend/pull/2768

**Comment by kelexa** [comment]
tested on staging - OK
