### ISSUE TITLE
refactor forms to use maskedMoneyInput as number input

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2832]
**Background**
after this `https://github.com/neufund/platform-frontend/issues/2747` has been merged,
- modify masked input if necessary in a way that it can be used in all forms as number input
- refactor number inputs in all forms

**eto registration forms:**
- [x] LegalInformation.tsx (except shareholders.shares)

- [x] InvestmentTerms.tsx

- [ ] EtoVotingRights.tsx
- liquidationPreferenceMultiplier

- [ ] EtoTerms.tsx
- minTicketEur
- maxTicketEur
- whitelistDurationDays
- publicDurationDays
- signingDurationDays
- product.maxInvestmentAmount

- [ ] shareholders.shares 

**Designs**

**Acceptance criteria**
everything should look and work as before :))

**Technical notes**

**Testing notes**

**Comment by AlexeyTuboltsev** [comment]
let's wait for https://github.com/Neufund/platform-frontend/pull/2768

**Comment by glupiawymowka** [comment]
*tested on stage*
