### ISSUE TITLE
Trans-History #3. Modal Template

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#2833]
We will start with this Modal in its most basic form and add increasing complexity later on.

To begin with we have a template for a modal with and without a link to the issuer profile:

Template WITH profile link:
https://zpl.io/bJpJERn

This template will apply to all modal states for which there is an available issuer profile:

- Invested
- Claimed token (Except NEU)
- Claimed refund

Template WITHOUT profile link:
https://zpl.io/bzqEY9A

This template is for states with no available issuer:

- Purchased nEURO
- Redeemed nEURO
- Confiscation
- Paid out
- Transferred
- Claimed NEU reward
- Committed to ICBM

The two fields consistent across all transactions are status and timestamp

All other fields sit in the space called Modal Content. This will be covered in Ticket #4 

Thanks!

**Comment by glupiawymowka** [comment]
ok on stage
