### ISSUE TITLE
Platform issues with Mac-Pro, using Safari

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2842]
**Describe the bug**
User reports that he cannot register on the platform, due to the fact that it doesn't load.

**To Reproduce**
Use - mac book pro with safari
Go to - platform.neufund.org

**Expected behavior**
Page Loads as expected

**Screenshots / Videos / Links**
![image](https://user-images.githubusercontent.com/48217191/57140472-22fe1e00-6db8-11e9-952e-9ea136f64afd.png)

If this affects a specific device, browser, environment, etc put details here e.g.

 - Browser [safari]

**Comment by AlexeyTuboltsev** [comment]
moved to frontend
https://github.com/Neufund/platform-frontend/issues/2842

**Comment by andywalton** [comment]
Hello, I just tested this on my Macbook Pro.

I successfully created a Light Wallet using Safari.

<img width="396" alt="Screenshot 2019-05-07 at 11 21 37" src="https://user-images.githubusercontent.com/609657/57288745-614a5480-70ba-11e9-84e1-9be8f3493426.png">
<img width="698" alt="Screenshot 2019-05-07 at 11 24 19" src="https://user-images.githubusercontent.com/609657/57288901-b0908500-70ba-11e9-9eca-610b35d29823.png">
<img width="1376" alt="Screenshot 2019-05-07 at 11 23 33" src="https://user-images.githubusercontent.com/609657/57288853-93f44d00-70ba-11e9-8735-495c710a550d.png">
<img width="1376" alt="Screenshot 2019-05-07 at 11 21 19" src="https://user-images.githubusercontent.com/609657/57288762-69a28f80-70ba-11e9-826a-29aa07d1bef2.png">
<img width="1376" alt="Screenshot 2019-05-07 at 11 21 24" src="https://user-images.githubusercontent.com/609657/57288771-6dcead00-70ba-11e9-9917-c1d7fe29fd92.png">

Can we ask the user more information. What version of Safari is he/she using?
