### ISSUE TITLE
Copy edits ETO setup Step 2 next step component

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2848]
When an Issuer is on Step 2 of their ETO application. The following copy changes are required.

![issuer-changes-001.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/784521c1-9b59-401e-b3f1-9a2368359c92)

**STEP 2: SET UP YOUR ETO**

> Hi! You are ready to go now.
>
> This is your dashboard which will guide you through the whole process of setting up your ETO. Below you see the so-called ETO-forms which categorize all the necessary information for a beautiful, transparent and fully regulated fundraising. 
>
> All the information provided in the ETO forms will be visible on your companies listing page, before publishing you can preview you it any time in the sectio “ETO page” on your left.   You don’t have to fill our your profile in one go. You can save the process and return later to make additions or edits. After submitting your listing page for publishing you will still be able to update all marketing information and assets.

---

If you have any questions speak to Andy or Aga.

**Comment by andywalton** [comment]
Okay so pushing this PR now. This copy isn't 100% IMO and I've done some edits. We can review it when we focus on further improvements to this flow. It will now read as follows:

> STEP 2: SETUP YOUR ETO
> 
> Hi! You are ready to go now.
> 
> This is your dashboard which will guide you through the whole process of setting up your ETO. Below you see the so-called ETO-forms which categorize all the necessary information for a beautiful, transparent and fully regulated fundraising.
> 
> All the information provided in the ETO forms will be visible on your company listing page, before publishing you can preview your listing by clicking on “ETO Page” in the main menu.
> 
> You don't have to fill out your profile in one go. You can save the process and return later to make additions or edits. After submitting your listing page for publishing you will still be able to update all marketing information and assets.

**Comment by kelexa** [comment]
tested on staging - OK
