### ISSUE TITLE
Copy edits ETO setup Step 3 next step component

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2849]
When an Issuer is on Step 3 of their ETO application. The following copy changes are required.

**Change the Step 3 page heading to:**
>  STEP 3: Upload term sheet and publish your ETO listing page

<img width="654" alt="Screenshot 2019-05-05 at 21 55 36" src="https://user-images.githubusercontent.com/609657/57199541-8d61ba80-6f80-11e9-83b5-ef4940edb6f9.png">

---

Then, this step has two states. The copy for each should be:

**1. Upload term sheet state**
> Heading: Upload your signed term sheet
> Helper text: Please go to the documents section, download the generated term sheet, sign it and upload it to the platform. This will enable you to publish your ETO listing page and start your fundraising campaign.

<img width="749" alt="issuer-changes-002b" src="https://user-images.githubusercontent.com/609657/57199505-f39a0d80-6f7f-11e9-8131-ece44a773ffe.png">

---

**2. Submit your proposal**
> Heading: SUBMIT YOUR ETO LISTING FOR REVIEW
> Helper text: You have completed all the required fields and can now submit your ETO listing for review. Someone from our team will review and coordinate with you the publishing time of the ETO page. By publishing your ETO Listing Page your ETO campaign will start. 

<img width="851" alt="issuer-changes-002a" src="https://user-images.githubusercontent.com/609657/57199508-fdbc0c00-6f7f-11e9-9bec-677ba7333dc7.png">

—
If you have any questions speak to Andy or Aga.

**Comment by kelexa** [comment]
tested on staging - OK
