### ISSUE TITLE
Copy edits ETO Listing is in review

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2850]
*Description*
When an Issuer’s ETO application is in review, the copy on the Dashboard should change to the following:

> ETO LISTING IS IN REVIEW
>
> Thank you for submitting your ETO listing. Someone from our team will review and coordinate with you the publishing time of the ETO page. By publishing your ETO Listing Page your ETO campaign will start. 

<img width="1046" alt="issuer-changes-003" src="https://user-images.githubusercontent.com/609657/57199586-17118800-6f81-11e9-83ac-85f9b1ccb8f0.png">

---

If you have any questions speak to Andy or Aga.

**Comment by kelexa** [comment]
tested on staging - OK
