### ISSUE TITLE
Copy change to the enable Whitelisting component

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2851]
On the issuer dashboard, when an ETO is ready to be whitelisted the copy should change to the following in the enable whitelist widget:

> ENABLE SUBSCRIPTION FOR YOUR WHITELIST
> 
> Your ETO listing is public now. You can now start your fundraising campaign. You can also start collecting subscriptions for your whitelist. You have 500 slots to give away. All investors signed up for the whitelist will have access to the presale of your fundraising. You can disable the subscription any time or it will be automatically disabled once filled or two weeks before the start of your presale.

The heading of the page should also then change to:
> ETO campaign public

<img width="568" alt="issuer-changes-004" src="https://user-images.githubusercontent.com/609657/57199650-c2224180-6f81-11e9-8753-772a788dfab1.png">

---

If you have any questions speak to Andy or Aga.

**Comment by glupiawymowka** [comment]
this is already on .io (and probably also stage)
