### ISSUE TITLE
Make the Upload Approved Prospectus component content dynamic

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2852]
On the Dashboard, when we ask an Issuer to upload their approved prospectus or investment memorandum via a component on the Dashboard. We need to conditionally change the copy based on their ETO product type they’ve selected. Ie. if the ETO product asks for an investment memorandum the copy needs to reflect this. Currently it doesn’t.

This is the component being referred to:
<img width="270" alt="issuer-changes-005a" src="https://user-images.githubusercontent.com/609657/57199696-2c3ae680-6f82-11e9-94b5-8b167cca56b0.png">

1. When an ETO product requires the Issuer to upload a prospectus, the component content should say:

> Headline: Upload your approved prospectus
>
> Text: Please go to the documents section and upload your approved prospectus. After that you will be able to set the date of your fundraising. This is the last step before you can collect funds.
> 
> Button: Upload prospectus

2. When an ETO product requires the Issuer to upload a prospectus, the widget copy should say:

> Headline: Upload your signed investment memorandum
>
> Text: Please go to the documents section and upload your signed investment memorandum. After that you will be able to set the date of your fundraising. This is the last step before you can collect funds.
>
> Button: Upload investment memorandum

<img width="599" alt="issuer-changes-005b" src="https://user-images.githubusercontent.com/609657/57199691-247b4200-6f82-11e9-8e53-2bb11df99a34.png">

**Acceptance criteria**
- [ ] The component displays different messaging if an ETO product type requires an investment memorandum or a prospectus documents to be uploaded.

---

If you have any questions speak to Andy or Aga.

**Comment by desfero** [comment]
This was already done and tested as a part of #3289
