### ISSUE TITLE
Add new field to ETO Forms > Legal Information called > Company legal description

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2853]
We need to add a new field to the ETO form section Legal Information called `{listed.company.description}`. This field should be added after the **Legal Form** field.

**The field is required and no length validation is needed.**

The field should be labeled **Company legal description** and it will be connected to the definition `CompanyData` and the field is called `company_description`.

See line 347 of the ETO definitions file: https://github.com/Neufund/platform-backend/blob/master/py_platform_common/platform_common/apis/swagger/eto_definitions.yaml#L347
![image](https://user-images.githubusercontent.com/609657/57199793-88523a80-6f83-11e9-8508-46a24c2d0717.png)

**Acceptance criteria**
- [x] When an issuer navigates to the Legal Form ETO forms and tries to save the page, it won't let them save without completing the Company legal description field.
- [x] This information then is saved correctly to our backend. When returning to the page, your previously entered information will exist in this new field.

---

If you have any questions speak to Andy or Aga. Tomek also did the API.

**Comment by rudolfix** [comment]
field will be named `company_legal_description`

**Comment by rudolfix** [comment]
please look at following PR to be merged, it adds requested field.

please note that field is **mandatory** and submitting ETO will not work without setting it

**Comment by Moejoe90** [comment]
Please don't forget to `unskip` eto tests once its done 
`FullEtoRegistrations`
And 
`RequiredEtoRegistration`

**Comment by kelexa** [comment]
tested on staging - ok
