### ISSUE TITLE
Issuer document links and uploads need to listen to ETO Product selected

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2854]
**Bug**
As an issuer, if I select an ETO product that is LI-based, a 5M Eur ETO and I see a “Prospectus Template” link and an “Upload Prospectus Document” in the documents to upload sections instead of an “Investment Memorandum Template” and an “Upload Investment Memorandum Document”.

**Expected behavior**
The Prospectus/Investment Memorandum Templates links as well as the request to “Upload Prospectus/Investment Memorandum Document” should be dynamic and based off the data coming from the ETO product type the Issuer has selected due to the requirements for that specific product.

**Environment**
This happens in all browsers as it’s a functionality bug due to the recent ETO changes.

**Screenshots**
<img width="1008" alt="issuer-bugs-001" src="https://user-images.githubusercontent.com/609657/57199884-ad937880-6f84-11e9-9a35-c4d7c7bce345.png">

---

If you have any questions speak to Andy or Aga.

**Comment by Moejoe90** [comment]
I have tested this and I believe it might be a fixture issue as you can see 
![image](https://user-images.githubusercontent.com/23242822/57568474-2876ec00-73e8-11e9-82ea-21c5fe419ec2.png)

**Comment by kelexa** [comment]
currently I get the following on .net after KYC is verified and I'm trying to access either dashboard, eto page or documents:

![image](https://user-images.githubusercontent.com/40295416/57770902-a5b89e80-7711-11e9-9070-3581b90115b1.png)

@glupiawymowka we will test again after staging is deployed.

**Comment by kelexa** [comment]
tested on staging - OK
