### ISSUE TITLE
Hide empty cap table "donut" circle graphic

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2855]
**Description**
If an Issuer doesn’t enter cap table information we currently show an empty gray circle (donut) graphic on the company ETO page. We need to hide this if no information exists and only show it if the Issuer has entered information.

**Actual behaviour**
This is how it currently looks without cap table information (incorrect):

<img width="976" alt="issuer-bugs-002b" src="https://user-images.githubusercontent.com/609657/57199931-4b874300-6f85-11e9-9594-980b65ffa891.png">

**Expected behavior**
It should look like this without cap table information (correct):

<img width="944" alt="issuer-bugs-002c" src="https://user-images.githubusercontent.com/609657/57199933-5346e780-6f85-11e9-9f93-77be5a0ac73f.png">

And like this when cap table information exists (correct):

<img width="944" alt="issuer-bugs-002a" src="https://user-images.githubusercontent.com/609657/57199947-65288a80-6f85-11e9-9bcb-f75e6fda6edd.png">

**Comment by kelexa** [comment]
tested on staging

the donut was dropped when there is no shareholder information entered but there is an issue with the space between texts and alignment with the texts below see screenshot

![image](https://user-images.githubusercontent.com/40295416/57850397-1e852c80-77de-11e9-8ecc-7d432ba3f9ed.png)

**Comment by glupiawymowka** [comment]
fixed
