### ISSUE TITLE
[ETO jurisdiction] - drop the header and fix copy in the disclaimer modal

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2863]
**Description**
Our current copy is confusing. Personally, I see the question in the header and always click "No", but this action is actually taking the user back. He should click "Yes" but this is not clear 

![image](https://user-images.githubusercontent.com/18315589/57235963-58a73f00-7024-11e9-9d55-14b87f8ddf0a.png)

**Environment**
.io, .net

**Steps To Reproduce**

1. login/register with any unverified account on .io
2. From the dashboard, try to choose the German Jurisdiction ETO

**Expected behavior**
- [ ] Please drop the header completely
- [ ] Please change the copy as follows: 

"This offering is not available to Lichtenstein residents.
Are you a resident of Lichtenstein?"

Buttons

YES, I AM>    /    NO, I'M NOT> 
![image](https://user-images.githubusercontent.com/18315589/57236199-c81d2e80-7024-11e9-9a39-e5d92c19a5cc.png)

**Comments, context, logs**

**Comment by andywalton** [comment]
Pushing a PR for this now.

Updated this modals image, removed the title and revised the copy and button styling and labels.

<img width="1436" alt="Screenshot 2019-05-16 at 23 12 31" src="https://user-images.githubusercontent.com/609657/57887611-2cfc3400-7830-11e9-8943-f1c60975c157.png">

@glupiawymowka please will you take a look at this tomorrow.

**Comment by glupiawymowka** [comment]
ok on .io, untestable on stage
