### ISSUE TITLE
forms justified left after switch to grid

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2866]
**Description**
forms are justified to left after new Panel was switched to grid layout

**Environment**
any issuer

**Steps To Reproduce**
log in as issuer and go to any of the registration forms

**Actual behaviour**
forms are justified to the left inside Panel

**Expected behavior**
central justification, width 100% 

**Comments, context, logs**

**Screenshots**
![image copy](https://user-images.githubusercontent.com/14041336/57239826-4aa9ec00-702d-11e9-84bc-d7d6dc1cd7b5.png)

**Comment by kelexa** [comment]
tested on staging - OK
