### ISSUE TITLE
Please remove Founders Bank from platform.neufund.org

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2869]
Please remove Founders Bank from platform.neufund.org under the section:

MEET OTHER COMPANIES TOKENIZING THEIR SHARES SOON

![Screenshot 2019-05-07 at 11.15.46.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/c9d90d71-fee8-4943-9f59-a042d067278e)

**Comment by glupiawymowka** [comment]
this is on .io already

**Comment by glupiawymowka** [comment]
tested on .net
