### ISSUE TITLE
Only sent salt with put /users/me when it is needed

### ISSUE THREAD

**Issue by huesforalice** [Neufund/platform-frontend#2873]
**Description**
Currently the frontend sends the users salt also when cancelling the current email activation. It is not needed here and will actually trigger a wrong action in the backend in the form of sending out a "Wallet Recovered" email.

**Environment**
Tested on staging

**Steps To Reproduce**
Create a new account with a light wallet, then verify your current email. Then create a new email verification and cancel that one. You will receive a "wallet recovered" email, and in the chrome console you'll see that the salt was send for this cancelling request.

**Actual behaviour**
Salt is part of users put request.

**Expected behavior**
Salt should not be part of users put request.

**Comments, context, logs**
Ask Dave if anything is unclear. This ticket is kind of important.

**Screenshots**

**Comment by glupiawymowka** [comment]
tested on  stage
