### ISSUE TITLE
ETO Form image upload for Preview card

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2882]
**Task**
Add an extra image upload field to allow an Issuer to upload a "Preview image".

This field should be added to the bottom of the Company information ETO Forms view.

![image](https://user-images.githubusercontent.com/609657/57375759-8adcac00-719e-11e9-8262-32960bdfb052.png)

Note this field is required. The image should be called `Preview` and the image dimensions we ask for should be `768 x 400 png` (that text should change one day!)

Once an image is uploaded, it should allow the same functionality as the two other image upload fields. Ie. it validates and it is possible to delete.

**Designs**
![image](https://user-images.githubusercontent.com/609657/57376224-c9bf3180-719f-11e9-89f0-aa5ff6cd4c28.png)

**Acceptance criteria**

- [x] The ETO preview cards use this new Preview image instead of the Banner image on the Dashboard view as below.

![image](https://user-images.githubusercontent.com/609657/57376324-012dde00-71a0-11e9-9f76-826907a56cc6.png)

- [x] The preview card images don't overlap as per the image above.

**Technical notes**
`company_preview_card_banner` - also see attached backend ticket

**Testing notes**
It should be possible to upload a Preview image for your fake ETO campaign. This image should be deletable and it should display on your ETO campaign that is listed on the Investor Dashboard.

We should add a test for this field, it's a required field.

**Comment by rudolfix** [comment]
backend PR was merged and will be available on Monday backend image. added on io fixtures too

**Comment by shanile** [comment]
was tested on Net and it's not there @AlexeyTuboltsev mentioned that it was not merged yet 

Tested on io and the 3 imges apear 
![image](https://user-images.githubusercontent.com/36156487/57776771-9e4cc180-7720-11e9-914f-56e13cbef761.png)

tested also the investor side and the banner and logo is the same

**Comment by kelexa** [comment]
tested on staging - ok
