### ISSUE TITLE
ETO page - make Advisors, Investors and Partners visible components

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2888]
**Task**
Hey Wiktor, Andy asked me to leave a comment here - we misunderstood each other.

We should have three standalone modules:

Team
Partners
Investors, Advisors, rest of the key individual groups
What is new?
Partners as standalone module
&
Order of tabs in the third module: we should always show investors first.

**Acceptance criteria**
- [ ] Team and Partners  are standalone components and are stacked one one below the other.
- [ ] Investors, Advisors and the rest -> still in single component with tabs in this order

**Comment by andywalton** [comment]
@drakkein -> I'm sorry but there has been a change in the order mentioned above.

The correct order above should be:
1. Investors
2. Advisors
3. Partners

**Comment by Vanilizer** [comment]
Hey Wiktor, Andy asked me to leave a comment here - we misunderstood each other. 

We should have three standalone modules:
1. Team
2. Partners
3. Investors, Advisors, rest of the key individual groups 

What is new? 
Partners as standalone module
&
Order of tabs in the third module: we should always show investors first.

Hope this helps.
