### ISSUE TITLE
Filter only offers in Multi-Jurisdiction logic

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#2910]
**Background**
https://github.com/Neufund/platform-frontend/issues/2789#issuecomment-489084892
**Acceptance criteria**
* [x] ETOs that are finished are always shown to all users without restrictions
* [x] ETOs that are finished do not need additional modal both for logged and unlogged users

**Technical notes**

**Testing notes**
We cannot test this with E2E due to lack of German ETO fixtures in different states

**Comment by kelexa** [comment]
tested on .io - OK

no way to test properly on staging since fixtures for ongoing DE ETOs and LI ETOs missing.
