### ISSUE TITLE
change handling of default derivation paths due to Ledger Live

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2923]
**Background**
Ledger Live discontinued the use of derivation paths they supported for the last two years, that is
44'/60'/0'/n

the current default is
44'/60'/n'/0/0

while BIP standard is
44'/60'/0'/0/n

see here
https://github.com/iancoleman/bip39/issues/327#issuecomment-491122711

**Designs**
no designs needed

**Acceptance criteria**
* [ ] swap the default address: 44'/60'/0'/0/0 goes first, then 44'/60'/0'/0
* [ ] put `(legacy address`) under address 44'/60'/0'/0
* [ ] now we have a problem on what to do when user selects "MORE ADDRESSES", IMO we should do two cases of derivation path expansion
* [ ] default when user (or system) enters 44'/60'/0'/0/0 - we use ledger style expansion
44'/60'/0'/0/0
44'/60'/1'/0/0
44'/60'/2'/0/0
etc.
* [ ] our current expansion, when anything else than string above is typed

**Comment by pstroinski** [comment]
@rudolfix this has an implication on current users. They registered (the old ones) with the different one so they would need to always go to advanced options which is not super intuitive
Do you still want to push this change?

**Comment by Moejoe90** [comment]
I wouldn't push this due to what we discussed before
