### ISSUE TITLE
ETO preview card styling tweaks

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2926]
**Tasks**
Please update the ETO preview card as follows:

1. The category tags need to match the same styling as the tags on our ETO page for Issuers.

Change the tag class from `ghost-bold white` to rather use `bold dark`.

Please also ensure the category tag has a border radius as follows: `border-radius: .1875rem;`

2. Left align the ETO status tag.

Update the ETO status tag class with the following css properties:

```
margin: 12px 25px;
float: left;
```

**Acceptance criteria**

- [x] The card should look as per the screen grab below:

<img width="1486" alt="Screenshot 2019-05-14 at 13 28 24" src="https://user-images.githubusercontent.com/609657/57694899-32e5ef80-764d-11e9-9353-27110b8078d5.png">

- [x] NB the category tag needs to have a `border-radius: .1875rem;`

<img width="337" alt="Screenshot 2019-05-14 at 13 37 37" src="https://user-images.githubusercontent.com/609657/57695028-848e7a00-764d-11e9-9692-4803ce124af0.png">

**Comment by glupiawymowka** [comment]
tested on stage
