### ISSUE TITLE
[ISSUER FLOW] - fix the marketing preview submit modal 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#2937]
**Description**

This is how the module looks currently for the issuer: 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/cfe825bf-807b-479d-8db2-6b95ec90a2e7)

**Steps to reproduce**
- create new issuer account and verify it on .io 
- fill out the requested fields in media forms 
- when it's done, the module to submit and publish your marketing data will appear 

**Expected behavior** 
We need some design/designer input here, but generally, it should fit the other modals on the platform

**Comment by Louisswryan** [comment]
Hi sorry for the lack of specifics. let's use the preset card that is half the width of the current one. That is, the same format as the PRESALE DATE card. Leave the SUBMIT cta centred, this should look less out of place. Hope these instructions are clear.
