### ISSUE TITLE
calculator on Investment Terms does not refresh

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2939]
**Description**
when investment terms are edited, calculated values are not updated which is extremely misleading

**Environment**
any browser

**Steps To Reproduce**
login as ISSUER_PREVIEW and try to edit 
https://platform.neufund.io/eto/registration/eto-investment-terms

**Actual behaviour**
Calculated values below do not refresh
![image](https://user-images.githubusercontent.com/17202864/57795745-057d6c80-7747-11e9-9735-4ae920c1151f.png)

**Expected behavior**
* [ ] values refresh when any editable value is changed
* [ ] refresh is delayed by 500ms and typing cancels previous one - you know what I mean. it should not delay typing

**Comment by glupiawymowka** [comment]
*tested on stage*
