### ISSUE TITLE
bring back Fundraising Statistics for on-chain etos

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2943]
**Background**
We can switch back Fundraising Statistics for on-chain etos. we have it done for FF ETO and we'll switch it on for new etos as well. This is also important for "build to demonstrate" that shows platform as live working product

**Designs**
![image.png](https://images.zenhubusercontent.com/5a72da804b5806bc2bc52ecc/4f1eff17-2c20-448e-96ec-f32b62053650)
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5b7c2f346d8b230e716f04cf

**Acceptance criteria**
* [x] leads to production version of ICO monitor https://icomonitor.io/#/0x01A1f17808edAE0B004A4F11a03620D3d804b997, replace with eto_address you get from eto_data
* [x] opens in new tab

**Comment by glupiawymowka** [comment]
it's gone from stage & dev now.  Is the feature flag on?

**Comment by pstroinski** [comment]
Related to: #3045
