### ISSUE TITLE
use product field of eto_data to populate validators instead of PlatformTerms

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2944]
**Background**
We have removed all product-related settings from platform terms and moved it to ETOTermsConstraint contract that is used to set parameter space for ETOTerms. This data is extracted by backend and returned as "product" field of "eto_data" definition.
Please use this data to set validators in issuer forms: like min and max tickets or min and max days of the ETO.

**Acceptance criteria**
* [ ] use `product` data for issuer forms validation (if not yet done). please figure out which form controls they apply to - it's straightforward
* [x] replace `DATE_TO_WHITELIST_MIN_DURATION` with product equivalent everywhere - please note that it's part of eto_data, not a global constant
* [x] finally update artifacts

**Technical notes**
backend ticket must be merged to master
https://github.com/Neufund/platform-backend/pull/1695

**Comment by Moejoe90** [comment]
After checking I think this ticket is already implemented can you please confirm @rudolfix 
As the changes are made by you
