### ISSUE TITLE
remove any product related data when only marketing data is displayed

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2945]
**Background**
We display several datapoints that are part of the product before issuer has any chance to set it up. Now that's ok - all issuers use same product but in the future that will not be the case. Currently we display
- jurisdiction
- asset type
- offering type (memorandum)

those are forcibly set to default by backend so when issuer changes them, investor do not see it before changes are finally published. this is nasty hack however

**Designs**

**Acceptance criteria**
when displaying only marketing data
- [ ] we do not display jurisdiction banner, nor jurisdiction information on the terms
- [ ] we do not display asset type
- [ ] we do not display modal in german ETOs (as jursidiction is not set)

**Technical notes**
please request changes from backend when ticket is started - to drop product fully from `eto_data` when investment terms are cleared out

**Comment by pstroinski** [comment]
To be moved to asana @andywalton
