### ISSUE TITLE
issuer dashboard lacks clear indication that profile is publicly visible

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2946]
**Background**
When issuer submits marketing data and is being accepted and listed via backoffice app, the SUBMIT widget just disappears and status is still PREVIEW. we should clearly indicate somewhere that profile is being listed!

**Designs**

**Acceptance criteria**
- [ ] when profile is publicly visible we display something in the issuer dashboard and (possibly) in issuer view of public profile

**Technical notes**
tbd.

**Testing notes**
tbd.

**Comment by Moejoe90** [comment]
As per discussion with @andywalton we will close this ticket
