### ISSUE TITLE
Company listing page changes need for "coming soon" ETO state

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2951]
Please make the following changes to the Company profile page an Issuer's ETO is in the  `Coming soon` state:

- [x] **Pitch deck button**

At the top of the company listing page, please add a `Pitch deck` button link above the Term sheet button link as per the image below. **It's visible in all states**

![Screenshot 2019-05-16 at 10.36.55.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/69ed83df-4dd8-45f8-9938-1cc97d18e010)

- [x] **Hide the whole section “ETO investment terms” in Coming soon state**

![Screenshot 2019-05-16 at 10.43.32.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/de3ad150-a2df-4e12-bbd7-d4e03c41ea6e)

- [x] **Default display first Pitch accordion**

In the **Pitch** section, the accordions are all by default set to be closed. Please change this so that the **first accordion** displayed in this section is always set to open (ie. not collapsed).

![Screenshot 2019-05-16 at 10.27.50.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/2af397e9-f53c-4c4c-89b5-093c0f56cbe9)

![Screenshot 2019-05-16 at 10.28.00.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/625f683b-3e82-4475-bcff-1fc70f70e64d)

- [x] **Move the module “Partners” up under the Team module...**

... And above the module with the rest of key individuals. All these modules should not be in Tabs, they should be individual modules.

This is related to ticket: [#2888](https://github.com/Neufund/platform-frontend/issues/2888)

![Screenshot 2019-05-16 at 10.45.39.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/07e7ff21-30fc-4ccc-a386-0cda9f5a5c02)

**Comment by rudolfix** [comment]
technical details:
for pitchdeck there's a new field in the `company_data`:
```
company_pitchdeck_url:
        $ref: "#/definitions/Link"
```
it should be a link and properly validated

see https://github.com/Neufund/platform-backend/pull/1699 to be merged

**Comment by andywalton** [comment]
Hi @drakkein --> See the new `company_pitchdeck_url`. I'm going to provide you with a screen shot of where to put this field shortly...

**Comment by rudolfix** [comment]
@drakkein there's related ticket that you should do together with this #2888 please do it in single PR

**Comment by andywalton** [comment]
@drakkein in #2888 - there has been a small order change with those modules.

**Comment by andywalton** [comment]
<img width="1436" alt="Screenshot 2019-05-16 at 21 23 52" src="https://user-images.githubusercontent.com/609657/57929598-0aabfa00-78b4-11e9-893f-3b3cd7e2116a.png">

@drakkein @rudolfix, here was the design that never got added. It's Githubs Preview tab causing "no saving" of edits.

Please add the Pitch Deck to the top of the Media section.

**Comment by andywalton** [comment]
```
<label ...>Add Pitch Deck link *</label>
<p>Link to your shared Pitch Deck file</p>
<input placeholder="url" ...>
```

**Comment by glupiawymowka** [comment]
Edge case: 
on stage, I have an account that already had marketing visible. 
After the changes, I cannot open ETO forms on this account. 
Please let me know if you need a private key as we don't have a fixture here. 

![image](https://user-images.githubusercontent.com/18315589/58027302-9b830f80-7b18-11e9-816e-6eaadab80079.png)

**Comment by glupiawymowka** [comment]
*tested on stage*
