### ISSUE TITLE
Pitch deck is not working without youtube video

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#2955]
**Description**
Right now if you try to add only slideshare presentation without any youtube video it won't display any presentation on the eto profile.

**Environment**
-

**Steps To Reproduce**
* Log in as an issuer 
* go to Media forms
* add slideshare link and save
* go to eto view
* there is no slideshare (pitch deck) displayed

**Actual behaviour**
there is only `pitch deck` tab title without content

**Expected behavior**
slideshare should be properly displayed below tab title

**Comments, context, logs**
seems like we should filter `falsy` children values here https://github.com/Neufund/platform-frontend/blob/7a91812bd3c40c1e6f21bd83af5d08b119d4a11d/app/components/shared/Tabs.tsx#L93-L104

as we are trying to get `activeIndex` of 0, where `children` array equals to `[false, slideshareTab]` because `isYouTubeVideoAvailable` is set to false.
**Screenshots**

**Comment by glupiawymowka** [comment]
*tested on stage*
it's a bit confusing how should the link look tho
