### ISSUE TITLE
hide reservation agreement when you didn't participate in ETO of particular equity token

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2963]
**Description**

**Environment**

**Steps To Reproduce**

**Actual behaviour**

**Expected behavior**

**Comments, context, logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/17202864/57881331-4b0e6800-7821-11e9-80e9-026671335983.png)

**Comment by pstroinski** [comment]
Missing data. Please provide some additional info if it's still valid @rudolfix
