### ISSUE TITLE
introduce inactivity timeout

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2965]
**Background**
we are getting feedback from our users that they perceive long lived login cookies as insecure. ok - we should probably be more like banking sites which have strict sessions timeouts.

**Acceptance criteria**
* [x] user is logged out after 10 minutes of inactivity (both investor and issuer)
* [x] if user has many tabs open that belong to the same browser (and can communicate via events) activity in one tab resets timer in the others

* [ ] ~~if user closes all tabs we should log him/her out (JWT in session cookie then?)~~
Discussed with @rudolfix we will skip this point
* [x] if user explicitely logs out, we log out from all tabs (we have it like it now)

**Testing notes**
both should be tested if possible... maybe there's a way to mock inactivity timer and simulate closing of the session?

**Technical notes**
JWT are used to authenticate users to the backend, not to manage sessions, check #2970 for details on how they are issued and refreshed

**Comment by glupiawymowka** [comment]
tested on stage
