### ISSUE TITLE
Link bank account button in the Wallet is displayed as a blue text

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#2969]
**Description**
Seems that bank account link that looked good now is changed to some small text

**Environment**
PRD

**Steps To Reproduce**
Log into the platform with an account without linked bank account and go to the Wallet

**Actual behaviour**
Blue text to link an account

**Expected behavior**
Nice text or icon

**Comments, context, logs**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/27957897/57919167-92840b00-7898-11e9-9a6b-ab1500801356.png)

**Comment by glupiawymowka** [comment]
@pstroinski this is not a bug. It was always designed this way, I was even confirming it double. 
@Louisswryan please take a look 
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c585e62f4fd2f423c1ad4ea

**Comment by Louisswryan** [comment]
Hi @glupiawymowka @pstroinski 

This is how this has looked as long as I remember and it appears this way in our working files.

The mission, once Transaction History is implemented, is a layout change for the Wallet. These portals need to be more accessible.

@andywalton has made designs for a mobile platform so this is an opportunity to take a mobile-first approach to designing the Wallet and the platform in general.

**Comment by pstroinski** [comment]
So if it's like this in the designs I think it would be good to make it look better in the future releases. Especially that in the profile tab there is the same function but with the icon.
In this case for sure, it's not a bug but a feature

**Comment by glupiawymowka** [comment]
please also keep in mind that this is not the only place where we have a button represented this way. It's at least redeem and investment flow, too
![image](https://user-images.githubusercontent.com/18315589/58092864-72708680-7bcd-11e9-9fa0-e521095e4e55.png)

**Comment by Louisswryan** [comment]
I am going to add this ticket to the UI Epic.

I totally agree that these old-fashioned links look like quick patches but they are in fact very important features.

The Wallet update will need an Epic which I can start once we are done with demo issuers.

I will take a look at the investment flow but this will also require a redesign as I can see we still have the incorrect EUR symbol. Perhaps something more in line with the Transaction Wizard.

**Comment by Louisswryan** [comment]
As we are looking at bigger changes that will will cover this issue, I think this ticket can be closed but I will get approval from everyone individually
