### ISSUE TITLE
small fixes to investor dashboard

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2977]
**Description**
small fixes to investor dashboard:

* [x] fix myNeu widget height on production (difference in css on prod and dev) 
* [x] remove ICBM wallet link from myWallet widget on dashboard

**Environment**
na

**Steps To Reproduce**
log in as an investor, go to dashboard and 👁👁 

**Actual behaviour**
see screenshots

**Expected behavior**
1. MY NEUMARK widget is stretched from top to bottom of the widget
2. myWallet widget doesn't show the icbm link

**Comments, context, logs**

**Screenshots**
![image-1](https://user-images.githubusercontent.com/14041336/57934646-71cfab80-78c0-11e9-9122-d2a1cc12e1d1.png)
![image-2](https://user-images.githubusercontent.com/14041336/57934651-74ca9c00-78c0-11e9-96e1-5a342674ff4e.png)

**Comment by glupiawymowka** [comment]
tested on stage and live
