### ISSUE TITLE
rearrange issuer journey on the dashboard - new widget placements and state transitions

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#2980]
**Background**
By rearranging issuer flow and adding new semi-state (marketing visible) we broke our flow and now steps are disarranged and conflicting widgets are visible at once. This rather large ticket intends to fix the situation up until LISTED state (where terms are visible to investors)
We also improve texting.
See https://docs.google.com/presentation/d/1v2gQFfd_gCI1XDgoDPCVFQpjEpqXbzYg-ehOHILHUlQ/edit#slide=id.g51830a132c_4_4 pages 46 - 55

**Designs**
No new designs are required however it would be good to have reference design with new layout and some widgets and forms

**Acceptance criteria**
* [x] Unify layout of element on the dashboard
See page 46 of attached document. We have certain elements from the top to the bottom of the page places in order that never changes:
- eto status - always there !
- introduction text - html formatted - depends on the step (see below). currently hardcoded and shown for steps 2 to 8, otherwise hidden
- step number and step name with optional explanation text underneath
- widgets (like submit eto, upload termsheet)
- eto forms

please implement those placements, I've notices that sometimes Steps are attached to widgets and we can see two steps at once

* [ ] implement steps 2 - 8
There's step 1, please do not touch it - it's ok. Makes sure issuer has e-mail verified and KYC done.
Please also note that (with some exceptions) we do not have any changes in when we show widgets and how the states change inside widgets. We are almost good with switching logic.

**Step 2: Fill in information about your company**
Issuer is in step 2 when it didn't yet fill all necessary company data. Issuer goes to step 3 when all this data is filled

**Step 3: Publish your listing page**
In this step our new "submit marketing data" widget becomes visible and we unlock ETO forms (as we do now!). Issuer is in this step as long as he submits marketing data in the widget (->4) or he fills all eto forms and submits terms (->6)
Please show *submit marketing data* and *upload terms* widgets side by side if that case happens!

**Step 4: Listing page in review**
Issuer submitted marketing data (`visibility_pending` on `is_marketing_data_visible`.). All other things as above, except we go to state 5 when backoffice accepts listing

**Step 5: Set up your ETO**
Issuer is in this state when marketing data is visible and he didn't yet fill all required eto forms. During that state 'upload terms' may pop up when enough data is filled (do not change existing logic, it's good). Issuer goes to step 6 once terms are uploaded.

**Step 6: Publish your investment offer**
In this step, the old eto submission widget shows up. **make sure to hide marketing data submission widget - they are mutually exclusive**. Issuer goes to step 7 when he/she submits

**Step 7 & 8**
No changes in logic here!

* [ ] Make sure you use all new texting
As defined in the document - each step has it's own page. In particular
- step name
- step optional explanations
- new texting on widgets

do not touch STATE names (like CAMPAIGNING) - we'll have final ticket for that

**Technical notes**
There will be more tickets for later steps. Would be good to implement a separate function that gives you step as defined in some enum based on input data (like current eto and company data, etc. anything which is relevant) and then another function that gives step a number, name and optional explanations.
100% we'll insert some more steps between existing ones etc. so decoupling numbering from steps is important.

**Testing notes**
Please do a lot of visual inspections on codechecks with @Vanilizer

**Comment by andywalton** [comment]
![IMG_0347](https://user-images.githubusercontent.com/609657/58017856-923a7880-7b01-11e9-9681-5490854e8244.JPG)

@drakkein the image of a wireframe above describes the Issuer Dashboard structure at a high-level. It has the following sections:

1. **Status indicator** at the top of the page, Ie. **`colour dot` In draft** (Always visible)
2. **Intro text** - (Always visible unless mentioned it should be hidden)
3. **Step #: Step description** - (Always visible)
Some steps have a paragraph of helper text
4. **Step Widgets** (Change based on step)
5. **Company and Marketing Info** section with fields (Always visible)
6. **ETO Settings** section with fields (Only visible from Step 3: Publish your listing page)

Ps. @Louisswryan is mocking this up as a design file as well.

Please shout if you have any questions.

**Comment by Louisswryan** [comment]
Hello, 

Here is an updated design for the Issuer Flow.

@andywalton, @rudolfix  I have responded to a couple of issues that became apparent when recreating this design in higher fidelity.

- The header text is necessary but makes the content of the Dashboard overwhelming. It is now hidden inside a Tip.

- Numbering the steps above the widget has been the source of much confusion. This is a good model for the future but for now, I have labelled our top cards 'available actions'. This is accurate and nicely segments our three areas of interaction within the Dashboard environment.

These decisions have been run by @Vanilizer but if you think they don't work, let me know.

@drakkein below are zeplin links for the issuer dashboard template with and without the tooltip activated.

+ Tooltip
https://zpl.io/VKD9kyq

- Tooltip
https://zpl.io/VDAQk1r

Please keep in mind that the relevant information is still substituted based on the issuer's state, it is just a template change.

Also this whitelisting and presale card presentation will be unfamiliar, this is something I am dealing with in another ticket.

Please ask if you have questions.

Thanks!

**Comment by glupiawymowka** [comment]
tested on .io, not available on stage yet

**Comment by glupiawymowka** [comment]
tested on stage
