### ISSUE TITLE
Replace app logo and update site navigation background colour

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#2994]
Please update the app logo to use the attached logo:

The width this logo should be used at is `142 px wide by 32 px high`. This logo should always be visible all the way down to mobile device screen sizes.

Please us this logo:
[logo_neufund_on_dark.zip (SVG inside)](https://app.zenhub.com/files/116978635/fb4b9d94-8448-480c-9ac2-eea8101ef98e/download)

![logo_neufund_on_dark.svg](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/fb347e2b-ed94-4a5b-9420-4f75dc22a78c)

Then we need a colour change for:
- `navbar` (top header) background colour
- `aside` menu (left main menu) background colour and note the top border colour as well
- `footer` background colour

Should also change to: `#142431` which is a darker grey that what we have currently.

Currently the app looks like this:

![Screenshot 2019-05-21 at 12.34.19.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/0b12306d-eb99-4e30-9989-cd503baa7401)

After these changes the app should look like this:

![Neufund logo replacement.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/29be6c04-0a03-4b99-babc-3617b79e7205)

Thank you.

**Comment by glupiawymowka** [comment]
*tested on stage*
