### ISSUE TITLE
Access your recovery phrase modal keeps reloading

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#2995]
**Description**
when trying to access recovery phrase on initial light wallet setup the password prompt keeps popping up

1. user clicks on `Generate recovery phrase` 
2. password prompt comes up
3. user types in password, clicks confirm
4. recovery phrase shows up
5. after 1-2 seconds recovery phrase goes away, Confirm prompt shows up
6. after 1-2 seconds confirm prompt turns into password prompt
steps 2-6 keep repeating unless user manages to click confirm in step 5.

**Environment**
.io

**Steps To Reproduce**
see description

**Actual behaviour**
see description

**Expected behavior**
user enters password and gets recovery phrase without any further actions

**Comments, context, logs**

**Screenshots**

**Comment by Moejoe90** [comment]
This might be happening because of `IS_CYPRESS` is enabled in you're env var 
can you confirm if this happens also on `io`

**Comment by glupiawymowka** [comment]
it's not happening on .io
