### ISSUE TITLE
[PROFILE] - updated email won't appear as verified unless you refresh the whole page manually

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3004]
**Description** 
verify-email-widget is not updating automatically. 
This can end up with the situation where the user activates their email (by default another tab will open), but it stays inactive in the main tab as long as the user manually refresh the whole page. 

**Steps to reproduce** 
1. register with any wallet and add email 
2. click on the right activation link in sendgrid
3. the platform will open in another tab, informing you that the email was successfully verified. Close this new tab. 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/3b5b447f-1b18-4a8b-b207-ac0247e94bd1)

4. Go back to the old tab. There, you will see that you still need to verify your email. You can change tabs, but this modal won't update unless you re-login or refresh the whole page manually 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/c6902d2c-7894-40fa-a965-eea84e1685dd)

**Comment by rudolfix** [comment]
* [ ] please poll the user data when there's e-mail being activated (`unverified_email` field is not None). poll every 5 seconds. do
* [ ] in other states poll each 5 minutes

**Comment by glupiawymowka** [comment]
tested on stage
