### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.web3.previousConnectedWallet.address')

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3005]
**Description**
Related sentry issue https://sentry.neusrv.net/sentry/production/issues/5685/?referrer=slack

**Environment**

**Steps To Reproduce**
@Moejoe90 if you are able to reproduce please add one

**Actual behavior**
-

**Expected behavior**
-

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
I can't open the sentry issue. Is there something for me to do?
