### ISSUE TITLE
Company list view layout bugs on mobile

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3017]
**Description**
On the company listing ETO page, there are some layout bugs we need to fix:

- [x] **1. Carousel components aren't hiding modal content mobile**

The Key Individuals components, Team, Partners, Investors, Advisors etc. we should only show an image, name and social link. Clicking on each item will then show additional content in a modal. Currently the extra information is displaying on iOS/Android devices - Safari/Chrome devices. Please hide this additional text and display it in a modal when a user taps on the relevant item. Here is how the problem looks.

![Screenshot_20190523-102332](https://user-images.githubusercontent.com/609657/58239888-39115580-7d4a-11e9-8e3d-3ea9e255964f.jpg)

![Screenshot_20190523-102325](https://user-images.githubusercontent.com/609657/58239891-39115580-7d4a-11e9-8ad8-baffc225ebf3.jpg)

---

- [x] **2. Jurisdiction banner is covering the company image**

We need to fix the below.

1. Please push the image below this banner - ie. add a margin equal to the height of the banner.
2. Add left / right padding (20-30px padding)

![Screenshot_20190523-102231](https://user-images.githubusercontent.com/609657/58239894-39a9ec00-7d4a-11e9-9c81-48573dcb935b.jpg)

Here's what we're aiming for:

<img width="465" alt="Screenshot 2019-05-23 at 11 15 17" src="https://user-images.githubusercontent.com/609657/58241246-db323d00-7d4c-11e9-8b5f-49bd8d700633.png">

---

- [x] **3. Legal Information single column layout**

The Legal Information, please collapse the columns from a 2 column layout to a 1 by 1. Ie. put the Cap table below the company information and 100% both column. If you change the `col`'s to `col-12` it should sort this out.

![Screenshot_20190523-102305](https://user-images.githubusercontent.com/609657/58239892-39115580-7d4a-11e9-868e-865f374d0a74.jpg)

We're aiming for this:

<img width="428" alt="Screenshot 2019-05-23 at 11 22 32" src="https://user-images.githubusercontent.com/609657/58241500-64497400-7d4d-11e9-8d8e-8d47236e01d8.png">

**Comment by glupiawymowka** [comment]
*tested on stage*
