### ISSUE TITLE
several flaws setting start date in issuer panel

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3024]
**Description**
Setting start date is hard to use and provides misleading/outdated info. A few small changes will easily change it.

**Environment**
Dev/demo site

**Steps To Reproduce**
Login with ISSUER_NO_ST_DATE and try to set and change start date

**Actual behaviour -> expected behaviour**

* [x] hardcoded "The whitelisting phase will stop automatically 2 weeks before your chosen presale date" -> replace `2 weeks` with `N days` where N comes from product definition `selectIssuerEtoDateToWhitelistMinDuration` see #3023 
* [x] when setting date for the first time... could you initialize the date not to now() but to now() + selectIssuerEtoDateToWhitelistMinDuration() * 2?
* [x] if whitelisting enabled and start date is set and transaction is mined, please also reload whitelisting widget state
![image](https://user-images.githubusercontent.com/17202864/58379106-876b6200-7f9f-11e9-82f2-c0e5211f0a9b.png)
* [x] when I want to set the date, the calendar/time widget appears. and then randomly disappears in 2-3 seconds. I need to be fast here
* [ ] when I switch to setting time, each press on arrow closes the widget, it's a PITA

**Comments, context, logs**
* [x] also make your e2e test to work again after #3023 is merged

**Comment by pstroinski** [comment]
We still have an issue with the calendar display

**Comment by glupiawymowka** [comment]
calendar fixed on io
