### ISSUE TITLE
Suitability Test Questioner 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#3043]
**Background**

To create a questioner of 5-8 questions that will give us a better overview and better profile on our investors.
The questions are related to the investor: experience knowledge and finance status. 

The goal is to use it for:

Marketing 
Investors analysis 
Risk assessment where we can consider some of the investors based on low knowledge/ experience versus high investment amount 

Please use the PRD https://docs.google.com/document/d/10FxNNcNKFqytN9o7E7hrJuFcSNc4u5EjbJgqgxbtCrQ/edit which explain step by step the feature

**Comment by Moejoe90** [comment]
I will close this ticket for now until product decides to push it forrward
