### ISSUE TITLE
[ETO page] - twitter feed empty on iPhone

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3055]
**Description**
If an user opens an ETO page on mobile, Twitter feed shows up as an empty field 

**Environment**
all, tested with iPhone Xs, iOS 12.

**Steps To Reproduce**
1. login/register using a real device (browserstack will show you a correct, but irrationally long twitter feed) 
2. Open any ETO page 
3. Scroll  down to the twitter feed and check how does it look 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/23768365-5101-4b2a-b569-cea81e1b1e0a)

**Actual behavior**
The feed is either too long (browserstack) or not visible at all (real device) 

**Expected behavior**
short, visible twitter feed. 
Perfectly a scrollable item, but if not let's simply limit the number of visible posts

**Comment by AlexeyTuboltsev** [comment]
can't reproduce it in a debuggable environment, postponing for now

**Comment by pstroinski** [comment]
@glupiawymowka if you can still reproduce please reopen and move to ready for dev with updated info
