### ISSUE TITLE
Write e2e tests for bank verification/purchase/withdraw flow for Issuer

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3062]
**Background**
We need to have e2e tests for neur flow while logging in as issuer to cover neur flow for issuer.
Related slack discussion https://neufund.slack.com/archives/GAK8XK0CB/p1559057706052500

**Technical notes**
I hope we can fully reuse investor neur tests as the flow is the same.

**Testing notes**
not needed

**Comment by pstroinski** [comment]
To be moved to QA
