### ISSUE TITLE
[demo] Bionic ETO having strange dates

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3067]
**Description**
Bionic ETO start dates are in the past - year 1970

**Environment**
Demo

**Steps To Reproduce**
Go to Bionic ETO and check the ETO timeline

**Actual behaviour**
Start dates: 15/01/1970

**Expected behavior**
Dates in the future

**Comments, context, logs**
Dates should be fixed to represent the real dates in the future

**Screenshots**
![image](https://user-images.githubusercontent.com/27957897/58892466-90220d80-86ee-11e9-8b43-fe8c66986e0d.png)

**Comment by desfero** [comment]
@glupiawymowka should be fixed already

**Comment by glupiawymowka** [comment]
fixed in another ticket
