### ISSUE TITLE
[ETO forms] - mark "company founding date" as obligatory field

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3100]
**Description**

When going through the forms, the issuer will see "company founding date" as the voluntary field. However, it is not possible to save without filling this one. Please make it visible to the user that this field is obligatory. 

**Env** 
All

**Steps to reproduce**

1. Register as a new company or use ISSUER_BLANK_QA_HAS_KYC on .io 
2. Go to the "Legal" form and fill in only the fields with asterisks 
3. Try to save 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/9546a4b5-b518-4103-a356-a03c5c6d5908)

**Actual behavior** 
Form won't save as it sees "Company_founding_date" as the obligatory field

**Expected behavior** 
There is an asterisk next to the Company_founding_date so the user knows they need to fill this input to continue

**Comment by desfero** [comment]
I wanted to fix this one for ages... Let me fix it

**Comment by glupiawymowka** [comment]
*tested on stage*
