### ISSUE TITLE
[ETO documents] - visualize available document actions properly

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3101]
**Background**
Currently, the user has no idea what actions are possible on generated documents and uploadable documents. We must design all actions as in acceptance criteria.

CURRENT VIEWS
**autogenerated documents**
This sections contains documents that are automatically generated and are available to download at all times. Documents are in word format and are automatically filled with data when eto progresses (we internally call them `templates`). At some point templates are fully filled in and in that case they are typically downloaded, amended by some lawyers, signed by CEO and uploaded to section below.

Possible actions: download word document
States:
- there's no inactive state - they are always available to download
- we'd like to have a clear indication that template is finalized

![image](https://user-images.githubusercontent.com/17202864/63290340-8bb6cb00-c2c1-11e9-896d-e617b6c3eecf.png)

**uploadable documents**
In this section issuer will upload finalized and signed documents that are required for the eto. Upload functions is available only in certain states. For example: investment memorandum can be only uploaded when ETO is already listed and campaigning

Possible actions:
- upload document
- delete document
- download previously uploaded document

states:
1. inactive before uploaded (empty): upload not yet possible (we can even hide those)
2. document is **not** yet uploaded and
2a. upload action available
2b. delete action available
3. document is uploaded and actions above are available
4. document is uploaded and no upload/delete actions are available (final state) - 
5. mind that once uploaded, download action is always available

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/c5d856a8-f26e-4309-89c6-c13c2f0391a0)

**Designs**
Example "Document" Page Layout: https://zpl.io/awPEkMK
States - Auto-Generated Documents: https://zpl.io/29nXxrp
States - Uploaded Documents: https://zpl.io/VQ1lXZ5

**Acceptance criteria**
- [x] the user sees very clearly what to click to download auto-generated document and that it's word format
- [ ] the user clearly sees which autogenerated documents are finalized (fully filled) and are safe to download and sign
- [ ] the user sees very clearly what to click to download/upload/delete the document
- [x] the user clearly sees that document is uploaded / not uploaded
- [x] the user clearly sees that document is not yet uploaded and should be uploaded
- [x] IMO having the document icon to grow and shrink depending on document name length kind of sucks ;)

**Technical notes**
1. Marcin confirmed that the steps for which the delete can be available are already defined in the backend. 
2. We'll not provide DELETE function for signed ISHA upload OR we need to make Ethereum transaction on delete.

**Testing notes**
This is a design ticket. We may implement parts of it at start

**Comment by andywalton** [comment]
Please speak with @andywalton and/or @Trilbi when this ticket is assigned by Frontend for some handover.

For example the document timestamps and last updated dates might not be available on the backend - if that is the case we need to coordinate when we'll be able to pull that information - the designs attached can work without it so we can start working on this ticket without timestamps.
