### ISSUE TITLE
platform.neufund.org page changes

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3104]
## Overview

This is for @desfero, as discussed we are making some temporary changes to our platform.neufund.org holding page until such time as we retire this page in the near future.

We'd like to highlight current as past investment opportunities on this page as well as investment opportunities that are coming soon.

We need to revised the page content between the existing header and footer of this page, which will remain as per the current.

![Screenshot 2019-06-12 at 17.25.22.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/5831e3dc-2d04-41c5-9060-e88a3e3cf9e0)

So this page needs to change from this:
![Screenshot 2019-06-12 at 17.26.09.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/67ca7430-55a2-450d-a7a8-1429a9c8bd37)

To this:
![Screenshot 2019-06-12 at 17.26.09.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/f9c55edc-f031-4c40-be8e-99e6c8c2fe2f)

---

## Designs & Assets

You can see the full page design here via Zeplin: https://zpl.io/29KoeWy

You can also download exported card thumbnails and svg icons used in the designs here: [https://app.zenhub.com/files/116978635/860301ae-cbee-4739-9f9d-db36349664d8/download](https://app.zenhub.com/files/116978635/860301ae-cbee-4739-9f9d-db36349664d8/download) 

---

## Content

The page therefore has the following content:

### 1. Herospace section
 - [x] **Left column**

>Equity investments made better
>
> Easily access and invest in innovative companies from around the world  through a single interface.

- [x] **Right column**

Add 3 icons + features bullets.

> Invest in EUR / ETH
> 10 EUR min. ticket size
> Access tradable assets

On mobile these columns should collapse into a single column with the right column below the left.

### 2. Investment opportunities section

> Investment opportunities

The first two cards are our current investment listing cards we have on the platform. These need to be dynamic and on click will link through to the relevant company pages (in a new tab)

- [x] **Card 1: Greyp Bikes**

- [x] **Card 2: Fifth Force**

The cards 3-7 are new static cards but these should have the same layout and use the same React components we used for cards 1 & 2 (however just with static data)

The content and links for these cards are:

- [x] **Card 3: ICBM Capital Raise**

```
ICBM Capital Raise
More than a thousand investors participated in Neufund’s first fundraise in 2017. The capital is now ready to be invested by the investors.
https://commit.neufund.org
```

- [x] **Card 4: NGRAVE**

```
NGRAVE
Blockchain, Belgium
Next gen cryptocurrency hardware wallet developed with one sole focus: no compromise on security. Create, manage and initiate transactions with you Ngrave wallet fully offline without the need to expose it to a physical or network connection.
https://www.ngrave.io/
```

- [x] **Card 5: Emflux Motors**
```
Emflux Motors
Mobility, India
Electric superbike changing the landscape of transportation & mobility. India-based venture backed by both crypto and traditional investors with a mission to power 10 million electric bikes in India by 2027.
http://www.emfluxmotors.com/
```

- [x] **Card 6: mySWOOOP**

```
mySWOOOP
Re-Commerce, Germany
Omni-channel re-commerce platform buying and selling new and used electronics. With tailored software technology, mySWOOOP automatically determines current market prices in real-time assuring attractive resale-margins.
https://www.myswooop.de/
```

 - [x] **Card 7: AirProfile**

```
AirProfile
Cleantech, Germany
Based on a new patented technology for detecting precise wind speed, Air Profile boosts the energy transition all over the world. The device simplifies the wind resource assessment for each and every wind farm project worldwide.
https://www.air-profile.com/
```

**Please note:**
All these cards should collapse onto a single column for our mobile breakpoint..
Card design changes will be done as per a separate ticket. Ie. highlighting the success status of the campaigns and how much they raised.

As agreed, the fonts and grid system changes from the design will happen as separate tickets so for now use what we have and match the layout in as close as possible without making grid system and font changes, we'll continue to use Lato for all fonts.

However, please try match the hero heading as close as possible as it's already a custom heading and it's only used on the platform landing page. The font can remain Lato. The font size for this heading should change from `48px` on desktop to `24px` on mobile.

![Screenshot 2019-06-12 at 17.01.08.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/0f9916f2-f284-41a0-b8b2-2bcf763750ed)

---

If you have any please chat to @andywalton.

**Comment by glupiawymowka** [comment]
tested on stage, desktop + android + ios
