### ISSUE TITLE
[ISSUER REGISTER] - wrong redirection on failure 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3107]
**Description**
To register as an issuer, the user needs a special link. However, for browser registration, the user gets redirected to ledger on failure. Also, there is no other way to go back to MM, but pasting the link again. 

**Environment**
all

**Steps To Reproduce**
1. Take the "magic link" for issuer browser register and proceed
2. Don't sign the metamask request, cancel it instead 
3. The modal will inform you of the unsuccessful signing process. Choose to ``GO BACK``

![image](https://user-images.githubusercontent.com/18315589/59443787-d8cb7c00-8dfc-11e9-82d0-f80961419ed5.png)

4. At this point, you land in the ledger issuer register 

![image](https://user-images.githubusercontent.com/18315589/59444820-d407c780-8dfe-11e9-9e73-3d0e7bb08346.png)

**Actual behavior**
Unsuccessful browser login redirects to the Ledger login 

**Expected behavior**
Unsuccessful browser login causes browser login retry 

**Comments, context, logs**

**Screenshots**

**Comment by rudolfix** [comment]
That's because we have default registration wallet type which is ledger - and that happens only in the issuer registration.
prop to solve it:
we drop the default. if you started registration in metamask you go back to metamask etc. there's no way to change wallet type

**Comment by rudolfix** [comment]
@glupiawymowka this one should be gone. if not we need to fix it!

**Comment by glupiawymowka** [comment]
@rudolfix this still happens. I'm getting the "Go back" button on the unsuccessful screen, but then this button leads me to ledger register 
![image](https://user-images.githubusercontent.com/18315589/64697443-26f62700-d4a1-11e9-8c5d-71f5ae513ba7.png)

![image](https://user-images.githubusercontent.com/18315589/64697484-3a08f700-d4a1-11e9-948c-395fa748435a.png)

**Comment by glupiawymowka** [comment]
fixed by new onboarding
