### ISSUE TITLE
unit tests for maskedNumberInput and related forms

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#3134]
**Background**
this is about missing unit test to this pr:
https://github.com/Neufund/platform-frontend/pull/3115
(see comments)

**Designs**

**Acceptance criteria**

**Technical notes**

**Testing notes**

**Comment by Moejoe90** [comment]
How about we think of a couple of scenarios to test? 

As in a clear set of input that every function should be able to handle including `number` `NAN` `undefined` `string` `object` etc with that we don't have to think again and again about what to put in unit tests as edge cases.
