### ISSUE TITLE
[ETO FORMS, ABOUT] - solve the image upload issues 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3146]
## UPDATED with designs via the last comment below.

**Description**
The company images upload that we provide at the moment is a bit below the quality we try to keep. 
What is wrong: 
- ~We're giving dimensions that are not checked or cut, and we don't mention that this is just a suggestion for the best view~ - DONE, we ask for the specific size now 
- we say we support png pictures (and no other type is mentioned), but this is not true. We also support jpg (we don't support gif though, and you can choose gif  file from the list, but it will throw the same error as for the big file)
- we don't accept files bigger than 4MB, and we don't inform about the max upload size, at all 
- we're throwing some very random error when an unaccepted file type/size is being uploaded

dimensions are just a suggestion so present it like that
png is just one of the accepted types
no info on max image size to upload
error label! wtf is this

copy: for the suggestion, error label (4mb now!), 
**Environment**
all 

**Steps To Reproduce**
1. login with ISSUER_PREVIEW or QA_KYC'd
2. go to `About` form
3. Check the given parameters
4. Upload an image of >4MB
5. Upload jpg image

**Actual behavior**
- jpg file is accepted
- random error is thrown for a bigger file 

**Expected behavior**
- [x] all accepted file types are listed correctly
- [x] given dimensions are being checked (done, it shouldn't be affected by this fix)
- [x] the error bar shows only when the file of >4MB is being uploaded
- [x] there is a new copy from @andywalton or @Louisswryan provided for the error mentioned above

**Comments, context, logs**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/61ed88e0-83fd-46c5-9083-7bd2d0ff2602)

**Comment by Louisswryan** [comment]
Below is a new design for this update.

https://zpl.io/VK6NdEq

The component to use is our alerts/info alert (below)

https://neufund.github.io/platform-frontend/?selectedKind=Alerts&selectedStory=InfoAlert&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**ADD NEW COMPONENT

**Comment by Louisswryan** [comment]
:DRAFT:

Hello,

We have a component with all states for the image uploader.

The component states are laid out below.
https://zpl.io/V0p7dJQ

Note, the transition from 'Delete Hover' to 'Delete Active' is animated.

Here is how the component will appear in context.
https://zpl.io/Vxr7M8k

**Comment by Moejoe90** [comment]
We will need to update the ticket with new specifications and requirements. 
In addition to this design change we will need to refactor this component so that it can connect with our forms. 

We need this in order to make the valiations as light as possible. 

The component can still upload normally but what we miss is the information of what this component has.

**Comment by glupiawymowka** [comment]
tested on stage
