### ISSUE TITLE
The big navigation change - side navbar to top navbar

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3152]
### Background

We are moving the platform’s navigation from the left hand side to a top navbar position. This change is to done for a few reasons:

1. To better align with the website experience and recent design changes;
2. To fix the layout issues we’re experiencing on very wide screens when the main content space fills the entire available space to the right of the navbar.

This change is the start of more visual changes and it will require some attention to detail. Please ask Andy if you have any questions any time.

### Design 

The designs can be found on Zeplin where you'll see sizing, padding and colours for desktop, tablet and mobile screens. View this here: https://zpl.io/boMXPlv

SVG icons can be found here:
[Top navbar.zip](https://github.com/Neufund/platform-frontend/files/3318624/Top.navbar.zip)
 
The designs will look as follows:

**Desktop (logged in)**
![Desktop 1440px](https://user-images.githubusercontent.com/609657/59982071-05f20880-960d-11e9-8233-4e9bcab657ca.png)
__Note the dropdown menu for My Account.__

**Desktop (logged out)**
![Desktop 1440px --logged out user](https://user-images.githubusercontent.com/609657/59982074-0b4f5300-960d-11e9-8251-0bee163f82ee.png)

**Tablet (logged in)**
![Tablet 768px](https://user-images.githubusercontent.com/609657/59982080-199d6f00-960d-11e9-93a3-9f6af9243f57.png)

**Tablet (logged out)**
![Tablet 768px  --logged out user](https://user-images.githubusercontent.com/609657/59982084-2ae67b80-960d-11e9-9c79-4d724b35ebae.png)

**Mobile (logged in)**
![Hamburger closed](https://user-images.githubusercontent.com/609657/59982099-4cdffe00-960d-11e9-9d9c-8db813e68176.png)
![Hamburger open](https://user-images.githubusercontent.com/609657/59982098-4c476780-960d-11e9-9822-1895b8cd6bf1.png)
_Mobile hamburger menu is open_

**Mobile (logged out)** 
Note, no hamburger menu is required for logged out users on mobile. We also reduce the logo to simple be the “N” brand icon.

Things to note regarding the designs:

1. The navigation is mostly dropping the usage of icons with the exception of My Account. Note the font colours and the active / hover indicator that is a bottom border of 4 pixels.
2. My Account has a dropdown menu
3. The pending transactions icon has changing to a bell notification icon with a notification dot.
4. When the desktop is larger than 1200 pixels we maximise the width of the main site container to 1140px. ie. `max-width: 1140px; width: 100%;` The existing component `Content-module__content` will most likely need to change for this.
5. The margin below the main header and between the platform content. It’s 32px on desktop and is reduced down to 20 pixels on tablet down to mobile.
6. The site background colour needs to change to: `#F3F5F7;`
7. We are introducing new fonts to the site soon. The navigation and footer are a good start for this. These components will change to use Roboto Regular (400) and Medium (500) weights. You can grab a copy here: https://fonts.google.com/specimen/Roboto?selection.family=Roboto:400,400i,500,500i,700,700i

### Acceptance & Testing

- [x] The side nav has been retired and replaced by a top navigation that looks as per the designs
- [x] This top navbar is responsive and it’s styling changes as you change the screen size from desktop to tablet to mobile
- [x] The My Account has a dropdown menu on Desktop and Tablet but not on Mobile. Mobile has a hamburger menu.
- [x] The mobile navbar comes is required from the breakpoint 540px and smaller - no My Account dropdown. It shows the hamburger menu and navigation
- [x] The site main content area is fixed to a maximum width of `1140px` when desktop screens when the size is `1200px` or greater. This content should be centered in the browser - ie. `margin: 32px auto;`.
- [x] The site should have a background colour of `#F3F5F7;`
- [x] The navbar is `80px` tall on desktop, and `64px` tall on tablet and mobile.
- [x] The navbar is fixed to the top as the user scrolls vertically. Therefore the body of the app should take into account padding at the top to allow for this.
- [x] The navigation and footer should use the font Roboto.
- [x] The navigation handles both a logged in (authenticated) and logged out (non-authenticated) states.

**Comment by glupiawymowka** [comment]
*tested on codechecks with: 
- desktop view on chrome
- mobile view on android and ios safari
- issuer view (comments to be discussed)
- notifications (comments to be discussed, no success state by design(?))

still to be tested after merge: 
- issuer register with magic link (is the navbar gone?)*

**Comment by glupiawymowka** [comment]
issuer login works correctly (as much as it could for now). 
Mobile landing page tested no stage
Mobile dashboard **NOT** tested on stage as mobile login/register bug is a blocker. 
Web tested on stage
