### ISSUE TITLE
[ETO Page] - fix critical issue on claims when ETO link was used 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3154]
**Description**
If the user goes to ETO page straight from the link, not from the dashboard, claiming and refund throw a critical error. 

**Environment**
.io and who knows what more 

**Steps To Reproduce**
1. login as an investor with claim option (INV_ICBM_ETH_M_HAS_KYC_DUP_HAS_NEURO for example) 
2. From the dashboard, go to the ETO with claims (ISSUER_CLAIMS Ltd.)
3. Copy the URL and go back to dashboard 
4. Paste the URL (may be in a separate tab) 
5. Try to claim tokens 

**Actual behavior**
Critical error

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/39824fcc-cd7c-48fb-8107-819197a8d54d)

**Expected behavior**
Successful claims/refunds 

**Comments, context, logs**

**Screenshots**

**Comment by desfero** [comment]
@glupiawymowka this was probably done by @drakkein with refund?

**Comment by glupiawymowka** [comment]
tested on .io (no fixture on stage)
