### ISSUE TITLE
[ETO Page] - pitch & youtube video(s!) saga

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3156]
**Background**
We received feedback from our customers, that pitch deck is not really visible on the ETO page, while it's just one of the media tabs, next to the youtube video. 
What is more, some of the issuers would love to have the availability of adding more videos than just one. 

NOW: 
![image](https://user-images.githubusercontent.com/18315589/60176350-5092a100-9816-11e9-8df8-80d1b8fee22e.png)

We struggled already with some crazy empty areas on the page when all the media is uploaded vs some of them is missing. We could combine this all together and have a nice, proper column separation here and solve all of the issues at once :) yay  

**Designs**

**Acceptance criteria**
- [ ] pitch deck is not hidden in a tab, but visible as a separate modal *(like a twitter feed, videos and so on)*
- [ ] empty spaces issue is solved, also for shrunk and large screens *(it might be by columns, but any other idea could also work here)*

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/b07ef2ed-591b-4662-a929-a37c982148e7)

- [ ] multiple youtube videos upload is available (*this will probably develop into the separate ticket as an additional field would be needed in forms, but let's not split the ideas before we think about them as a whole)*

- [ ] there is a proper design solution to present multiple videos on the ETO Page *(on unroll?)*

**Technical notes**

**Testing notes**
Try to save, delete, save, change browser window screen and devices while: 
- [ ]  adding video without pitch deck 
- [ ] adding pitch deck without video 
- [ ] adding both video and pitch deck
- [ ] as above, but with multiple videos 
- [ ] adding only media data and obligatory fields for publishing
- [ ] adding all the forms content, without media
- [ ] visual check of different modals reaction, combined with media area 
- [ ] page reaction when multiple videos are played at once (is it somehow blocked?)

**Comment by andywalton** [comment]
This ticket has become obsolete due to #3206 Visual fixes to the listing page.
