### ISSUE TITLE
Create landing page for user message topic unsubscribe link

### ISSUE THREAD

**Issue by banciur** [Neufund/platform-frontend#3159]
We attach unsubscribe link to marketing user messages. It should lead to landing page where user can confirm his decision. Confirmation will be done by visiting (XHR request) to link provided in query string. 

example link: `https://platform.neufund.org/unsubscription/{email}?confirmation_url={confirmation_url}`

`email` is user email that will be unsubscribed
`confirmation_url` contains link that performs actual unsubscription

Please note that there is backend issue - https://github.com/neufund/platform-frontend/issues/3160
To provide string template that will contan url of this landing page.

---

**Designs**
Please see the screen designs links with code handover via Abstract's Inspect.

Note we've agreed on the following user flow:
1. User receives and email and clicks on the unsubscribe link
2. They are taken to a confirmation page where then are asked to confirm they want to unsubscribe
3. The success page highlights that the user has successfully unsubscribed and shows a link back to our website.

The assumption is that this never fails - if it point 2. fails we should show an error message asking them to retry. We can use our default warning alert for this. (This is most likely an edge case right :) )

The designs can be viewed and inspected here:

![1  Confirm unsubscribe](https://user-images.githubusercontent.com/609657/62286250-9e26ad00-b457-11e9-9b2e-83dcf4ee95db.png)

-> Confirm page design here: https://share.goabstract.com/c21b21b8-056a-447b-b9ea-6a1274d9489a?mode=build&sha=58c7c6169445334be9f5a8adf08cdbe0bd9a7c61

![2  Unsubscribe success](https://user-images.githubusercontent.com/609657/62286575-518fa180-b458-11e9-9d9a-735a730a736a.png)
-> Success page design here: https://share.goabstract.com/d1299e06-b6f4-4813-90c1-64a7cdf151e8?mode=build&sha=58c7c6169445334be9f5a8adf08cdbe0bd9a7c61

---

**Acceptance**
- [ ] A user can unsubscribe following the designs and process above.

**Comment by banciur** [comment]
@andywalton please note that description has changed. As now we have just one unsubscribe action variables regarding topics are removed so no `topic` parameter nor `invalid_topic` state

**Comment by banciur** [comment]
Renamed `forged` to `invalid` as it's less scary name

**Comment by banciur** [comment]
@andywalton @pstroinski  Changed description of ticket to match new flow

**Comment by andywalton** [comment]
@banciur @pstroinski -> I added the designs to the ticket. Please take a look and shout if you need anything more.

**Comment by pstroinski** [comment]
Page must be on an unprotected part of the platform (no login needed)
