### ISSUE TITLE
show ISHA download link in public profile selectively

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3169]
**Background**
Due to https://github.com/Neufund/platform-frontend/pull/3163 which allows issuer to bring their own ISHA, the moment it is available to display is delayed. Still we can provide all relevant information to investors by displaying termsheet when ISHA is not available.

**Designs**
![image](https://user-images.githubusercontent.com/17202864/60508083-ed978300-9cc9-11e9-9862-8b181a8d3284.png)

**Acceptance criteria**
* [ ] when signed ISHA is available in `documents` collection then link to it, if not
* [ ] when ISHA template is available in `templates` collection then link to it (that's what we have right now), if not
* [x] when signed termsheet is available in `documents` then link to it
* [ ] we use relevant titles and always provide downloads as pdfs

**Testing notes**
* termsheet is available in listed state
* ISHA is available in prospectus approved state
* signed ISHA is available in claims and payout on chain states

**Comment by glupiawymowka** [comment]
1. Why is this a "template" for an ETO in refund state? Actually, in all the steps starting from "prospectus approved" till "claims" 
Do we show a document named "template" to the investors? 

![image](https://user-images.githubusercontent.com/18315589/61297643-ee0d3f00-a7dc-11e9-9bbf-e9ca31fbb6f6.png)

2. There's a disappearing table divider (again) - try to shrink and enlarge the page to see
![image](https://user-images.githubusercontent.com/18315589/61297848-66740000-a7dd-11e9-8f8a-a1ea0ddc4f6d.png)


What is correct: 
- [x] for a company in whitelisting state, not isha, but the term sheet is available 
- [x] SIGNED ISHA (not a template) is visible only for ETO in CLAIM and PAYOUT state

The flow looks ok, but @rudolfix  needs to explain the steps to me as I don't want to mark as ready to deploy something I do not fully understand

**Comment by rudolfix** [comment]
Termsheet and ISHA are typical investment documents. You start with termsheet and when investmend is closed, investors sign new SHA with the company. In our case we have following steps

Signed Termsheet gets replaced with ISHA template that gets signed and then it gets replaced by Signed ISHA

the template part is essential for investors that are able to preview what Nominee will sign with Issuer and what are they rights. It's much more detailed than Termsheet and is actual document on which investmen is made

In refund state there's no Signed ISHA obviously as investment didn't happen. There's just template that never got signed. Other question is naming. You can propose alternatives @glupiawymowka

**Comment by rudolfix** [comment]
btw. ticket got merged and is on production now, it seems to me!
