### ISSUE TITLE
[ETO cards] - add the company tagline to the cards in marketing "coming soon" state 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3172]
**Description**

We don't ask for the minimum investor quote length. This quote is present on the ETO card in coming soon state though. 
To avoid empty ETO cards in this case, we could add company tagline on the card

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/6eba9dc7-83bb-47f7-a053-c33cde27ad53)

**Challenges**
for the longer investor quotes, we might have an opposite situation where there's not enough space for the tagline. Thus, this ticket should go to the design team first 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/53c85a0d-6ac1-4254-b502-b9d0290e2a8f)

**Comment by pstroinski** [comment]
To be moved to Asana and managed by product
