### ISSUE TITLE
[documents download] - solve the multiple downloads issue 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3173]
**Description**
We do block multiple downloads of a single file before the first download is completed, but only for Claim flow. 
In this case, we deactivate the download button and show a waiting cursor: 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/cda0db00-13d0-4e21-bcd2-a7643480c0df)

We should implement a similar solution for all the downloads as some files are big and the user tends to click on download multiple times 
**Environment**
all

**Steps To Reproduce**
To see the implementation we already have for the Claim  flow: 
1. Login with INV_ICBM_ETH_M_HAS_KYC_DUP on .io
2. Go to "claim token" in portfolio 
3. Click on document download icons

To see how it works for other sections, go to any ETO page and click multiple times on any of the Legal Documents

**Actual behavior**
Nothing suggests the user that a file is waiting to be downloaded
Multiple downloads are very easy to get accidentally
 
**Expected behavior**

- [ ] The user is stopped from downloading the same document multiple times in a row by deactivating the download link until the first action ends

- [ ] the solution is implemented for all the downloads

- [ ] (optional), there is a pending download/waiting cursor icon
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/4a356f63-4aa0-43c6-8287-ac47b93a8674)

**Comments, context, logs**

**Screenshots**

**Comment by pstroinski** [comment]
To be moved to Asana
