### ISSUE TITLE
[ETO progress bar] - fix the case when soft and hard cap overlap

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3174]
**Description**
When soft cap and hard cap are too close, the labels simply overlap

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/d9ae6257-8b2e-4a85-ad67-ef5ae545d0e3)
**Environment**
all
This affects also the ETO progress bars in portfolio
**Expected behavior**
even if soft and hard cap are (almost) the same amounts, the labels should be readable

**Design**

**Comment by andywalton** [comment]
Some solution options.

**Option 1: Recommended solution**
Only show the soft cap.
<img width="425" alt="Screenshot 2019-07-08 22 41 53" src="https://user-images.githubusercontent.com/609657/60841413-0fb16980-a1d2-11e9-9ee0-c5185b67c162.png">

**Option 2:**
Show both soft and hard caps labels. BUT never let the two overlap by giving the hard cap a fixed distance that preceeds the soft cap indicator line (green bar) and it's label which should be right aligned and never go past this soft cap indicator line.
<img width="398" alt="Screenshot 2019-07-08 22 45 09" src="https://user-images.githubusercontent.com/609657/60841608-83ec0d00-a1d2-11e9-8dbe-fdb942f6b642.png">

**Option 3:**
Show the the hard cap label above the soft cap. (or vice versa)

This doesn't work in my opinion and it's a bit confusing.

<img width="417" alt="Screenshot 2019-07-08 22 44 04" src="https://user-images.githubusercontent.com/609657/60841651-9c5c2780-a1d2-11e9-95d4-ce6d682819d9.png">

---

### Recommendation

My recommendation = option 1. It's not necessary to show the hard cap. If we do, we should highlight it on the graph and then better display what the soft and hard caps amounts are.

If that is the case, I'd suggest we add something like the below to the graph to add additional meaning to the graph data being presented.

<img width="247" alt="Screenshot 2019-07-08 22 50 50" src="https://user-images.githubusercontent.com/609657/60841751-dcbba580-a1d2-11e9-9a40-aa68907074c6.png">

**Comment by pstroinski** [comment]
Let's do option 1

**Comment by glupiawymowka** [comment]
tested on stage
