### ISSUE TITLE
[TOPNAV] - feature improvements - please don't close yet 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3185]
This new top navigation bar is awesome! And still needs some improvements

**1. Notifications**
the current notifications are designed only to show a pending transaction. 
We had the logics of multiple statuses in notifications, so we simply want it back + the new icons 

No pending transactions - we already do have a message to show on hover, let's keep it) 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/0a5fb145-65e3-4f4e-9e85-04b8ab5bfa3f)

Pending transaction - we already do have a message to show on hover. 
If the transaction pending is external (for example, done in Metamask), we do have a separate summary. If there is no `on-hover message` for external transaction, the regular one + "external" will do
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/7e1f0394-4f5c-4950-8a62-3cd35e805eb7)

Error + message on hover 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/85471d73-ac2c-4421-a040-b5bf50cc4c6f)

Success +message on hover 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/04363e7c-79dd-4196-9a9b-72adb6961b84)

The logic should be as before the changes, so : 
- [x] pending transaction status changes into error or success, but never disappears completely 
- [x] error or success notification changes into "no pending transactions" when the user: 
- has the transaction summary open and follows the whole flow as it happens
- already clicked on the notification icon and saw the summary of error/success 

**2. Buttons positioned unevenly**

- [x] in the navbar (mind the spacing between  Dashboard & Portfolio, then between Portfolio & Wallet) 

![image](https://user-images.githubusercontent.com/18315589/60971519-a55d0e00-a324-11e9-835a-affc820153be.png)

- [ ] for tablets
Play with the screen resolutions <1000 x 400 to see it clearly  

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/296a5b70-8889-4fb1-b719-9600d121e166)

**3. Wrong step triggered from ETO Page**

When an inactive user takes the following journey: 
Landing Page => company ETO Page => ``Login`` OR ``Get Started``
They're being forwarded to the Landing Page first.
 Login or Register page appears only on the second click (so, if the user already is on the landing page) 

So the journey actually is the following: 
Landing Page => ETO Page => ``Login`` OR ``Get Started`` = > Landing Page => ``Login`` OR ``Get Started`` => Login OR Register page

Should be:
``Login`` OR ``Get Started`` always triggers the opening of the right page 

**4. ETO Banner is wider than other page elements**
@andywalton I'm not sure how/if we solve it, please advise

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/24b229e4-5736-49a8-8caa-14f1b2cefdaf)

**5. In the issuer flow, when modals are still loading, the page looks like come CSS is broken/missing**
This point would need a design/discussion so I'm just posting it here as a note 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/b8473f56-e55c-435b-8782-652a6d308a07)

**Comment by andywalton** [comment]
@AlexeyTuboltsev adding these icons here as well.

[Transaction Progress Icons.zip](https://github.com/Neufund/platform-frontend/files/3377338/Transaction.Progress.Icons.zip)

I'll look into point 4 - this might be something we don't fix this time round as we're planning some improvements too this page but I'll see about a quick fix solution for this.

For point 5. I'd suggest not showing any content in the gray area whilst the page is loading. Ie. hide the Hi! You can start now! etc...

**Comment by andywalton** [comment]
**Regarding point 4) above**

This should look as follows:

Please restrict the width of the jurisdiction banner and the image below it to `1140px` max-width.

Also, add a box shadow that matches the other container box shadows on this page around both these two elements. ie. it would probably be best to wrap the juridiction notification and the banner below it in a container element and apply the styling to that.

The current box shadows are: `box-shadow: 0 2px 4px 0 rgba(0,0,0,.1);`

After this, it should look as follows:
<img width="1552" alt="Screenshot 2019-07-12 15 29 08" src="https://user-images.githubusercontent.com/609657/61131748-51842d80-a4ba-11e9-83e6-7e1a6daa6e8b.png">

**Comment by glupiawymowka** [comment]
1. There is no message on hover for: 
- [ ] Transaction pending state
- [ ] Transaction success state 

@andywalton could you please provide @AlexeyTuboltsev with the copy? 

2.2.  I don't know how to show it better, but the buttons are of different size which makes the left one way closer to the border. It is visible when you shrink the screen in Inspect -> Toggle device toolbar

![image](https://user-images.githubusercontent.com/18315589/61305450-24ea5180-a7eb-11e9-9291-2a4751429f12.png)
![image](https://user-images.githubusercontent.com/18315589/61305549-48ad9780-a7eb-11e9-980c-4988368aac47.png)

3. I will explain the problem in person, but in general the thing is that IF you click LOGIN button on ETO Page, it is not leading to LOGIN, same with Get started

**Comment by glupiawymowka** [comment]
*previous changes tested on stage, but the ticket is still connected to the ongoing fixes*
