### ISSUE TITLE
Platform landing page visual fix

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3190]
Please fix the landing page to the below layout. It's more inline with the original design - see: https://platform.neufund.org/

![Screenshot 2019-07-12 14.48.23.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/0168dd25-e56c-4da5-a3aa-01f53fdd3d73)

The current page on dev `https://platform.neufund..io` has a few problems:

![Screenshot 2019-07-12 14.48.51.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/c12192d1-26d5-4dcc-b6bd-76ee3380ddef)

1) The herospace section is boxed in. The section bg should be `100%` the width of the page and the content inside should be centered and have a maximum width of `1140px`

2) The Investment opportunities sections background colour needs to change to `#f3f5f7`.

After these changes it should look as follows:
![Screenshot 2019-07-12 14.48.30.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/c20f0e7f-9800-4435-ae93-e9b852a472b0)

3) Adjust the spacing between the heading: `Equity investments made better` and the yellow detail line above it. It should be the same as what we have on .org currently.

I looks to be `2rem. (32px)`.

After this change the heading should look as follows:
<img width="640" alt="Screenshot 2019-07-12 15 13 15" src="https://user-images.githubusercontent.com/609657/61130824-e0437b00-a4b7-11e9-9155-3d517b886071.png">

**Comment by glupiawymowka** [comment]
*tested on stage*
