### ISSUE TITLE
Hide content when topnav mobile menu is open

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3201]
**Description**
When the mobile menu is open it's still possible to scroll page content. 
When menu content is longer than viewport it's not possible to pick menu options outside of the visible area (aka scroll is missing)

**Steps To Reproduce**
First bug:
1. Add opacity to menu
2. Try to scroll
3. Content behind the menu is scrolled
![Jul-15-2019 22-37-11](https://user-images.githubusercontent.com/7031578/61247896-42b7a800-a752-11e9-8717-c77d14aa4ed2.gif)

Second bug:
1. Use chrome dev tools response device toolbar
2. Make it ~600px
3. It's not possible to scroll to logout
![Jul-15-2019 22-47-58](https://user-images.githubusercontent.com/7031578/61248177-da1cfb00-a752-11e9-8f9c-feb75e0e24bb.gif)

**Expected behavior**
1. It should not be possible to scroll the page content
2. It should be possible to scroll modal content

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
Bug 2 was fixed and tested on code checks for: 
- iphone (safari) 
- web (chrome) 
- android (firefox) 

Bug 1 still to be fixed

**Comment by glupiawymowka** [comment]
tested on stage
