### ISSUE TITLE
Visual changes for the ETO landing page

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3206]
**Background**
Make visual changes on the ETO landing page. Important from the marketing point of view.

**Designs**
@andywalton could we get clearance on points 3 and 4? How it should feet the site

### Acceptance & Testing

- [x] Separate video and Pitch deck. Make both visible without having to click. First pitch deck, then video
- [x] Separate investors and advisors. Make all visible at first, without forcing the user to click
- [x] "Marketing documents" should be moved to the top of the page and separated from Legal documents. I would suggest to leave legal documents here and move "Marketing documents" underneath the description of the company as "More information" and combine it with a link to their website. Also, move Twitter here, before the Media links
- [x] Link to the company website moved to the part of the company information. For example inside the box that already contains a company description. A current place so not intuitive

**Comment by Moejoe90** [comment]
Based on point ` Separate investors and advisors. Make all visible at first, without forcing the user to click` 
Does this mean we will only separate advisors and investors but still `Key customers` and `Key Alliances `

**Comment by pstroinski** [comment]
Hm... where do you have this part? I don't see it.
Anyway at this point we wanted to separate only Investors and Advisors

**Comment by Moejoe90** [comment]
It needs to be filled out. I can see it in the code you will only see it if it gets filled out. ok so that's what i will do
