### ISSUE TITLE
After confirming a new email the local storage should be updated

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#3216]
**Description**
[this is not confirmed yet, need to test it on .io ]
the local storage (and email) is updated on email confirmation

if the user with light wallet changes their email then logs out and tries to log in again, the cached light wallet login still has the old email. 

**Environment**

**Steps To Reproduce**
create light wallet, confirm email, change email, confirm the new one, log out and go to light wallet login page. There's the old email shown.

**Actual behaviour**
if the user with light wallet changes their email then logs out and tries to log in again, the cached light wallet login still has the old email. 

**Expected behavior**
the local storage (and email) is updated on email confirmation

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
I tried it with the account where I changed the email yesterday. My findings: 
1. **Old** access link worked. And showed the **old** email address on login. *New* address visible in profile.
2. **Old** address cached after logout and re-login
3. *New* access link used. *New* email visible on login
4. **Old** address cached after logout and re-login

Now most important, answering your question, **Old** email cached after email change and re-login.
