### ISSUE TITLE
Event. composedPath is not supported on Edge

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3221]
**Description**
Edge throws an error when someone tries to open the header menu.
See related sentry report https://sentry.neusrv.net/sentry/production/issues/6447/?referrer=slack

**Environment**
production

**Steps To Reproduce**
Open the platform on EDGE
Log in 
Open header menu
An error is thrown from an event handler

**Actual behaviour**
-

**Expected behavior**
-

**Comments, context, logs**

**Screenshots**

**Comment by AlexeyTuboltsev** [comment]
is not worth the effort as edge is migrating to chromium anyway
