### ISSUE TITLE
[ETO Forms] - wrong percentages shown in Allocation of funds

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3228]
**Description**
If the user adds `useOfCapital` points, which won't sum up to 100%, the platform will simply (and randomly) add missing % to the positions. 

**Environment**
all 

**Steps To Reproduce**
1. Login with any fixture of issuer in setup state
2. Add a couple of points and % to the `Allocation of funds` in `Pitch` form 
3. Make sure the total % of all the added positions is not 100%, save
4. Go to the ETO Page and open `Allocation of funds` tab 

**Actual behavior**
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/dfd12a99-635b-4957-ac05-7eecac6ab662)

**Expected behavior**
For this specific graph, the user can't save unless the total is 100%. 
There should be an error message informing about it, like "Please make sure the total percentage is 100%"

**Comments, context, logs**

**Screenshots**

**Comment by AlexeyTuboltsev** [comment]
this is the same issue as #3225. They should be fixed in one ticket

**Comment by AlexeyTuboltsev** [comment]
fixed in #3501

**Comment by glupiawymowka** [comment]
tested on stage
