### ISSUE TITLE
Metamask signer is shown after visiting `login/browser` when already logged in

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3230]
**Description**
Metamask signer is shown after visiting manually `login/browser` when already logged in.

**Environment**
-

**Steps To Reproduce**
1. Log in
2. Visit `/login/browser` url 
3. Metamask message signer appears

**Actual behaviour**
Metamask signer appears 

**Expected behavior**
We should not show any kind of signing request. 

**Comments, context, logs**

**Screenshots**
![Jul-26-2019 13-00-09](https://user-images.githubusercontent.com/7031578/61947392-5a3e2e80-afa5-11e9-9d5a-da9c666c49d1.gif)

**Comment by glupiawymowka** [comment]
another similar case I had is: 
1. There was an open metamask + investor session in one browser window
2. Forgetting about it, I tried to open a new metamask + issuer account by using the secret link.
 The action was done in a new browser window, with just created metamask wallet 
3. The dashboard with my new wallet address opened, but the account was an investor

left: old browser window,      right: new browser window
![image](https://user-images.githubusercontent.com/18315589/62205058-d7471a80-b38e-11e9-91bd-0bf38a503cff.png)

**Comment by glupiawymowka** [comment]
tested on .io

**Comment by glupiawymowka** [comment]
tested & released
