### ISSUE TITLE
widget for uploading ISHA template

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3238]
**Background**
We changed lifecycle of ISHA template. Right now it's needed just before ETO is going on-chain. We've already dropped it from generated documents as per #3169 and there's no place to upload it. It's a blocker for starting ETO.

ISHA template is a word document and we need to use alternative upload endpoint. Endpoint is parsing such document and requiring all the placeholders to match backend expectations. Threre are more error cases than with pdf upload.

**Designs**
* [ ] we need a design for the widget. it's ok to just copy current document upload one (we'll change texting)
* [ ]  we need a slight change in current upload modal start screen as specified below. we should be able to accommodate a title
* [ ] we need some modal state when error in document appears - toaster is not enough

we do not need anything fancy or going beyond what we currently have. this is still a hack.

**Acceptance criteria**
* [ ] show widget to upload ISHA in `prospectus_approved` state
* [ ] widget is a copy of our existing document upload but accepts only docx documents
* [ ] we need a separate copy for start screen below
![image](https://user-images.githubusercontent.com/17202864/62045952-15b1cd80-b207-11e9-80ad-9229cc5f6cc5.png)
that includes
- title
- explanation of what ISHA template is
if that's easier we can apply same scheme to other documents/templates that are uploaded
* [ ] after successful upload ISHA should appear in "Generated Documents" in documents section. You may redirect user to that view and refresh
* [ ] we need an error screen in case we detect problems in word document that is another modal state. a toaster is not enough. for that we need a design. I'm providing you error cases below. We should align on the wording later
* [ ] widget is not visible if ISHA template is already uploaded. re-upload will be solved later (we need to change documents section for that)

**Technical notes**
You have a whole set of new apis for templates that are identical to document ones
- `/etos/me/templates/state_info` - you have a lifecycle of uploadable templates here identical to documents lifecycle. for widget you do not need that but when we add upload to documents then yes
- `/etos/me/templates/{document_type}` - this you already use to resolve placeholders. endpoint got a `POST` method and `DELETE` method so you have parity with document endpoints.
the code we use in python to upload template is
```
    def post_template(self, eto_id: str, file: BinaryIO, document_type: str, validate_only: bool = False) -> Entity:
        """
        Uploads and creates new template entry with "document_types" in "templates" of eto_data
        """
        files = {"file": ("file", file)}
        res = self.client.post(
            TEMPLATE_URL % (eto_id, document_type), files=files, params={
                "validate_only": validate_only
            })
        return cast(Entity, res.json())
```
 - `validate_only` let's you check if document is OK before stroing in IPFS right now ignore it
- see `eto_listing_api` swagger for more details

** error handling**
we have error cases when ISHA does not contain all the required placeholders or contains unknown placeholders.
 - http status is 400
- you'll see typical json error document where
```
assert error["type"] == "exceptions.PlaceholderMismatchException"
        assert error["extra_placeholders"] == []
        assert error["missing_placeholders"] == [missing_placeholder]
```
if type is `exceptions.PlaceholderMismatchException` we should show our error state modal that will say

if there are `extra_placeholders` we should say
"Problems detected in your template"
if there are `missing_placeholders`
"We could not find all relevant information in uploaded word document. Please make sure that you appended On-Chain Investment Appendix to your document. When contacting support please provide following list of missing items: <missing placeholders>"

if there are `extra_placeholders`
"You provided additional information in uploaded word document that we cannot handle. Please make sure that you appended On-Chain Investment Appendix to your document. When contacting support please provide following list of missing items: <extra placeholders>"

**Testing notes**
- There's propsectus approved state in in eto fixtures. use it to do e2e tests
- We have a working ISHA template! just request it from Dialika or @banciur API will not accept documents not conforming to required list of placeholders

**Comment by andywalton** [comment]
Please let me know your thoughts @rudolfix @Vanilizer @pstroinski regarding the below: 

I'd recommend some changes to this ticket as this flow and specification has changed.

From a design point of view I think what's needed is as follows (as far as my understanding of this goes):

**Background**
To make our ETO flow more flexible for our Issuers, we are moving the ISHA (Investor Shareholder Agreement) step to later in the campaign setup. The Issuer has to upload an ISHA before they can start fundraising and will only become required after they have uploaded their Investment Memorandum / Prospectus (depending on the ETO product type they choose).

What we need to do first is redesign the ISHA upload process as this process now only requires the Issuer to upload a pdf document of their ISHA. To assist in the writing of the ISHA we now provide a Cheatsheet document is is autogenerated and populated with the investment term fields an Issuer should use in their ISHA.
 We therefore need to make changes to our Issuer setup flow and our documents section.

**Designs**
We require the follow designs: 
- [ ] We need a design for the widget that is shown on the Dashboard to an Issuer when they are in `prospectus_approved` state. It's ok to just copy the current widget that tells the Issuer to upload documents. We simply need to revise the text to tell the Issuer to visit the Documents section to upload their ISHA ignorer to start fundraising. We might even highlight the fact that we we’ve autogenerated an ISHA cheatsheet for them .
- [ ] On clicking to upload an ISHA, we need to change the current upload modal start screen to include a title, we could also consider highlighting the need for a.
- [ ] We should highlight on the upload screen that they need to upload a PDF and that this PDF should be no larger than 4mb.
- [ ] We should properly validate the document and display any validation errors.
- [ ] On success we should do highlight this.
- [ ] After upload, returning to the documents screen the user will see that their document has been added to the uploaded documents section.
- [ ] We also need to find a way to show the ISHA Cheatsheet document that is available for download.

**Comment by Vanilizer** [comment]
@rudolfix

**Comment by pstroinski** [comment]
To be moved to asana @andywalton @rudolfix
