### ISSUE TITLE
[DESIGN TICKET] new transaction direction types: EXCHANGE and NONE

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3244]
**Background**
We are introducing several new transaction types (specifics in separate ticket later). We have new "direction" cases that needs list item design:
- `EXCHANGE` transaction is where token is swapped for another token. Examples: gas exchange where nEUR is swapped for ETH (to use for gas and yes we have those transactions already in the wild from our ETO) and investment transaction where payment token is swapped for equity token (at least we could represent it like that if we want)
- NONE - where funds/assets were not transferred. example ICBM WALLET UPGRADE

**Designs**
* [ ] list element for EXCHANGE transaction
* [ ] list element for NONE

**Technical notes**
1. EXCHANGE transaction has two tokens and two amounts that are exchanged. we should somehow make it visible in the list
2. NONE transaction has no amount at all and is more like technical operation

**Testing notes**
- wallet upgrade fixture: 0x0020D330ef4De5C07D4271E0A67e8fD67A21D523 (NONE)
- gas exchange transaction: INV_HAS_EUR_HAS_KYC

**Comment by Louisswryan** [comment]
Hey @desfero,

Below are the new tx types. No new components are required but 'Exchange' has different formatting in the Wallet View (also provided).

Exchange:

https://app.zeplin.io/project/5cd04b4bbe9abf68390b8e59/dashboard?seid=5d51723a4d1a189b7e47edca

None:

https://app.zeplin.io/project/5cd04b4bbe9abf68390b8e59/dashboard?seid=5d51724ed376a09c099fd882

Any questions.. Shout out.

Thanks!

**Comment by andywalton** [comment]
Marking this as closed.
