### ISSUE TITLE
changes to Token Holder Rights form

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3250]
**Background**
Company governance is complicated and we set up many parameters that should be configured by issuer to match Nominee (shareholder) rights in ISHA and corresponding token holder rights. We'll also automate several governance processes like voting and company liquidation on exit etc. so we need to have right values in smart contracts.

We need to add several elements to the Token Holder Rights form to let issuer set them up and make them aware that they are important. If that seems complicated to you, it's because it's complicated. Help me find a way to make it less complicated but what surely cannot happen is that we have different terms in smart contracts than in ISHA.

All of those must be in ISHA cheat sheet (coming ;>) and in the ISHA itself.

**Nominee linked to this ETO**
* Nominee > Disabled state

**Voting Rules for Shareholders**
* Does the Nominee have voting rights? > Default, “Yes”. Disabled state.
* General voting duration for shareholders (in days) > No default. Minimum duration is 15 days.
* Restricted voting duration for shareholders (in days) > No default. Minimum duration is 15 days.
* Shareholder voting majority > Default, “More than 50% voting power”. Disabled state.
* Voting results upload deadline (in days) > No default.

**Voting Rights for Token Holders**
* General voting rule for Token Holders > Default, “Nominee votes, “Yes””. Disabled state.
* Tag Along Voting Rule for Token Holders > Default, “Nominee votes, “No””. Disabled state.
* Token Holder voting majority > Default, “More than 50% voting power”. Disabled state.

**Further Shareholder Rights**
* Liquidation preference > No default. Four choices: 0, 1, 1.5 and 2
* Does the Nominee have information rights? Default, “Yes”. Disabled state.
* Does the Nominee have dividend rights? Default, “Yes”. Disabled state.

**Existing company rules**
* Is there an advisory board > No default.
* If “Yes” is selected, display a comment area > “Describe the advisory board structure”
* If “No” is selected, don’t display comment area
* Is there a Drag-Along-Right for shareholders? > Default, “Yes”.
* Is there a Tag-Along-Right for shareholders? > Default, “Yes”.
* Do founders have vesting? > No default

**Designs**
[Zeplin link](https://zpl.io/a7QmZv8)

**Acceptance criteria**
* [ ] components are added and connected to backend fields (they already exist, except advisory board)

**Technical notes**
I will provide mapping when we have understanding how to do this ticket. just FYI: this stuff is already assumed and will be present in the ISHA and all backend fields with values are there.

**Comment by AlexeyTuboltsev** [comment]
as we discussed with @andywalton, nominee selection is now a separate form. Maybe it makes sense to move the nominee stuff to it

**Comment by Vanilizer** [comment]
Regarding Advisory Board, if "YES" please show this instructional text in the input field:
Instructional text:
[If the Company has an advisory board, please insert information about the composition of the board and the role of the board in particular actions that the board is entitled to take (e.g. approvals of corporate actions or decisions)]

Cheatsheet can be viewed here and I think it sheds like on categorization of information:#
https://docs.google.com/document/d/1fUtLaVf6hW3vQdWJRG4Hcn313Rvlrh1vqAKb6fnl0YY/edit?ts=5d4176f9

Also you can always refer to the excel spread sheet tracking all variables we use in legal documents which are also categorized: https://docs.google.com/spreadsheets/u/1/d/1C3ov5UD2rFRHne0H2GcG3aTRojGNbINYuuwg_2dk7zQ/edit#gid=0

Trilbi + Andy and me have a short alignment on this today, please involve in the design process of this form. 

Thanks :)

**Comment by AlexeyTuboltsev** [comment]
***here's the mapping to api how I understood it:***
Nominee voting rights ==> ??? (always yes)
Nominee general information rights ==> has_general_information_rights  (always yes)
Nominee dividend rights ==> has_dividend_rights (always yes)
Token Holders Tag Along Voting Rule ==> tag_along_voting_rule (always Positive)
General Voting Duration ==> general_voting_duration_days (15-60 days, default 10)
Restricted Act Voting Duration ==> restricted_act_voting_duration_days (15 to 60, default 14)
Majority Rule ==> voting_majority_fraction (more than 50% voting power) see questions
On-chain Voting Finalization ==> voting_finalization_duration_days [read only]
Advisory Board ==> ??? (yes/no)
(If yes, advisory board description) see questions
Drag Along Rule/Rights ==> has_drag_along_rights (yes/no)
Tag Along Rule/Rights ==> has_tag_along_rights (yes/no)
Founders under vesting scheme ==> has_founders_vesting (yes/no)
Missing:
1. Nominee voting rights
2. Advisory Board
Questions:
voting_majority_fraction:
1. Is the value read only?
2. What should I show in UI? Is it “more than 50% voting power” or a number of percents (how many then)?
if it’s not read only:
3. Is it a text input?
4. what’s the format -- Is it percentage?
5. Do we allow fractional percents?
6. What is the minimum value (max is 1)?
advisory board description
1.is it a rich text editor?
tokenholders_quorum
1.What is it and is it used in Token Holder Rights form (sounds like it should) ?
approved_nominee_id
nominee
1. What’s the first one and how is it related to the second one? (edited)

**Comment by rudolfix** [comment]
here we go with technical details:
1. "NOMINEE VOTING RIGHTS" - it's always YES. you can hardcode it. backend will prevent with saving any other value (see later)
2. `approved_nominee_id` will be dropped. take nominee from 'nominee` field
3. `General voting duration for shareholders (in days)*` - there will be swagger update that will give you min max and default
4. same for `Restricted voting duration for shareholders (in days)*`
5. `voting_majority_fraction` value is read only and it's a decimal fraction, for example 0.5 is 50%. I will add default to swagger.
6. `Voting results upload deadline (in days)` it's writable value, you will get swagger update with min. max and default
7. `Describe the advisory board structure*` - it's connected to `advisory_board`, It will be added to swagger. not a rich text (it's a part of legal document). if field is not present or empty, advisory board is "No" if user sets it to yes we do not accept empty string
8. pls ignore `tokeholers_quorum` for now

**Comment by Louisswryan** [comment]
Found an existing radio button component to replace the one that is currently being used.

https://neufund.github.io/platform-frontend/?selectedKind=forms%2Ffields%2FFormFieldBoolean%20%26%20FormRadioButton&selectedStory=radio%20button&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Also had a discussion about how to avoid this situation in the future.

The key takeaway is that new components will be handed over separately to feature designs.

**Comment by AlexeyTuboltsev** [comment]
blocked by https://github.com/Neufund/platform-backend/issues/2011

**Comment by glupiawymowka** [comment]
tested on stage
