### ISSUE TITLE
Provacy policy on platform.neufund.org

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#3254]
**Background**
Currently, the Privacy Policy on this page https://platform.neufund.org/ links to an outdated PDF document. It should link to https://neufund.org/privacy-policy.
**Designs**
Just a link
**Acceptance criteria**
Privacy policy on this page https://platform.neufund.org/ links to https://neufund.org/privacy-policy.
**Technical notes**
-
**Testing notes**

**Comment by andywalton** [comment]
Hey Panor, please will you factor this ticket in.

**Comment by pstroinski** [comment]
Duplicate of @3282
