### ISSUE TITLE
Sync ethereum transaction confirmation with backend

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3255]
**Background**
Right now backend waits for `3` new blocks to confirm transaction where frontend just check if a transaction was mined. Because of the above, we have some UX related problems: as an example: Go to a wallet, do withdraw close the modal when it's completed and look at the transaction history, you already successful transaction is not yet there (i will appear only after ~40 seconds).

**Designs**
@Louisswryan @andywalton when we sync implementation with backend then the user will gonna wait longer to see successful transaction modal. @rudolfix suggested that we can try to add an intermediate state between `PENDING` and `SUCCESSFUL` called `WAITING_NETWORK_CONFIRMATION`. But that's up to the product team, maybe we even call leave UI as it is as we have transaction status in the header.

**Acceptance criteria**
- [ ] **Given** I'm on the wallet **when** I withdraw some eth **then**  after tx was successful I can find it in the tx history list.

**Technical notes**
Please put in the env variable how many blocks we should wait before marking the transaction as successful.

**Testing notes**
The easiest way to test this is to do withdraw and see whether it will appear in the tx list right after it was marked as successful. 

@Moejoe90 : edited block confirmation and changed the requirement to follow the backend in terms of block confirmations

**Comment by andywalton** [comment]
My recommendation for this would be to add a "dummy" transaction to the top of the transaction list that shows the pending transaction as it's in progress.



See the third wireframe.
![Transaction history flow@2x](https://user-images.githubusercontent.com/609657/62304166-bd383580-b47d-11e9-97ee-28b42a39ee47.png)

So a user for example sends ETH, while this transaction is busy being finalised, we already showcase this pending transaction via the transaction status icon in the site navbar. So in addition to this, we show this in progress transaction and highlight that it's in progress at the top of the transaction list. When this transaction gets put onchain, we replace it with the real thing and show this instead of the dummy one.

What do you guys think @desfero @Louisswryan @rudolfix?

**Comment by andywalton** [comment]
PS. you can view this in more detail here FYI:

[Transaction pending wireframe](https://whimsical.com/PDg4AWs1mWVUhUe97FvZne)

**Comment by rudolfix** [comment]
I like it! I will move it to design and prepare it for Ready For Dev. also I'm bumping this up - lag on production is pretty significant (long block time)

Some technical details (https://github.com/Neufund/platform-frontend/issues/2821)
- we display dummy as long as it's hash is not in transaction list.
- we cover almost all transaction types in the history. there are edge cases (like nominee is signing agreement) which are not covered. in that case, dummy will be there forever. what about keeping it there for two minutes and if transaction does not come, we hide it?
- IMO we do not need special backend api for that. "dummy" is visible as long as react state is preserved so will disappear after a full page refresh. is that all right?

this will let us to implement it cheaply.

a final question to @andywalton and @desfero : when we should show dummy, we have two choices
1. we show it only when transaction is successfully mined
2. we show it when transaction is PENDING, remove it on REVERT

I would go for option (1)

**Comment by rudolfix** [comment]
here's design proposal from @Louisswryan 
IMO it's kind of cool and more or less what Andy did
Linked below is a wallet view I am playing with that shows how this pending state might appear
https://share.goabstract.com/c1a9c8a8-755c-4130-8475-28c04f2f4b1d?mode=design&sha=61de094af81b5522d69fa512867cb1694cf432a7

**Comment by andywalton** [comment]
I'm going to move this into Design so that we can finalise this for development.

**Comment by andywalton** [comment]
@Louisswryan - let's chat about this on Monday, I have a few points but I think we can quickly get this "Ready for dev". 👍

**Comment by Moejoe90** [comment]
As per discussion with @andywalton . We will also use block hight for our confirmation. 
This means the logic where we assume a transaction is mined should be edited and block hight added

**Comment by DmitriyNoa** [comment]
@Moejoe90 @andywalton Is it possible that there will be several transactions in this state at the same time?
