### ISSUE TITLE
[Issuer] - Investment terms can have negative min max amounts

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3257]
**Description**
Editing the Investment Terms, we managed to create a situation where we have a negative (-) min and max investments amount.

Ooops. 

**Environment**
Chrome, Mac (latest versions/OS)

**Steps To Reproduce**
Login as using a fixture that allows you to act as an Issuer that can enter Investment Terms. Play around with the amounts as per the screengrabs below. 

**Actual behaviour**
Displays negative min max investment amounts. 

**Expected behavior**
Expect the values to validate correctly and warn you that this doesn't look right. You shouldn't be able to raise a negative amount.

**Screenshots**
![Screenshot 2019-08-01 17.27.34.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/5609184f-6925-4032-93b9-ce1cd27f9851)

**Comment by Moejoe90** [comment]
I know that we copied a python implementation from the backend. 
The backend already has unit tests for that and AFAIK we also have unit test. 

Please check if we have all cases covered and all Unit tests are written from our side. 
- [  ] Check if we have all unit tests from the python implementation provided by @rudolfix 
- [  ] If yes all tests should pass 
- [  ] if yes do all forms have correct restrictions `max` `min`

**Comment by glupiawymowka** [comment]
tested on stage
