### ISSUE TITLE
Add `NF_ALLOWED_RTE_IMG_HOSTNAMES` to all environments

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3264]
**Background**
#3253 introduced image support for rich-editor. To restrict image hostname for RTE new env flag was created `NF_ALLOWED_RTE_IMG_HOSTNAMES`. Without the flag set, images are not gonna be shown to the end-user. Please set the env var to the following values:

**.io**
`NF_ALLOWED_RTE_IMG_HOSTNAMES="documents.neufund.io"`

**.net**
`NF_ALLOWED_RTE_IMG_HOSTNAMES="documents.neufund.net"`

**.org**
`NF_ALLOWED_RTE_IMG_HOSTNAMES="documents.neufund.org"`

**Comment by pstroinski** [comment]
@desfero why prd for dev?

**Comment by desfero** [comment]
oh, @pstroinski good catch should be `.io`
