### ISSUE TITLE
Await submitting form until all files where saved correctly

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3269]
**Description**
Currently, it's possible to submit the form when image saving is in progress for e.g. add some image to a rich text editor and then right after click save (some network throttling is needed to catch the issue). If you see what was sent to the backend you can find there empty `img` tag. This issue is not only related to RTE, but the same is also with other fields where user can download a file (for e.g see company information form)

**Environment**
all

**Steps To Reproduce**
as in `Description`

**Actual behaviour**
Image is not saved correctly to the backend 

**Expected behavior**
We should wait until all files were saved to the backend.

**Comments, context, logs**

**Screenshots**

**Comment by pavelneu** [comment]
Tested with throttling:
Rich Text Editor (ckeditor): upload, change, delete image/text,
Single Upload Component: upload/delete image.
The error message "File uploading is in progress" appears for RTE and the component.

The feature is ready to be merged.
