### ISSUE TITLE
Platform Padding in line with 8px rule

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3279]
Hey @desfero ,

We are currently designing spaces on the platform to fit multiples of 8px.

We need to change the padding on the front end to match this. There is a general card padding of 25px, can we please change this to 24px. There is also a less noticeable instance of padding at 15px, this needs to change to 16px. Some examples are below.

![Screenshot 2019-08-07 at 09.51.35.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/f5d30dff-50ce-464c-b228-ca779ce3c55e)

![Screenshot 2019-08-07 at 09.51.53.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/e4bb3588-6be2-480b-8dcb-c83fee5a87b8)

![Screenshot 2019-08-07 at 09.52.18.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/98c4ab39-8497-41d9-822e-6059661da883)

If there are other instances that don't fit this 8px rule please let me know.

Thanks!

**Comment by andywalton** [comment]
Closing this as it's no longer relevant.
