### ISSUE TITLE
Cleanup for #3209 no.2

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#3286]
**Original Ticket**
#3209 

**Link to code Review**
https://github.com/Neufund/platform-frontend/pull/3276/files

**Technical notes**
moving the user state logic to sagas

**Testing notes**

**Comment by glupiawymowka** [comment]
from the PR 

> nominee can register, set up account and link to an issuer (everything that we already had should work ).
 nominee is shown the next step - withdraw money. After nominee redeems money this step is not shown anymore, there's a waiting state instead

**Comment by glupiawymowka** [comment]
part of the redeem ticket that for some reason appeared only on .io
