### ISSUE TITLE
Include an Initiated/Pending/Mining status to Tx history events

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3287]
Currently we have the notification bell that used to be the spinning ethereum to notify the user that an event is being mined but is not yet recorded on the blockchain.

Along with this notification, can we please show the event in the tx history list with the simple indication that it is in a pending state. 

This is something that users will expect from interactions with transactions that take some time to process.

I understand that there is concern that this is not a literal communication of blockchain events but on a product level, this is our platform being as transparent as it can be.

Linked below is a wallet view I am playing with that shows how this pending state might appear
https://share.goabstract.com/c1a9c8a8-755c-4130-8475-28c04f2f4b1d?mode=design&sha=61de094af81b5522d69fa512867cb1694cf432a7

Thanks!

**Comment by rudolfix** [comment]
this is duplicate to #3255 I will merge those tickets and close this one
