### ISSUE TITLE
[ETO Page] - Twitter feed misplaced when Pitch is missing

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3295]
**Description**
If the user won't add any data in Pitch form (not obligatory), the documents section and Pitch is misplaced 

**Environment**
all 

**Steps To Reproduce**
1. Login as a ISSUER_QA_BLANK_HAS_KYC
2. Fill out some forms (especially Media) , but leave the "Pitch" form empty
3. Go to the ETO Page preview

**Actual behavior**
![image](https://user-images.githubusercontent.com/18315589/62851642-14909e00-bce7-11e9-8cd5-2e073efe0f80.png)

**Expected behavior**
- [ ] everything that was designed to stay in the right column is glued there, no matter which form was not filled yet 

**Comments, context, logs**

**Screenshots**

**Comment by AlexeyTuboltsev** [comment]
can't reproduce this...
looks like it has been already fixed

**Comment by andywalton** [comment]
I think this bug isn't that important for now as it's part of a bigger story about improving the company listing page.

For now, this is the correct behaviour, if the Pitch information doesn't exist we don't show that section and then the Media links, Docs, Twitter feed etc. are suppose to move to the left.

We could lay those sections out if that is the case and the screen is wide enough side by side but for now I'm happy that it behaves this way.

This however will be improved in the short term.
