### ISSUE TITLE
[Issuer] State in Listing page in Review

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3302]
**Background**
On the step "Listing page in Review" the state of the ETO should be Orange and "In Review"

**Designs**

**Acceptance criteria**

**Technical notes**
This requires a ticket that adds the param 
isMarketingDataVisibleInPreview 
Into the logic of ETO state which uses `getStateName`

**Testing notes**

**Comment by glupiawymowka** [comment]
tested on stage
