### ISSUE TITLE
[Issuer] Add step - Link Nominee

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3303]
**Background**
After filling all data in the ETO Settings there should be an additional step:
Link Nominee to your ETO

Which presents the information box:
Title: LINK NOMINEE TO YOUR ETO
Body: “In order to link a Nominee to your ETO please give the Nominee the ETH address that you are registered with on this platform. The Nominee will send you a request.”

We should display the ETH address of the Issuer (with copy option)

When Nominee sends an invite this box should change to the:
Please go to Shareholder and Token Holder Rights form and accept your Nominee.
Button: Go to Shareholder and Token Holder Rights Form
Step and box titles stay as above.

**Comment by desfero** [comment]
@pstroinski assigned to @AlexeyTuboltsev, it's probably already done

**Comment by pstroinski** [comment]
It's done from the Nominee side. Needs to be added on the Issuer too (@desfero)

**Comment by glupiawymowka** [comment]
![image](https://user-images.githubusercontent.com/18315589/63926853-dae0c680-ca4c-11e9-985d-a768e0208ca9.png)

![image](https://user-images.githubusercontent.com/18315589/63927558-3cedfb80-ca4e-11e9-80c5-aa772b33c9c2.png)

 is this the correct look @pstroinski? 
Otherwise, the flow looks and works ok

**Comment by pstroinski** [comment]
Yes, first you send request, then after request is sent you need to accept it in the form

**Comment by glupiawymowka** [comment]
tested on stage
