### ISSUE TITLE
[Issuer] YOUR FUNDRAISING CAMPAIGN IS LIVE - whitelisting status

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3305]
**Background**
While being in YOUR FUNDRAISING CAMPAIGN IS LIVE and after enabling whitelisting the status stays in campaign. When whitelisting is enabled it should change to green and set the title to Whitelisting

**Technical notes**
Currently Whitelisting in not connected at all with the state. 
We need to create a substate for the main state listed. That takes into account whitelisting. This is a longer task

**Comment by glupiawymowka** [comment]
tested on stage
