### ISSUE TITLE
[Issuer] Investment terms blocking term sheet box

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3306]
**Description**
If not all fields in the investment terms form are filled (meaning showing 100% filled, even if not obligatory) then the term sheet upload does not appear.

**Expected behavior**
Investment terms form should show 100% filled when all obligatory fields are filled. Currently, 100% is only when all fields are filled (together with no obligatory)

**Comment by glupiawymowka** [comment]
tested on stage
