### ISSUE TITLE
assets are missing in the portfolio

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3307]
**Description**
QTT token which I have balance > 0 and which is visible in PAST INVESTMENTS and in metamask is not visible in MY ASSETS

**Environment**
Found on `io`

**Steps To Reproduce**
Use fixture "INV_HAS_EUR_HAS_KYC" (`0xfA1Af2E251ee739F83e14d7daCfd77B3d0E930b7`)
1. log in
2. go to portfolio

**Actual behaviour**
there's no QTT token in MY ASSETS, but it's in past investments

**Expected behavior**
QTT token visible in MY ASSETS and PAST INVESTMENTS

**Comments, context, logs**
additionally confirm by adding QTT to metamask as custom token (token address ` 0x2d96e2a0f117232debc9ea4e780a4b5c1ee5aa73`)

also note that MY ASSET balance of QTT should be less than PAST INVESTMENT (purchased tokens) due to token transfer
![image](https://user-images.githubusercontent.com/17202864/62884363-9fe55000-bd36-11e9-9181-5b47569120c3.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/17202864/62880481-be931900-bd2d-11e9-9e34-0cb99e1094af.png)

**Comment by desfero** [comment]
@rudolfix this is because we show only assets that reached `payout` state

**Comment by rudolfix** [comment]
so it must be fixed!
