### ISSUE TITLE
recently claimed token not visible in MY ASSETS nor PAST INVESTMENTS until refresh

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3308]
**Description**
After claiming NOMERA TECH token, it is not visible in MY ASSETS, but is visible in PAST INVESTMENTS immediately after claim. You must refresh the page to see NOM in MY ASSETS

**Environment**
On `io`

**Steps To Reproduce**
Use fixture "INV_HAS_EUR_HAS_KYC" (`0xfA1Af2E251ee739F83e14d7daCfd77B3d0E930b7`)
1. log in
2. go to portfolio
3. claim NOMERA TECH
4. wait for SUCCESS
5. click "go to portfolio"

**Actual behaviour**
NOM appears in PAST INVESTMENTS but not in MY ASSETS.

**Expected behavior**
NOM appears in both places

**Technical notes**
Please add/modify e2e tests to cover this edge case

**Comment by glupiawymowka** [comment]
Again, the claimed token is not appearing in "Your assets" instantly. 
This time on **stage** env 

If it's the first token that user claims, only NEU appears, every other token claimed shows up in the correct modal after changing tab/refreshing manually. 

![image](https://user-images.githubusercontent.com/18315589/72794129-c8556c80-3c3b-11ea-97bd-4f0885166e24.png)

**Comment by glupiawymowka** [comment]
As the latest fixes didn't change anything on stage, waiting for the PR #3977 as the last hope

**Comment by Moejoe90** [comment]
@glupiawymowka  Actually please push it back to `Ready for dev` and ping @drakkein

**Comment by Moejoe90** [comment]
@glupiawymowka we need a last check if this is still relevant
