### ISSUE TITLE
[Nominee task 2 of 3] Redeem Share Capital

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3320]
**Background**
When ETO enters Signing phase, capital increase which is always in nEUR goes into Nominee wallet. This is done by smart contract, not by ISSUER!

**Designs**
https://app.zeplin.io/project/5d2b7e0bd1281e565d9d08e4/screen/5d3f01e026e1a00dd4d202e0

also change text to the following
```
Fifth Force GmbH successfully completed it’s fundraising campaign and 10 000.0000 nEUR of share capital has been transferred to your wallet. Please redeem the funds to your bank account and thereafter a wire transfer to your Issuer’s bank account as payment of shares sold during the fundraising campaign. Please contact them for bank details.

Note that you must complete Investment and Shareholder Agreement signing process in XXX days|hours
```
**Acceptance criteria**
* [x] notification contains countdown to signing deadline (which is the time of claim state) in days and hours. please bold it so it's clearly visible
* [x] correct share capital amount is displayed
* [x] redeem dialog is displayed with correct share capital already entered. mind not to enter more than wallet balance. in most cases you will do "transfer all" operation
* [x] widget is shown as per technical notes below

**Technical notes**
- obtain capital increase by calling contributionSummary, second field is the value in nEUR. use it to display and to populate redeem dialog
- when to show widget: (1) eto is in SIGNING state, (2) eto.contract.signedInvestmentAgreementUrl() returns empty string (3) nEUR wallet balance is >= capital increase (mind rounding)

the last one is just a heuristic, assumes that Nomine does not purchase nEUR and does not have any other ETO in parallel

**Testing notes**
* [ ] there's issuer, eto and nominee in SIGNING state in fixtures

**Comment by AlexeyTuboltsev** [comment]
waiting for https://github.com/Neufund/platform-frontend/issues/3237

**Comment by Louisswryan** [comment]
@AlexeyTuboltsev 

This has been updated 
https://zpl.io/VKy6J38

**Comment by glupiawymowka** [comment]
this step did not appear on stage
