### ISSUE TITLE
[Nominee task 3 of 3] Upload and Sign the Investor Shareholder Agreement

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3322]
**Background**
When ETO is in signing phase, issuer uploads ISHA to IPFS and provides hash to smart contract. Now nominee must confirm that ISHA he has has the same hash. On successful confirmation

**Designs**
https://app.zeplin.io/project/5d2b7e0bd1281e565d9d08e4/screen/5d3f0272c987b90d2ea58454

Note must have this text (like redeem note)
```
Note that you must complete Investment and Shareholder Agreement signing process in XXX days|hours
```
**Acceptance criteria**
* [ ] notification has company name properly replaced
* [x] ISHA is uploaded and IPFS hash is correctly calculated
* [x] Ethereum transaction as specified below is executed.
* [ ] notification contains countdown to signing deadline (which is the time of claim state) in days and hours. please bold it so it's clearly visible

**Technical notes**
The task of this step is to prove to ETO smart contract that both parties signed the same investment agreement.

- eto must be in Signing eto smart contracts state
- First issuer uploads signed ISHA and adds ipfs hash via calling companySignsInvestmentAgreement
when
- to show this step, nominee checks if signedInvestmentAgreementUrl() returns anything. we do not show this value to the user! see later
- Nominee and Issuer must share same binary version of signed ISHA - preferably sent by notary
- Nominee "uploads" ISHA. We calculate IPFS hash. this should happen purely on frontend!
https://ethereum.stackexchange.com/questions/44506/ipfs-hash-algorithm
- you compare this with what is in signedInvestmentAgreementUrl() if there's any difference we show an error!
- if no differences you call nomineeConfirmsInvestmentAgreement, if transaction is completed eto will transition to Claim state!

**Testing notes**
we must have unit test for IPFS hash calculation against known document and hash
as with redeem step there's a fixture in Signed state

**Comment by AlexeyTuboltsev** [comment]
waiting for https://github.com/Neufund/platform-frontend/issues/3237

**Comment by glupiawymowka** [comment]
tested on stage (countdown is not done yet)

**Comment by glupiawymowka** [comment]
tested on stage
