### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3323]
Transaction History

PRD:
https://docs.google.com/document/d/1ileQzHNis9RBHmZc6bHE2cF9kj7PCyUXAZEFYXSQpnY/edit

DESIGNS:
https://app.zeplin.io/project/5cd04b4bbe9abf68390b8e59/dashboard?seid=5d51723a4d1a189b7e47edca

**Comment by pstroinski** [comment]
Closing the epic as transaction history is done
