### ISSUE TITLE
Token Transfer Portal from Portfolio

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3325]
Hey @Moejoe90 

Here is a kind of placeholder design to allow for the sending of tokens from the portfolio.

This will change as we include a receive token feature and perhaps a universal transfer wizard 

https://zpl.io/VkeyXW8

We need three things

- Add a send button that opens the transfer wizard for the related equity token

- Change download documents from a link to a button (as this opens a modal)

- Change 'My Assets' to 'Your Assets' (platform consistent)

Let me know if there are any issues around this

Thanks!

**Comment by glupiawymowka** [comment]
tested on stage (buttons are currently still links)
