### ISSUE TITLE
[Nominee refund task] return share capital to ETO in case of failed signing

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3326]
**Background**
In case when issuer and nominee do not sign ISHA in time, ETO is cancelled and investors are refunded. In that case, however, Nominee must return share capital to the ETO contract to allow all investors to claim their funds back. This very small amount typically but must happen.

**Designs**

**Acceptance criteria**
* [ ] step is visible as defined below
* [ ] amount to be returned is displayed correctly
* [ ] nEUR transfer transaction is performed correctly

**Technical notes**
- we display widget in eto refund state
- we display widget if Nominee history does not contain transfer from nominee to ETO with share capital value. special backend call may be needed or getLogs can be used directly against node
- we display widget only if contributionSummary contains share capital > 0

**Testing notes**
We'll need REFUND fixture that failed at signing step! interesting case but not there yet

**Comment by pstroinski** [comment]
To be moved to Asana and product
