### ISSUE TITLE
Review Whitelisting Widget on ETO page

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3338]
Points to Address

- EUR represented with symbol. This is no longer correct

- It is not completely clear that the checkbox toggles the email visability

![Screenshot 2019-08-19 at 14.04.19.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/b2860c38-1b87-46c0-af1f-e2cd8c3b8146)

**Comment by pstroinski** [comment]
To moved to Asana
