### ISSUE TITLE
Documentation to install Neufund platform

### ISSUE THREAD

**Issue by ndaxio** [Neufund/platform-frontend#3344]
Hola Team, 

I have checked out your platform, i am impressed but what you have created so far. We are a canadian company and i am interested to contribute to the overall development of this project. 

Do you currently have any start-up documentation with requirements to get your system up and running quickly in a staging or test environment? 

Thanks

**Comment by pstroinski** [comment]
Hey,

Thank you for reaching out. Currently, we can't share any docs as to run the env you would also need to have our backend.
