### ISSUE TITLE
Issuer submits for marketing listing but we reject it.

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3356]
**Background**
Marketing listing can be rejected, we should handle rejection on the frontend.

Therefore we need to make some changes to our current issuer flow.
In case marketing listing was rejected:
1. Dashboard status should be changed to `<red> Rejected`
2. Dashboard header should be changed to `Listing page rejected` 
3. Step description should be set to:
```
Thank you for submitting your listing page. Unfortunately, we had to reject it since the marketing information you uploaded needs some more work. We will contact you directly to discuss how to improve your listing page.
```

Related slides: https://docs.google.com/presentation/d/1v2gQFfd_gCI1XDgoDPCVFQpjEpqXbzYg-ehOHILHUlQ/edit#slide=id.g51830a132c_4_77
https://docs.google.com/presentation/d/1v2gQFfd_gCI1XDgoDPCVFQpjEpqXbzYg-ehOHILHUlQ/edit#slide=id.g5f03e622ab_0_34

**Designs**
Reuse what we have right now as it's mostly texting changes.

**Acceptance criteria**
- [ ] Given I'm on the issuer dashboard when marketing list was rejected then the text should be changed to the one provided above
**Technical notes**

**Testing notes**

**Comment by rudolfix** [comment]
@andywalton we need to ask Dialka how to carry on this

**Comment by andywalton** [comment]
We're going to handle this using direct communications and not via the platform. I'm going to close this ticket as it's not going to be handled by frontend.
