### ISSUE TITLE
[ETO Page] - company tagline cut if there are too many/too long tags

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3358]
**Description**
We're not limiting the length of manually added tags. This can cause two problems - never-ending tags, and company tagline cut to the screen size. One is rather extreme, the other one we already can see live (despite the short tagline). 

**Environment**
all

**Steps To Reproduce**

1. Visit Greyp ETO and play with the screen size 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/a8c0d96f-f068-4d50-b4fa-265e73aeb350)

2. Login with an issuer fixture in preview state (QA_BLANK_KYC or ISSUER_PREVIEW)
3. Open `About` form and manually add a tagline (don't be shy, add a long one!)
4. Save the form and check ETO Page
**Actual behavior**
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/abd9dbe6-c5d3-402b-b0dc-652f17e80916)
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/474d0d47-323a-40f4-add9-b2bb2ec4c1ac)

**Expected behavior**
Tags are less important than the tagline. They should be of limited size and well scaled to the used tagline. 

**Comments, context, logs**

**Screenshots**

**Comment by andywalton** [comment]
Hello @glupiawymowka 

Here is my solution for the company tagline truncation issue if too long or on smaller screens.

1. Remove the company name and tagline from the banner image section.

_Current_
<img width="1552" alt="Screenshot 2019-08-29 09 37 27" src="https://user-images.githubusercontent.com/609657/63921300-d9120580-ca42-11e9-9dc0-72868e32e29b.png">

_After change - removing the company name and tagline from the banner_
<img width="1552" alt="Screenshot 2019-08-29 09 36 24" src="https://user-images.githubusercontent.com/609657/63921368-f8109780-ca42-11e9-8a98-6d866728b53f.png">


2. Add the company tagline to the section title that has the company description in it.

Make it `<company_name> + " | " + <company_tagline>`

_It will then look as follows:_
<img width="1552" alt="Screenshot 2019-08-29 09 49 59" src="https://user-images.githubusercontent.com/609657/63921492-30b07100-ca43-11e9-8be9-f7291341f4cd.png">

Please also while you are making this change rename the video section title from **Youtube** to **Video**.

So done when:

- [ ] Remove company name + tagline from banner section at the top of the company listing page
- [ ] Add tagline to the section title where we have the company description
- [ ] Copy change - update the video section title from Youtube to **Video** 

Regarding tags that are too long. We will solve this later when we figure out if we want to standardise tags for filtering purposes etc. I'd be happy to put a max. length on tags but not sure exactly what would work best for our customers so we need to research this in more detail. Don't want to hold up this ticket.

Shout if you have any questions.

Thank you.

**Comment by Trilbi** [comment]
This ticket will be merged into https://github.com/Neufund/platform-frontend/issues/3411

**Comment by Trilbi** [comment]
This ticket has been merged to https://github.com/Neufund/platform-frontend/issues/3411
