### ISSUE TITLE
Fixes to the Rich text editor images/image caption

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3359]
**1. Company description input, stage** 

- [ ]  Overlapping toolbars
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/4b0a06cf-3c1f-4af8-84bf-894a11c31fdd)
- [x] image added at the end of the text is disappearing just after it was added 
- [ ]  trying to add more than 1 character at once to the image caption results with replacing the image with regular text.
- [ ]  Deleting a character from text or caption deletes the whole image
- [ ] no character limit is shown, so the text is simply cut after being saved

**All inputs**
- [ ] no character limit for image caption
- [ ] image caption character limit is shared with the general limit for the input

**Comment by desfero** [comment]
@glupiawymowka there is a pr that will fix `image added at the end of the text is disappearing just after it was added`. 
`Overlapping toolbars` bug is reported on the CKEditor bug tracker so let's wait for a fix there and then just update

**Comment by pstroinski** [comment]
Please check if the fix already done on the Rich text editor
