### ISSUE TITLE
Enable EU-SME ETO in Issuer forms

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#3363]
**Background**
Since the EU-SME ETO is now legal live - raise up to 20M - we should enable it in the ETO Terms Form. I remember it is done, just hidden. Please enable it.

**Designs**
not needed.

**Acceptance criteria**
If I can see it in ETO Terms Form and settings work.

**Technical notes**

**Testing notes**

**Comment by pstroinski** [comment]
Duplicate of currently implemented https://github.com/Neufund/platform-frontend/issues/3963
