### ISSUE TITLE
Cover the logic after marketing listing was accepted 

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3369]
**Background**
We need to cover the logic after marketing listing was accepted to be sure state transitions are correct one.

**Blocked by the backend as there is no way to accept marketing listing from test mock API**

**Acceptance criteria**
- [ ] - EtoLinkNomineeStep.spec.e2e checks that after marketing was accepted ETO was moved correctly to `Link Nominee` step
- [ ] - EtoPreviewRegistrationAndSubmit.spec.e2e checks that after marketing was accepted ETO was moved correctly to `Setup Eto` step

**Comment by pstroinski** [comment]
To be moved to QA
