### ISSUE TITLE
Eth Withdraw + Token Transfer Modal Update

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3371]
Hello,

Based on the conversation we had yesterday (Monday 26.08.19), here are designs updated to remove gas from the tx setup.

Setup
https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/dashboard?seid=5d650c26b97b6e156e2d9f99

Confirm
https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/dashboard?seid=5d650c4de0f07c9bf98378ae

Summary
https://app.zeplin.io/project/5d10c5d1bb83d271220e0af7/dashboard?seid=5d650c68efda4b70bb53870c

We also discussed discarding 'transfer all' but I have been told by @Moejoe90 that we are leaving this in now.

This is now a universal tx setup. Both Eth Withdraw and Token Transfer are the same modal so this is reflected in the design.

Currently we have storybook components for the new components here. We are sticking with what we currently have and these new components will be introduced with further tickets.

Ask with questions,

Thanks!

**Comment by rudolfix** [comment]
@Moejoe90 please check it out. I think we can close this ticket - changes were implemented

**Comment by Moejoe90** [comment]
Latest designs were done
