### ISSUE TITLE
After Nominee is linked eto should move to `Upload signed termsheet step`

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3379]
**Description**
After we accept nominee we should allow to upload termsheet (fixed in #3304) and also we need to change the step to `Upload your signed term sheet` which is a part of this ticket

Related slide: https://docs.google.com/presentation/d/1v2gQFfd_gCI1XDgoDPCVFQpjEpqXbzYg-ehOHILHUlQ/edit#slide=id.g5f03e622ab_0_107

**Steps To Reproduce**
Link nominee 
The wrong step is shown on the dashboard (`Setup ETO`)

**Actual behaviour**
`Setup Eto` step is shown

**Expected behavior**
Step should be set to `Upload your signed term sheet` 

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
tested on stage
