### ISSUE TITLE
[Issuer] Add new step: Sign ETO legal agreements

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3395]
**Background**
After Investment memorandum was uploaded we should transition eto dashboard state to `YOUR NOMINEE IS CURRENTLY SIGNING ETO AGREEMENTS`.

State for this step: Your current ETO status is:  <green> Whitelisting/Campaigning
Step text: Your ETO smart contracts are deployed on-chain now. We have notified your Nominee to sign the legal agreements on-chain. Once all agreements you will be able to review all ETO terms, sign legal agreements from your side and set the date and time for the ETO.

**Designs**

**Acceptance criteria**
- [ ] Given I'm logged in as an Issuer When smart contracts were deployed then step should be changed to `YOUR NOMINEE IS CURRENTLY SIGNING ETO AGREEMENTS` with text as above

**Technical notes**

**Testing notes**

**Comment by glupiawymowka** [comment]
tested on stage
