### ISSUE TITLE
Listing view, header improvement - Phase 1

### ISSUE THREAD

**Issue by Trilbi** [Neufund/platform-frontend#3411]
## **Background**
On the ETO listing view, the header on mobile looks broken. A lot of users are opening this view on mobile and this is the first thing they see. This fix would also be applied to the other screens sizes.
This will be implemented in two phases. This ticket is the first phase for a quick fix. The second phase will be more considered and possible to use different assets or layouts.

To see this, visit Greyp's listing and reduce the screen size or view mobile screen sizes in Chrome's Inspect element

---

## **Mobile layout**
The layout we’re aiming for is as per this screenshot (screen on the right)

![Mobile Header Before and After.png](https://images.zenhubusercontent.com/5d6f69a892b6f300012d29ad/38aaf6ce-7ad2-4aba-9641-a8967745ec1c)

---

### **Jurisdiction banner** 
**Mobile ( *@media (max-width: 767.98px)* )**
- [x] Change font size to 12px
- [x] Remove uppercase text-transform so the sentence reads in Sentence case and not uppercase.

**Other screen sizes**
- [x] Font size remains the same
- [x] Remove uppercase text-transform so the sentence reads in Sentence case and not uppercase.

---

### **Banner container height**
**Mobile ( *@media (max-width: 767.98px)* )**
- [x] The container of the banner should be bigger in height. Currently there an attribute, "padding-top: 32%;" on the container - I edited this to be "padding-top: 52%;" so the height of the banner is taller for mobile only

**Other screen sizes**
- [ ] Remains how it currently is in live

---

### **Company logo** 
**Mobile ( *@media (max-width: 767.98px)* )**
- [x] Scale down to 60px instead of 80px
- [x] Position 16px from the left of banner and 16px from the bottom of banner

**Other screen sizes**
- [x] Position the company logo bottom left of the banner so the distance from the bottom of the logo to the bottom of the banner must be the same distance as from the left of the logo to the left of the banner. The spacing differs per media query i.e. if the logo is 32px from the left of the banner, then the distance from the bottom of the logo to the bottom of the banner should also be 32px. Please ask me (Trilbi), if this needs more clarity :) 

---

### **Company title (in the banner)** 
- [x] Vertically centre the company title to the company logo for all screen size

---

### **Company tag line** 
- [x] For all screen sizes, remove the company tagline from the banner and add it to the section title that has the company description in it. Make it `<company_brand_name> + " - " + <company_tagline>`.
_It will then look as follows:_
<img width="1552" alt="Screenshot 2019-08-29 09 49 59" src="https://user-images.githubusercontent.com/609657/63921492-30b07100-ca43-11e9-8be9-f7291341f4cd.png">

---

### **Status** 
- [x] Remove the word, "Status" for all screen sizes

---

### **Company title (beneath the status)** 
- [x] Remove this company title for all screen sizes. Only the token name should be displayed. 
- [x] The token name should be vertically centred to the token icon

---

### **Tags**
**Screen sizes @media (min-width: 992px)**
- [x] Don't show the tags for this screen size since the company title gets truncated 

---

### **Copy change**
- [x] Update the video section title from *Youtube* to **Video** 

---

**Comment by glupiawymowka** [comment]
please don't skip the QA pipeline unless it's a purely technical ticket. 

tested on stage.
