### ISSUE TITLE
Autogenerated documents need an indication that issuer details have changed.

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3412]
Background:

It is currently possible for our issuer to download an autogenerated document based on the details they have filled out in the issuer flow. It is also possible for the issuer to change the details of their company after downloading and re-uploading their documents. There is currently no indication in the documents section that this document is now invalidated by the change of details. 

Opportunity:

one solution could be, if a change is made that invalidates an autogenerated document that has been reuploaded, we automatically remove the reuploaded document (after a warning to the issuer that this action must be taken and a confirmation). This action forces the user to only have up-to-date documents in their uploaded documents section and could save lots of headache.

Must dos:

At the very least, this solution must make the issuer aware that the content of their legal documents have changed and that what they have uploaded is no longer valid. I think the best solution is to disallow an outdated document as this is surely a mistake on the part of the issuer but they can not wait until their documents are reviewed to discover that they made changes that invalidated their documents without warning.

This is a backend task but I will leave it in design for now to discuss the best way to manage the flow of this operation

**Comment by Trilbi** [comment]
Solved as part of this ticket: https://github.com/Neufund/platform-frontend/issues/3101

**Comment by pstroinski** [comment]
To be moved to asana @andywalton
