### ISSUE TITLE
Update to TS 3.6

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3420]
**Background**
Typescript 3.6 was released a couple of weeks ago and it brings a long-awaited stricter typings for generators. 
It's worth to update as soon as we can because in a lot of places yielded values from generators are typed as `any` (or wrongly typed by a developer). It's especially important as we keep inside `redux-saga` a lot of business logic and as of now, there was no proper way to type generator in a completely type-safe way. Updating typescript to 3.6 may catch potential null pointer errors and typings mismatch so let's do it.

Release notes: https://devblogs.microsoft.com/typescript/announcing-typescript-3-6-beta/

**Comment by Moejoe90** [comment]
Update we need to update to typescript 3.7 :D 
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/
