### ISSUE TITLE
[ THR Form ] - Advisory board "no" setting doesn't save 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3433]
**Description**

If the user fills out the Shareholder and Token Holder Rights form and selects that no `advisory_board` is being used, the whole form but this one field will save. This is quite critical as selecting one of the options is obligatory. Hence this choice is not saved, the ETO can be  blocked from going on-chain. 

**Technical notes**
 - [ ] Please uncomment `TODO` in `will fill and submit voting rights` eto form tests after this get's fixed.

**Environment**
io

**Steps To Reproduce**

1. Use the fixture that can already have the Nominee added (like ISSUER_PREVIEW (Planti))
2. In the backoffice, you can force any Nominee, just copy an already used address and paste it to your ETO 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/e78594e4-dd04-4f99-8d8a-71bd78016de4)
3. Go back to the Shareholder rights form, since you've forced Nominee, you don't have to approve it
4. Fill all the obligatory fields. Remember to set `IS THERE ADVISORY BOARD` to **NO**
5. Save the form
6. Re-open the form and check `advisory board`

**Actual behavior**
If `no advisory board` was selected, the form acts like it was correctly saved. 
All the other inputs save correctly indeed.
But the `advisory board` option stays empty without letting the user know that something went wrong. 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/4e87a219-f3d6-416a-a611-b579e210a497)
**Expected behavior**

**Comments, context, logs**
Network: 
`Request URL: https://platform.neufund.io/api/kyc/individual/document
Request Method: GET
Status Code: 400 
Remote Address: 104.27.189.119:443
Referrer Policy: strict-origin-when-cross-origin
cf-ray: 5142703f0906d10d-TXL
content-length: 2293
content-type: application/json
date: Tue, 10 Sep 2019 15:29:37 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
status: 400
x-xss-protection: 1; mode=block
:authority: platform.neufund.io
:method: GET
:path: /api/kyc/individual/document
:scheme: https
accept: application/json, text/plain
accept-encoding: gzip, deflate, br
accept-language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJzdWIiOiIweDIzOWZEMjk2MzhjOGY0MmUyNjc1ZDg0NDU1YTYzMjE1NzE1MmRmNDYiLCJ1aWQiOiIweDIzOWZEMjk2MzhjOGY0MmUyNjc1ZDg0NDU1YTYzMjE1NzE1MmRmNDYiLCJ1aWRfdHlwZSI6IndhbGxldF9hZGRyZXNzIiwiZXhwIjoxNTY4MTI5ODg4LCJpc3MiOiJuZXVmdW5kIiwiYXVkIjoiZXh0ZXJuYWwiLCJpYXQiOjE1NjgxMjkyODguMzI4NTkwNiwianRpIjoiNDM0MjJkMDYtNTA2ZS00NTdmLWFlZGUtMWUzMmYzMjZhNTJlIiwicGVybWlzc2lvbnMiOnsic2lnbi10b3MiOjE1NjgxMjkzNDh9fQ.AXIP42giVRj8POV7ApTRI9zlAVSH6-1DtugZWDB8C4fIACWGmy_bHcpWhVo9xpNrk78TxF_T36RjaUzohNekg9BaAMKt4Zjclrdfrwh0DJlQvj9nj3Nr-3V74jXCSdCpVo_PQ0Nlk_DsAnS9f9N7er9bHR_sn0npQi2ink9pEh2SEaBL
cache-control: no-cache
content-type: application/json
cookie: __cfduid=d1b1f9be1c09dcaa189e66bf7b44713ef1566555617; _ga=GA1.2.1108816940.1566556092; _gid=GA1.2.1725841405.1568024559; _gat=1
pragma: no-cache
referer: https://platform.neufund.io/dashboard
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
x-nf-authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJzdWIiOiIweDIzOWZEMjk2MzhjOGY0MmUyNjc1ZDg0NDU1YTYzMjE1NzE1MmRmNDYiLCJ1aWQiOiIweDIzOWZEMjk2MzhjOGY0MmUyNjc1ZDg0NDU1YTYzMjE1NzE1MmRmNDYiLCJ1aWRfdHlwZSI6IndhbGxldF9hZGRyZXNzIiwiZXhwIjoxNTY4MTI5ODg4LCJpc3MiOiJuZXVmdW5kIiwiYXVkIjoiZXh0ZXJuYWwiLCJpYXQiOjE1NjgxMjkyODguMzI4NTkwNiwianRpIjoiNDM0MjJkMDYtNTA2ZS00NTdmLWFlZGUtMWUzMmYzMjZhNTJlIiwicGVybWlzc2lvbnMiOnsic2lnbi10b3MiOjE1NjgxMjkzNDh9fQ.AXIP42giVRj8POV7ApTRI9zlAVSH6-1DtugZWDB8C4fIACWGmy_bHcpWhVo9xpNrk78TxF_T36RjaUzohNekg9BaAMKt4Zjclrdfrwh0DJlQvj9nj3Nr-3V74jXCSdCpVo_PQ0Nlk_DsAnS9f9N7er9bHR_sn0npQi2ink9pEh2SEaBL`
**Screenshots**

**Comment by AlexeyTuboltsev** [comment]
Actually this is not a bug. The requirement was to not set any default. That means if 'advisoryBoard' comes undefined from backend I can't really know is it because the user already chose "no" or haven't done any choice yet. In both cases I show it without any preset value, per requirement. 
The network error thatyou show here has nohing to do with it as well. It's just a failing individual kyc request because user has a biz kyc.

**Comment by glupiawymowka** [comment]
this is partly done. the choice saves, but if you want to continue with default "no", it will tell you that it's an obligatory field.

**Comment by glupiawymowka** [comment]
tested on stage
