### ISSUE TITLE
Transaction history amounts aren't visible on screens smaller than 768 pixels in width

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3436]
**Description**
Hello, here's a simple bug.

The transaction history items have an "amount" field that isn't visible on screens smaller than 768 pixels.

You therefore see this:
![Screenshot 2019-09-11 12.20.22.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/412b26f1-9caf-44af-8151-5a5b0ca840ae)

This is a very quick CSS fix.

The problem is that one of the NewTable classes has a min-width set to 200% as follows:
```
.NewTable-module__table___3H9Gm {
    min-width: 200%;
}
```

Changing this back to 100% fixes it. That 200% must've been a type?

**Environment**
Responsive web and mobile

**Steps To Reproduce**
Visit https://platform.neufund.io/wallet and view your Wallet transaction history. Resize the browser so that the screen is less than 768 pixels in width.

You'll see you can no longer see the transaction amounts.

**Actual behaviour**
Transaction history amounts are hidden on small screens.

**Expected behavior**
You can see the transaction amount, floated and visible to the right of the transaction item description.

The entire amount should always be visible.

**Comments, context, logs**
~

**Screenshots**
Before fix:
![Screenshot 2019-09-11 12.20.22.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/06a356c9-92aa-4188-8d7c-56a5a4fdd2c8)

After fix:
![Screenshot 2019-09-11 14.16.47.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/653bfd74-28cf-4027-babf-c8ac88e53542)

![Screenshot 2019-09-11 14.17.32.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/bf90396a-05a3-4a73-87dc-c2efeac0eaea)

**Comment by glupiawymowka** [comment]
tested on stage
