### ISSUE TITLE
[Recurring bug! ETO Timeline] - Weird dates shown on the on-chain etos

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3442]
**Description**

If the whitelisting has started and ETO is on-chain, but no start date is set yet, the timeline is showing weird results. 

We were fixing this already at least 4 times, please, when fixing it this time, make sure that a test is written to prevent this in the future. From what I know, we will never handle an ETO in 1970.

**Environment**
io, stage

**Steps To Reproduce**
Just open the affected ETO and see the timeline:
Bionic on .io https://platform.neufund.io/eto/view/LI/f046b225-1e4f-41b0-aa28-efdf724bb84e
Wonderland or Planti  on stage

**Actual behavior**

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/96f2535c-5f54-4e66-8412-98b0f657c64e)

**Expected behavior**

Only the valid dates provided by the company are shown on the timeline. Otherwise no dates at all.

**Comment by rudolfix** [comment]
do not display dates at all before start date is set in the ETO. this you can get by checking startOfState for WHITELISTING. if it's 0, start date is not set and all start dates for other states are meaningless. there's even selector that returns that

**Comment by glupiawymowka** [comment]
tested on stage
