### ISSUE TITLE
replace shares with share capital 

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#3450]
to do (copied from #3449 ): 
please note that all schemas are updated to implement changes below

## PUBLIC PROFILE **
- [x] 1. add currency code to EXISTING SHARE CAPITAL (like EUR or PLN) take it from company_data.share_capital_currency_code (added to YUP schemas!)
![image](https://user-images.githubusercontent.com/17202864/64873099-b1c55600-d648-11e9-9b87-d72ca440cf1b.png)
![image](https://user-images.githubusercontent.com/17202864/64873114-b853cd80-d648-11e9-83ac-264ce0c4d74b.png)

- [x] 2. same here +
• add curency coe to authorized capital
• below authorized capital add another entry to the table NEW SHARE NOMINAL VALUE: and take it from new_share_nominal_value (added to YUP schema) + currency code. do not use new_share_nominal_value_eur!
• take the data from eto_data, yes currency code element is duplicated (like share capital)
![image](https://user-images.githubusercontent.com/17202864/64873199-dc171380-d648-11e9-8e8c-c04373572d47.png)

## FORMS
**Legal Information Company**
- [x] 3. add SHARE CAPITAL CURRENCY CODE field of type string. it accepts only capital letters and only 3 letter codes (see regex in swagger). default is EUR and provided by backend. field obligatory
put it below AMOUNT OF SHARE CAPITAL
![image](https://user-images.githubusercontent.com/17202864/64873319-141e5680-d649-11e9-9313-f18f9d155bb7.png)

**Investment Terms**
- [x] 4. we change order to
![image](https://user-images.githubusercontent.com/17202864/64873450-665f7780-d649-11e9-93db-86b530c4f1db.png)
add SHARE CAPITAL CURRENCY CODE, field obligatory, works as the one above
NEW SHARE NOMINAL VALUE field which works exactly like the one below but is bound to newShareNominalValue! field obligatory. 
![image](https://user-images.githubusercontent.com/17202864/64873458-6b242b80-d649-11e9-8c6f-15bbfbde904b.png)

NEW SHARE NOMINAL VALUE IN EUR: stays the same. obligatory. additional validation: if EUR is selected as currency must be same as the one above
achtung **take all data from etoData, including currency code**
 
![image](https://user-images.githubusercontent.com/17202864/64873695-f1407200-d649-11e9-9600-8395249aadeb.png)
![image](https://user-images.githubusercontent.com/17202864/64873705-f6052600-d649-11e9-9211-8baa9d6ff5dd.png)

and then the rest of the form
**THR FORM:**
- [ ] 5. we show SHAREHOLDERS VOTING QUORUM which is bound to shareholderVotingQuorum. we show it as percent. see swagger for ranges and default value. field obligatory!
we show it below
![image](https://user-images.githubusercontent.com/17202864/64873852-43819300-d64a-11e9-9c7c-d362d597248f.png)

**Comment by rudolfix** [comment]
SMALL TEXTING CHANGES TO THR FORM

in here:
![image](https://user-images.githubusercontent.com/17202864/64908946-f9f67e00-d705-11e9-912b-a466904a6ae5.png)
change % of voting power -> % of voting quorum

in new field `SHAREHOLDERS VOTING QUORUM`
add text `% of voting power` -> same layout as above

why?
now you can specify required quorum for voting (how many votes out of all possible need to be cast in order for voting to be valid)
and majority rule - % of votest cast with yes in order for voting to pass

**Comment by rudolfix** [comment]
@glupiawymowka some testing notes:
**PUBLIC PROFILE**
please read the ticket to see where changes are expected. in public profile check out this one:
it should have share capital in PLN!
https://platform.neufund.io/eto/view/LI/6ccaaeb6-ceca-49eb-9523-1497ef572273
also check out of all values in investment terms are present (TBA)

check out several other profiles

**ISSUER**
Login as ISSUER_CLAIMS which has six shares token. check out all word documents if the download and if PLN is used as shares capital... 
Login as ISSUER PREVIEW and try out all the forms, see the ticket for new fields

**INVESTOR**
use one of the investors to invest in available ETOs
