### ISSUE TITLE
Use `PATCH` http method for `Shareholder Agreement` form

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3456]
**Background**
While working on #3256 we found that it's not possible to remove `advisoryBoard` throught `PATCH` method. https://github.com/Neufund/platform-backend/issues/2103 ticket was raised to address the issue on the backend side. 

**Designs**

**Acceptance criteria**
- [ ] Given I'm in `Shareholder Agreeement` form When i submit the form Then only values related to this form are saved 

**Technical notes**
If it's done we can remove `options` param from `saveEtoStart` action.

**Testing notes**

**Comment by pstroinski** [comment]
Issuer dashboard to be done in the future
