### ISSUE TITLE
Status colour correction (blue, green, yellow, orange)

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3459]
Please check the ETO status colours on our ETO Cards and Company Listing pages. For example, we have an incorrect colour for the Campaign status which should display a green circle, not a blue one.

![Screenshot 2019-09-16 11.47.03.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/6327cfdd-e990-48c5-ae1a-f53b803d2039)

![Screenshot 2019-09-16 11.47.13.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/30f47fbd-d421-424b-8c6c-783a1b477b81)

Please correct the status colours based on the list below:

![Screenshot 2019-09-16 11.10.39.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/bc51e411-4fb5-466d-9bbf-47eaa13f0f32)

**Done when**
- [x] Status colours match the image above.

**Comment by glupiawymowka** [comment]
tested on stage
