### ISSUE TITLE
Hide Documents

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3470]
@andywalton commented on [Mon Sep 16 2019](https://github.com/Neufund/platform-backend/issues/2107)

Refer to other ticket

---

@andywalton commented on [Mon Sep 16 2019](https://github.com/Neufund/platform-backend/issues/2107#issuecomment-531715490)

@Moejoe90 this one is more important than the status colour ticket please.

**Comment by glupiawymowka** [comment]
tested, released
