### ISSUE TITLE
Quick fix to show the correct Funding Round on ETO card

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3479]
![Screenshot 2019-09-18 13.57.12.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/6dfd87c2-7a32-41e0-bdb4-329954062884)

There is a bug on our ETO Cards, it's displays the **Last Funding Round** where it should show the **Current Funding Round**.

Before we working on a proper fix (which requires API etc.), we'd like to do a temporarily fix by inferring the current funding round by looking at the last and +1's the value by looking at the funding round names in the Last Funding Round enum.

![Screenshot 2019-09-18 13.46.18.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/f6bdb234-ab11-4698-a02b-d93184bde556)
_So for example, if the last funding round is Seed, the next will be Series A._

We have a proper fix for this planned but it requires more change. See ticket #3474 for more context.

**Done when:**
- [ ] The ETO card displays the the current funding round, which is the next round when looking at the last funding round.

**Comment by glupiawymowka** [comment]
tested on stage
