### ISSUE TITLE
Copy change on the platform card, when whitelist slots are filled 

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#3480]
![Image from iOS (1)](https://user-images.githubusercontent.com/48217191/65227883-ba46e200-dac9-11e9-8b1f-a187c437a4f4.jpg)
1. Change "Whitelist closed - limit reached" to "Whitelist closed - all slots filled";
2. Change "[amount] EUR signed up" to "[amount] EUR committed"

**Comment by glupiawymowka** [comment]
tested  & deployed
