### ISSUE TITLE
[ETO cards] Visual layout fix

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3485]
Increase the width of the `.EtoOverviewThumbnail-module__label` to 60% so that labels for the example image above aren't wrapping onto two lines.

For example look at our test ETO below:
![Screenshot 2019-09-19 15.26.40.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/26d492c0-7613-4678-9c31-0ee877f5c12f)

After the CSS width of the class is set at 60% if visually looks better as Company Headquarters for example is on a single line:
![Screenshot 2019-09-19 15.25.39.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/6a096b62-df1b-4133-b15a-427abfc896e8)

**Comment by desfero** [comment]
Fixed in https://github.com/Neufund/platform-frontend/pull/3583

**Comment by glupiawymowka** [comment]
tested on stage
