### ISSUE TITLE
Change Investment to use estimate gas

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3489]
**Background**
Currently Investment flow is using a constant. The constant is very high there is a plan to move to start using stipends so Investment should be migrated to the new flows
**Designs**

**Acceptance criteria**

**Technical notes**

**Testing notes**

**Comment by glupiawymowka** [comment]
waiting for presale on stage

**Comment by glupiawymowka** [comment]
tested on stage
