### ISSUE TITLE
Copy change on the listing page

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#3509]
![image (6issue)](https://user-images.githubusercontent.com/48217191/65423539-9527db80-de09-11e9-9ab8-9ef63f6636d6.png)

When an unregistered user sees the listing page:
1. Change "ETO" to "offering";
2. Change "Register on Neufund and become a verified investor now" to “Register and start building your investment portfolio today!”

**Comment by andywalton** [comment]
Referenced this ticket in PR  #3511

**Comment by glupiawymowka** [comment]
tested and deployed
