### ISSUE TITLE
KYC changes for Accredited US investors

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3519]
**Background**
As part of our this Epic #3518, we need to make the following changes to our KYC process to allow US accredited investors to use our platform.

Changes from an Individual KYC point of view are expected as follows:
1. If user is US, display a dropdown to allow the user to select the `State` they are from
2. Ask the user then to upload their Accredited Investor documentation. If they aren't accredited yet, we will display a URL that will take the user to a page / place where they can find out more about how they can get accredited, or simply to start that process online.
3. For Investors who aren't accredited, then cannot complete KYC until they get accredited and have the relevant documentation in place. We should then display a message asking them to carry and complete KYC once they have this accreditation.

For business investors, we need finalised the process and then design the solution as per above. This will be handed over together.

**Designs**
Frontend development can start, please note some small changes happen, please work closely with @Louisswryan.

Designs are in Zeplin and have been reviewed: https://zpl.io/VD1RzgW

Some copy might changed as @vizmab is working on a support article for this.

@Louisswryan is going to add to the designs so that we can allow US Investors to upload and/or provide a link to their US accreditation documentation.

**Acceptance criteria**
- [x] 0. As a user, I can complete KYC as a US Investor and upload my accreditation documentation.
- [x] 1. US investors that start KYC now will be allowed to carry on, previously we blocked them.
- [x] 2. The one condition however is that they need to be an Accredited US Investor
- [ ] 3. We therefore ask them to upload and/or provide a link to this accreditation documentation should they be accredited, if not we let them know they will need to do this before we can finalise verifying their account. We however let them carry on with KYC either way.
- [x] 4. They then will enter their Current address details. If they enter that they live in the US, we show a new field called States with all the US States displayed in a dropdown.
- [x] 5. The investor would then carry on with the rest of KYC.
- [ ] 6. They’d land on the Profile page and it would show that we’ll verify their identity within 2-3 days. They would also see that they still need to upload their US Accreditation documentation and this should then allow them to do so and manage their expectations as we review the document/s they uploaded for this.
- [ ] 7. Once we’ve verified the investors KYC we can show that is verified. If they still need to upload their US Accreditation documents, we block investing on the platform for them until they do that.
- [ ] 8. We allow the US investor to manage their accreditation - upload/link new accreditation proof documentation. This we can do via a new component we add to the Profile view that shows the status of the US investors accreditation. We need something in backoffice that allows this and we are again going to need final copy for this.

**Technical notes**
Backend work is required. We will add the technical details here before fronted end can start.

**Testing notes**
Same as criteria.

**Comment by Louisswryan** [comment]
The new component for the accreditation documents is below with notes included:
https://zpl.io/V1pMo9Q

**Comment by Louisswryan** [comment]
Hrey @drakkein 

Design for doc uploader reviewed with all states.

This is still slightly different to the img uploader but has been brought more back into line with the existing design.

here -- https://zpl.io/adYpBg1

Cheers

**Comment by glupiawymowka** [comment]
- [ ] accreditation document should be obligatory
- [ ] no uploaded documents = `continue` button disabled
![image](https://user-images.githubusercontent.com/18315589/68132292-ba3a5e80-ff1e-11e9-92ed-58e7f3673653.png)
