### ISSUE TITLE
Conditional disabling of nEUR functionality

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3521]
**Background**
For Accredited US Investors, the nEUR functionality will initially only be supported by 3 US states, namely:

1. Delaware
2. New York
3. California

For the rest of the US states we need to disable this functionality and they will be required to invest using ETH.

Therefore, the task here is to enable this for the 3 states above and disable for all others if the user is an Accredited US investor.

<img width="586" alt="Screenshot 2019-09-24 17 19 55" src="https://user-images.githubusercontent.com/609657/65525811-63d60b00-def0-11e9-9134-097350918305.png">

*Allow this widgets functionality to be disabled*

**Designs**
If a user is not from Delaware, New York and California we need to hide the link bank account functionality from the nEUR widget in the wallet view. We will also display copy to say that unfortunately at this time they cannot use nEUR to invest.

<img width="1552" alt="Screenshot 2019-10-08 00 11 32" src="https://user-images.githubusercontent.com/609657/66748098-9d15f100-ee86-11e9-8699-d5fc6f075ff2.png">

We also need to hide this functionality from the Profile view.

**Acceptance criteria**
- [ ] All nEUR functionality is disabled for US Investors that aren't from the 3 states above.
- [ ] We hide the verified bank account and link bank account cta from the widget for these disabled states.
- [ ] Conversely, users who are from Delaware, New York and California can use nEUR as per usual.
- [ ] We make it easy to add to this list as more US states come onboard (backend).
- [ ] We need to make it clear to users why this has been disabled (need copy for this - please verify the copy)
- [ ] We hide the verified bank account and link bank account cta from the Profile view.

**Technical notes**
We'll require this information from backend.

**Comment by glupiawymowka** [comment]
just a comment here, but how do we solve payouts for the US investors that can't use this functionality? 
We'd need to make sure they only get ETH so they won't take nEUR out of the platform.

**Comment by andywalton** [comment]
@glupiawymowka -> that is a good question and yes, I think we'll have to only allow them to invest in ETH and receive payouts in ETH

**Comment by pstroinski** [comment]
@desfero we need to hide it from all US, also from those 3 states
