### ISSUE TITLE
[demo platform] - blinking incoming payout counter at 00:00:00 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3531]
**Description**
If the user logs in to the demo platform, the countdown keeps blinking at 00:00:00. 
The similar case happened to me once when the counter was at 00:00:00 on .io, but I'm not able to reproduce this one. 

**Environment**
.io, hard to check on other environments 

**Steps To Reproduce**
1. Just login with the demo investor (demo investor 8 was taken for this test, ask @glupiawymowka if you need more details)
2. Check the dashboard 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/aba830e0-37d6-4311-a07a-43df0296b1ca) 

**Actual behavior**
A blinking counter at 00:00:00

**Expected behavior**
- [ ] if the countdown requirements are met, show the correct countdown
- [ ] if there is no incoming payout, or the amount is below the requirements, don't show the countdown
- [ ] if the countdown reaches 00:00:00 and there is some payout that the user can take, show that there is a given amount to payout

**Comment by Moejoe90** [comment]
After Investigation it was found that the `DEMO` ethereum node wasn't refreshing
