### ISSUE TITLE
Profile view broken

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#3539]
**Description**
User reported that they cannot start identity verification.

**Environment**
Production
**Steps To Reproduce**

test Firefox  69.0.1. on Debian 10

**Screenshots**
![profile issue](https://user-images.githubusercontent.com/609657/65758136-d1fd1680-e118-11e9-9c93-10d5f9472b18.png)

**Comment by andywalton** [comment]
This to me looks like a CSS Grid overflow bug. CSS Grid is fully supported in Firefox 69.0.1 and has been for a very long time.

@AlexeyTuboltsev would be the best to check this out as he did the grid layout change.

I'll take a look in FF myself now also.

**Comment by andywalton** [comment]
<img width="1552" alt="Screenshot 2019-09-27 11 16 15" src="https://user-images.githubusercontent.com/609657/65758351-3c15bb80-e119-11e9-9ca8-7dd00154f977.png">

Tested this on .io on a Mac with Firefox 68 and then upgraded to V69.0.1 and still can't replicate.

**Comment by Moejoe90** [comment]
I can't reproduce
