### ISSUE TITLE
UX issues with investment wizard

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3547]
**Background**
There are a few problems with current investment wizard
Serious
- wallet selector is misleading. we have reports that people think that they switch from nEUR to ETH wallet by just writing in the ETH box. this however does not switch the wallet. you will still invest from nEUR wallet just the amount you typed in Ether. and vice-versa. you will invest in ether if you selected Ether wallet, even if you type nEUR value. in that case there will be a penalty for currency conversion in the smart contract

Annoying
- if I invest in pre-sale there's no discount shown on first screen. I want to be sure I have what I was promised
- if I invest from fixed slots, my special deal is not visible!
- when I invest for a second time in pre-sale, the minimum ticket value is token price, but not discounted!

**Comment by andywalton** [comment]
To resolve the serious issue - @Moejoe90 has made changes as per this ticket: https://github.com/Neufund/platform-frontend/issues/3559

The pr #3558 is in review.

**Comment by andywalton** [comment]
#3615 deals with the rest of this ticket.
