### ISSUE TITLE
[WHITELISTING] - add separate widget state for the whitelisted investors  

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3552]
**Background**
We got feedback that people don't really understand what happens when they took part in the whitelisting, but see the general widget state when all slots are filled (the whitelisting is closed). 
We should show the user that they are successfully whitelisted, so they're not worried about their status

**Designs**
Please ping @andywalton if some more specific designs are needed. 
We should keep something similar to the general solution (green text), but with a different copy if the user is whitelisted: 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/804184cb-4125-4229-906e-3f9477ae0ba4)

- [ ] Case 1 : whitelisted, whitelist is full/closed, presale date **not known**
"You're on the whitelist! Presale date will be announced soon."

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/f11bbc6f-7d1d-4dcc-be6d-cb5af4277950)
- [ ] Case 2 : whitelisted, whitelist is full/closed, presale date **known**
"You're on the whitelist!"

**Acceptance criteria**
- [ ] unverified OR not_whitelisted user will still see the "whitelist full/closed" state on the widget
- [ ] whitelisted user, presale date not known,  will see "You're on the whitelist! Presale date will be announced soon." instead "whitelist full/closed" copy
- [ ]  whitelisted user, presale date known,  will see "You're on the whitelist!  instead "whitelist full/closed" copy + the countdown
- [ ] no other part of the widget is affected, just the copy in green

**Technical notes**

**Testing notes**

**Comment by andywalton** [comment]
@Moejoe90 

Here are the states changes for whitelisted investors (and for those who aren't whitelisted) on company listing pages:

1. NON REGISTERED / LOGGED IN INVESTORS - CAMPAIGN DATES HAVEN’T BEEN SET YET 
- [ ] Change 1a to 1b

2. INVESTOR IS LOGGED IN - THEY HAVE NOT SIGNED UP TO THE WHITELIST - PUBLIC SALE DATE ISN’T KNOW YET

- [ ] Add line of text to say `Public sale date will be announced soon.`

3. INVESTOR IS LOGGED IN - THEY HAVE SIGNED UP TO THE WHITELIST - PRESALE DATE ISN’T KNOW YET

- [ ] Change copy as per image. Also add text include the `Presale date will be announced soon.` 

4. INVESTOR IS LOGGED IN - THEY HAVE SIGNED UP TO THE WHITELIST - PRESALE DATE IS SET
- [ ] Show the countdown when the presale date is set

![EtoOverviewStatus - whitelisting state changes](https://user-images.githubusercontent.com/609657/66058566-e5561a80-e53a-11e9-841d-57b2f8963729.png)

Please shout if this doesn't make sense.

**Comment by glupiawymowka** [comment]
tested on stage
