### ISSUE TITLE
non-ICBM wallet shown for ICBM only investor in pre-sale

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3556]
**Description**
When investing in pre-sale only ICBM wallets should be visible for ICBM investors not added to the whitelist. And this works.
However after first investment, all the wallets show up. When I refresh page it goes back to normal

**Environment**
`io`, `stage`

**Steps To Reproduce**
use fixture
0x139Fab72691f03eA1589A847b110096c7cD56e35

on eto:
https://platform.neufund.io/eto/view/DE/b4214209-45c0-4d9b-b1f3-6b22641cf1df

where investor is not on whitelist but has ICBM wallet so he sees presale

1. invest from ICBM ETH balance
2. wait for transaction to be mined, close modal
3. click "invest" from public profile again
4. you see ETH wallet as on the screenshot
5. invest from ETH wallet and transaction reverts!

**Actual behaviour**
ad step 4. ETH wallet should not be visible

**Expected behavior**
ad step 4. just ICBM wallets should be visible
but if investor is on whitelist all wallets are visible!

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a72da804b5806bc2bc52ecc/43caeced-8815-4312-8689-d543697a057f)

**Comment by glupiawymowka** [comment]
no testing account on stage
