### ISSUE TITLE
[Investment flow] Remove investment amount ETH / nEUR confusion

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3559]
**Background**
Our investment flow currently has a confusing investment amount input fields as you can enter ETH and it converts to nEUR and vice versa.

We want to solve this quickly by tying the investment amount field to the wallet currency you select. Ie. if you select to invest from your nEUR wallet, you will only be able to enter nEUR as your investment amount. Similarly, if you select to invest from your ETH wallet, you'll enter your investment value in ETH.

Currently we have this:
<img width="790" alt="Screenshot 2019-10-01 11 26 27" src="https://user-images.githubusercontent.com/609657/65955860-5ddcae80-e449-11e9-9097-3de1dafb6218.png">

We want to fix it as follows:
Invest using **ETH**
<img width="760" alt="Screenshot 2019-10-01 12 50 22" src="https://user-images.githubusercontent.com/609657/65956191-1acf0b00-e44a-11e9-8bd9-c7c22db78a8e.png">

Invest using **nEUR**
<img width="774" alt="Screenshot 2019-10-01 11 32 49" src="https://user-images.githubusercontent.com/609657/65955921-81075e00-e449-11e9-83a1-915138836c14.png">

**Acceptance criteria**
- [x] We only show a single Investment amount input field, this input field accepts the "currency" of the wallet selected.
- [x] The gas fee and total of the investment corresponds correctly based on ETH or nEUR (EUR) investment. No need to convert the gas fee into EUR.

**Comment by rudolfix** [comment]
@andywalton can we add value after currency conversion below amount edit box?
![image](https://user-images.githubusercontent.com/17202864/65960847-ab5f1880-e455-11e9-9e3f-f01bc9dad340.png)

that's really important in case of ETH as base currency is Euro. and people should see how much they invest.

I know that there's some total EUR at the very bottom but IMO it's not enough. what do you think?

**Comment by glupiawymowka** [comment]
waiting for presale on stage
