### ISSUE TITLE
[ETO widget] - widget not reflecting the valid sale states

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3560]
**Description**
There are a few ETO widget behaviors that are wrong currently. 
At least these ~two~ three should be solved ~before the live presale starts~ soon

**Environment**
stage, io 
___
**Steps To Reproduce**
## CASE 1 - new, unverified investor vs ETO with countdown to presale (and whitelist full in this case): 
1. Login as an investor without KYC
2. Open the ETO page and check the widget. The state is right 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/490b3e4f-3046-45ee-836e-d6bb4a28d919)

3. Refresh
4. The widget acts like in the default (undefined) state, showing the quote 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/8cdc6ff8-4d4b-425d-bca4-ff4ec28c444f)

## CASE 2 - whitelisted investor, waiting till the presale starts 
*This will be rather hard to reproduce as you need an ETO with countdown to presale close to 0" 
movie: https://neufund.slack.com/files/U72NAUC6A/FP5R2D9K3/nagranie_z_ekranu_2019-10-14_o_12.27.07.mov
1. Login as a whitelisted investor and observe the countdown.
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/1b7331b7-0ff3-453b-a2d8-dea16054fd18)

2. Once it reaches 00:00:00, the correct state informing the block is being mined shows up for a brief moment

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/3dc25fc1-0c44-46c3-9199-ef8dd39fd49f)

3. Next, the incorrect "whitelist closed, presale date will be announced soon" state shows up and stays so till the investment state loads

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/89edf9a9-08ed-4aee-b8b0-efc427445638)

## CASE 3 - for slower networks, the countdown to public sale shows up before the presale investment modal loads 

movie: https://neufund.slack.com/files/UCL07JCH0/FPFSXNUTG/oct-15-2019_12-56-25.gif
1. login as a whitelisted investor
2. go to an eto with active presale
3. set your network throttling to 150ms min
4. refresh the whole page
___
**Actual behavior**
widget not reflecting the valid ETO state 

**Expected behavior**
- [x] widget reflects the valid state, also after refresh 
- [x] the "waiting for block" state is shown once the investment state is loading 
- [ ] no "inbetween" states are shown between the block mining and investment modal

**Comments, context, logs**

**Screenshots**

**Comment by AlexeyTuboltsev** [comment]
the last point is really hard to fix. The reason for it is that the app determines if the user is whitelisted or not by getting the user's pledge which is a separate api call. Before that it just shows the ui for the not whitelisted investor. Reordering our sagas to get the api calls in a particular order for this edge case looks kinda risky to me, I suggest to leave it as is for now
