### ISSUE TITLE
Change wording in document sections of nominee, issuer and listing page

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3565]
Please change the following:
- "Preview of Investment and Shareholder Agreement" to "Investment and Shareholder Agreement" in the document section & listing page (ETO terms / legal documents section)
After the ETO we should display "Signed Investment and Shareholder Agreement" in the document section & listing page (ETO terms / legal documents section)

**Comment by glupiawymowka** [comment]
tested on stage
