### ISSUE TITLE
ETO card should make the Whitelist status (closed) more visible

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3568]
**Background**
We should have a more visible status of the closed whitelist with the committed amount. Something that will correspond more to the one we have on the website (Charlene design)

**Designs**
Charlene or to be created

**Acceptance criteria**
Visible amount of funds committed during the Whitelisting period

**Testing notes**
As on design

**Comment by andywalton** [comment]
@pstroinski 

Here are is a solution I'd recommend for this:

We should create a new component based off our ETO success state card.

So create a **new component** based off this:
<img width="405" alt="Screenshot 2019-10-02 17 10 55" src="https://user-images.githubusercontent.com/609657/66056565-9d81c400-e537-11e9-8e00-75a673df10da.png">

ie. the `EtoStatusManager-module__successful-info` component.

And make it look like so:
<img width="391" alt="Screenshot 2019-10-02 17 04 11" src="https://user-images.githubusercontent.com/609657/66058814-4da4fc00-e53b-11e9-8d4c-f916c0eda603.png">

This only css change required is:
`background: #E7EBEE;`

And the text:
Info text for the case of all whitelisting slots filled:
`Whitelist closed - all X slots filled`

If not all slots are filled then:
`Whitelist closed - X of Y slots filled`

Then add how much was committed during the whitelist:
`X EUR committed`

**Show this when:**
- [ ] show this when the whitelist is closed and no campaign dates have been set for sales (ie. no countdowns are active)
- [ ]
