### ISSUE TITLE
Copy and copy styling edits for nEUR purchase / Linking bank account

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3577]
Customers are getting confused during our linking and purchasing of nEUR. A lot of people are forgetting to include the reference number.

Therefore, please update the copy on the nEUR modals for:

1. Purchase nEUR, &
2. Link your bank account via bank transfer 

- [x] Change the introduction sentence/s for each of the modals to read:
`Please complete a wire transfer using the bank details below, and ensure you include the reference number and your name. We recommend sending funds in EUR to avoid additional bank fees.`

- [x] Bold the words: **ensure you include the reference number**.

- [x] Change amount to send to: `Minimum amount to send`.

- [x] Bold the reference number in the details table.

- [x] Centre align the orange information text and change the copy to: `Please note that the nEUR purchase takes around 1 - 3 business days.`

- [x] Make sure the title for the linking modal reads `Link your bank account via bank transfer`, it currently says `Link you`.

Once done, these screens will look like this:
<img width="832" alt="Screenshot 2019-10-03 23 42 23" src="https://user-images.githubusercontent.com/609657/66166691-49123d80-e638-11e9-87e7-575dbf96beb1.png">

<img width="832" alt="Screenshot 2019-10-03 23 52 43" src="https://user-images.githubusercontent.com/609657/66167091-790e1080-e639-11e9-808f-5fc9ed011b92.png">

**Comment by andywalton** [comment]
Talk to @vizmab also if you need further copy clarity with this. I'll be offline until late Saturday, 5 October.

**Comment by glupiawymowka** [comment]
tested on stage
