### ISSUE TITLE
show countdowns to (pre)sale instead of whitelist limit reached

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3581]
**Background**
Current implementation of states in `getEtoSubState` puts `WHITELISTING_LIMIT_REACHED` over any other state. in on chain this will prevent countdowns to be shown.

here's how we should fix it (final fix would decouple LIMIT REACHED from states but let's not touch it).

1. if there's start date and whitelisting is disabled (isBookbuilding===false) we show countdowns no matter what
2. else we have our current code

intention of (1) is to show countdowns when we are within 7 days (so you cannot change start date anymore) from pre-sale.

**Designs**
We do not change UI

**Testing notes**
OK - we do not have a fixture exactly in that state. you can produce one by setting start date to minimum possible value and then wait for a few minutes.
Also the api mock call to change whitelist limit is coming

**Comment by desfero** [comment]
Fixed in https://github.com/Neufund/platform-frontend/pull/3583

**Comment by glupiawymowka** [comment]
tested on stage
