### ISSUE TITLE
Copy change on the registration page

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#3594]
As we are experiencing issues with Ledger login, we'd like to remove the text that platform copy that is suggesting using Ledger over Light Wallet.

**The current copy**
![copyreg](https://user-images.githubusercontent.com/48217191/66480964-1cc74880-eaa0-11e9-9be6-2997e5a3a243.png)

"In a few steps, you’ll be able to start investing on blockchain! The first step is to create your wallet. The Light Wallet is a starter solution for those who are new to blockchain. For larger balances, we recommend using a Ledger Nano."

**Change to**:
"In a few steps, you’ll be able to start investing on blockchain! The first step is to create your wallet. The Light Wallet is a starter solution for those who are new to blockchain."

**Comment by pstroinski** [comment]
To be changed in the new onboarding and outdated
