### ISSUE TITLE
Copy/design change on the Ledger registration page

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#3595]
The current copy on the Ledger registration page is not correct.
![image ledger](https://user-images.githubusercontent.com/48217191/66481094-6e6fd300-eaa0-11e9-9b67-4c6f5beded36.png)

1. In point 5 we should say Enable "Contract data" instead of "Contract support"
2. In point  6 we should say Enable "Display data" instead of "Browser support"

@Louisswryan - could you please help with the updated design?

**Comment by Moejoe90** [comment]
As per discussion with @andywalton we will close this ticket and it will be handeled first from a design point of view and added seperatly to relevant tickets
