### ISSUE TITLE
Issuer Flow - Whitelisting (Your ETO Starts Soon)

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3599]
**Background**
Issuer should see a proper status of the ETO (Whitelisting) during the whitelist stage.
We should also display two modules:
- whitelisting module (already implemented)
- set date module

We need to adjust the ETO Date module:
Title: ETO DATE
Body: You have successfully set the date for your ETO. Make sure you communicate this to your community. The whitelist subscription will be automatically disabled 14 days before the start of the presale.

Presale starts in:
The date of the ETO can still be changed for the next ___ days, ___ hours.

Button: Change the ETO date

**Designs**
We should adjust the module with the date box.
![should_be_in_this_format_with_different_data](https://user-images.githubusercontent.com/27957897/66492589-f4961480-eab4-11e9-8428-e9cafc5ec39a.png)

**Acceptance criteria**
- [ ] Available module with proper whitelist status (open, closed, disable)
- [ ] Module with the set date option with adjusted copy

**Comment by Louisswryan** [comment]
Hey @drakkein 

Please see below a solution for this:

https://zpl.io/aN58mWn


It isn't so nice but this who environment is being reviewed.

One change that is necessary, is to change the countdown timer to the actually date of presale. It is my understanding that currently it is set to when the issuer may no longer change the date.

I will contact you directly about this.

Cheers!

**Comment by glupiawymowka** [comment]
tested on stage
