### ISSUE TITLE
Recovery flow starts pooling of user/gas/pending-transaction

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3650]
**Description**
At the moment recovery flow starts pooling for data that require jwt in the store, therefore, an error is throw in the console because jwt token is not set at that moment.
![image](https://user-images.githubusercontent.com/7031578/67222077-4c2d6c00-f435-11e9-8b8f-bd17ed2b6d3a.png)

**Environment**

**Steps To Reproduce**
Go through recovery flow until `A new access link has been sent to your email.` then check console.

**Actual behaviour**
It pools under the hood user/gas/pending-transactions api's

**Expected behavior**
It should not start any kind of pooling under the hood.

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
tested on stage
