### ISSUE TITLE
Small responsive issues with Fundraising Statistics

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3655]
Hey @drakkein,

We have 2 small issues to take care of with regard to the new Fundraising statistics page.

Firstly: There is some small misalignment with these cards which is a bit unsatisfying. 
![Screenshot 2019-10-22 at 12.57.56.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/06e181e1-8b72-4a04-9468-6bdb52cfb184)

Can we please correct so that they match up perfectly. Perhaps something like the below.
![Token Distribution Review.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/85379e6f-4b7b-42d9-85bf-c4cb76fe1b1b)

Secondly: A small responsive issue. The EUR-ETH conversion breaks at smaller tablet size.

Can we please wrap the converted value underneath the selector at tablet size and smaller?

![Screenshot 2019-10-22 at 13.12.48.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/ec832861-c854-418f-8185-fea6b6fdc9e8)

Thank you!

**Comment by drakkein** [comment]
Linked PR from ico monitor repo https://github.com/Neufund/ico-transparency-monitor/pull/223

**Comment by drakkein** [comment]
PR has been merged, waiting for @pstroinski to redeploy. Will ping @glupiawymowka when ready for tests.

**Comment by drakkein** [comment]
Deployed, ready for tests

**Comment by glupiawymowka** [comment]
tested on stage
