### ISSUE TITLE
[WALLET RECOVERY] - edit copy to facilitate the process 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3656]
**Description** 
There is no hint for the user, what's the email they should look for. 
Let's add the email subject to facilitate the search 

**Current view** 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/901c3308-95d7-4a05-a81a-4a3adf0d5f90)

**New copy** 
Before recovering your wallet, please check your inbox and spam folder for your registration confirmation email, which contains the access link. The email subject is: "Complete registration on Neufund".

**Comment by Moejoe90** [comment]
This is outdated as there is a new copy for recovery
