### ISSUE TITLE
Bookbuilding widget is hanging on loading state

### ISSUE THREAD

**Issue by drakkein** [Neufund/platform-frontend#3675]
**Description**
For the `ISSUER_SETUP_NO_ST` bookbuilding widget is hanging on loading state.

**Environment**
`.io`

**Steps To Reproduce**
Login as `ISSUER_SETUP_NO_ST`, go to ETO dashboard.

**Actual behaviour**

**Expected behavior**

**Comments, context, logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/10601291/67641172-71701d80-f900-11e9-9680-e0fe0a2bfb72.png)

**Comment by glupiawymowka** [comment]
tested on stage
