### ISSUE TITLE
Parse errors coming from the Tx Node 

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3686]
**Background**
Currently we don't parse the error coming from the tx node. 
We need to take the error coming from the node and check it with our known errors. For example there can be an out of gas error coming from the tx - node
**Designs**

**Acceptance criteria**
User should have an Out of Gas error from the node and the correct error should show up. 
**Technical notes**

**Testing notes**

**Comment by pstroinski** [comment]
outdated
