### ISSUE TITLE
Business KYC request - time to finish

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3693]
**Background**
In case of a Personal KYC we have an information that the manual process takes 2-3 business days:
![image.png](https://images.zenhubusercontent.com/5beab1a20cefa317ea424319/38cd2f97-b546-41fc-a1d8-0e15cb830c39)

We should have an information that in case of business request it's gonna take 7-14 days as it's much more complicated process.
Currently at the end of business document upload there is an info:
![image.png](https://images.zenhubusercontent.com/5beab1a20cefa317ea424319/8ab530e8-4e5a-4bae-9f00-bb96f78e4763)
We should have it separated from Individual and Business

The same then in the Profile:
![image.png](https://images.zenhubusercontent.com/5beab1a20cefa317ea424319/db1cbabd-9155-4428-8cf1-d3f18a6faf98)

**Designs**

**Comment by arjunu** [comment]
This has implemented in https://github.com/Neufund/platform-frontend/pull/4020

**Comment by glupiawymowka** [comment]
can be merged after solving health check conflict
