### ISSUE TITLE
[KYC changes 1] - KYC user flow changes to incorporate Onfido

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3714]
**Background**
Due to incoming regulation changes we can no longer manually verify individual/personal accounts manually. We therefore need to use an accredited KYC vendor for this. Currently we have IdNow integrated, we are adding a second option called Onfido. This ticket deals with the user flow changes required to integrate Onfido into our KYC flow as well as removing the manual verification method.
 
See technical details in this closed PR with initial Onfido exploration: #3397

**Designs**
![002a](https://user-images.githubusercontent.com/886612/68591333-cbd8b480-0490-11ea-8d0f-54445b6da951.png)

Please see the detailed designs here with the relevant steps: https://zpl.io/V49gGX4

Note, the UI design has changed from our current. This new UI should be implemented. Please work closely with Trilbi and Louis regarding these changes should you have any questions.

Changes you'll see:
1. The navbar doesn't show our navigation or profile / status links when you're in KYC. It's essentially a full-screen modal. In this navbar there is a "Save and close" button. This should save the last completed state of the user so that when they return to KYC themselves later, the landup on the step they left off at.

2. New stepper to track progress at the top just below the navbar.

3. For this initial round of changes, there are the following steps:

- [x] Account type selection
- [x] Personal details (This step should factor in the US investor fields)
- [x] Address details
- [ ] Verify account (this will either show Onfido or IdNow or both, depending on what the backend sends us - TBD, this might simply be based on country, ie. If Germany show IdNow only, else show Onfido only for everyone else)
- [x] We show a success or failure message.

4. There are two new fields we'll ask the backend to provide:
- Personal details: `Country of permanent residency`
- Address details: `Additional information (optional)`

See all fields below:
![KYC - Individual KYC user flow@2x (1)](https://user-images.githubusercontent.com/609657/68581525-d9824000-0478-11ea-907c-e4aa5e7195d8.png)

Lastly note:
- Final copy will be incoming this week Thursday - will add a separate ticket for this.
- We're going to add a new illustration to the success/error confirmation screen. This will be ready later this week. It will simply replace the success "tick" for example.

**Acceptance criteria**
As a user I can complete the KYC process.

**Technical notes**
There are two new fields we'll ask the backend to provide:
- Personal details: `Country of permanent residency`
- Address details: `Additional information (optional)`

See technical details in this closed PR with initial Onfido exploration: #3397

**Testing notes**
To be discussed with Nikola.

**Comment by huesforalice** [comment]
**Backen API Changes**
