### ISSUE TITLE
Changes to eto progress bar logic and visualisation

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3744]
Hello,

We are making a change to the logic of the eto progress bar. 
This affects how we show softcap and hardcap. 

From now on, the progress bar moves from empty to softcap which is called 'target' and is our new point of completion for the progress bar. 

After this, the amount raised can continue to grow up until the point of hardcap or 'limit'.
In this instance, the percentage funded will simply continue to rise past the 100% mark as is done by seedrs among other platforms. Once at 100%, the progress bar stays the same regardless of hardcap being reached ect...

Zeplin link with designs  below:
https://zpl.io/2ExEPYy

This progress bar features on the eto card, the eto widget and portfolio so each must be accounted for.

Please note the ETO widget contains all of the same content but is arranged in a way to guide the investor towards the call to action. Please ask if there are difficulties surrounding this. I am aware that this is for a quick release so understand if cannot be a priority.

For the portfolio view, we simply apply the new progress bar. Can we please move the campaign countdown to underneath the token name and rather than using the view profile link, simply link the token name to the profile to clear that necessary space.

There are one or two more visual changes here e.g. the change of the lichtenstein offering tab and removal of the filtering subjects. Let's talk this through once this has been assigned and decide what we can do and what is unrealistic or unnecessary.

Thank you!

**Comment by Louisswryan** [comment]
Had a meeting today with @drakkein to decide on priorities for this task. The conclusions are listed below.

 - New progress bar and logic remains the core feature. 

 - ETO widget button changes are not actionable as this would create overlapping work so ETO widget will remain as it currently is (except for the replaced progress bar).

- In the investor profile, the %funded will shrink to 12px font size and the size of the progress bar will be justified to the size of the column that the bar sits within.

 - A further change is necessary in the profile section. The progress bar should be accompanied by the remaining time left in the eto/phase of eto. This will sit beneath the token name. So that it has enough space, it is necessary that we remove the 'view profile' link that sits to the right of the token name. We will increase the token name to 16px font size and make the block that contains the name and token icon the link to the issuer profile

**Comment by Louisswryan** [comment]
Hello,

This update is in response to an issue that was highlighted this morning:

Currently, the target amount in the progress bar is susceptible to change based on discounts that are given out, usually in the presale phase.

This amount has been designed to be static so needs to be made dynamic to reflect this need.

We also need to make the original target amount accessible so will do this with the use of a tooltip.


New rule for tooltip

![Screenshot 2019-11-21 at 13.37.36.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/604afa97-5c4c-4f63-94db-b37436f5f472)

ETO investment terms

![Screenshot 2019-11-21 at 13.37.52.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/c7447831-2e27-4157-8251-8f06cfe18997)

Portfolio

![Screenshot 2019-11-21 at 13.38.16.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/afa75fce-8b45-4cb4-9f5c-02365a567db3)



There is also another issue that was overlooked in the original ticket. That is the communication in the grey bar that appears once the soft cap is reached. If not already done, can we please remove this as it is no longer necessary.

(seen below)

![Screenshot 2019-11-21 at 13.53.25.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/c4adb564-77b4-472e-ab0c-c38517f02e4f)



Updated Zeplin link with annotations
https://zpl.io/2ExEPYy

**Comment by glupiawymowka** [comment]
The bar itself seems to work/change as expected. 
Please note that the tests for an unregistered user can only be finished when PR is merged. 

@andywalton @pstroinski @Louisswryan  my doubts are: 
- [ ] there was no design for the card in presale. This is how it looks and I didn't get a confirmation if it's correct or not. I consider it correct for now. 
![image](https://user-images.githubusercontent.com/18315589/69435061-23074080-0d3f-11ea-9e03-68523505fa09.png)
- [ ] The amount of different variable target investments can be complicated and confusing at first sight. It's not the matter of this ticket but please consider if that's what we wanted to communicate
![image](https://user-images.githubusercontent.com/18315589/69435361-b2145880-0d3f-11ea-9df1-ba63f2d88689.png)

![image](https://user-images.githubusercontent.com/18315589/69435427-d53f0800-0d3f-11ea-96d6-571b94e4567f.png)

**Comment by Louisswryan** [comment]
@glupiawymowka 

The design in the presale state issue has been corrected but I need to outline it in a new issue

The other issues will have to wait until we re open this case
