### ISSUE TITLE
optimize getting bookbuilding stats and user pledges

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3762]
**Background**
Optimized and proxy cacheable methods are available for getting bookbuilding stats for a list of ETOs and for taking all pledges for logged in user. Please use them to reduce number of calls to backend and maybe to simplify your code.

**Acceptance criteria**
* [ ] no changes in app behavior when displaying bookbuilding stats
* [ ] no changes in app behavior for users adding/changing/deleting pledges (includes e-mails)

**Technical notes**
A method to obtain bookbuilding stats for a list of etos.
```
/bookbuilding-stats:
    get:
      operationId: api.eto.bookbuilding_stats_multiple_etos
      tags:
      - Pledge stats
      parameters:
        - in: query
          name: eto_ids
          type: array
          collectionFormat: csv
          items:
            type: string
            pattern: ^0x[a-fA-F0-9]{40}$
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/BookbuildingStats"
        404:
          description: eto not found
```
warning: **it may be cached and cannot be used to replace method to obtain stats for particular eto that is used when user is changing/deleting pledge!**
```
/pledges/me:
    get:
      operationId: api.pledge.get_all
      description: Get all pledges of user
      tags:
        - Pledge
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Pledge"
```
A method to obtain all pledges for particular user. It is never cached. You should still use old method when changing/deleting pledge. We planned it to be used in dashboard.

**Comment by glupiawymowka** [comment]
there are commitments added, but the *widget of doom* doesn't show them to the unverified user 
![image](https://user-images.githubusercontent.com/18315589/72892846-dd073280-3d17-11ea-9aab-a453f62c167e.png)

The commitments show up correctly on the ETO card 
![image](https://user-images.githubusercontent.com/18315589/72892905-02943c00-3d18-11ea-826e-02d51cd6ac72.png)

**Comment by pavelneu** [comment]
Tested via codechecks.
Works well, the issue doesn't show up anymore.
The word `remaining` was changed on `left`.
