### ISSUE TITLE
Split DocumentUploadable.tsx into small files

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3764]
**Background**
Document Uploadable needs to be split and the interface cleaned up. 

**Acceptance Criterea** 

- [ ] `DocumentUploadableDropzone` and `DocumentUploadableTile` should be in seperate files 

- [ ] There should be one folder that has this component 

- [ ] Diffrentiate clearly when to use `DocumentUploadableDropzone` and when to use  `DocumentUploadableTile`

- [ ] Add DocumentUploadableDropzone to storybook

- [ ] Add DocumentUploadableTile to storybook

**Comment by pstroinski** [comment]
outdated
