### ISSUE TITLE
Refactor modals to not throw an error on close/cancel

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#3767]
**Description**
closing/cancelling modals shouldn't be an error

**Environment**

**Steps To Reproduce**

**Actual behaviour**
at the moment if the user closes a modal the saga throws and error that gets caught then. It's not clear why it's and error - cancel a modal is just a regular user action.

**Expected behavior**
sagas don't throw errors on close/cancel

**Comments, context, logs**
the underlying sagas should be refactored to use `race()` and to avoid throwing errors as indication of closing/cancelling

example of bad behaviour: `/platform-frontend/packages/web/app/modules/access-wallet/sagas.ts:180` 

**Screenshots**

**Comment by Moejoe90** [comment]
Before going deep in this PR we need to think what approach should we take and what are the pros and cons of each step.

**Comment by Moejoe90** [comment]
Will close this as there is no need to use Race in this case.
Can be reopened
