### ISSUE TITLE
Expose source-maps as a separate files on production.

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3774]
**Background**
At the moment it's hard to debug complex production issues reported to the sentry. We have two options to make it better: 
1. Expose source-maps on production
2. Send source-maps to the sentry server after deployment.

The first one is the simplest and given frontend is open-sourced we can easily just switch webpack configuration to include source maps.

**Acceptance criteria**
- [ ] Source maps are available and linked to correct files in the `./dist` folder.

**Technical notes**
Please test whether the sentry can read the source map and display the proper error stack.

**Comment by arjunu** [comment]
In https://github.com/Neufund/platform-frontend/pull/3928 have turned off sourcemaps for now webpack build is failing with heap out of memory.

**Comment by pstroinski** [comment]
It was also disabled in Sentry
