### ISSUE TITLE
Move ETO Views main components into Sagas

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3786]
**Background**
Since ETO View has its own Route. We start moving all data fetching and calculations into sagas. 
The main logic should be moved into sagas and the ETO view should start having its own reducer for all calculated values. 

Take caution to not over do this. As each small component might have indeed some calculations but it doesn't make sense to spend precios developement time moving everything there. 

Please focus on moving only the main components and the main calculations. 

Note that ETO view reducer should only be concerned with the information required for the ETO View nothing else. The saga should be activated the moment you enter the main route. 

Note that even though we are copying the data in theory from different sources this will solve our issue in regardance to data integrety as in. If I am an Issuer and i want to see what an Investor see' I don't need to change any deep internal logic as all the correct data should be populated by the reducer. 

**Acceptance criteria**

Everything should works as before

**Technical notes**

**Testing notes**

**Comment by glupiawymowka** [comment]
this was already merged, no PR to review.
