### ISSUE TITLE
Add Withdraw E2E test for Ether tokens

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3789]
**Background**
Withdraw tests on master now changed and they test only ether. 
Create a new test suite for `node-e2e` with only two tests. 

1 - Regular Ether Token Transfer
2 - EtherToken transfer to a smart contract

**Designs**

**Acceptance criteria**

**Technical notes**

**Testing notes**

**Comment by pstroinski** [comment]
To be moved to QA
