### ISSUE TITLE
Changes to progress bar for presale, whitelisting + minor CSS

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#3791]
Hello,

These changes have been made but are currently in review. They are as follows:

1. Remove the progress bar from whitelisting card state.

2. Increase the COMMITTED and SLOTS LEFT to the same size and weight as %FUNDED in the public sale state.

3. Reuse the entire progress bar component from the public sale state in the presale state (it currently does not use the %FUNDED and new additions).

4. Justify the text in the second column of the |ETO details to the right.

Thanks!

**Comment by glupiawymowka** [comment]
tested on codechecks for: 
- unregistered view, mobile + web
- registered view, mobile + web
- presale 
- whitelisting

**Comment by glupiawymowka** [comment]
tested on stage
