### ISSUE TITLE
Add proper e2e tests for outsourced KYC providers

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3818]
**Background**
At the moment we either don't have e2e tests (Onfido) or tests are pretty naive (id-now) for outsourced providers. Unfortunately due that it's an external provider we need to mock on the backend communication and call appropriate webhooks to simulate that behavior during e2e tests. 

**Technical notes**
@huesforalice please add some technical notes for the APIs we need to call and when.

**Comment by pstroinski** [comment]
To be moved to QA
