### ISSUE TITLE
Fix new buttons UI bugs  

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3822]
**Description**

- [x] Notification should not be centered
![image](https://user-images.githubusercontent.com/7031578/70333621-2113a600-1844-11ea-8128-8dd31dc0b9e0.png)

- [x] Mobile header menu logout button should have icon close to the text
![image](https://user-images.githubusercontent.com/7031578/70333718-53250800-1844-11ea-8e52-1615fbeebfcd.png)

- [x] Icon should inherit color from button text color
![image](https://user-images.githubusercontent.com/7031578/70333834-849dd380-1844-11ea-99e8-0d83cdd3d834.png)

- [x] Icon button should be properly positioned 
![image](https://user-images.githubusercontent.com/7031578/70333876-9ed7b180-1844-11ea-9e3f-4ea157a0c160.png)

- [ ] Outline button should be not transparent we need to apply always white background (here how it looks inside new KYC UI flow)
![image](https://user-images.githubusercontent.com/7031578/70334289-73a19200-1845-11ea-9b4a-5b4792bb84d3.png)

- [x] ICBM wallet enable button overflows container (for now will disable padding there so it at least looks okay but we need to talk with designers)
![image](https://user-images.githubusercontent.com/7031578/70334156-2d4c3300-1845-11ea-8ab8-0ad70339f330.png)

- [x] Document templates should be aligned to left 
![image](https://user-images.githubusercontent.com/7031578/70334522-e0b52780-1845-11ea-99d8-8791c5e2267d.png)

- [x] Eto view icons should look like before 
![image](https://user-images.githubusercontent.com/7031578/70334556-f296ca80-1845-11ea-9791-0064480ac55e.png)

- [x] Eto legal documents should be aligned to left
![image](https://user-images.githubusercontent.com/7031578/70334623-0d693f00-1846-11ea-8af3-01a7bd7c7ab3.png)

- [x] some buttons still showing uppercase 
![image](https://user-images.githubusercontent.com/18315589/70336669-ddbc3600-1849-11ea-87a3-375fa51d8cb7.png)

- [x] or lowercase
![image](https://user-images.githubusercontent.com/18315589/70336764-05ab9980-184a-11ea-9073-abd004660467.png)
 

And two that could, but doesn't necessarily need to be done before the release: 
- [x] img upload icons should be round and separated 
![image](https://user-images.githubusercontent.com/18315589/70335383-7bfacc80-1847-11ea-9466-5b67701f3415.png)

- [x] empty document upload icon should be changed to fit the designs again
![image](https://user-images.githubusercontent.com/18315589/70335496-ab113e00-1847-11ea-9bc4-2d0f62ba52f7.png)

- [x] link button should have proper disabled style 
![image](https://user-images.githubusercontent.com/7031578/71321415-8a8ce900-24c1-11ea-8f8e-3f22c676f5e7.png)

**Environment**
`dev` and `stage`

**Steps To Reproduce**

**Actual behaviour**

**Expected behavior**

**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
- the logout button got misplaced on stage 
![image](https://user-images.githubusercontent.com/18315589/70517285-a0e98b00-1b38-11ea-8fe8-23b2d2079953.png)

- only on iphone + safari, some media icons still stay unreadable 

![image](https://user-images.githubusercontent.com/18315589/70520484-e8bee100-1b3d-11ea-9dba-5bc51c836e80.png)
![image](https://user-images.githubusercontent.com/18315589/70520506-f2484900-1b3d-11ea-8573-9e830a8f9800.png)


- email verification modal buttons not responsive on mobile view
![image](https://user-images.githubusercontent.com/18315589/70520869-85817e80-1b3e-11ea-9d2b-3229d1a55962.png)
