### ISSUE TITLE
Wallet recovery access modal is still showing after navigation manually back

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3839]
**Description**
When you go to Recovery and then back through the browser back button the access modal is still visible.
Visual reproduction can be found here: https://neufund.slack.com/archives/GAK8XK0CB/p1574687513016200

**Environment**
prod

**Steps To Reproduce**
1. Go to the wallet recovery process
2. Wait until access modal appears 
3. Click the browser back button

**Actual behavior**
Modal is still showing 

**Expected behavior**
Modal should be automatically discarded and hidden

**Comments, context, logs**

**Screenshots**

**Comment by andywalton** [comment]
This will be fixed with the new Wallet recovery flow improvements.
