### ISSUE TITLE
Redesign Business KYC flow and layouts

### ISSUE THREAD

**Issue by Trilbi** [Neufund/platform-frontend#3851]
**Background**
Update Business KYC flow to match Individual KYC and new designs.
Text inputs should match the new designs (this might be done as part of individual KYC) https://github.com/Neufund/platform-frontend/issues/3775

_Please note:_
Make use of the progress component as already created as part of the Individual KYC changes already completed which show the current step and progress to a user as they step through the business KYC steps.

For example this older component:
<img width="601" alt="Screenshot 2020-01-20 17 48 45" src="https://user-images.githubusercontent.com/609657/72744061-27b86b80-3bad-11ea-84c5-2a223bc2f0a0.png">

Has been replaced with this:
<img width="1091" alt="Screenshot 2020-01-20 17 48 29" src="https://user-images.githubusercontent.com/609657/72744090-34d55a80-3bad-11ea-8427-fffa7a4c5431.png">

You can see the component in Storybook -> [progressbarsimple](https://neufund.github.io/platform-frontend/?path=/story/nds-atoms-progress-progressbarsimple--50)

-----

**Designs**
- Zeplin project (underneath Individual KYC): zpl://project?pid=5dc3eb1750731722a4ba5b7d

**Step 1 - Choose your account**
- zpl://screen?pid=5dc3eb1750731722a4ba5b7d&sid=5dc3ed039d96cd233b894b2a
- The entire container for the selecting individual or company KYC should be interactive and not just the button itself: 

**Step 2 - Company details**
- zpl://project?pid=5dc3eb1750731722a4ba5b7d&seid=5dcc3c295e2acb1652bd2f91
- The order of fields, “Company registration number ~(if applicable)~” and “Legal form” have been swapped as per the designs
 
**Step 3 - Managing director(s)**
- zpl://project?pid=5dc3eb1750731722a4ba5b7d&seid=5dd668038ec0d1bb8bdbfa65
- This is a new step
- This step is obligatory and the user should not be able to skip this step. 
- ~(More than one Managing director can be added.)~

**Step 4 - Beneficial owner(s)**
- zpl://project?seid=5dd2b6b2e70d79669ee51c91&pid=5dc3eb1750731722a4ba5b7d
- This step is optional and the user could skip
- More than one Beneficial owner can be added.
- An addition to business KYC is to allow a user to choose if the Beneficial owner is an individual or a company.
- When choosing radio button for “A company”, the form for Step 2 - Company details should be displayed: zpl://screen?sid=5de7ba006eb24b5788dce524&pid=5dc3eb1750731722a4ba5b7d

**Step 5: Account manager(s) details**
- zpl://project?pid=5dc3eb1750731722a4ba5b7d&seid=5dd67112813a0b0ad4c39707
- This step is optional and the user could skip it
- ~(More than one Account manager can be added.)~
- “Legal representative” is an incorrect term and has changed to “Account manager”.

**Mobile design notes:**
- If two input fields are positioned next to each other (desktop layouts), then stack them for mobile layouts. I.e. First name and Last name. City and Postal code: zpl://screen?sid=5dd667eab3ab1006492b1d24&pid=5dc3eb1750731722a4ba5b7d

- Modal design and upload component layout for mobile: zpl://screen?pid=5dc3eb1750731722a4ba5b7d&sid=5defbe18da4f1aa800d89512

- Font size for titles is smaller for mobile, and remove spacing between body copy and button: zpl://screen?sid=5dc4056ec3f78083ca307706&pid=5dc3eb1750731722a4ba5b7d

- In case a users' name is ridiculously long, please wrap the text to the next line and vertically centre it: zpl://screen?pid=5dc3eb1750731722a4ba5b7d&sid=5e30395a23cde97ff325df33

**Comment by Moejoe90** [comment]
Just a note @andywalton : 
There are a couple of new designs here or new components. We will use the old components or old design for now until we have these new components in our design `style-guide`

**Comment by glupiawymowka** [comment]
tested on stage both for mobile and Chrome.
The follow-up ticket with lower prio changes to be created after the release
