### ISSUE TITLE
Small UI bugs pack

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3860]
**Description**
We need to fix a couple of small UI related bugs.

- [x] In case metamask is not installed the message during login/registering overflows device `width`.
![image](https://user-images.githubusercontent.com/7031578/70715501-bacacf80-1cea-11ea-88c9-5df172b6a8f7.png)

- [x] In case ETO doesn't have any `Advisors` provided the header is still shown on the ETO view  
![image](https://user-images.githubusercontent.com/7031578/70715736-2a40bf00-1ceb-11ea-9668-b79a481bb756.png)

- [x] NEUR bank account button link is not in line with the header
![image](https://user-images.githubusercontent.com/7031578/71201078-f7299d00-22a1-11ea-962b-bdc955fdf04d.png)

- [x] Use a more user friently message in case provided value is not a number 
![image](https://user-images.githubusercontent.com/7031578/71201785-6f449280-22a3-11ea-8f17-83797bf22350.png)

- [x] Remove `Video` heading when video is not provided for the ETO 
![image](https://user-images.githubusercontent.com/7031578/71312201-ce83dd80-2430-11ea-9d43-2972ae86213d.png)

- [x] Fix the tooltips' arrow position for 1st and 2nd entry 
![image](https://user-images.githubusercontent.com/18315589/71907645-ba4c1a00-316c-11ea-9b4d-71aedf6265f3.png)

- [x] "upload ISHA" on nominee's side breaks if the uploaded file name is especially long
![image](https://user-images.githubusercontent.com/18315589/72062407-0a93bb00-32d8-11ea-924f-8d1ae4355327.png)

- [x] It's possible to delete on UI token icon when the form is in the read-only state (for e.g. ISSUER_SETUP fixture).
![Jan-09-2020 20-23-14](https://user-images.githubusercontent.com/7031578/72098241-5ec18e00-331e-11ea-8aa4-ec4211c47a55.gif)

- [x] Clicking on media icon opens also personal modal but it should just redirect to the media page without opening a modal 
![Jan-09-2020 20-25-09](https://user-images.githubusercontent.com/7031578/72098285-7b5dc600-331e-11ea-9815-d7d4aaea7469.gif)

- [x] Click here misaligned in Light Wallet login page
![image](https://user-images.githubusercontent.com/4038217/72146414-ab4bae80-339c-11ea-9b2f-9ec8822ff8f3.png)

- [x] The ETH word printed lowercase instead of with capital letters in Wallet -> Send ETH 
![Screenshot 2020-01-13 at 12 17 54](https://user-images.githubusercontent.com/59572156/72252278-45ab2c80-35ff-11ea-9dcd-228388cfc6fc.png)

- [x] Add margin after the warning 
![image](https://user-images.githubusercontent.com/7031578/73825847-d8cb3100-4850-11ea-8ed8-3e388dfd25ab.png)

- [x] The Metamask signing icon got really big and pixelated 
![image](https://user-images.githubusercontent.com/18315589/73826198-aa703600-47fd-11ea-9968-fc62bb11ef0a.png)

- [x] KYC header navbar - extra spacing on screens less than 768px wide between the header and the progress indicator below it. This is due to the header height changing at this breakpoint from 64px to 56px;

- [x] KYC header navbar - the `Save & Close` button, the `X` icon is not displaying correctly. It's position is off and the icon is being clipped.

- [x] Tooltip misaligned with heading in Portfolio page
![image](https://user-images.githubusercontent.com/4038217/75903219-90983200-5e41-11ea-9bf5-4ee8bf777005.png)

<img width="791" alt="Screenshot 2020-02-16 18 34 07" src="https://user-images.githubusercontent.com/609657/74610203-4731ae00-50f1-11ea-8402-4e276b690bce.png">

**Environment**
production

**Comment by andywalton** [comment]
@desfero -> added two small items to this, see the last two.

**Comment by desfero** [comment]
Seems all of them are fixed now (except metamask icon but that's moved to a separate PR). Thanks
