### ISSUE TITLE
Ledger not working on Master

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#3874]
**Description**
Currently you cannot login with the Ledger to the platform

**Environment**

**Steps To Reproduce**
Use the ledger to login into the platform 
**Actual behaviour**
When logging in you will get an Ledger Unavailable Error
**Expected behavior**
The user should login succeffully 
**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
tested on stage for login and transactions
