### ISSUE TITLE
Do not refresh JWT after logout

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3879]
**Description**
At the moment after inactivity logout, we do not stop refreshing JWT token therefore after less than 10 minutes from logout JWT refresh call is done with `undefined` JWT token. 

![image](https://user-images.githubusercontent.com/7031578/71905262-195b6000-3168-11ea-8a80-7379e7d81007.png)

**Environment**
production

**Steps To Reproduce**
1. Login to the platform
2. Wait without any action for inactivity logout
3. Wait up to 10 minutes for `jwt/refresh` request to be made 

**Actual behavior**
JWT refresh was sent after inactivity logout

**Expected behavior**
No JWT refresh should be done after logout

**Comments, context, logs**

**Screenshots**

**Comment by pavelneu** [comment]
Tested on stage.
The JWT refresh does not appear after inactivity logout.
