### ISSUE TITLE
Wrong link to terms of use of Quintessence

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3893]
**Description**
When linking a bank account or doing a bank transfer we are showing a link to Quintessence terms of use that links to: https://quintessence.global/terms-of-use.pdf
The proper link should be: https://quintessence.global/assets/files/terms-of-use.pdf

**Environment**
All

**Steps To Reproduce**
Clink on: Link bank account and see the terms of use

**Comment by glupiawymowka** [comment]
tested on stage
