### ISSUE TITLE
[NOMINEE] - critical error if ISHA signed before the redeem 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3909]
**Description**
The default steps after the ETO were: 
- Nominee redeems the shared capital
- Issuer uploads and signs ISHA
- Nominee uploads and signs their version of ISHA

In fact, nothing is blocking the Issuer and Nominee to sign ISHA before redeeming, but we throw a critical error in such case. 

**Environment**
most probably all (confirmed on io and stage) 

**Steps To Reproduce**
1. Login as an issuer in `signing` state
2. Upload ISHA and sign the new copy
3. Login as a nominee in `signing` state
4. Choose to upload ISHA 

**Actual behavior**
- the critical error is thrown :
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/c3c409f4-d61e-45ff-8b10-08fda047d32c)

- everything works correctly after refreshing the whole page, thus you can reproduce this only once for each nominee 

- Sentry error: 
https://sentry.neusrv.net/sentry/staging/issues/10657/?referrer=slack

**Expected behavior**
the document upload works exactly like after the refresh
no error is thrown 

**Comments, context, logs**

**Screenshots**

**Comment by drakkein** [comment]
Both me and @glupiawymowka tried to reproduce and find pattern for this issue. As for now we are not able to do it, every try is not failing. 
The error seems to be related to `SignNomineeISHASummary` component, specifically speaking to the `uploadState: nonNullable(selectNomineeAcceptIshaUploadState(state))`
