### ISSUE TITLE
[ETO agreements] - fix the documents appearance in Portfolio & ETO page 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#3915]
**Description**

Having the token transfer feature implemented, we need to change slightly what do we show to the user. 
Some documents are only valid for the investor, for the token holder and so on. 

This will also fix a bug when the user who received a transferred token tries to download RAAA.

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/19c90304-868c-47ef-9b27-8be1d7632603)

**Environment** 
All (the screen was taken on the live platform) 

**Fixes for Portfolio** 

To deal with the broken document quickly, we decided to 
- [ ] add the Agreements button in the Past Investments that currently look like this: 
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/ddde9276-de82-499a-bb0f-d5c6de56df38)

Here, we would see all the 3 agreements

*Design for the new view to be added by @andywalton* 

- [ ] keep the Agreements button for `Your assets`, but without the `RESERVATION AND ACQUISITION AGREEMENT`

**Fixes for the ETO Page** 
- [ ] Once the `Investment memorandum` is signed, it should be shown instead of ISHA. `Term Sheet` is still shown before the IM.
So now we should show TS first, then IM.

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/c3b97d90-a5ee-4c1b-a194-46fbfc1df4b3)

- [ ] Signed  ISHA is removed from this view. The entitled investor will see it in `Portfolio` 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/74753d37-39d0-40e4-a412-d5429823c78f)

**Acceptance criteria**

- [ ] RAAA not available from `Your assets`
- [ ] RAAA available for downloads from `Past investments`
- [ ] Signed ISHA and Token Holder Agreement available from both sections
- [ ] Term Sheet is shown before Investment Memorandum
- [ ] Investment Memorandum is shown since signed, till the end of the ETO 
- [ ] Signed ISHA available only from `Portfolio`, for the relevant token holders

**Comment by pstroinski** [comment]
To be moved to asana @andywalton
