### ISSUE TITLE
Portfolio visual issue

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#3916]
**Description**
There is a problem with the "BIG" icons in the portfolio view
![image](https://user-images.githubusercontent.com/27957897/72448077-bea0b480-37b6-11ea-8c23-144d904dea0d.png)

**Environment**
`io`

**Steps To Reproduce**
Go to portfolio (but you need some pending payouts to see it, I recommend INV_ICBM_ETH_M_HAS_KYC_DUP_HAS_NEURO fixture)

**Expected behavior** 

![image](https://user-images.githubusercontent.com/18315589/72448923-23104380-37b8-11ea-9715-f433c7b86320.png)

![image](https://user-images.githubusercontent.com/18315589/72449095-666ab200-37b8-11ea-9cf2-8fb569dde9bb.png)

**Comment by glupiawymowka** [comment]
tested on stage
