### ISSUE TITLE
Create the Onboarding Widget

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3935]
**Background**
As part of moving to the new user onboarding we need to create a new component that resembels a state machine. 

**Designs**
Please speak to @andywalton should should you have any questions regarding this widget and it's various states.

The aim of the onboarding widget is to help and guide first time users in a more visual way so that they can successfully see and complete the steps needed to finish there account setup.

As a user can sign up using 3 methods, the widget steps might look different depending on if a user signed up with their email address for a Light Wallet or if they connected an existing wallet using Metamask or Ledger Nano. 

**Responsiveness** - please collapse the widget and hide (remove the thumbnail image) on screens that are smaller than our medium breakpoint. Ie. <768px. ie. anything smaller than our portrait table breakpoint.

Please see the designs in Zeplin here: https://app.zeplin.io/project/5dcae4b293ec9fff68a73bdd/styleguide/components?cseid=5e31632e7119da7e690b51c6

Look in sections titled:

1. Onboarding - Light Wallet states (Desktop/Tablet)
2. Onboarding - MetaMask/Ledger states (Desktop/Tablet)
3. Onboarding - Onboarding - Responsive (Mobile)

It is possible to open a step that you've already completed. Ie. if you verify your email and it's on step 2 asking you to backup your recovery phrase, then you should be able to click on the Verify your email heading and it will then show you the relevant state of that step. It acts as an accordion and will collapse and only show the active step and other steps will be hidden.

It should not be possible to jump ahead unless the business logic exists for that already, please follow the same logic as we current have in our My Account /  Profile section as this onboarding widget visually represents those steps we already have.

Please also ignore the ability to "hide" this widget for now. So the `x` icon at the top of the component should be hidden for now.

**Important to note:** Once the user has completed all the steps for account setup, then this widget should hide automatically. Ie. so in your Profile, when you have green tickets against all required account setup requirements that allow you to invest, once that happens this widget should not be displayed.

Speak to @Moejoe90 regarding the reusability of our existing component logic we have in the Profile section for this.

**Acceptance criteria**
In this ticket the widget should only be presented as a storybook stories. 

**Technical notes**
- This is concerned with the visuals and components creation 
- We should all status added to storybook. 
- We should have all status in our defined sized (Desktop/Tablet + Mobile) 
- The state Machine should be simple where each component reports the correct state based on the available logic
- We developed this component already as part of the Nominee dashboard. This include a few small design changes so take not of that please.

**Testing notes**

- The widget should change state as per the current behaviour we expect when a user completes there account setup via the profile section.

**Comment by andywalton** [comment]
@Moejoe90 - I updated this ticket with design links and more details. Happy to talk any dev through this before they start.

**Comment by AlexeyTuboltsev** [comment]
- It is possible to open a step that you've already completed -- this requirement has been dropped (ask @andywalton )

**Comment by glupiawymowka** [comment]
tested on stage for
Chrome + lightwallet
+ metamask
+ mobile
+ nominee
Firefox + lightwallet
