### ISSUE TITLE
Connect Onboarding Widget to Dashboard

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3936]
**Background**
Once the Onboarding Widget is composed with all correct states in story book we need to connect this comoponent to the dashboard and states. 

```
Draft
`Email Verify state` -> `Key backup state` -> `Kyc Info step`
```
**Designs**
Please compose the Onboarding widget onto the investor Dashboard as per this example view:
https://zpl.io/2GdzEWj

**Acceptance criteria**

**Technical notes**
This focuses on the logic, 
Most of the business logic is already there. @Moejoe90 Can add exactly which sagas are concerned with which state.

**Testing notes**

**Comment by glupiawymowka** [comment]
tested on stage
