### ISSUE TITLE
Add Portfolio Summary + Business Logic

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3938]
**Background**
To see how this is composed once completed, take a look here: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/screen/5e21a62020fe71558dc080d4
**Designs**
The designs for the components are here: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/styleguide/components?seid=5e31635560b01e541a3327d1

Please see all the states and responsive layouts here:
1. Dashboard metrics - All states (Desktop / Tablet)
2. Dashboard metrics - Responsive (Mobile)

For this ticket, only worry about the Portfolio section of the Dashboard Metrics. It's important that these components are developed as individual components that we compose together to create the Dashboard Metrics component.

Some product rules:
- [x] **Only show up to 3 portfolio assets** a user has and exclude NEU from as it has it's own section. If they have more than 3 (including reserved assets), we should change the call to action to read from `View Portfolio` to `View more`.
- [x] **For the Portfolio balance** - we should add up everything you own in your Portfolio and show this as EURs. This includes all your assets, including NEU and reserved assets. (This might change as I need to check this with @rudolfix).
- [x] **The component call to action** - if a user hasn't completed there account setup (ie. KYC) yet, then we should say `Complete account setup` - this should link to the My Account/Profile page.

**Acceptance criteria**
- [ ] Make sure all states are in story book.
- [ ] Connect the component to my assets Saga Add unit tests for sagas

**Technical notes**
Add all visual states to storybook. (Loading + Error + Empty + regular) state. 

**Testing notes**

**Comment by andywalton** [comment]
@drakkein @Moejoe90 - I've updated this ticket. I'm going to chat with @rudolfix to double check how we can total up the component balance. I'll write back here once it's confirmed.
