### ISSUE TITLE
Change My Neumark Component

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3939]
**Background**
This should be only a visual change. It makes use of existing components and has restyled them to work together.

To see how this is composed once completed, take a look here: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/dashboard?seid=5e21a62ec6308557a5061c6b

**Designs**
The designs for the components are here: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/styleguide/components?seid=5e31635560b01e541a3327d1

Please see all the states and responsive layouts here:
1. Dashboard metrics - All states (Desktop / Tablet)
2. Dashboard metrics - Responsive (Mobile)

For this ticket, only worry about the My Neumark component of the Dashboard Metrics.

Some product rules:
- [ ] This is exactly as per our current. It's simply a reskin so our existing logic stay the same.
- [ ] However, note how we now include the "payout banners" - incoming and claim available states.

**Acceptance criteria**
- [ ] The My Neumark component functions as per current, with the styling matching the updated designs and it should show the payout banners inside this component now.

**Technical notes**
We need all the possible status. (see Zeplin link above)
+ Component Loadiing + Error + Empty + regular 
+ With payout incoming + With payout claim 
+ About NEU button goes to a blog post in a new tab - same as current URL

Business logic for Neumark + Payout already exists

**Testing notes**
See above.

**Comment by andywalton** [comment]
@Moejoe90 @drakkein -> Added links and info to this ticket.
