### ISSUE TITLE
Change visuals for Dashboard Wallet Component

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3940]
**Background**
To see how this is composed once completed, take a look here: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/dashboard?seid=5e21a62ec6308557a5061c6b

**Designs**
The designs for the components are here: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/styleguide/components?cseid=5e31632e7119da7e690b51c6

Please see all the states and responsive layouts here:
1. Dashboard metrics - All states (Desktop / Tablet)
2. Dashboard metrics - Responsive (Mobile)

For this ticket, only worry about the Wallet component of the Dashboard Metrics. It's important that these components are developed as individual components that we compose together to create the Dashboard Metrics component.

Some product rules:
- [ ] This is exactly as per our current. It's simply a reskin so our existing logic stay the same.

**Acceptance criteria**
- [ ] The wallet component functions as per current, with the styling matching the updated designs.

**Technical notes**
+ Add all status to storybook 
+ Regular + Loading + Error + Empty wallets
+ The business logic should be the same, its a pure style change

**Testing notes**
* Same as acceptance and technical notes.

**Comment by andywalton** [comment]
@Moejoe90 @drakkein - updated ticket with design links.
