### ISSUE TITLE
Change General Dashboard Components Style (Footer + Header)

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3943]
**Background**
We will change the Navbar and Footer components. This could be done as a separate step independently from all the other work.

**Designs**
Please see the designs here:

Some layout examples for the Navbar & Footer examples for Desktop/Tablet & Mobile are: https://app.zeplin.io/project/5dcae4b293ec9fff68a73bdd/dashboard?seid=5e31687167876e5527b83549

See all the components in the Zeplin styleguide: 
1. **Navbar:** https://app.zeplin.io/styleguide/5dcae025a4cf6cfed74cab61/components?cseid=5e314a018dfe177ed75262de
2. **Footer:** https://app.zeplin.io/styleguide/5dcae025a4cf6cfed74cab61/components?cseid=5e314e85b8886880cc1b5edd

**Acceptance criteria**
Platform match designs.

**Technical notes**
Navbar and Footer should be done in one ticket

- [ ] Make sure of style in different sizes
- [ ] Check full view visual regression

**Testing notes**
This is a pure style edit.

**Comment by andywalton** [comment]
Added design links @drakkein @Moejoe90

**Comment by andywalton** [comment]
PS. I'd recommend working on this ticket together with #3982.

**Comment by glupiawymowka** [comment]
tested on stage for:
Chrome
Firefox
Safari mobile
