### ISSUE TITLE
Add new password input field component that shows hidden information when eye button is clicked

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3945]
**Description**
As part of the changes we are making to our Sign up / Log in views, we require the password input field to have additional functionality that allows the user to toggle the visibility of the password they have entered.

By default, all passwords should remain hidden until the user decides to toggle the visibility.

**Designs:**
View the password field as part of the "Onboarding" Zeplin project here - see Sign up / Log in views: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/dashboard?seid=5e205392bc6a8a7cdfef6f9e

Look here for examples of how the password field should function:
https://zpl.io/VDwo0gq

See password input field components here:
https://app.zeplin.io/styleguide/5dcae025a4cf6cfed74cab61/components?cseid=5dd280691f36296255b1252b

**Technical details**
+ you will need to investigate if the old toggle component fits with the designs
+ since terms of service toggle is not planned for now you don't need to change any business logic

**Acceptance:**
- [ ] The visibility of a users password should toggle between hidden / visible.
- [ ] By default, the password should be hidden
- [ ] The input field functionality should remain the same as per the styles shown here: https://zpl.io/2j9Zy0A

**Comment by andywalton** [comment]
@Moejoe90 added password field info here
