### ISSUE TITLE
Add new wallet selector

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3947]
**Background**
We are changing our wallet selector. In theory you should use the the new wallet selector should be simpler.

The only difference is the new wallet selector is only available in lightwallet register and lightwallet login. Once you click on metamask for example the view should change as per designs with no wallet selector.

**Designs:**
Please see the Connect with section that includes the two buttons - MetaMask/Ledger here:
https://zpl.io/aR78yJn

UPDATE: I've added the Wallet selector components here: https://app.zeplin.io/styleguide/5dcae025a4cf6cfed74cab61/components?cseid=5e31632e7119da7e690b51c6

Look under the Components section for the group titled: **Wallet Selector**.

The Wallet selector is now always visible on all Sign up and Log in views. It however will change depending if the user is Signing up using Email (ie. for a Light Wallet), using MetaMask or Ledger Nano. These buttons can therefore have 3 possible combinations.

![Wallet selector example](https://user-images.githubusercontent.com/609657/74088248-4dda7880-4a94-11ea-83b9-705f65fea827.png)

Use as follows:
1. Sign up/Log in for Light Wallet - show MetaMask and Ledger Nano buttons
2. Sign up/Log in for MetaMask - show Email and Ledger Nano buttons
3. Sign up/Log in for Ledger Nano - show Email and MetaMask buttons

Please use a `secondary-btn` for these two buttons.

Also, ask Andy if this is unclear.

**Acceptance criteria**
- [ ] This should only be a storybook addition
- [ ] The buttons should change correctly based on the Sign up or Log in url the user is on
- [ ] The buttons should only link the new link there are no Active states

**Technical notes**
+ Dev should create the new wallet selector component + 
Connect the buttons to the correct routes 

+ Dev should check the styles make sure of sizes. 

+ Both buttons are links that route to Browser or Ledger Link or to Light Wallet Login / Sign up views.

**Testing notes**

**Comment by andywalton** [comment]
@Moejoe90 I updated this ticket.
