### ISSUE TITLE
Metamask + Ledger Login

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3949]
**Descritpion** 
The moment we enter via the link we should start trying to access the wallet

**Designs**
See Zeplin *Log in with MetaMask/Ledger* flows here:
https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/dashboard?seid=5e20c02236c30c7dfbd284d0

Please see the section titled: **Log in with MetaMask/Ledger**

Take note of the Zeplin notes.

**Technical Note**
+ The logic/flow of the original should be the same this means the `hd path` for the ledger should remain etc
+ That also includes a situation that user connects a wallet for which we do not have user account created. we should still fully support it as it is now

**Comment by andywalton** [comment]
@Moejoe90 updated this
