### ISSUE TITLE
Lightwallet Recover

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3950]
**Background**
This is a refactoring of our Light Wallet Recovery flow.

**Designs**
See designs in Zeplin here under the section titled **Account recovery**: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/dashboard?seid=5e20bf10853c8c01a6428d58

Please ignore the "12/24 word" toggle for now. We will do this later.

**Acceptance criteria**
- [x] A user can recover their Light Wallet.

- [x] Add the recovery component to the  Light Wallet.

- [x] A user should be able to see error messages.

- [x] The same component should be used during wallet recovery in the profile

**Technical notes**
+ Ignore the toggle and 12 words recovery for now.

+ Rewrite the wallet recovery component so that it has all the words in one step.

+ You can use at the moment the same component we already have 

**Testing notes**

1. Same as acceptance.
2. A users should be able to recover their Light Wallet.
3. If the user is recognised as a new user, they will be asked to Sign up and import their wallet into a new Neufund account. (See technical note and comment below)
4. If the user is already a user of the platform, they will be asked if they want to change their existing email address and to change their password. (See technical note and comment below)

**Comment by rudolfix** [comment]
**technical note**
as a last step of fully completed recovery process (when new vault entry was created and user is in the dashboard seeing the confirm e-mail modal) you should call new `/confirm` method of the vault api.
```
/vault/{vault_id}/confirmation:
    put:
      operationId: api.encrypted_vault.confirm
      tags:
      - wallet
      summary: Confirm vault-id, delete all other vaults with same ethereum address
      parameters:
      - $ref: '#/parameters/vault_id'
      responses:
        202:
          description: Vault confirmed
        404:
          description: Vault not found
        406: 
          description: JWT-authentication does not match ethereum address stored in vault
```
* [ ] this call requires JWT with escalated permissions `MANAGE_USER_WALLET: str = "manage-user-wallet"` - obtain permission when logging in for seamless user experience
* [ ] this call may take a second to finish and can be implemented in fire and forget manner

what the call does: it will disable the possibility to login with the old salt + passwords combinations, this also enables us to implement password change in safe manner!
