### ISSUE TITLE
Changes to Eto View 

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3958]
**Background**
We will need to conduct a couple of changes to the ETO view.

1. On the top bar we need to have 3 states indicating the time in the past, present, future:
- To be publicly offered in Liechtenstein
  * for the offer that is in marketing listing and does not have the investment memorandum or prospectus uploaded (same for Germany)
- Currently publicly offered in Liechtenstein
  * for the offer that has the prospecuts/investmet memorandum already online (same for Germany)
- Publicly offered in Liechtenstein
  * For the offer that switched to all states after the public sale (so payouts, signing, failed) (same for Germany) 

This works like described in any setup of the ETO.

2. The timeline needs to be hidden on the Marketing listing and visible on the states starting from the Investment Offer listing (prospectus/investment offer uploaded)

This works like described in any setup of the ETO.

3. We need to add the disclaimer under the legal section. There should be a possibility to have 2 different disclaimers, one for DE offerings and one for LI offerings:
This is an advertisement and is intended only for informational purposes. A prospectus has been or will be submitted to the competent authority and can be viewed here when available. An approved prospectus is not an endorsement by any financial authority and investors should make an independent decision to invest based on the entirety of the information available in the prospectus.

This disclaimer is in any marketing listing and in any listing with the prospectus. In the case of the Investment Memorandum, this disclaimer disappears. 

**Designs**
Please see design in Zeplin here: https://zpl.io/2EpWerv

Note, only the disclaimer banner in the content of the page is a new component. There other changes are as described above.

**Acceptance criteria**
 - [x] Status changes depending on the ETO state: To be publicly offered/Currently publicly offered/Publicly offered
- [x] Timeline not visible in the marketing listing and visible in later stages
- [ ] New disclaimer visible during the whole eto process for the prospectus offerings and always on the marketing listings

**Comment by rudolfix** [comment]
technical note:

ad 1.
we are in `To be publicly offered in Liechtenstein` step if eto state is in "preview, pending, listed"
we are in `Currently publicly offered in Liechtenstein` if eto_state is in "prospectus_approved, on_chain" and on_chain_state is less than Signing = 3
the last state happens in `on_chain` with on chain state Signing and later

ad 3. the disclaimer is **always visible** in "preview, pending" eto states. and it **stays visible** if product is prospectus based (`offering_document_type` of `product` collection is `prospectus`)

**Comment by arjunu** [comment]
@rudolfix so for #1 the conditions look like
case 1: `PREVIEW || PENDING || LISTED`
case 2: `PROSPECTUS_APPROVED || (ON_CHAIN && onChainState < Signing)`
case 3: `ON_CHAIN && onChainState >= Signing`

what should happen if none of these are true?

**Comment by andywalton** [comment]
@arjunu - FYI I updated the disclaimer card and added a `box-shadow: 0 2px 4px 0 rgba(0,0,0,0.1);` inorder to match it to the other cards on the page. Please see updated Zeplin example.

**Comment by Moejoe90** [comment]
Lets add e2e tests for all these cases. The e2e tests should be simple tests that assert if the component is there or not
