### ISSUE TITLE
Add new Product Type to the Frontend

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3963]
**Background**
We will add a new product type. Please refer to
https://github.com/Neufund/platform-backend/issues/2413
https://github.com/Neufund/platform-contracts/issues/325
**Designs**
N/A
**Acceptance criteria**

- [ ] Given I'm an  issuer who wants to choose the new product all should work with no issues

**Technical notes**

**Testing notes**

**Comment by glupiawymowka** [comment]
this is more of a general problem, but we let the user type whatever max ticket they want, even if it exceeds the capital raise limit. 
Besides, this is tested on stage
