### ISSUE TITLE
Check then bring back userVerifiedOnChain check for e2e tests

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3969]
**Background**
There is a suspected issue with `assertIsUserVerifiedOnBlockchain`. My observation is that `assertIsUserVerifiedOnBlockchain` always returns `User not marked as verified on blockchain` error even in cases where the tests failed and the user already logged in.

**Designs**
N/A
**Acceptance criteria**

- [ ] Please confirm if the issue mentioned in the background is truly the case 

- [ ] If so please fix this hanging promise issue

**Technical notes**
N/A
**Testing notes**
N/A

**Comment by pstroinski** [comment]
fixed already
