### ISSUE TITLE
[KYC] Add missing PEP and income self-declaration field back to KYC individual flow

### ISSUE THREAD

**Issue by Trilbi** [Neufund/platform-frontend#3979]
**Background**
The PEP and income declaration fields are missing from the current KYC flow. These are required steps and need to be added back.

**Income declaration step** https://zpl.io/b6m7QmN  
- The options to choose from in the dropdown are, "Yes" and "No".
- Since this step is required, the "Continue" button remains disabled until the user chooses an option from the dropdown

**PEP (Politically Exposed Person) field** https://zpl.io/bJxAOWJ 
- The options to choose from in the dropdown are, "Yes, I am" and "No, I'm not".
- The info in the current tooltip needs to be included: https://zpl.io/VY74jkk
- This is an entirely new step (step 4 of 5) in the KYC flow

**Comment by glupiawymowka** [comment]
tested on stage
