### ISSUE TITLE
New header states

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3982]
**Background**
There are a couple of states for the header that needs to be developed. based on the specific route/state

**Designs**
![Navbar examples](https://user-images.githubusercontent.com/609657/73769183-87e90900-477a-11ea-8ab5-95426c8ce555.png)

Please see an example of the navbar states here: https://zpl.io/V0mQvRl

You can see the components here: https://app.zeplin.io/styleguide/5dcae025a4cf6cfed74cab61/components?seid=5e314a018dfe177ed75262de

> Please note the comments in Zeplin, I just updated the Navbar states to show the "Full-screen wizard" navbar that has the `Close X` button to the right of the brand. We use this with "wizard steppers" like our new KYC flow and for MetaMask/Ledger Nano Log in / Sign up views as well as the Wallet Recovery flows.

This ticket is related #3943. Would recommend working on these two together as they're related.

**Acceptance criteria**
- [x] Navbar header states are in Storybook
- [x] These states are correctly applied as per the example navbar states page and they work across device sizes.

**Technical notes**
None

**Testing notes**
Same as acceptance. You can see which state the navbar header should be in by looking at the Onboarding user flows here: https://zpl.io/amv1gBe

**Comment by glupiawymowka** [comment]
tested on stage for: 
Chrome
Firefox
Safari mobile
