### ISSUE TITLE
Remove all time related polling and use new block event instead 

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#3990]
**Background**
Currently we have a couple of services that pool for information based on a clock or manually added arbitary time limit. 

We will unify the implementation of all these sagas and use the unified new block status
**Designs**
N/A
**Acceptance criteria**

- [ ] There should be no more time polling unless necessary

- [ ] All sagas should react correctly to the new block event

**Technical notes**
This will optmize our requests so that all the app information is somewhat taken at one point. without the need to follow up on arbitary timers

**Testing notes**

**Comment by glupiawymowka** [comment]
not sure I can really test it besides the general regression. 
At least that's what I get from this ticket.
