### ISSUE TITLE
Add navigation library to mobile app

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3991]
**Background**
Given that we have wireframes now we can progress further with the initial setup for the mobile app.

Please add a navigation library and a couple of mock routes (we know how the app gonna look from the wireframes) just for us to know how we should use it.

**Technical notes**
Also at the moment, react-native community is split by `react navigation` and `react native navigation` so please research which one is better for us.

**Testing notes**

**Comment by DmitriyNoa** [comment]
I heard positive recommendations on the Airbnb navigation library https://github.com/airbnb/native-navigation. Also to consider.

**Comment by desfero** [comment]
After some research and going through the docs `react-nativation` seems the most promising library for us:

My thoughts about the alternatives
`native-navigation` - completely unmaintained from 2018 and even marked as not production-ready.
`react-native-navigation` - a good one as navigation is handled natively so it's quite performant but there is quite a small amount of customization options. 
`react-navigation` - the one below by community and the most popular one with support for a ton of custom customizations.
`react-router-native` - a native version of `react-router`, this one is not suited for the proper native navigation as the idea here is to mimic the web routing in the native app which is not the same.

From npm trends `react-navigation` is clearly the most popular https://www.npmtrends.com/react-navigation-vs-react-native-navigation-vs-native-navigation-vs-react-router-native
