### ISSUE TITLE
Expose the mobile app for QA and product owners 

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#3996]
**Background**
To make our testing process easier we need to find a way to distribute the apps without cloning a repo and running it manually.

At the moment there are a couple of ways to provide a dynamic installation link without putting the app into the store, mainly I'm aware of the `Visual Studio App Center` and `Firebase App Distribution` (previously https://get.fabric.io/). 

Therefore as a part of this ticket, we need to analyze what's the best approach for us and integrate it into our mobile app.

**Technical notes** 
Also, we need to analyze the scalability and pricing model of a chosen approach. The final decision should be approved by @rudolfix as for e.g. we already plan to use `push notification` from firebase so maybe we should go with Firebase App Distribution?

**Comment by pstroinski** [comment]
Third one: Amazon AWS Mobile
