### ISSUE TITLE
[Copy] - Change Invest Now call to action buttons

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3997]
There are two instances where we have incorrect invest button call to actions. I've looked through our locales file (https://github.com/Neufund/platform-frontend/blob/master/packages/web/intl/locales/en-en.json) and I see two instances we need to change:

`"investment-flow.invest-now": "invest now"`

"shared-component.eto-overview.invest-now": "Invest now",

- [x] Please change the copy from `invest now` to simply read `Invest`.
- [x] Check that there are no other instances of buttons where the call to action reads `Invest now`. If so, change then to `Invest`.

**Comment by glupiawymowka** [comment]
tested on dev for public sale and presale case. 
No running ETO on stage
