### ISSUE TITLE
Wallet Management

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#4006]
**Background**
High level interface to various wallet management functions that wrap #4000 and #4001 and provide convenience methods without knowing the details of wallet storage, schema and key storage.

Note that wallet access for signing and verification happens via #4002 

**Acceptance criteria**
* [x] wallet status: does it exist or not
* [ ] backup status: do we have phrases backup? do we have cloud backup
* [x] wallet metadata access: uid, public key, wallet type anything else we need
* [x] create new wallet (BIP-32 wallet with standard derivation path)
* [x] import wallet from list of pass phrases
* [x] import wallet from private key hex string
* [ ] import wallet from light wallet (salt, password) - we'll have separate ticket on that
* [ ] import cloud backup  - we'll have separate ticket on that
* [x] export seed as phrases (unsafe - may be used only to do seed backup)
* [x] export private key as hex string (as above)
* [ ] optionally: delete seed from wallet if cloud/pass phrases backup done

**Comment by desfero** [comment]
Cloud backup and light wallet import gonna be moved as a separate ticket
