### ISSUE TITLE
Chromium based browsers wrong size grid

### ISSUE THREAD

**Issue by drakkein** [Neufund/platform-frontend#4013]
**Description**
After update to version 80 of Chromium engine we've got issue with our Investment Opportunities grid. Problem occurs only on browsers updated to recent Chromium versions. Firefox, Opera, legacy Edge and Safari are not affected by problem. 

**Environment**
.io

**Steps To Reproduce**
Open [https://platform.neufund.io/](https://platform.neufund.io/) browser with Chromium engine in version 80. (Chrome, Brave, new Edge) 

**Actual behaviour**
Second and Third column is different from the first one. 

**Expected behavior**
All columns are the same 

**Comments, context, logs**

**Screenshots**
_Chrome v79_
![image](https://user-images.githubusercontent.com/10601291/74184885-e107df80-4c47-11ea-9750-5d8efc6fe13c.png)

_Chrome v80_
![image](https://user-images.githubusercontent.com/10601291/74184920-f250ec00-4c47-11ea-9dc0-bac982d7ca9a.png)

**Comment by glupiawymowka** [comment]
tested on stage
