### ISSUE TITLE
[ETO widget] - fix latency of the widget in whitelisting state

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4014]
**Description**
Some of the whitelisting states are loading slowly (even after a couple of minutes). This is giving an impression of a buggy page

**Env**
Mostly visible on stage, but other environments can be affected

**Actual results** 

- [ ] Correct widget state loads on the ETO page refresh/open
- [ ] Incorrect (old) widget state loads in the open, inactive tab after ~10min

pic 1. Initial state after refresh *(incorrect because investor count didn't load )*
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/1b2a9654-1bfa-40e1-b56f-c435c5026635)

pic 2. When kept ~10 min in the inactive tab *(incorrect because wrong copy)*
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/1a9af21b-ff38-4cc9-9860-88d45ff7b179)

correct state with correct copy:
![image](https://user-images.githubusercontent.com/4038217/78128881-f5ca4d80-7416-11ea-9405-459c384d7fae.png)

- [ ] some previous whitelisting states are visible before the expected state loads 
*(investor logged in and whitelisted, ETO date not settled)*

![Large GIF (640x114).gif](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/baaff7ea-26f6-46a2-9ca0-badeb5361ea3)

**Expected results**
~The current commitment is not visible to the unregistered user~
- [x] there is no change on the widget if the page is being left inactive
- [x] the closed/filled whitelist state is visible instantly after reload, without previous states appearance

**Comment by glupiawymowka** [comment]
I postpone it until I find out how it should actually look now, I remember that some designs were changed in the meantime

**Comment by arjunu** [comment]
Ticket updated to include investor count.

**Comment by glupiawymowka** [comment]
the refresh part needst to be retested on stage as codechecks doesn't allow refreshing. 
Everything else works fine on stage, the state doesn't switch even after a long waiting time

**Comment by glupiawymowka** [comment]
tested on stage
