### ISSUE TITLE
[Portfolio view] Compose the view using the new components

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4030]
**Background**
This ticket is related to the Portfolio view update epic #4028. Please take the components that you created and added to Storybook in #4029 and compose the view changes as per the screen designs you'll find below.

**Designs**
![Master  Portfolio](https://user-images.githubusercontent.com/609657/74375752-3297a200-4de1-11ea-85f5-76bc33d181ff.png)

The above is an example of how this page might looked once it's composed.

Please visit the Zeplin project here for the Portfolio view screen designs: https://zpl.io/b6m6OBy

Take note of the following:
- [ ] In general please see the spacing between elements, between sections, the page title and the text displayed.
- [ ] The typography of the headings, section titles and paragraphs and the relevant  #line-heights.
- [ ] There are more information icons (i) to the right of section titles. These display a tooltip with section information. Please see copy in for this here: https://app.zeplin.io/project/5e44287708ae50b499274757/dashboard?seid=5e445c6ffe647394ea434b38
- [ ] The empty/error and loading states have a minimum "table height". We don't show the table head and total rows when these states are active.
- [ ] Please use our existing loader and not the placeholder image show in the loader component.
- [ ] Table data for the values have been right aligned with the table header labels for better legibility.
- [ ] The table row call to actions are aligned to the right of each table row. The Primary and Secondary buttons used are separated by 16px.

**Acceptance criteria**
- [ ] The composed view adheres to the new designs as detailed above and business logic of the current existing page.

**Technical notes**
- [ ] Nothing technical here other than some summary totals that need to be required - this would most likely have been handled already when creating the components.

**Testing notes**
- [ ] The general logic of this page is exactly as per our current page, the same data is displayed with the exception of additional summary totals for some values. This is therefore more a clean up of the visual UI rather than a completely new page.

**Comment by Moejoe90** [comment]
As per discussion with @Louisswryan I understand that we will leave the issue of responsivnesss for now and keep the old functionality

**Comment by pavelneu** [comment]
Tested on IO.
Report is here:
https://neufund.ontestpad.com/script/15/report/?auth=9ae6c3872b71463f0418f5932ad2a5d9

Several minor issues still exist:
- ICBM Investor has 0.0000 NEU as reward instead of `~`
- clicking on pending payouts' tooltip requires a fast movement (jump) from the tooltip to the link
- enhancement: the tooltip's link should have target="_blank"
- the ether price fluctuates on io from 167 to 210 EUR per 1 ETH because of an exception on backend side: https://github.com/Neufund/platform-backend/pull/2537

**Comment by Moejoe90** [comment]
@pavelneu Regarding the `0.0000` I think we should keep it as 0.0000 as its useful information. 
It doesn't make sense to hide it the fact is you are getting no neu reward from this investment why would you want to shouw some special symbol? 

any that is up for debate
