### ISSUE TITLE
BlockTracker request returns an error during LightWallet connect process

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#4045]
**Description**
when dealing with LightWallet (log in or register flow), there's an error thrown by our `/user/transaction/tx_ethereum_json_rpc` API during LightWalletConnect process:
```
PollingBlockTracker - encountered an error while attempting to update latest block:
Error: {
  "detail": "Additional properties are not allowed ('skipCache' was unexpected)",...
```

this happens during initialization of LW,  at the moment the `engine` (`engine = new Web3ProviderEngine();`) is started and then immediately stopped. Between those two moments It calls blockTracker with default options that include 'skipCache' and BlockTracker issues a request to our API. The skipCache in the request is unexpected and request returns an error. 

Solution: either add `skipCache` option to API schema or explicitly add the PollingBlockTracker with skipCache set to false.

see LightWalletConnector.ts:84-95

**Environment**
dev
**Steps To Reproduce**
open console and try to log in with LightWallet

**Actual behaviour**
see above

**Expected behavior**
no errors are thrown

**Comments, context, logs**

**Screenshots**
![Screen Shot 2020-02-17 at 13 40 07](https://user-images.githubusercontent.com/14041336/74654632-0ab29080-518b-11ea-875b-1d71b93d0f06.png)

**Comment by glupiawymowka** [comment]
I still get in both on dev and stage
![image](https://user-images.githubusercontent.com/18315589/82202554-5e578600-9902-11ea-899e-9f99983ef676.png)

**Comment by rudolfix** [comment]
use `NullTracker`

**Comment by glupiawymowka** [comment]
tested on .io

**Comment by glupiawymowka** [comment]
tested on stage
