### ISSUE TITLE
Wrong value is showing up in ETO View 

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#4047]
**Description**
There are cases where a 0 is showing up in the ETO View
Ask @Moejoe90 for more information 
**Environment**
All
**Steps To Reproduce**
Simply go to any ETO view that contains `lastFundingSizeEur`
**Actual behaviour**
shows 0 
**Expected behavior**
shouldn't show anything
**Comments, context, logs**

**Screenshots**

**Comment by glupiawymowka** [comment]
Given there was no previous funding round, the value is not shown anymore
