### ISSUE TITLE
[Onboarding widget] - Layout bug

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4052]
**Description**
Please correct a paragraph spacing issue on the *Backup your recovery phrase* step of the Onboarding widget for Light Wallet users.

![Screenshot 2020-02-18 10.44.07.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/a42f24d2-4c30-44b4-907c-29ac6742c327)

The spacing between the two paragraphs of copy for this step should have a paragraph spacing between them. Currently it's a line break. It should look as follows:
![Onboarding:LW-001b.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/a13faa54-8510-4a4b-80e4-ea189afa7c5f)

**Environment**
.io & .net at the moment

**Steps To Reproduce**
1. Create a new account (Light Wallet) by signing up with email
2. Verify that email address to move to step 2
3. You'll see the copy layout issue as described above.

**Expected behavior**
As described above.

**Comment by andywalton** [comment]
@AlexeyTuboltsev -> here's a small layout bug in the Onboarding Widget (Light Wallet) user.

**Comment by glupiawymowka** [comment]
tested on .io for: 
- chrome
- firefox
- mobile
