### ISSUE TITLE
Handle email confirmation email

### ISSUE THREAD

**Issue by krzkaczor** [Neufund/platform-frontend#406]
- send a request to one of the API services to confirm email (does it need auth?)
- it should have login data (salt, email etc) so user can login easily (if he is not logged in)
Blocked by backend @Exef

**Comment by Moejoe90** [comment]
https://localhost:9090/login/light?email=krzkaczor@gmail.com&salt=nZwEhYq51ZUYk3JVOosUkWBSKwid1cj0GbfREyOh9i8=
