### ISSUE TITLE
Setup user biometrics for mobile app

### ISSUE THREAD

**Issue by DmitriyNoa** [Neufund/platform-frontend#4064]
**Background**
As part of implementing secure App storage #3998 - set up user biometrics support (face or touch id).

**Designs**

**Acceptance criteria**
- [ ] Platform independent Interface to access biometrics
- [ ] Check if biometrics are available.
- [ ] Check if biometrics are enabled.  
- [ ] Face ID.
- [ ] Touch ID.
- [ ] Fingerprint scan (android).

**Technical notes**

**Testing notes**

**Comment by huesforalice** [comment]
Done with secure storage PR
