### ISSUE TITLE
Research a way for getting tx data into data

### ISSUE THREAD

**Issue by krzkaczor** [Neufund/platform-frontend#407]
We need to have a way to track tx for neumark token, and ether token and ether (? should we combine ether and ether token?).

![image](https://user-images.githubusercontent.com/1814312/38244734-e1684834-373b-11e8-87cd-34de16458229.png)

**Comment by banciur** [comment]
https://github.com/EverexIO/Ethplorer/wiki/Ethplorer-API 
It has limit to last 10 operations. We need to contact them to see if its possible to get all operations and check if it supports  EUR-T and ETH tokens. Then maybe we could use it directly from dapp. 

Other solutions will require our own endpoints and some caching.
