### ISSUE TITLE
wallet recovery: add API call to disable the old vault

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#4075]
_extracted from #3950 :_

as a last step of fully completed recovery process (when new vault entry was created and user is in the dashboard seeing the confirm e-mail modal) you should call new `/confirm` method of the vault api.
```
/vault/{vault_id}/confirmation:
    put:
      operationId: api.encrypted_vault.confirm
      tags:
      - wallet
      summary: Confirm vault-id, delete all other vaults with same ethereum address
      parameters:
      - $ref: '#/parameters/vault_id'
      responses:
        202:
          description: Vault confirmed
        404:
          description: Vault not found
        406: 
          description: JWT-authentication does not match ethereum address stored in vault
```
* [ ] this call requires JWT with escalated permissions `MANAGE_USER_WALLET: str = "manage-user-wallet"` - obtain permission when logging in for seamless user experience
* [ ] this call may take a second to finish and can be implemented in fire and forget manner

what the call does: it will disable the possibility to login with the old salt + passwords combinations, this also enables us to implement password change in safe manner!

**Comment by pavelneu** [comment]
Checked on codechecks, 
the confirmation request is sent `/confirmation` during the last step of successful account backup.
The previous login/access link does not work for that user.
