### ISSUE TITLE
[ETO widget] - marketing listing widget always shows "investment memorandum" tag

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4086]
**Description**
Even if the user is using the prospectus as per the product type chosen, `Investment memorandum` is shown in the widget. 
This may make people think that the offer will be memorandum, not prospectus-based. 

**Environment**
all 

**Steps To Reproduce**
1. Login to  ISSUER_PREVIEW
2. Change the product type to Retail Growth ETO  (Prospectus-based) 
3. In the backoffice, hard-add a Nominee to Planti ETO 
4. Go back to the Issuer dashboard and fill out the missing forms, upload term sheet
5. Go to the ETO Page and switch between the issuer's preview and investor's view (not doable on codechecks) 
6. Accept Terms sheet in the backoffice and check the widget again 

As an addition to this ticket, please align the first TBA (with tooltip) with the others
**Actual behaviour**
- [x] marketing preview (with misaligned TBA) 
![image](https://user-images.githubusercontent.com/18315589/75037774-3f895500-54b5-11ea-9b7b-72792c743403.png)

- [x] investment offer published (correct document type shown) 
![image](https://user-images.githubusercontent.com/18315589/75037836-5f207d80-54b5-11ea-9789-8700ea11ec0f.png)

**Expected behaviour**
- [x] The tag is showing the actual document type depending on the product type, either `Prospectus` or `Investment memorandum`
- [x] The tag changes with the change of the product type
- [ ] The tag never shows `Prospectus approved`, unless Term sheet with investment terms is published from the backoffice
- [x] The first TBA is aligned with the others
- [x] The tooltip still works

**Comments, context, logs**
As agreed with designers, we're not fixing the tooltips in general for now as they're waiting for the full styling changes

**Screenshots**

**Comment by rudolfix** [comment]
in PREVIEW state the type of offering document is unknown as product may change. that's the reason we show some default to investor. we need to come with some idea @andywalton ? should we just hide "prospectus approved" / "memorandum" box until ETO is `listed`? as I mentioned before listing such details should not be visible - just marketing

**Comment by pstroinski** [comment]
@rudolfix this was already discussed with Dialika. We need to show the proper document that's assigned to the certain product type, we shouldn't hide the document

**Comment by rudolfix** [comment]
OK - then I'm moving to this ticket to backend, beacuse it's a purely backend change

**Comment by rudolfix** [comment]
what about this 
> The tag never shows Prospectus approved, unless Term sheet with investment terms is published from the backoffice

so should we or should we not show it? anyway backend change is required so I'll move this ticket there when we agree on the above

**Comment by pstroinski** [comment]
> what about this
> 
> > The tag never shows Prospectus approved, unless Term sheet with investment terms is published from the backoffice
> 
> so should we or should we not show it? anyway backend change is required so I'll move this ticket there when we agree on the above

- when we have a product selected which has a memorandum we show it how it's now - memorandum in gray, and when uploaded we show normal memorandum document
- when a product with prospectus is selected we show prospectus in gray (without saying it's approved) and when the approved prospectus is uploaded we show approved prospectus like it's now in later stages

**Comment by glupiawymowka** [comment]
no `prospectus approved` fixture to check the state transition

**Comment by glupiawymowka** [comment]
tested on stage (without the on-chain case that needs to be tested separately as a part of the full ETO listing flow)
