### ISSUE TITLE
MVP for Impact on platform

### ISSUE THREAD

**Issue by Louisswryan** [Neufund/platform-frontend#4090]
We have a starting point for the introduction of impact into our platform.

The current solution on the issuer side, is for impact to be included as another optional input field in the 'pitch' section of company information on the issuer side. 

This new input field is to be placed underneath 'Market Traction' and above 'Roadmap' and will use the same rich text editor and ui component as both of those input fields.

Seen below:

![Screenshot 2020-02-24 at 12.12.18.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/a89a8331-535a-45e6-9d41-e55f999ab6ee)

On the investor side, impact will again follow the same rules as the content from the 'pitch' input fields. It will be added to the stack at the bottom of the listing page with all of the pitch details. See below

 ![Screenshot 2020-02-24 at 11.55.06.png](https://images.zenhubusercontent.com/5c5184c7df0733a30553c211/e27e457c-407a-4cf6-b18f-acc473e6ee18)

If you have any questions or want clarification, please ask.

Thanks

**Technical Details**
+ Please hide the form under a feature flag I sugggest the name `NF_ISSUER_IMPACT_COMPANY_ENTRY`. 
+ We need to also have documentation about the name of this feature flag and what it does

**Comment by Moejoe90** [comment]
Looks good to me and easy to implement

**Comment by pstroinski** [comment]
We need a backend ticket for it too

**Comment by Moejoe90** [comment]
I have edited the ticket with information regardng adding a feature flag so we don't have to wait for the backend implementation
