### ISSUE TITLE
Log In with Ledger

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#4108]
This is a copy of #3949. New design should be synced with the Ledger flow, let's add it to this ticket

**Descritpion** 
The moment we enter via the link we should start trying to access the wallet

**Designs**
See Zeplin *Log in with MetaMask/Ledger* flows here:
https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/dashboard?seid=5e20c02236c30c7dfbd284d0

Please see the section titled: **Log in with MetaMask/Ledger**

Take note of the Zeplin notes.

**Technical Note**
+ The logic/flow of the original should be the same this means the `hd path` for the ledger should remain etc
+ That also includes a situation that user connects a wallet for which we do not have user account created. we should still fully support it as it is now

**Comment by andywalton** [comment]
Thank you, @Louisswryan is on it and we'll let you know when the designs are added here

**Comment by Louisswryan** [comment]
Hello,

Designs for Ledger Nano sign up flow are complete. 

Zeplin link here: https://app.zeplin.io/project/5e20533697f09f7ff8d0726d/dashboard?seid=5e5ce251430c5778c4f57524

The solution begins much the same as that with Metamask, just with some word changes for Nano users.

Once the user has reached the point at which they would have completed the Metamask flow, they reach the steps that are unique to Ledger Nano.

The user arrives at the 'select wallet' screen, here: https://zpl.io/VkvdxZq 

This screen in an overlay that operates like a full screen modal with the close icon moved into the header. An example of this is already in use in the KYC flow. In that example, the CTA in the bespoke header reads 'Save and close', here it reads, 'Cancel', apart from that one change, we can reuse that full screen modal.

The values displayed in the 'Select wallet address' component are any wallet addresses that have transactions performed on them and we show above the number of results that are being shown. A wallet is selected simply by hitting the select button to the right of the values.

The wallet addresses are truncated to our standard format. Should the user desire, the can reveal the full address on hover, seen here: https://zpl.io/VQ8kGwn (a further ticket will be written to implement this address reveal across the platform)

Another option the user has, is to hit the 'show more' button underneath the wallet selector component. The result of this action will be to reveal every wallet address that the user has in order of derivation path, seen here: https://zpl.io/bzerGD3

At this point, the component will change to reveal the total results with navigation to cycle through the overall amount in blocks of results. In the designs here, we have this number at blocks of 25 results but let's just leave this quantity as it is currently. Also the 'showing X' information must change accordingly to showing X of the total.

The user may cycle through to reveal the next block of results, seen here: https://zpl.io/V1dXjWJ All that changes at this point is the option to cycle backwards (previously disabled) is now active.

Should the user be in this expanded list and use the search bar in the component header, results that contain their search term will be shown. As well as this, the 'showing X' value in the header changes back to 'showing X result' like the original 'select wallet address' screen.

Once a wallet is selected, the user should see a modal instructing them to sign on their Ledger. Once signed, the flow is complete.

Please ask with any questions,

Thanks

**Comment by Moejoe90** [comment]
```
The values displayed in the 'Select wallet address' component are any wallet addresses that have transactions performed on them and we show above the number of results that are being shown. A wallet is selected simply by hitting the select button to the right of the values.
```

I think we should skip this point for now as it will require a significant change in our logic
