### ISSUE TITLE
Change copy on the widget (register button)

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#4114]
**Description**
We need to change the copy on the investment widget where we display register button. Currently we have:
![image.png](https://images.zenhubusercontent.com/5beab1a20cefa317ea424319/29dd68a7-c327-41a3-88df-82d454286bdf)
Copy: "Interested in taking part in this offering? Register and start building your investment portfolio today!"

It should be changed to:
![image.png](https://images.zenhubusercontent.com/5beab1a20cefa317ea424319/eddf6d48-7b4d-482f-8fb9-0edffe3b52b2)
Copy: "Interested in the company? Register and find out more!"

**Environment**
All

**Steps To Reproduce**
Go to the listing page of an ETO that is not yet finished as a logged-out/not registered user.

**Actual behaviour**
Around the register button we have the text:
"Interested in taking part in this offering? Register and start building your investment portfolio today!"

**Expected behaviour**
The register button should have the text:
"Interested in the company? Register and find out more!"

**Comment by glupiawymowka** [comment]
please keep the copy in two lines to prevent the ugly one-word paragraphs 
![image](https://user-images.githubusercontent.com/18315589/75453869-d9994380-5974-11ea-8ab0-dd8a0e70ee44.png)

**Comment by glupiawymowka** [comment]
tested on stage
