### ISSUE TITLE
[ETO Page] - visible page reload bug 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4121]
**Description** 
Registered user can see the previously opened ETO page before the one that was opened as a second one opens. 

**Env**
.io 

**Steps to reproduce** 
1. Login as any investor user 
2. Open an ETO Page, look at the state, banner, widget
3. Go back to the dashboard
4. Select any other ETO 
5. Open the ETO page, look at the state, banner, widget

**Actual results** 

![eto reload small.gif](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/4d1cfa1b-2e77-4805-abfe-5d99b74a9be9)

- [x] the previously chosen ETO Page's details are shown before the current ETO loads

**Expected results** 
- [x]  The chosen ETO Page loads as soon as it's opened

**Comment by pavelneu** [comment]
Tested on branch:
The fix works properly, the caching is prevented, 
the bug is not reproduced anymore.

**Comment by glupiawymowka** [comment]
tested on stage
