### ISSUE TITLE
Connect Wallet Connect to a mocked wallet as an initial test

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#4130]
**Background**
Once we have wallet connect as a hooked wallet. We will need to connect to a mocked wallet that simply signs messages and transaction automatically as a test. 

have a look at `truffle-privatekey-provider` we already have it in our package.json and it should automatically sign all transactions and fullfill all wallet features.
**Designs**
N/A
**Acceptance criteria**

**Technical notes**

**Testing notes**

**Comment by AlexeyTuboltsev** [comment]
as discussed, we don't need truffle for this, it can be done with the `https://github.com/WalletConnect/walletconnect-test-wallet`
