### ISSUE TITLE
Missing assets while logged starting from lading page

### ISSUE THREAD

**Issue by drakkein** [Neufund/platform-frontend#4141]
**Description**
If you login in starting from landing page (wait for Investment opportunities to load) you will see that you have no assets in your portfolio for few seconds.

**Environment**
Probably all

**Steps To Reproduce**
Go to landing page, click login and login as any account which has some tokens in portfolio. 

**Actual behaviour**
`You have no assets in your portfolio yet.` message is being displayed. 

**Expected behaviour**
Show loading indicator until all data is ready. 

**Comments, context, logs**
We are assuming that ETO's are loading while `displayOrder` from etos state is set as undefined (`packages/web/app/modules/eto/sagas.ts:430`). If we start from landing page and wait for ETO's to load we have populated state, which never gonna be erased, but we do not have token data loaded. In that case we are no showing loading indicator anymore, but as we do not have detailed data, we also show that user have no assets (`selectMyAssetsWithTokenData` selector). 

**Screenshots**
![image](https://user-images.githubusercontent.com/10601291/75820059-f9c56a00-5d9b-11ea-9968-b052a16cea68.png)

**Comment by glupiawymowka** [comment]
tested on stage
