### ISSUE TITLE
[ETO Page] - images overlapping Pitch fields

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4143]
**Description**
 if the image in any of the `Pitch` form inputs is left or right-aligned, it overlaps the area of the other fields: 

**Environment**
.io, .net

**Steps To Reproduce**
1. login as any ETO in Draft or preview state (ISSUER_PREVIEW)
2. go to `pitch`
3. add images both left and right aligned, each in another input field
4. Save and check the `pitch section on the ETO Page

**Actual behaviour**

![image](https://user-images.githubusercontent.com/18315589/75798155-73e2f800-5d76-11ea-842c-256cfe179da1.png)

**Expected behaviour**
images stay inside their input's area 

**Comments, context, logs**

**Screenshots**

**Comment by pavelneu** [comment]
Tested on codechecks:
Pictures with:
- left,
- right,
- center aligned

surrounded by:
- text with heading, bulleted and numbered lists,
- pictures left, right and center aligned

Behaves as expected.
