### ISSUE TITLE
Company listing page copy edits

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4154]
Due to our new ETO product type and for consistency purposes to avoid confusion with what we say in legal documents, we are required to make some copy changes to our company listing page.

 1. General copy changes:
- [x] Change the heading "ETO Investment Terms" to "Investment terms"
- [x] Change the heading “ETO Timeline” to “Investment timeline” 

 2. "ETO Investment Terms" component copy changes:
- [x] Change "INVESTMENT AMOUNT (INCL. DISCOUNTS)" to "TOTAL INVESTMENT AMOUNT"
- [ ] For the above "Total investment amount" copy change, please also change the amounts we show - currently we display what these amounts would be due to the presale discount an issuer might include, please change the amounts so that the amounts before any presale discount are shown. You will therefore need to update the tooltip copy. Please make it read: `The target investment amount with presale discount included is 900.2k-4M.`
- [x] Add an info tooltip to accompany the “Ticket size” field (add our [i] icon). This tooltip should read: “Investment amount per investor per investment"
- [x] Remove “Token tradable” from the terms section TOKEN HOLDER RIGHTS

Please speak to @andywalton or @Vanilizer if you have any questions.

**Comment by pavelneu** [comment]
Checked on branch:
all changes were made according to the ticket.
