### ISSUE TITLE
[ETO Forms] - Media links containing capital letters are being transformed

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4165]
**Description**
Given the media link that the issuer want to use on their listing page contains capital letters, these are automatically being transformed into the small ones. 
This is causing opening a wrong website and throws an error that the page doesn't exist. 

**Steps to reproduce**
1. Find a link containing capital letters, like www.example.com/About-Capital_Letters
2. Paste the link into `Media` -> Media and press links
3. Save the form and go to the ETO Page
4. On the right side of the page, find your link and open it 

**Actual behavior** 
- [x] The link that opens will be in the form www.example.com/about-capital_letters
- [x] Most likely the page that was linked won't open 

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/b10e22ac-9dd5-4b79-bc29-7c0ef898f617)

**Expected behavior**
- [ ] The links are not being transformed into small letters
- [ ] The linked page opens

**Comment by pavelneu** [comment]
Checked on branch, 
the capital letters are not changed to lowercase ones.
