### ISSUE TITLE
[Token Transfer] - Checkbox "Not verified address" is automatically unmarked during transfer

### ISSUE THREAD

**Issue by pavelneu** [Neufund/platform-frontend#4179]
**Description**
The "This is a new address" checkbox is automatically unmarked when user tries to send tokens via Token Transfer modal to not verified address.

**Environment**
io

**Steps To Reproduce**
1. Login using fixture ("INV_HAS_EUR_HAS_KYC"), 
open Portfolio, click on Send button in Your assets block
2. Type not verified address, (e.g. 0x00b30CC2cc22c9820d47a4E0C9E1A54455bA0883)
3. Click on the "Accept not verified address" checkbox
4. Click on `Transfer all` link (or type your own amount)

**Actual behaviour**
The button is disabled, the tick is gone from the previously selected checkbox ("Accept not verified address"). The user has to select this checkbox again.

**Expected behaviour**
The Continue button is enabled

**Comments, context, logs**
@drakkein: we are performing wallet address check on every change in form

**Comment by glupiawymowka** [comment]
fixd
