### ISSUE TITLE
/api/analytics-api/transactions/me is being used for polling

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#4190]
**Description**
`/api/analytics-api/transactions/me` should be changed and use `/new` instead of pooling
**Environment**
N/A
**Steps To Reproduce**
N/A
**Actual behaviour**

**Expected behaviour**

**Comments, context, logs**
Use existing `getUpdatedTransactions` 

**Screenshots**

**Comment by huesforalice** [comment]
One note from my side. TX History is moving to shared. We can probably wait to implements this until tx history is in shared on master.

**Comment by AlexeyTuboltsev** [comment]
`analyticsApi.getUpdatedTransactions()` uses `/transactions/new/me`
no change needed, closing the ticket
