### ISSUE TITLE
unsupported browsers - fix unsupported browsers behavior

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4212]
**Description** 
The default windows10 browser, Edge, is not supported by our platform. 
~This is okay, but if the user opens the access link in this browser, they will see the blank screen without any information on what is happening.~

According to @desfero this browser in the newest version should work, so there is another thing to fix in this ticket. 

This was reported also on Firefox for MAC (but it's hard to reproduce anything more than a bit longer loading)

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/16bd22bc-1107-4da0-9b01-a2191d544a6e)

We should create a page that would contain some information and instructions for all unsupported browsers and old browser versions. 

**Designs**
![Upgrade browser - desktop](https://user-images.githubusercontent.com/609657/78117962-96fcd800-7406-11ea-84e1-31e0e3c60167.png)
![Upgrade browser - mobile](https://user-images.githubusercontent.com/609657/78117977-9a905f00-7406-11ea-95a6-8e33b4698a2d.png)

The screen designs of the Upgrade browser page (desktop/tablet and mobile) can be viewed seen [here](https://www.figma.com/proto/TAlLGW9Kjpa5AShrknRAAy/Platform-Error-Pages?node-id=2%3A2&viewport=423%2C352%2C0.3114073872566223&scaling=min-zoom).

Note, the browser download links should open in a new tab:

1. Chrome: https://www.google.com/chrome/
2. Firefox: https://www.mozilla.org/en-US/firefox/new/
3. Safari: https://support.apple.com/en-us/HT204416
4. Opera: https://www.opera.com/download
5. Edge: https://www.microsoft.com/edge/

**Acceptance criteria**
- [x] The EDGE browser works with a light wallet
- [x] There is an error page if the user tries to log in from an old browser version that can't be supported
- [ ] The error page contains instruction on how to access the platform (newest Chrome or Firefox recommended)

**How this will be tested**
- [x] open a login link in the EDGE browser (win10)
- [ ] open a login link in any old, unsupported browser version (Firefox)

**Comment by Moejoe90** [comment]
Please use https://github.com/Modernizr/Modernizr
They seem have all the configration we need covered afaik. so less work from our side

**Comment by glupiawymowka** [comment]
when retested on stage, there is a blank page for: 
- [ ] Firefox before 52 (both mac and windows ) and from 52up we show the regular login screen
- [ ] iPhone (iOS before 10)
- [ ] Chrome before 55

![image](https://user-images.githubusercontent.com/18315589/78689967-30405880-78f7-11ea-90e3-e1184976bbd9.png)

___
works for IE, Opera (but for opera the pics are broken) 
![image](https://user-images.githubusercontent.com/18315589/78689876-17d03e00-78f7-11ea-95f9-78c784c532f5.png)
