### ISSUE TITLE
do not show "email verification box" if activation e-mail was not sent

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#422]
see image below. user schema does not contain "unverified_email" so why do you display this box?

![image.png](https://images.zenhubusercontent.com/5a72da804b5806bc2bc52ecc/3bee61c2-4dd0-40e7-8e72-17cee846fa56)

**Comment by krzkaczor** [comment]
This was fixed by @Moejoe90 by hiding verify button when email is not set. IMO makes sense. Closing...
