### ISSUE TITLE
When the user got's removed from the database app is crashing 

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#4225]
**Description**
Given that we store the wallet in the storage and refresh the token without checking if the user exists in case the user gets deleted from the database the app is crashing with an error

**Environment**

**Steps To Reproduce**
Log in as a new user
Delete the user from the backoffice
Wait until JWT token expires
Open the app

**Actual behaviour**
The app crashes

**Expected behaviour**
User is automatically recreated

**Comments, context, logs**

**Screenshots**

**Comment by desfero** [comment]
Done as a part of #4245

**Comment by glupiawymowka** [comment]
I can't really test this as we don't have any straight access to removing from the database
