### ISSUE TITLE
Provide signing modal for signing messages in Wallet Connect

### ISSUE THREAD

**Issue by AlexeyTuboltsev** [Neufund/platform-frontend#4237]
**What to do**
When there's message signer on the remote wallet (not the transaction signer) we do not display anything on the desktop. Wait 10 minutes for e-mail change permission to expire and try to change e-mail to verify
Signing process itself works - message is sent to the mobile wallet and valid signature returned

**Comment by andywalton** [comment]
This feels connected to here this #4387 where we display a modal to tell the user they need to sign via their "3rd party wallet". We could make this more dynamic and display the wallet connected. Let's talk through this @AlexeyTuboltsev when this is picked up.

**Comment by AlexeyTuboltsev** [comment]
this is being done in #4387. 
this ticket should be closed when #4387 is merged
