### ISSUE TITLE
Home view

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4242]
**Background**
The context for this ticket is to display the home view of the app. This is the default view a user will land on after creating an account and each time as they unlock the app.

This view consists of a `Top bar` with that displays the Neufund logo on the left and a QR code scanner icon button on the right.

Below this is a Portfolio summary (displaying the latest 2 portfolio items + their NEU), below this a Wallet summary (with their ETH and nEUR balances) and below this a list of investment opportunities on the platform.

> A note regarding Portfolio. Until you have your own portfolio assets ie. you have invested, the decision was made to see all available tokens on the platform. Once you have invested in an ETO, we can change this to only show your assets in the portfolio. This will therefore impact the Portfolio summary on the Home view. Please ask me @andywalton about this. 

**Designs**
<img width="1113" alt="Screenshot 2020-04-05 21 40 28" src="https://user-images.githubusercontent.com/609657/78508754-8e4f2d80-7789-11ea-93c7-c3def1deda72.png">

See Zeplin for the screen designs here in the Home section as well as in the Sign up and Log in sections: https://zpl.io/anR1n3r

The Home view has four possible states:

1. - [ ] The view is loading - https://zpl.io/aRdog6v
2. - [ ] New user - https://zpl.io/29elkpA
3. - [ ] Returning user - https://zpl.io/anR1BwY
4. - [ ] Returning user - same as 2 but the Portfolio summary has a reserved asset - https://zpl.io/ad0Dv55

- [ ] The layout of the assets components is defined under the **List items** section of the styleguide here: https://app.zeplin.io/project/5e6f48a43076c61012fd3793/styleguide/components?cseid=5e5fc696db3e1f1140b9a006
- [ ] These components have different states -> Loading, Loaded, Pressed. You can ignore the empty state.
- [ ] Note how the Portfolio and Wallet summaries are grouped differently on the home view when compared to the Portfolio / Wallet views. The padding between the items is removed on the home view and they're more tightly grouped. See here: https://zpl.io/bWErzEk & https://zpl.io/VY4yg4p

**Acceptance criteria**
- [ ] As the view loads, I see the https://zpl.io/Vqg8NBN
- [ ] As a user I can see my portfolio summary (latest 2 + NEU). It takes into account the note regarding Portfolio I highlighted above
- [ ] As a user I can see my wallet summary (ETH & nEUR)
- [ ] As a user I can see a list of ETOs
- [ ] As a first time user - I am asked to enable push notifications: https://zpl.io/bPpz0yM
- [x] As a user I can tap the QR code icon - which opens the Scan QR code flow as per #4250
- [x] As a user, I can navigate the app using the bottom TabBar menu

**Technical notes**
@desfero -> please add technical notes here.

**Testing notes**
@glupiawymowka -> Same as acceptance criteria but edit this if you want.

**Comment by andywalton** [comment]
@desfero @glupiawymowka 

After our Slack conversation I updated the ticket for the Home wallet and portfolio summary widgets.

<img width="769" alt="Screenshot 2020-04-09 16 13 38" src="https://user-images.githubusercontent.com/609657/78904647-26486200-7a7d-11ea-9ddf-597bc767ea3a.png">

**Comment by desfero** [comment]
Connecting UI to modules moved as 3 separate tickets 
https://github.com/Neufund/platform-frontend/issues/4416
https://github.com/neufund/platform-frontend/issues/4386
https://github.com/Neufund/platform-frontend/issues/4385
