### ISSUE TITLE
Portfolio view

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4247]
**Background**
The context for this ticket is to create the Portfolio view of the app.  

> A note regarding Portfolio. Until you have your own portfolio assets ie. you have invested, the decision was made to see all available tokens on the platform. Once you have invested in an ETO, we can change this to only show your assets in the portfolio. This will therefore impact the Portfolio summary on the Home view. Please ask me @andywalton about this.   

_A breakdown of this view:_
1. This view consists of a Portfolio balance in EUR at the top of the view.  
2. Below this we display each token a) the user holds or b) if no tokens are held, we display all tokens on the platform listed from New to Old. 

**Designs**
<img width="1117" alt="Screenshot 2020-04-05 18 04 12" src="https://user-images.githubusercontent.com/609657/78504362-f8a5a500-776c-11ea-9169-2a91c5b15867.png">

See Zeplin for the screen designs here: https://app.zeplin.io/project/5e6f48a43076c61012fd3793/dashboard?seid=5e89ca07e11e8db9ce300410  Individual components are available in the Design System. See the List items and TopBar components.

**Acceptance criteria**
- [ ] As a user I can see my portfolio balance (Assets held + Reserved assets + NEU tokens. Sum the EUR conversion of each)
- [ ] As the Portfolio view loads I see the loading state: https://zpl.io/VY4ygMm
- [ ] As a first time user I see my balance as 0 and a list of available tokens on the platform with 0 balances: https://zpl.io/bPpLO1M
- [ ] As a returning user with assets held, I see my actual balance and only the assets I hold or have reserved with relevant token and EUR values. Note, I will always see NEU regardless of if it has a balance or not: https://zpl.io/aMG5Xvr
- [ ] If I have reserved assets, these assets are highlighted in the Portfolio: https://zpl.io/ag0oYzR
 - [ ] As I scroll, the TopBar transitions into a fixed smaller balance: https://zpl.io/aXNZA7P
 - [ ] The Portfolio assets should be ordered from New to Old. NEU will therefore always be at the bottom.

**Technical notes**
@desfero -> please add technical notes here.

**Testing notes**
@glupiawymowka -> Same as acceptance criteria but edit this if you want.

**Comment by desfero** [comment]
Portfolio UI is already done. The new issue was created to connect UI with modules https://github.com/Neufund/platform-frontend/issues/4385
