### ISSUE TITLE
Profile view

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4249]
**Background**
The context for this ticket is to create the Profile view of the app.

_A breakdown of this view:_
1. You will see a profile avatar icon and the user name at the top of the view. 
2. Below this we will display the users wallet address.  
3. Below this we then display various user settings and options.

**Designs**
<img width="1108" alt="Screenshot 2020-04-05 19 53 33" src="https://user-images.githubusercontent.com/609657/78505984-27287d80-7777-11ea-933c-a40113a94a3f.png">

<img width="835" alt="Screenshot 2020-04-05 19 53 38" src="https://user-images.githubusercontent.com/609657/78505987-2d1e5e80-7777-11ea-9ec7-ab707b9bc250.png">

See Zeplin for the screen designs here under the Profile section: https://app.zeplin.io/project/5e6f48a43076c61012fd3793/dashboard?seid=5e6f490859bc10157745adea  

Individual components are available in the Design System. See the various components used here in the Settings section: https://app.zeplin.io/styleguide/5e5f852f2f231b17c87f8622/components?cseid=5e88bf69247263ba8100a69a

 **Acceptance criteria**
- [ ] As a user I can navigate to my Profile. https://zpl.io/V1neAYw
- [ ] As a user I will see my Wallet name at the top of this view. For MVP please always show the Wallet name for Fixture accounts and for all other accounts, we display no wallet name until the user has submitted KYC information and we know their First & Last name.
- [ ] As a user I can see my Wallet address + OPTIONAL features to 1. Tapping on that entire component and it copies this address to the users clipboard and 2. Allowing users to share this address using default device sharing capabilities, ie. you could select and share via an app of your choice like WhatsApp.
- [ ] The Account verification item simply shows my verification status. It doesn’t do anything at this stage other than display the status that is returned from our Users API.
- [ ] Account backup will show users their account recovery phrase (the Copy to clipboard is  optional) and a user can also choose to show their Private key. Doing so will simply toggle the recovery phrase text with the private key. The Show private key button will change to Hide private key. https://zpl.io/aRdoDzn
 - [ ] As a user I should be able to toggle Push notifications on and off from here (user the device rules to determine this please. Talk to @andywalton if you have questions regarding this point) - https://zpl.io/VY4yO7L
- [ ] As a user I can navigate to Neufund Web - which will show the details of any active wallet connect sessions, or if none, a message with a CTA to scan a QR code. If there is an active session, I can cancel this session. https://zpl.io/awDBKXj or https://zpl.io/2j0krWO
- [ ] Lastly, as a user I can Switch accounts, this will show a list of accounts you can switch to or decide to connect more accounts which will kick off the import accounts flow. @glupiawymowka @desfero, I've added designs for the filtering of longer lists. Tapping on the username / profile avatar of the user at the top of the view should also open this Switch accounts view. See https://zpl.io/VQ5Ejp5 & https://zpl.io/VxZlzOg & https://zpl.io/V1BlKmX

**Technical notes**
@desfero -> please add technical notes here.

**Testing notes**
@glupiawymowka -> Same as acceptance criteria but edit this if you want.

Please note: @desfero @glupiawymowka we have no concept of log out (other than in Dev mode) as a way for us to test the wallet as a new user. https://zpl.io/2ZNz7Rl

**Comment by desfero** [comment]
Basic UI was already done. Leftovers split by 3 separate tickets:
https://github.com/Neufund/platform-frontend/issues/4419
https://github.com/Neufund/platform-frontend/issues/4418
https://github.com/Neufund/platform-frontend/issues/4417
