### ISSUE TITLE
QR code scanning / WalletConnect flow

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4250]
**Background**
The context for this ticket is to create the QR code scanning views to allow the Neufund mobile app to connect the the Neufund web app via WalletConnect.

**Designs**
<img width="1080" alt="Screenshot 2020-04-05 21 54 40" src="https://user-images.githubusercontent.com/609657/78508717-4af4bf00-7789-11ea-8e43-160d234030b1.png">

See Zeplin for the screen designs here under the WalletConnect - Scan QR code section: https://app.zeplin.io/project/5e6f48a43076c61012fd3793/dashboard?seid=5e89f42aad9e6e23fcc965cb  

Individual components are available in the Design System.

It makes use of the TopBar/ModalStack component and then default system messages to ask the user to gain access to their camera, the same with the error should a QR code not be recognised.  

**Acceptance criteria**
- [x] As a user I can Scan a QR code by tapping on the `QR code icon` on the Home view in the TopBar or via `Profile > Neufund Web > Scan QR code`
- [x] The first time I try do this, a system permissions dialog will ask me to confirm access to my device camera.
- [x] If I grant permission to the app to use my camera, I will see a view that will allow me to scan a QR code.
- [x] If the QR code is valid, it will connect, a confirmation signer modal will display that will confirm what the connection is and I’ll be able to Accept or Reject this connect. 
- [x] If it doesn’t recognise a QR code, ie. it’s an invalid QR I’m trying to scan, a default device error should display this error to me.

> Note - further improvements such as error handling and the ability to paste in a QR code URL to connect without a camera will happen post MVP.

**Technical notes**
@desfero -> please add technical notes here.

**Testing notes**
@glupiawymowka -> Same as acceptance criteria but edit this if you want.

**Comment by glupiawymowka** [comment]
tested on .io
