### ISSUE TITLE
Redesign of platform has an error page

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4251]
**Background**
Our platform error page needed an refresh. 

It currently looks as follows:
![Screenshot 2020-03-31 11 12 1](https://user-images.githubusercontent.com/609657/78509395-ebe57900-778d-11ea-8ad8-e41e9db1af18.png)

This has been redesigned to fit with our recently redesigned 404 and upgrade your browser pages.

It will look as follows:
![image](https://user-images.githubusercontent.com/609657/104436911-774a3100-558e-11eb-8427-26edde615d3b.png)

**Designs**
The designs are here: https://www.figma.com/file/TAlLGW9Kjpa5AShrknRAAy/Platform-Error-Pages?node-id=241%3A657

Please ask @andywalton for access if you can't view them.

**Acceptance criteria**
- [ ] The page look as per the designs on both Desktop/Tablet and Mobile.

**Technical notes**
The page should display as per our current logic.
 
**Testing notes**
- [ ] Please test that the layout matches the design.
- [ ] UDPATED to remove the image on this page - we'll add images as the new brand visuals are released to the platform in the future.

**Comment by glupiawymowka** [comment]
@andywalton should we push this back for the sake of the branding session?

**Comment by andywalton** [comment]
@glupiawymowka I think we can go ahead with it as if anything we'll simply swap out the image.

**Comment by glupiawymowka** [comment]
tested on stage
