### ISSUE TITLE
[new onboarding] - logic and bug fixes 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4289]
**Description**

Some more time-consuming logic changes or bugs that appeared/were not fixed yet. 

## Metamask

1. Given that the user had Metamask plugin disabled while opening the platform, when the plugin gets enabled, the `Try again` button doesn't send a new MM signature request.

The current behavior from UI perspective is: `Try again` button not reacting. 
In the console:
![image](https://user-images.githubusercontent.com/18315589/79699563-88c90b80-8290-11ea-8662-4447dbfce0c1.png)
The expected behavior would be: 
- [ ] send a new signature request if the user press "try again" _(Can't be done)_
- [ ] if the above is too complicated/not possible: my suggestion is to simply refresh page by using the `try again` button. _(Shouldn't be done)_

- [x] 2. An error occurs if the signing wallet type is changed from Metamask to Ledger 
![image](https://user-images.githubusercontent.com/18315589/80472169-a8250000-8944-11ea-897b-a4d6a95a44ae.png)
- Go to login
- Select metamask
- cancel request from metamask popup
- go to sign up or select ledger nano, app crashes with 'an error occurred'

## Ledger
- [ ] there is a constantly loading icon in case the user doesn't connect Ledger
- go to login
- select ledger nano
- don't connect ledger (it loads)
- go to signup
- it keeps loading

## Account Recovery
When account is recovered, PUT/POST /user/me is done at the end of the process to send new login link to the user and in some cases to verify new email

- [x] Currently there are several cases when `new_email` is not set correctly. I’ve checked them all and **the best and only correct solution is to always set `new_email` to the e-mail user typed in the recovery form**. Backend will figure out when to send which e-mail template correctly.

- [x] When user account exists we display the screen below: both in case of verified/unverified e-mail 
This screen should be displayed **only when account does not exist and we import new account**
![image](https://user-images.githubusercontent.com/17202864/80018424-47c23880-84d6-11ea-90e4-f8e2b87095ce.png)

Please refer to designs or ask @andywalton where the correct screen is. Also @Moejoe90 says that it's already implemented and maybe a condition to display the right component was removed during conflict resolution

## Activation Link

- [x]  activation link infinite loop
 The link puts you in infinite metamask login loop (probably also ledger/lightwallet)
1. change e-mail. receive activation link below
https://localhost:9090/email-verify?code=4ff59df2-1978-4570-b36d3b563e2cad4a&email=rudolfix%40possij.pl&user_type=investor&wallet_type=browser&wallet_subtype
=metamask
2. activate e-mail
3. change e-mail again
4. you can log out or keep logged in
5. you click on the expired activation link
6. you land into endless login loop
7. the problem does not exist if there's no unverified e-mail. then expired link does not have any effect

## LightWallet Login 

- [x] BackupCodes is reset when user logs in 

- [x] Email is sent everytime the user logins

**Comment by Moejoe90** [comment]
@glupiawymowka Regarding the ledger you have to keep in mind that the timeout is 30 seconds if you wait 30 seconds you will see the error that the ledger is not available

**Comment by Moejoe90** [comment]
Regarding Metamask not available error I have removed the `try again` button when that error occurs the user must refresh manually

**Comment by glupiawymowka** [comment]
Tested on stage. 
All the light wallet accounts need recovery phrase to be done (irreversible change), but the emails are not being sent and, once done, the recovery stays saved
