### ISSUE TITLE
Keychain Storage of private keys and mnemonic phrases

### ISSUE THREAD

**Issue by huesforalice** [Neufund/platform-frontend#4292]
**Background**
As a first step to tighten security, we want to save the private key and mnemonic phrases in the iOS and Android keychains

**Designs**
Provided by operating system

**Acceptance criteria**
Secrets must be stored in the keychain vaults.

**General Notes**
This should be properly tested after wallet connect has been implemented.

**Comment by desfero** [comment]
already merge to master
