### ISSUE TITLE
Invest now button doesn't update for presale -> public sale transition 

### ISSUE THREAD

**Issue by arjunu** [Neufund/platform-frontend#4293]
**Description**
Invest now button doesn't update for presale -> public sale transition 

**Environment**
All

**Steps To Reproduce**
- Go to ETO public view
- Transition from Presale -> public sale 

**Actual behaviour**
Text stuck at "waiting for next block ..."

**Expected behaviour**
Text should change to "Ends in X days"

**Comments, context, logs**
Suspected issue with EndTimeWidget component where on finish logic is not implemented. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4038217/80091927-39b9f980-8562-11ea-9d1b-a0a5bbbe5c4f.png)

**Comment by glupiawymowka** [comment]
doesn't seem to happen anymore
