### ISSUE TITLE
[new onboarding] - inputs not reacting on iOS (mobile)| 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4305]
**Description**
As a mobile user with iPhone, I can't type in the Login/Sing in inputs. I also can't access my existing account on iPhone. 

**Env**
dev, stage

**Steps to reproduce**
There are two easy ways. You can use the real device or browserstack. Happens both on Chrome and Safari :

A. Try to access your existing account by opening an access link from the email. Try to type the password
B. Try to create a completely new account on mobile

**Actual results**
- [x] The inputs are not reacting to typing
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/57436b09-19ba-415c-95c5-5e22a023d846)
- [x] Autofill works normally
- [x] Everything works as expected on Android

**Expected results**
- [ ] The working flows (Android autofill) are not changed
- [ ] inputs work on iPhone, all browsers

**Comment by arjunu** [comment]
Note this issue exists on Safari desktop too

**Comment by glupiawymowka** [comment]
tested on mobile, stage
