### ISSUE TITLE
[recovery phrase] - error thrown for cached password 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#4326]
**Description**
Given the user just entered the password (for login or any other flow), and starts the recovery flow, then the platform is throwing an error in the signer module. 
Also, the error icon got misaligned (probably by the onboarding changes) 

**Environment**
.io (most likely also stage)

**Steps To Reproduce**
1. register with a light wallet 
2. Log out, verify your email address 
3. Instantly after you log in again, go to recovery phrase. There should be no password input, just the "confirm" button. Click it.
4. In case there was a password input already: enter it, go back, start the low again.

**Actual behavior**

![image](https://user-images.githubusercontent.com/18315589/81064108-5f87bc80-8ed9-11ea-8567-e005f20e9d0e.png)
nothing specific in the networks/console besides (allegedly not connected) 
![image](https://user-images.githubusercontent.com/18315589/81064284-b68d9180-8ed9-11ea-8834-c2d62982e447.png)

**Expected behaviour**
- [ ] error icon adjusted (always on the left of the copy)
- [ ] if the password is saved, the user can freely start the flow with just "confirm" button 

**Comments, context, logs**

**Screenshots**

**Comment by arjunu** [comment]
Error icon adjusted was fixed in another PR and is already merged.

**Comment by glupiawymowka** [comment]
tested on dev for multiple flows. 
The modal is currently always asking for password
