### ISSUE TITLE
Show investment opportunities on the home view

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#4339]
**Background**
As a user, I would like to see available investment opportunities. As for now we don't have eto logic in the shared-modules so the ticket is just for UI part. 

**Designs**
List - zpl://screen?sid=5e8a31f856d890b82c5c6c8a&pid=5e6f48a43076c61012fd3793
Web view - [zpl://screen?pid=5e6f48a43076c61012fd3793&sid=5e6f4a0996ef1f11b5e9227b](zpl://screen?pid=5e6f48a43076c61012fd3793&sid=5e6f4a0996ef1f11b5e9227b) (disregard bottom notification)

**Acceptance criteria**
- [x] Investments opportunities are done as per design 
- [x] After clicking the eto the web view appears with the eto details (from our platform web app) (without bottom notification)

**Technical notes**
I think in the long term we will inject a web provider in the webview with jwt token so you are logged in immediately and can just use an app in web view as usual.

**Comment by arjunu** [comment]
Note: the WebView will not have header and navigation controls in this ticket. It has been moved to https://github.com/Neufund/platform-frontend/issues/4354
