### ISSUE TITLE
Make platform work with Geth

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#4404]
**Background**
When adding Geth to our LB we get errors while connecting from the platform:
sentry/production/issues/13463/
sentry/production/issues/13462/

**Acceptance criteria**
Platform should work with both Parity and Geth nodes

**Testing notes**
Platform operational while both Parity and Geth are connected to LB

**Comment by Moejoe90** [comment]
After testing I found out if we use a healthy Geth node directly the application works, 
However there was an instance of a faulty node that didn't work, it was returning `0x0` on blockNumber Rpc requests. 

If there is one faulty node in the load balancer any request that will get passed through it will return invalid data
