### ISSUE TITLE
simple voting finalization

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#4422]
**Background**
Tokenholders should be able to see final result of the voting both on the token and the shareholder level. We are handling `tally` and `final` states in here
![image](https://user-images.githubusercontent.com/17202864/84645412-d2d11500-af00-11ea-9135-8e40154644b3.png)
Note that not all voting power is in the token. As long as company is not fully tokenized, there are off-chain shares that also vote. So in fact voting finalization has two stages
1. tokenholders vote in public phase, in parallel other shareholders vote off-chain.
2. when public phase ends we enter `tally` phase. at that point we know the tokenholders decision so we know how nominee that represents them will vote overall
3. `tally` phase ends when all off-chain votes are collected and added and fed back into smart contract. at that point we go into `final` phase when voting results for the whole company is known.

Another important note: voting power is expressed in tokens when we display tokenholder voting results but on the company level, voting power is expressed in share capital (where 1 unit of share capital is N tokens so conversion is easy)

**Designs**
tally state
https://app.zeplin.io/project/5e5fb4508e2ebb14273bf54d/screen/5ede097d8bad4ab89533dec3

final state
https://app.zeplin.io/project/5e5fb4508e2ebb14273bf54d/screen/5ede097e3686a3b90e86a70d

**Acceptance criteria**
* [x] display `voting ended` with absolute date
![image](https://user-images.githubusercontent.com/17202864/84646922-0ad95780-af03-11ea-8556-2343fcf35830.png)

* [x] display how nominee votes according to positive voting rule (see tech details)
![image](https://user-images.githubusercontent.com/17202864/84647062-38260580-af03-11ea-9d29-e9732832cddf.png)

* [x] display final results when in `final` state that are in share capital units. take units from ETO data (you have share capital currency there)
* [x] show "resolution has passed" or "resolution didn't pass" as per tech info below
* [x] investor/issuer can download voting finalization document
![image](https://user-images.githubusercontent.com/17202864/84647146-568c0100-af03-11ea-9b2b-e9aa3534b50b.png)

**Technical notes**
VotingCenter smart contract does not provide voting results - and this is by design! it just carries on voting procedure. Voting results should be available via `` implemented by voting initiator (if it's a smart contract) but in simple voting we do not have it. So a few things that would be taken from the observer contract, will be calculated

1. we hardcode positive voting rule for nominee which means that nominee votes yes by default. **nominee will vote no only if absolute majority of token holders votes no** so `against` > `tokenVotingPower/2`. mind that it's `gt` not `gte` relation. and use `floor` when dividing by 2
2. we show that resolution passed when `inFavor` + `offchainInFavor` > `against` + `offchainAgainst`. otherwise we show that resolution failed. (ask @andywalton for red color :D) here we simplify things by ignoring quorum and assuming that simple majority is 50%
3. final document can be obtained via `IVotingCenter::offchainVoteDocumentUri`
4. conversion from tokens to share capital:
```
sc = tokens.mul(shareNominalValueUlps).div(tokensPerShare).floor()
```
where `tokensPerShare` and `shareNominalValueUlps` you take from equity token. see `function* loadToken(` that does all you need and also has a fallback for nominal value of very old tokens.
5. mind to take share capital currency from ETO

**Testing notes**
two new voting proposals are available
`0x260336115aa587536ea0a8630c5b4cbf9da56a5a1577443beb7eb56ccfb25644` - in FINAL state with absolute majority voting NO so Nominee should vote NO. result document is available
`0x1e3943098338f486e09c2c3f2f6347c3646fe7c96da47c11b77d0c9a0b7bb880` - in TALLY state with nominee that should vote NO

see also testing notes for:
#4389 #4412

**Comment by Moejoe90** [comment]
There are two issues I have so far 

- There is no techincal detail on how to get the `Nominee` name, the temporary solution for now is to use the default word `Nominee`

- There is no clear way on how to access the ETO object with the information we have at the moment. I can't know the currency of the eto. The temporary solution is to assume that the currency is in Euros

**Comment by rudolfix** [comment]
ad 1. full nominee info is available in `company_view` endpoint.
ad 2. you need to convert the following to share capital
tokens abstained: `totalVotingPower` - `tokenVotingPower` (nominee always votes) - `offchainInFavor` - `offchainAgainst`
tokens voting yes: `offchainInFavor` + `tokenVotingPower` (only if Nominee votes yes)
tokens voting no: `offchainAgainst` + `tokenVotingPower` (only if Nominee votes yes)

formula for conversion is in technical details.
`share capital` is the all share capital of the company == `totalVotingPower` (converted to share capital currency)

**Comment by Moejoe90** [comment]
and how do you calculate the tokens if the nominee votes no?

**Comment by Moejoe90** [comment]
Based on slack 
```
tokens voting yes: `offchainInFavor` + `tokenVotingPower` (only if Nominee votes yes)
tokens voting no: `offchainAgainst` + `tokenVotingPower` (only if Nominee votes no)
```

wouldn't point `2` change to 
```
offchainInFavor + tokenVotingPower > offchainAgainst (if Nominee votes yes)
offchainInFavor > offchainAgainst + tokenVotingPower (if Nominee votes no)
```

**Comment by Moejoe90** [comment]
Answered on slack the ticket should change to 
```
offchainInFavor + tokenVotingPower > offchainAgainst (if Nominee votes yes)
offchainInFavor > offchainAgainst + tokenVotingPower (if Nominee votes no)
```

**Comment by glupiawymowka** [comment]
tested on stage
