### ISSUE TITLE
Governance General Information Page (Issuer)

### ISSUE THREAD

**Issue by arjunu** [Neufund/platform-frontend#4433]
**Background**
One part of https://github.com/neufund/platform-frontend/issues/4358

**Designs**
See epic

**Acceptance criteria**
See epic

**Comment by glupiawymowka** [comment]
tested for overall looks. Just a note for myself to check once the further PR's are done: 
- [ ] the signer modal (old one for now)
- [ ] appearance of the new voting for the investor 
- [ ] characters limit
- [ ] document upload
- [ ] points from epic description
