### ISSUE TITLE
Landing page changes

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#4439]
**Background**
We need to change the landing page to get the same content/design as the Neufund website.
We should keep the dynamic cards of the finished fundraises but remove all the coming soon cards.

Read more button should lead to:
https://blog.neufund.org/change-is-coming-8f5bcf4b2303

Newsletter sign-up should be the same as we have on the website.

**Designs**
https://www.figma.com/file/rjk3UJLvBt8c0I7zyoOJIN/Neufund_website_transition2020_landing?node-id=35%3A0

![Neufund_platform_landing_04.png](https://images.zenhubusercontent.com/5beab1a20cefa317ea424319/dc4a6513-2cd0-46d8-8391-b2637d29b069)

**Comment by glupiawymowka** [comment]
newsletter part got canceled or postponed
