### ISSUE TITLE
Wallet: Switching account from welcome screen crashes 

### ISSUE THREAD

**Issue by arjunu** [Neufund/platform-frontend#4497]
**Description**
Switching account from welcome screen crashes 

**Environment**
Wallet: Android/iOS

**Steps To Reproduce**
1. Login to wallet
2. Close app
3. Reopen app
4. In welcome screen don't unlock the app and instead go to switch account
5. Select an account and hit Connect account

**Actual behaviour**
Crash with an exception "EthManagerError: No wallet plugged, undefined"

**Expected behaviour**
Switch account works without any exceptions

**Comments, context, logs**

**Screenshots**

**Comment by ozanmanav-ng** [comment]
This is solved I guess I did not encounter such a problem right now.
