### ISSUE TITLE
Hide the redistribute button

### ISSUE THREAD

**Issue by pstroinski** [Neufund/platform-frontend#4522]
**Background**
Due to the high cost and often minimal amounts on the redistribute option we don't need this function now - it just brings the confusion to the users (they don't understand how it works)
Please hide the redistribute function.

**Designs**
![image.png](https://images.zenhubusercontent.com/5beab1a20cefa317ea424319/3c72446b-5ba5-4278-b714-04cf04738edd)
Redistribute should be hidden. Only accept should be available

**Acceptance criteria**
No redistribute button on the payout

**Testing notes**
No option to redistribute

**Comment by glupiawymowka** [comment]
tested on stage
