### ISSUE TITLE
warn if payout is less than gas cost

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#4530]
**Background**
We have high gas costs recently and often payouts that people claim are lower than the cost of gas. We need to warn & make user aware if what they do if they want to claim anyway.

**Designs**
@andywalton may provide some designs but we may just add a few lines to confirmation dialog
![image](https://user-images.githubusercontent.com/17202864/89405354-b476e100-d71b-11ea-90aa-b662be4c1f0a.png)

_Please read the acceptance criteria to better understand the designs._

Herewith some wireframes we can work from to get this ticket developed:
https://whimsical.com/57ZGFuPyzEiF5iTFxG8frE@3CRerdhrAw9Cj5YJwtqArjcx

The below shows a state where we don't show the less than 2 EUR checkbox
![Gas alert - Payout - greater than 2 EUR rule@2x](https://user-images.githubusercontent.com/609657/89904649-7aa94d00-dbe9-11ea-9438-43e2ec7d2a49.png)

This shows the possible states the payout modal can be in if the less than 2 EUR rule is triggered:
![Gas alert - Payout - less than 2 EUR rule--cta is disabled@2x](https://user-images.githubusercontent.com/609657/89904890-c0feac00-dbe9-11ea-960f-a0d756a111e0.png)

Checkbox checked = enabled Accept button
![Gas alert - Payout - less than 2 EUR rule--cta is active@2x](https://user-images.githubusercontent.com/609657/89904901-c4923300-dbe9-11ea-9b3b-d7625d9db3e2.png)

If the payout less gas costs results in a negative net total balance, please highlight this in "red". The red should be `#FF5B5B`.
![Gas alert - Payout - less than 2 EUR rule and negative balance--cta is disabled@2x](https://user-images.githubusercontent.com/609657/89904951-d4117c00-dbe9-11ea-9c0f-10986bc3bde7.png)

**Acceptance criteria**
* [x] we display gas cost of the transaction in ETH and EUR
* [x] we display total net payout (may be negative!) in EUR
* [x] if total net payout is less than 2 EUR we display the following checkbox
```
I understand that due to high gas cost on Ethereum network, transaction price I pay may be higher than the payout I will receive
```
* [x] in case checkbox is visible, confirm button is inactive

**Testing notes**
Make 2 EUR threshold easy to change so manual testing of the checkbox case is possible - if we cannot find a fixture with low payout (maybe there's one)

**Comment by andywalton** [comment]
@AlexeyTuboltsev -> this is ready for dev. Please let me know if you need anything clarified.
