### ISSUE TITLE
Add jwt to download of certain documents

### ISSUE THREAD

**Issue by huesforalice** [Neufund/platform-frontend#4550]
Downloading the documents of the following types need to have a jwt sent with the request to authorize the user:

- resolution_document
- resolution_results_document
- investment_and_shareholder_agreement
- investment_and_shareholder_agreement_preview
- signed_investment_and_shareholder_agreement

Please make sure that the e2e tests run against this branch: https://github.com/Neufund/platform-backend/pull/2712. Also make sure that all of these documents types actually can be downloaded.

**Comment by glupiawymowka** [comment]
this is tested on .io. Signed isha can't be downloaded by the investor in this environment, this might be the fixture problem. @huesforalice was investigating the issue and we should monitor it further
