### ISSUE TITLE
KYC | Larga File upload. Pls. increase the file size. 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#465]
Large files get an error on submission.

**Comment by MostafaBalata** [comment]
Hey @pstroinski this error from the outside nginx you could solve it by adding the following line into the server `client_max_body_size 20M;` you could double check maximum number from Sergie or Marcin. 

Thanx
![screen shot 2018-05-02 at 10 49 11 am](https://user-images.githubusercontent.com/1808867/39514082-850a74aa-4df6-11e8-869b-5864ef180378.png)

**Comment by pstroinski** [comment]
Already changed to 20MB. Please verify - added for backoffice app and KYC api

**Comment by MostafaBalata** [comment]
Thanks @pstroinski its working fine, I also modified the backoffice-nginx as well and every thing is ok.
