### ISSUE TITLE
Update icon to green, when KYC status is marked as accepted. 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#466]
![Screen Shot 2018-04-11 at 17.29.47.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/47dffff1-7512-4031-bf7d-0122920645aa)

<img width="1107" alt="screen shot 2018-04-11 at 17 49 30" src="https://user-images.githubusercontent.com/2290474/38628086-cfd2d690-3db0-11e8-9f26-ced0e4685cf6.png">

**Comment by krzkaczor** [comment]
We need to display errors during getting KYC status.
