### ISSUE TITLE
Handle gracefully invalid wallet-connect networks / daaps

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#4716]
**Background**
Let's see how our mobile app wallet-connect implementation works and fill bugs for cases that are not supported for some reason.

**Designs**
Not required at this stage.

**Acceptance criteria**
 - [x] **Given** I'm trying to log in to the `platform.neufund.org` **when** I scan wallet QR code on https://platform.neufund.org/wallet-connect **then** I can normally login into the app.
 - [x] **Given** i'm trying to log in to the `platform.neufund.io` **when** i scan qr code **then** i get an error about invalid ethereum chain (similar to the error you get with using metamask browser extension when it's connected to other chain)
 - [x] **Given** i'm trying to log in to the wallet-connect supported app (https://app.uniswap.org/#/swap, https://app.compound.finance/, or any other wallet listed in https://walletconnect.org/apps) **when** i scan qr code **then** i can normally login into the app.

**Technical notes**
Not required at this stage.

**Testing notes**
@KonradFilipiak it should be tested on a wallet app connected to production env (so we use eth mainned chain). You should have an invites to testfligh/google play store beta.

**Comment by andywalton** [comment]
@desfero -> just a reminder to put this into QA so we can test the various cases we might need to handle for this when trying to connect our wallet to a 3rd party Dapp. I'll move it to ready for dev with a QA flag for you.

When we publish and distribute the app on production, we need to write a test to simply ensure it's connected to the mainnet.

As a new feature, we could design and build a custom network proxy switcher that would allow our customers to connect the app to another network. For internal use, we can easily do this to allow us to test the app using our io backend via this type of network switcher toggle. Happy for this to also be an internal tool only initially.

**Comment by desfero** [comment]
@KonradFilipiak i just updated the description to match behavior we need to have
