### ISSUE TITLE
[BUG] Copyright date still says 2020

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4778]
Please update the copyright date to the correct year on the platform, currently, it still shows 2020 instead of 2021. This should dynamically change.

<img width="1440" alt="Screenshot 2021-02-03 at 12 19 04" src="https://user-images.githubusercontent.com/609657/106740871-43a57880-661b-11eb-9cbd-32f1392ae064.png">

**Comment by glupiawymowka** [comment]
tested on stage. 
The date now is connected to the user's device date and changes accordingly.
