### ISSUE TITLE
viewport goes blank when logging on nano ledge for more than 20-30 seconds

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#479]
1. chose login
2. connect nano ledger
3. select your account
4. system goes into wait for signature
5. disconnect nano ledger and wait

**Comment by banciur** [comment]
More observations:

On dev env after few seconds app goes to some broken state and only clear screen is visible.

On local when reproducing for a first time web3 disconnected toast is shown then app returns back to address selector stays there for a few seconds and returns to wallet chooser. For a second time it does same as on dev deployment
