### ISSUE TITLE
[Send tokens] Improve insufficient ETH for gas error message

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4794]
![Screenshot 2021-02-17 at 21.04.57.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/66ff5ffe-1c64-4d03-9860-a44c6dca6f90)

When a user tries to send a token as in the above example, the insufficient ETH error message leads to confusion as the user has no idea how much ETH they require to complete the transaction. To fix this, please update the wording to include the transaction cost as follows:

`You do not have enough ETH to pay the 0.005 ETH (~ 10.00 EUR) transactions costs for this transaction. Please send ETH to your Wallet and retry.`

**For testing**
Please check the wording and confirm the correct transaction cost is displayed.

**Comment by glupiawymowka** [comment]
tested on staging. 
Both calculations and the message appearance seems correct
