### ISSUE TITLE
Turning on react-native-debugger network inspect breaks the app

### ISSUE THREAD

**Issue by desfero** [Neufund/platform-frontend#4798]
**Background**
Inspecting network calls is quite useful and it for sure worked before without any problems.

At the moment when we enable `Inspect network` on `react-native-debugger` app breaks and shows an error screen.

**Comment by ozanmanav-ng** [comment]
react-native-debugger gives a error for JsonRpcProvider: 
![image](https://user-images.githubusercontent.com/82657734/115421736-e1fdaf00-a204-11eb-8e43-2808b6b6d2c1.png)

**Comment by ozanmanav-ng** [comment]
Due to React-native-debugger memory leak and network inspect problem, we decided to use flipper. Updating the React-native version allows us to use the flipper properly.
