### ISSUE TITLE
/kyc path is not locked when user didn't verify their email

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#480]
When you go to settings, you can't do kyc before verifying your email, however when you go to kyc via `/kyc` you can do kyc

**Comment by glupiawymowka** [comment]
*tested on .io*
from now on, user is being redirected  back to profile in this case

**Comment by glupiawymowka** [comment]
note: still not on stage

**Comment by glupiawymowka** [comment]
works on stage  now
