### ISSUE TITLE
confusing e-mail verification when signing in ledger

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#488]
register in ledger and go to settings. you didn't enter any e-mail yet

in that case both boxes 
![image](https://user-images.githubusercontent.com/17202864/38901786-f19f68b4-429d-11e8-9944-959bcbd4efd7.png)

and

![image](https://user-images.githubusercontent.com/17202864/38901796-f8d61c04-429d-11e8-85e3-421a1e278036.png)

are visible which is extremely confising. the top box (when no e-mail is entered, verified and unverified) should allow user to enter e-mail. it should basically force user to do it be being very visible.

lower "change e-mail" should not be visible, there is nothing to change

and stay tuned for marketing input, they want a kind step by step instruction there...

**Comment by glupiawymowka** [comment]
wording to be changed, otherwise works fine
