### ISSUE TITLE
[Mobile app] Update landing views to match latest designs

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#4882]
Please update the landing views of the mobile app to match the latest designs.

The new designs look as follows:
![image.png](https://images.zenhubusercontent.com/5c5861910b133e639c2b7056/0c4e7636-edd7-423d-a4b7-fa05fe08721e)

The carousel indicator components are here: https://zpl.io/aMovYKz

The screen designs and SVG exports for images are in Zeplin here: https://zpl.io/2GjOMvd

Note, the carousel should only move if the user swipes and it should be circular, ie. when you get to the last item it should swipe around back to the first view.

If a user clicks on the `Log in` button it should land you on the Log in options available to a user. Same for Sign up, it should allow the user to create a new Neufund account.

**Acceptance**

- [x] The views match the screen designs
- [ ] As a user I can swipe through the features carousel
- [x] The Log in and Sign up buttons work as expected

*Technical*
Nothing required.

Please ask @andywalton if you have any questions.

**Comment by KonradFilipiak** [comment]
@andywalton 

1. The carousel often stops in between the screens - it can be seen on the video and it's much easier to reproduce on a real device. 
https://images.zenhubusercontent.com/116978635/2f7d792c-0f33-4162-ae75-2045ff491f63/screen_recording_20210504_135500_neufund.mp4

2. If a user selects "Log in" on a screen with white background and then goes back, the app takes him to the first screen (with black background) and the text is still black as if it was white screen. User should be taken to the same screen where he clicked the button or the text's color should be back to white
https://images.zenhubusercontent.com/116978635/dc47d104-5db2-4858-9c95-a375d491894e/screen_recording_20210504_135900_neufund.mp4

3. Carousel is not circular as per description - `the carousel should only move if the user swipes and it should be circular, ie. when you get to the last item it should swipe around back to the first view`
