### ISSUE TITLE
ICBM Wallet upgrade flow

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#489]
The investor needs to migrate old ICBMLockedAccount to new LockedAccount that allows investing. 
It's the same wallet with only one difference that you can invetst from this wallet. Previously you could only store the escrowed value there. 

We already have upgrade button inactive.  
So here what I propose: 
1.User click upgrade wallet.
2. we show modal with info about upgrading and link to the new agreement. Clicks button Upgrade Now.
3. The user needs to sign a transaction (Metamask, Ledger, Lightwallet).
4. The new view shows ICBM wallet but not upgrade button. Or we add some icon to show that wallet is already upgraded. 
<img width="1440" alt="screen shot 2018-09-20 at 14 28 34" src="https://user-images.githubusercontent.com/2290474/45818456-15d96680-bce2-11e8-8dbd-65fb731f31be.png">

@falinebambi pls. suggest design views for this.

**Comment by krzkaczor** [comment]
We need to create whole migrate / upgrade flow with missing screens etc.

**Comment by Moejoe90** [comment]
@rudolfix 
What is the transaction that needs to be called for this upgrading? 
Is it just one transaction or a flow/processes

**Comment by falinebambi** [comment]
Just spoke with Marcin and we don't need any different designs just these signing transaction screens I just uploaded we can the rest of the transaction through the one click of that link shown on the design. Talk with Marcin if the above doesn't make sense.

**Comment by rudolfix** [comment]
what you do:
1. first you check if you have balance on new LockedAccount. if so, you are already upgraded. @falinebambi should we have any icon that we can invest from it? should we have "invest" button that leads to the current offer? we should clearly show that wallet is upgraded
2. then you check if ICBMLockedAccount (old) has a balance. if so it can be upgraded.
2a. you call `ICBMLockedAccount::currentMigrationTarget()` and if it returns valid address, "UPGRADE" button is active and can be clicked. if not it's grayed out as it is now. (method checks if migrations are at all enabled)
2b. then you make a transaction `ICBMLockedAccount::migrate()` which will migrate to (new) LockedAccount

when transaction is completed, wallet state should be reloaded

**Comment by Moejoe90** [comment]
Only thing missing is E2E tests
