### ISSUE TITLE
Login via email link doesnt work

### ISSUE THREAD

**Issue by krzkaczor** [Neufund/platform-frontend#491]

**Comment by Moejoe90** [comment]
This ended up as a backend problem frontend sends the correct salt and then the link received is wrongt example 

correct salt =`fkmqDP0KWsSZ6ZS5IFLCc95a2AtvWGw2rm2whhY3C/I=`
returned link

`https://localhost:9090/login/light?email=mohammed.elsharif@gmail.com&salt=ZmttcURQMEtXc1NaNlpTNUlGTENjOTVhMkF0dldHdzJybTJ3aGhZM0MvST0=`
