### ISSUE TITLE
Android e2e tests slow on Browserstack

### ISSUE THREAD

**Issue by arjunu** [Neufund/platform-frontend#4943]
**Description**
We need to investigate why wallet app loads slowly during e2e tests on Browserstack. No performance issues when tested manually on a real device. 

```
05-05 17:41:22.887 I/ReactNativeJS(15132): 'Retrieving secret for ref 5963', undefined
....
05-05 17:41:29.208 I/ReactNativeJS(15132): 'Added secret for ref 7385', undefined
```

For instance from device logs we see that it took 6 seconds here to retrieve secret and there was a lot garbage collection between these two.

Another example:

```
05-05 17:41:33.402 I/ReactNativeJS(15132): 'Token synced with storage', undefined
....
05-05 17:41:38.272 I/ReactNativeJS(15132): 'Resolving a balance for 0x70103B50E3c7567d6291E2aA86f28a3BF80aa41C', undefined
```

We have retries set up for the failed tests and on retries when the test passes the app seems to load quickly.

The GC statements look like
```
05-05 11:52:09.267 I/.neufund.mobil(29197): Explicit concurrent copying GC freed 50328(1899KB) AllocSpace objects, 1(20KB) LOS objects, 49% free, 4085KB/8171KB, paused 25us total 20.121ms
```

**Environment**
Android

**Steps To Reproduce**
Just run e2e tests on Browserstack

**Comment by desfero** [comment]
Fixed by disabling animations on landing screen so it doesn't wait for idle state
