### ISSUE TITLE
Update ICBM wallet view

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#497]
1. Hide call to actin in ICBM Wallets. 
2. Rename form Loked wallet to ICBM Wallet. 
<img width="1280" alt="screen shot 2018-04-20 at 10 59 43 copy" src="https://user-images.githubusercontent.com/2290474/39042178-7c80f2b6-448a-11e8-93c1-071bbf48e6de.png">

**Comment by krzkaczor** [comment]
@SergejSoft could you please verify with real data b/c we had troubles testing it. If it works move to Closed.
