### ISSUE TITLE
ETOs Status Filtr

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#499]
The filter in the Investor Dashboard and Landing page. 
To filter ETO by status. 
<img width="1280" alt="screen shot 2018-04-20 at 11 17 56" src="https://user-images.githubusercontent.com/2290474/39043000-91a038e4-448c-11e8-8af8-05f5500d86b8.png">

**Comment by desfero** [comment]
@SergejSoft we probably gonna need updated designs?

**Comment by glupiawymowka** [comment]
we stick  to this plan, but we will need some new designs
