### ISSUE TITLE
Nono Ledger Final User Test

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#501]
- [ ] https://platform.neufund.io/register/ledger. Chrome, Firefox, Safari

- [ ] https://platform.neufund.io/login/ledger Chrome, Firefox, Safari

- [ ] email sent/ text of email make sence???

- [ ] email update

- [ ] SEED Recovery.

- [ ] Migration from Nano to NeuWallet (Light wallet)

- [ ] KYC. Personal, Company each case. KYC Status.

- [ ] General comments what is not clear or not working

**Comment by banciur** [comment]
Some of points here are not relevant anymore, some I already did during fixing various ledger issues. I send one note during our submit form.
I also sent some feedback when performing my own KYC.
Regarding above I'm closing ticket as done.
