### ISSUE TITLE
KYC frontend: BUG in the issuer KYC (partnership)

### ISSUE THREAD

**Issue by huesforalice** [Neufund/platform-frontend#522]
@shanile commented on [Mon Apr 23 2018](https://github.com/Neufund/platform-backend/issues/318)

i completed the legal rep form and i cannot continue 

![image](https://user-images.githubusercontent.com/36156487/39125544-959f109e-46ff-11e8-871e-d9ef1887fa15.png)

**Comment by krzkaczor** [comment]
@shanile the problem is that form is missing question about US citizenship and we still validate it so the form is simply invalid. My question is: should I add to "Legal representative" form question about US citizenship or should I rather make it work without this question.

**Comment by shanile** [comment]
lets add this question as well
