### ISSUE TITLE
KYC IDnow verification statuses

### ISSUE THREAD

**Issue by huesforalice** [Neufund/platform-frontend#523]
@shanile commented on [Wed Apr 18 2018](https://github.com/Neufund/platform-backend/issues/293)

Im not sure who is dealing with IDnow 

we need to have some kind of different status or indication that these accounts were accepted/ rejected by ID now 

so i thought to add it that way 
Electronic verification: yes/no
Account status: accepted by ID now
Rejected by ID now + need the reason for the account was rejected based on IDnow reasons which can be find in this document https://www.idnow.de/wp-content/uploads/2017/11/IDnow_API_2017-11-13.pdf page 73 

Also if possible to re-write the resaons in simple and clear reason if yes i will create it

**Comment by krzkaczor** [comment]
@huesforalice is api returning these statuses?

**Comment by krzkaczor** [comment]
Related: https://github.com/Neufund/platform-frontend/issues/690
