### ISSUE TITLE
ETO langin login routings

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#528]
- [ ] ETO user by clicking LOGOUT need to be redirected back to ETO-landing  (now root landing)

- [x] Update email template to this. Dev: eto-welcome-login-email. ( Pls. test if it works. )

- [ ] When the user enters the **new email** and confirms. Old email remains confirmed log in with old email still works.  I think if we confirm a new email this need to be confirmed with new password and old email needs to be archived in the system.  RELEATED TO: https://github.com/Neufund/platform-frontend/pull/526

**Comment by krzkaczor** [comment]
Its fully covered by #526
