### ISSUE TITLE
SEED Restoring Neufund Wallet

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#537]
Get and error in console. Nothing happened on user side. ![Screen Shot 2018-04-25 at 13.43.48.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/9f126cc5-2f80-4f94-ba29-dbc256a59157)

**Comment by Moejoe90** [comment]
@SergejSoft  
When tested recovery was successful with a BIP30 generated from 
`https://iancoleman.io/bip39/?`
and the SEED provided by @SergejSoft
