### ISSUE TITLE
User get 500 while SEED back up

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#581]
![Screen Shot 2018-04-27 at 5.28.22 PM.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/7d634227-9a68-4c20-a008-eb4b0132b12b)

<img width="1440" alt="screen shot 2018-04-27 at 14 29 59" src="https://user-images.githubusercontent.com/2290474/39371563-5a1171e8-4a42-11e8-89e1-c5ff5fb03e19.png">

More than one user report this problem. Pls. test.

**Comment by krzkaczor** [comment]
It's gonna be covered with e2e test in: https://github.com/Neufund/platform-frontend/pull/657 For now I can't reproduce this issue.

**Comment by krzkaczor** [comment]
@glupiawymowka please just test it manually. We have now automated test that should prove that it works. You need to use real recovery phrases (ask me for details)

**Comment by glupiawymowka** [comment]
![image](https://user-images.githubusercontent.com/18315589/40039226-cae0ae76-5815-11e8-8449-85ea86d0718c.png)
chrome, production
1. select "recovery phrase"
2. go to the "The recovery phrase is crucial for the safety of your assets" screen
3. wait 30-60 sec

**Comment by krzkaczor** [comment]
@glupiawymowka is this happening AFTER providing 24 words? plese provide phrases that you used.

**Comment by krzkaczor** [comment]
By mistake I thought all the time about wallet recovery flow. 

We have another related ticket: https://github.com/Neufund/platform-frontend/issues/655
