### ISSUE TITLE
Create a different name for wallets in Register and Login

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#603]
For register
```
USE NEUFUND WALLET | CREATE NEUFUND WALLET
USE EXISTING WALLET | REGISTER WITH EXTERNAL WALLET
USE NANO LEDGER | REGISTER WITH NANO LEDGER
```
For login
```

USE NEUFUND WALLET | NEUFUND WALLET
-- | --
USE EXISTING WALLET | EXTERNAL WALLET
USE NANO LEDGER | NANO LEDGER


```

**Comment by glupiawymowka** [comment]
Login (should be without "use" each time)
![image](https://user-images.githubusercontent.com/18315589/39773470-84cec6d8-52f8-11e8-8255-496604a765cd.png)

Register (should be "create", "register with" x2)
![image](https://user-images.githubusercontent.com/18315589/39773517-ab517558-52f8-11e8-8a3c-5c85e3adc149.png)
