### ISSUE TITLE
Help on registering flow should link to support Desk

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#604]
![image](https://user-images.githubusercontent.com/23242822/39576302-ff6b66b8-4edd-11e8-96a4-5e8cc456985c.png)

**Comment by glupiawymowka** [comment]
![image](https://user-images.githubusercontent.com/18315589/39773206-9bea3a42-52f7-11e8-94f9-fca1f3b0c914.png)
"contact for help" doesn't link to support Desk
