### ISSUE TITLE
My Wallet

### ISSUE THREAD

**Issue by meneramandarin** [Neufund/platform-frontend#612]
On the platform it says MY WALLET 
<img width="200" alt="capture1" src="https://user-images.githubusercontent.com/22756141/39584784-8f29fe44-4ef3-11e8-99a2-6c749d8b7126.PNG">
there should be a little questionmark next to it over which users can hover to get more information. text for this will come once the questionmark is there

**Comment by Moejoe90** [comment]
@meneramandarin can you please provide needed text?

**Comment by Moejoe90** [comment]
This was closed by marketing plans changed
