### ISSUE TITLE
KYC wording PEP disclaimer 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#627]
Under Pep disclaimer If she/he answers “yes” then we need to tell them we will ask for more details (for PEP question)

text: You will be asked to provide more details about your situation at a later stage.

Please keep the changes in all KYC flows

**Comment by glupiawymowka** [comment]
![image](https://user-images.githubusercontent.com/18315589/39771103-521cb922-52f1-11e8-98fa-ac81f6c8270d.png)
no such information below
