### ISSUE TITLE
KYC wording income disclaimer 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#629]
Under Income Disclaimer please add the following text:

The German Federal Financial Supervisory Authority requires us to ensure that our clients invest within their means

**Comment by Moejoe90** [comment]
@shanile 
![image](https://user-images.githubusercontent.com/23242822/39710578-75589282-521d-11e8-88c6-ff4a1f3a2f09.png)
This is how it looks now

**Comment by shanile** [comment]
Its OK we can close this ticket
