### ISSUE TITLE
research metamask firefox

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#645]
@glupiawymowka commented on [Tue May 08 2018](https://github.com/Neufund/platform-backend/issues/390)

we need to check if metamask on firefox is legit and can be used to login

---

@glupiawymowka commented on [Tue May 08 2018](https://github.com/Neufund/platform-backend/issues/390#issuecomment-387378366)

https://metamask.io/
![image](https://user-images.githubusercontent.com/18315589/39755828-948fc67a-52c7-11e8-9f37-79d332f56eb4.png)
https://addons.mozilla.org/en-US/firefox/addon/ether-metamask/

---

@glupiawymowka commented on [Tue May 08 2018](https://github.com/Neufund/platform-backend/issues/390#issuecomment-387379169)

Issue moved to [Neufund/platform-frontend #643](https://github.com/Neufund/platform-frontend/issues/643) via [**ZenHub**](https://www.zenhub.com/)

**Comment by krzkaczor** [comment]
Okay it's supported on FF but it doesnt work with our app :( I am gonna close this ticket (research done) and create new one to bring support for it.
