### ISSUE TITLE
Verify your identity

### ISSUE THREAD

**Issue by meneramandarin** [Neufund/platform-frontend#648]
the link in the settings box "verify your identity" still says start KYC - can you please change it to "start the identity verification process"

**Comment by VolkSiems** [comment]
on firefox it still appears 

![kyc word](https://user-images.githubusercontent.com/38940284/39805926-9473dd28-5378-11e8-8b37-4fe1ab3e4357.png)

**Comment by Moejoe90** [comment]
@VolkSiems do you still see this?

**Comment by glupiawymowka** [comment]
looks fine for me, I'm waiting for Volker's input
