### ISSUE TITLE
Backup recovery phase 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#655]
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/a16f29ab-635b-4d88-8e99-e248414e3f9e)

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/d2479f21-0bfc-4d37-8e69-703e14d8a3ff)
staging, NEUwallet
1. don't verify your email
2. finish step 2, backup phrase
3. there still is an information that backup recovery needs to be done

**Comment by krzkaczor** [comment]
Please start with E2E test confirming the issue. 
1. Create account (there is already test that does it)
2. Go to settings
3. Assert backup recovery phrase not done
4. click backup phrase
5. finish backup flow
6. assert backup recovery done

Ofc it will fail b/c of the bug. But when test is fixed it should work.

**Comment by Moejoe90** [comment]
@glupiawymowka 
This is solved, for now, it looks into successfully backing up your codes. 
And you can test it and check with cypress as well
