### ISSUE TITLE
password not correct 

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#658]
![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/2a16c873-7535-4803-b70f-2d8a0dc06772)
this information should be more visible (maybe red?)

**Comment by glupiawymowka** [comment]
> @glupiawymowka @SergejSoft is it still an issue?


![image](https://user-images.githubusercontent.com/18315589/46293135-dee13b80-c592-11e8-8aec-a28d9ea43291.png)

this appears for maybe 1 second when the wrong password is given, so I believe it can be marked as done. Gif here to see what I meant by "appears for 1 second" [https://jmp.sh/5452oyl](url)

**Comment by desfero** [comment]
@glupiawymowka ok, so let's close it
