### ISSUE TITLE
KYC wording- Personal information disclaimer 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#671]
When client choose to go through business verification no matter if its small corporate or partnership we need to show him the personal information disclaimer as well before e start the verification process 

please add it to the beginning of the process and delete it from the beneficial owner as we have it now 

message: 
Why do we need this information?
The following information will be used to verify your identity in compliance with European Know Your Client and Anti Money Laundering policies. 

Your information is always kept confidential and needs to be stored for at least 5 years. 

By providing your information and clicking “Continue” you are consenting to your data being processed.

**Comment by meneramandarin** [comment]
Why do we need this information? The following information will be used to verify your identity in compliance with European Know Your Client and Anti Money Laundering policies. Your information is always kept confidential and needs to be stored for at least 5 years. By providing your information and clicking “Continue” you are consenting to your data being processed.

**Comment by krzkaczor** [comment]
FYI: My PR will normalize disclaimer to the same message on all flows (individual + 3 different business flows).
