### ISSUE TITLE
KYC wording - business flow PEP disclaimer 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#673]
1.PEP disclaimer needs to be changed as we are missing capital letters:

You are a Politically Exposed Person (PEP) if: 
1. You hold a prominent position or have influence, thus you’re being more susceptible to be involved in bribery or corruption,
2. You are any close business associate or family member of the former. 

2. We are missing the **?** with the explanation next to the PEP disclaimer in all business flows 

its needs to be everytime we ask for PEP confirmation: Legal rep (small business, Corp, partnership), a Beneficial owner in everyone they adding 

3.  For beneficial owner disclaimer why we answer it with plural pls change the answers to Yes, I am/ No, I am not
4. If he is a PEP pls add this: You will be asked to provide more details about your situation at a later stage
![image](https://user-images.githubusercontent.com/36156487/39819808-b189680c-53a4-11e8-989e-7b6b9f6e1cce.png)

**Comment by meneramandarin** [comment]
Please change the hover over text for Politically Exposed Person:

You are a Politically Exposed Person (PEP) if (1) you hold a prominent position or have influence, thus you’re being more susceptible to be involved in bribery or corruption, (2) you are any close business associate or family member of the former.

**Comment by Moejoe90** [comment]
1: ok
2: Not there
3: ok
@shanile can you please explain more what do you want with `For beneficial owner disclaimer why we answer it with plural pls change the answers to Yes, I am/ No, I am not` you realize that question is `this person` no `are you` do we change the question as well

**Comment by glupiawymowka** [comment]
![image](https://user-images.githubusercontent.com/18315589/40230968-ad5f1b72-5a99-11e8-801d-6c9811e74bb0.png)
this version is not correct neither, as Moe said. Simple Yes/No should be the safest option here
