### ISSUE TITLE
KYC wording- Beneficial owner 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#674]
Marlene can you pls write something we need to instruct them to complete the beneficial owner part if for those who hold more than 25% of the company share Can we add this sentence before they start putting any details on the beneficial owner 

Once you have the text Moe pls add it 

![image](https://user-images.githubusercontent.com/36156487/39820521-48b84bca-53a6-11e8-836a-1ac255de9431.png)

**Comment by meneramandarin** [comment]
Are there any beneficial owners of this company? Someone qualifies as such if they hold more than 25% of a company's shares. If there is a beneficial owner, please fill in the following details.

**Comment by meneramandarin** [comment]
Are there any beneficial owners of this company? Someone qualifies as such if they hold more than 25% of a company's shares. If there is a beneficial owner, please fill in the following details.
