### ISSUE TITLE
Final step in Manual KYC verification.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#675]
The final step has no clear indication about the process. UX Issue. 
Please  add success modal after user submits documents with the message: "We received your application and are currently processing it."                       
![Screen Shot 2018-05-11 at 11.35.49.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/957cc108-593a-41b0-a6c3-04990e9ae0f3)

**Comment by shanile** [comment]
If I can suggest here a message: Thank you for completing your identity verification process, our team will check your application and will communicate with you within 1 day. To contact support please click here, to continue deposit click here.

Of course you can change the English but in my opinion the CTA is much more clear here

**Comment by SergejSoft** [comment]
The same step is required for company verification.
https://platform.neufund.org/kyc/business/legal-representative
here how this looks like right. *so please make same success modal as in private verification. 
<img width="1408" alt="screen shot 2018-05-25 at 14 26 31" src="https://user-images.githubusercontent.com/2290474/40544196-b24a21c0-6027-11e8-94dc-798e9aafbc24.png">
