### ISSUE TITLE
Back office app. Layout

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#676]
Please move "user card" to and make Ethereum Adress not editable! View only. 

![usercar.png](https://images.zenhubusercontent.com/57dd639be40e5714b16f0753/f74926b6-0cb4-4ee3-bf82-a4c652e4488b)

**Comment by krzkaczor** [comment]
Issue moved to [Neufund/platform-backend #451](https://github.com/Neufund/platform-backend/issues/451) via [**ZenHub**](https://www.zenhub.com/)
