### ISSUE TITLE
Content management system. 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#677]
Now that we have proper string management I need to automate it so that developer time is not used for updating words and making them <stong>  etc. 
Please valuate which system is easier to integrate for English to English translation. 
or it's called Souce Copy translation.
https://localizejs.com/
https://www.transifex.com/
https://lokalise.co
https://phraseapp.com/
https://crowdin.com/

My ideal scenario: source file. Stings.EN-EN.yml in the GitHub 
and pulled by the system and is automatically synced upon changes/updates. 
The whole content management access is given to Marlene or Jeremi and they could freely change the Copy anytime they need. 
We have close to zero involvement. Only when creating a new content and updatign the source file in the proper format.

**Comment by Moejoe90** [comment]
https://phraseapp.com/ 
is chosen initially as a way to handle translations and content. 
Currently, it is using my user token to create Pull requests. 

A web hook is set with `front end`so that all changes push to master are automatically added

**Comment by Moejoe90** [comment]
- we need a yarn task to build production like build but with phraser overlay
- bot account should be making PRs to gh
- check if webhooks are working
