### ISSUE TITLE
KYC wording High Risk Countries 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#679]
Hi was decided by Jeremy to enable users to select high-risk countries but when they do show them the following message:

Unfortunately, we do not accept investors coming from those nations due to regulatory restrictions.

The high-risk countries are: 
DPRK
Ethiopia 
Iran 
Iraq 
Serbia
Sri-Lanka 
Syria
Trinidad and Tobago
Tunisia 
Vanuatu
Yemen 

Please keep this change in all flows (individual, small business, partnership and corp )

**Comment by Moejoe90** [comment]
@lizonp Is this connected with your PR?

**Comment by lizonp** [comment]
@Moejoe90 yes, it's.
