### ISSUE TITLE
back office feedback 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#684]
1. we need to be able to check only depositors investors (this was also agreed in the past with Serg) in case we will have lots of applications that we will not be able to check, we would like to give priority to depositors 

2. Need to find a way uploading docs directly from freshdesk to back office using this App  https://apps.freshdesk.com/attachment_manager/ can be at a later stage

**Comment by krzkaczor** [comment]
Issue moved to [Neufund/platform-backend #458](https://github.com/Neufund/platform-backend/issues/458) via [**ZenHub**](https://www.zenhub.com/)
