### ISSUE TITLE
Automated BROWSER login - Remove MIST - Add OPERA and GNOSIS

### ISSUE THREAD

**Issue by krzkaczor** [Neufund/platform-frontend#688]
Objectives of this ticket
1. propose automatic login/registration flow when browser (web3) wallet is detected
2. make it work on mobile in case of Opera browser
3. Remove mist wallet icon, add Opera and Gnosis

Current thinking is, @falinebambi please think it through

**on mobile**
If we can detect web3 injected we directly go to Metamask option and start login process (Opera)

**on desktop**
we do not change flow. When metamask is selected we try to connect in following order: opera, gnosis, metamask

**on both**
we display an icon of detected web3 wallet in a visible way, currently: opera, gnosis, metamask, other. will be cool to see where you are connecting to

Please read @andywalton summary below https://github.com/Neufund/platform-frontend/issues/688#issuecomment-476541603!

**Comment by banciur** [comment]
@krzkaczor 
I tried running our page inside mist browser - it is working. After I select account in mist browser that will be used for dapp I can go further in registration then person that filed this issue. 
Process stops with error about problems with servers. Error handling is not perfect in that place and I suspect cause is that we are trying to sign message with method used by metamask. That needs further investigation and running dev version in mist which might be a bit trickier.

**Comment by rudolfix** [comment]
now confirmed Mist browser does not support `eth_sign`. however we know that Opera Mobile on Android logs in as web3 browser. my proposition is to put Opera instead of Mist. it's pretty cool!

**Comment by Desperado** [comment]
Missing Acceptance Criteria and Testing Notes

**Comment by falinebambi** [comment]
![mobile opera](https://user-images.githubusercontent.com/17235402/53332507-d0a20c00-38f3-11e9-9c6b-3ca693d59e7c.png)

Design in Zeplin: 
https://app.zeplin.io/project/5a8a92c89c1a166a6a6e8f37/screen/5c73c8bb7429b21b937d14bb

**Comment by andywalton** [comment]
Okay so we met yesterday to consider possible solutions for this and agreed on doing the following:

1. We're going to first remove Mist Wallet logo and do this in the browser using the code inspector to edit the page - will supply a screengrab and a ticket explaining what needs to happen on the frontend end.

2. We're going to map out how we can better detect (listen) for web3 wallets and if we find one based on your browser type (ie. Opera with web3 wallet support) and/or Chrome MetaMask Extension existence etc. then we'll display these options to the user. This needs to go into further discovery and design. If anything, in the short term we still need to remove MetaMask and Ledger Nano from mobile browsers as they aren't currently supported - we should add a listener to display these web3 options should they exist on mobile.

3. Point 2 will be a part of our greater Onboarding improvements. This will be a separate project from the above however.

**Comment by andywalton** [comment]
Whiteboard scribbles from yesterdays meeting.

![IMG_0159](https://user-images.githubusercontent.com/609657/54986025-2f6daa80-4fb2-11e9-937b-f82c1ddeefe2.JPG)

**Comment by andywalton** [comment]
So I've looked into Point 1. of my previous comment - ie. removing Mist / Parity logo's from the MetaMask registration/log in views.

This is how we currently have it:
<img width="1392" alt="Screenshot 2019-03-28 at 13 02 40" src="https://user-images.githubusercontent.com/609657/55156561-95953180-515a-11e9-8589-6d2449c19455.png">

I'm assuming it should change to this:
<img width="1392" alt="Screenshot 2019-03-28 at 13 02 36" src="https://user-images.githubusercontent.com/609657/55156588-a47be400-515a-11e9-8435-0a0c4075e574.png">

Ie. removing the section 'MetaMask also supports'.

@falinebambi - Will you please let me know if this is what you had in mind and also if there is somewhere else we need to do this for?

**Comment by andywalton** [comment]
This ticket needs additional design before it will be ready for development.

Chatted with Kirstyn and we're going to do the following:

1. We're going to rename the MetaMask tab to read "Web3 Browser Wallet" or "Browser Wallet" and the "Ledger Nano" tab to "Hard Wallet".

2. When you click on "Browser Wallet" it will listen for a Web3 browser wallet extension or connection. If one exists it will start the signing processes for the user to connect to Neufund. If a browser wallet connection isn't found it will show an error message that recommends our supported wallets. ie. MetaMask.
3. If a user clicks on Hardwallet, they will see a screen as current that asks them to plugin their Ledger Nano or other hard wallets we support.

Lastly, this screen is getting a redesign as part of onboarding so this change now is an interim step

**Comment by andywalton** [comment]
I've added a ticket for point 1 of my previous comment: https://app.zenhub.com/workspaces/nf-platform-5a620eae4604395352a06fdb/issues/neufund/platform-frontend/2757

In regard to removing the Mist and Parity logo's from the MetaMask registration and login views.

**Comment by pstroinski** [comment]
Parity and Mist are already removed. For the Gnosis there is a different project - closing this one
