### ISSUE TITLE
Back office - automatic confirmation email 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#689]
We discussed this in the past to create auto emails that will be sent from back office once the account status changed to accept,  I think this is very crucial for now 

https://docs.google.com/spreadsheets/d/1CoV2tM4iiYheZP-_yjcmrqQ6NFUd2abJapgAGsZrfB0/edit#gid=0

I know you are busy and rest of messages can wait for now, but if possible to create an auto email for a verified account will be great

**Comment by krzkaczor** [comment]
Issue moved to [Neufund/platform-backend #457](https://github.com/Neufund/platform-backend/issues/457) via [**ZenHub**](https://www.zenhub.com/)
