### ISSUE TITLE
KYC wording: Verification status messaging 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#690]
messaging on te setting screen on verification status:

**Client passed the verfication process both IDnow and Manual:**

Today message:
![image](https://user-images.githubusercontent.com/36156487/40059078-601235c2-5853-11e8-86e9-cd9fc5cd6494.png)

**Suessted message**:
Headline: Your account is verified 
message: Thank you for completing Verification Process, your Neufund Account is now fully active. You can start investing, see Current Equity Token Offering here [link].

**IDnow failed verification** 
Today message:
“Your instant identification is being processed. You will be notified by e-mail once this is completed.”
**Sugessted message:** 
Headline: Continue your Identity Verification
message: We experienced issues with processing your application. Please, continue your instant verification here or alternatively upload your identity documents here.

**Messages for failed manual verification** 

Today message:

![image](https://user-images.githubusercontent.com/36156487/40053867-309f8d54-5843-11e8-9106-7ac61a18c0a5.png)

New message;

- Unfortunately, you have failed the identity verification process, an email with an explanation has been sent to your email address which you registered with us.

Please read the email and either reply back or upload once again the correct document.
Link to upload document + link to freshdesk to check ticket status.

I'm trying to get the failed message from IDnow as well

**Comment by meneramandarin** [comment]
"review_pending" --> "Your identity verification is still in process. We will notify you by email once we have successfully reviewed your identity."

"aborted" --> "The identity verification process has been stopped or aborted. Please follow the link to try again. Still not working? Go to our Helpdesk(LINK) to get in touch with one of our agents. 

LINK = https://neufund.freshdesk.com/support/solutions/36000112710

"other" --> "We are still reviewing the information you provided to verify your identity. You will be notified via email once we have finalized the process."

**Comment by krzkaczor** [comment]
@meneramandarin @shanile the LINK to freshdesk doesnt work. Is this supposed to be like this? (it's not yet public or something)

**Comment by meneramandarin** [comment]
i got the link from @shanile - shani can you please enlighten us about it? :)
