### ISSUE TITLE
Hide Wallet Buttons

### ISSUE THREAD

**Issue by VolkSiems** [Neufund/platform-frontend#691]
as a user i don't want to click on buttons that dont work. 

So please hide the buttons of withdraw, deposit, receive, send. 

"some of  those are active and are opening `https://platform.neufund.org/wallet/deposit/eth` but it doesnt make sense (bearbeitet)"  --> please hide anyway

**Comment by krzkaczor** [comment]
This should be hidden not disabled @lizonp
