### ISSUE TITLE
Birthday Format

### ISSUE THREAD

**Issue by VolkSiems** [Neufund/platform-frontend#692]
As a user i want to see DD MM YYYY, and then go through it without use of tab or scroll left.  

birthdate format is broke![birthdate.png](https://images.zenhubusercontent.com/5aeadce44b5806bc2bd1992d/1551b4b1-9ab4-4146-af68-f111d79145a5): too many characters for the day

**Comment by krzkaczor** [comment]
Navigating without tab is not done. Lets make separate ticket for it since it's not very important

**Comment by krzkaczor** [comment]
New ticket: https://github.com/Neufund/platform-frontend/issues/713
