### ISSUE TITLE
Back Office: Upload documents

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#694]
Need to have an option to manually upload documents from the client card. Individual Request.
Pls. make it same way we have for Business Request. 
![plus](https://user-images.githubusercontent.com/2290474/41291388-d5e48f4a-6e4f-11e8-922f-99dad0021870.png)

**Comment by krzkaczor** [comment]
Issue moved to [Neufund/platform-backend #456](https://github.com/Neufund/platform-backend/issues/456) via [**ZenHub**](https://www.zenhub.com/)
