### ISSUE TITLE
Back Office Country IP 

### ISSUE THREAD

**Issue by shanile** [Neufund/platform-frontend#720]
Please show country IP in Back Office as for now it's not showing and if possible to move it under person will be great 

![image](https://user-images.githubusercontent.com/36156487/40128446-ef46bd10-5931-11e8-83e4-76bf084ccec3.png)

**Comment by krzkaczor** [comment]
Issue moved to [Neufund/platform-backend #452](https://github.com/Neufund/platform-backend/issues/452) via [**ZenHub**](https://www.zenhub.com/)
