### ISSUE TITLE
Wording: Ledger Nano 

### ISSUE THREAD

**Issue by meneramandarin** [Neufund/platform-frontend#728]
it is "LEDGER NANO" not "NANO LEDGER"

gracias!

**Comment by VolkSiems** [comment]
Where is that?

**Comment by meneramandarin** [comment]
when you log in ? register

**Comment by Moejoe90** [comment]
@meneramandarin do i understand that you want to change where 
`NANO LEDGER` to `LEDGER NANO` its mentioned in a couple of places

**Comment by meneramandarin** [comment]
indeed. please change it wherever it pops up :)
