### ISSUE TITLE
please change "web3 disconnected" popup via info that ledger nano was disconnected

### ISSUE THREAD

**Issue by glupiawymowka** [Neufund/platform-frontend#748]
user disconnects his nano, this is what he can see

![image.png](https://images.zenhubusercontent.com/5ae1e2334b5806bc2bd0c3bb/b80ee762-551b-4049-9f1a-3a7d9c7d9e86)

**Comment by glupiawymowka** [comment]
@meneramandarin please suggest wording for this info

**Comment by meneramandarin** [comment]
Your Nano Ledger was disconnected

**Comment by meneramandarin** [comment]
For all others:
Your Browser Wallet was disconnected

**Comment by glupiawymowka** [comment]
works on dev, doesn't work on staging
