### ISSUE TITLE
Basic SEO setting

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#785]
Someone just used `https://platform.neufund.org/` on facebook. It showed crappy 401 as fb scrapped data over month ago. I used their social debbuger and rescraped data but as we are missing social tags fb preview will look empty.
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fplatform.neufund.org%2F
Pls. also look at Google Console and update basic metadata so better indexing by search engines.

**Comment by glupiawymowka** [comment]
impossible to test on stage (stage is secured with a password and will always show 401), will check with prod when deployed

**Comment by glupiawymowka** [comment]
image (logo) is not loading

![image](https://user-images.githubusercontent.com/18315589/40618155-e9d8bec4-6290-11e8-96ea-690f7974f97a.png)

**Comment by krzkaczor** [comment]
@glupiawymowka it's already deployed. Could you retest?
