### ISSUE TITLE
Deploy PhraseApp version of platform locally 

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#799]
The files for translation management is set
Deploy for marketing
@rudolfix : another domain. platform-translation.neufund.io tun task code yarn build:translate

**Comment by rudolfix** [comment]
1. make it routable to outside and behind the password
2. drop CSP headers
3. copy of original build with `yarn build:translate`
4. use different ports than original build and route in front nginx

**Comment by Moejoe90** [comment]
add ENV flag 
```
NF_TRANSLATION_ID="6c987746f39a4c910f601940bba9b912"
```

**Comment by pstroinski** [comment]
Done, released under https://platform-translate.neufund.io

**Comment by krzkaczor** [comment]
It's not working correctly:
 -  we need to switch off `content security policy` headers in nginx @Moejoe90 elaborate, please
 - i think that node env is not setup correctly b/c there is a warning in the console

**Comment by pstroinski** [comment]
content security policy removed
There is a contract address error

**Comment by Moejoe90** [comment]
Just to elaborate phraseApp injects some scripts from outside and this is why we need to disable content security for this build

**Comment by pstroinski** [comment]
After redeploy and CSP removed all is working
