### ISSUE TITLE
Update Landing Page ETOs

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#805]
Please extend existing landing page platform.neufund.org

Please build each box as a component. The order of the boxes is random, and will be uses in the future for different type of companies. (Known, coming soon, testimonials.)

 https://zpl.io/bPd3gJp

- [ ] Make sure landing page is responsive.

- [ ] Image as placeholders.

- [ ] Texts as strings with key (translation usefull)

- [ ] Links with href_blank (open in new windows on click)

**Comment by krzkaczor** [comment]
More info:
- 4th tile shows what should happen on hover (so each tile will have some quote associated)
- whole tile should be a link
- last tile is a "teaser tile" probably should be a separate component
