### ISSUE TITLE
when custom nano path is given, screen never loads

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#828]
see below, I'm on Chrome. A lot of request are made to the node but I do not see any pending. so all loaded. I'd reduce number of addresses per page. also reloading should start after a second or two of inactivity. I think you are shooting some async function and never complete them

![image](https://user-images.githubusercontent.com/17202864/40743708-99487b02-6452-11e8-8e18-eeda16fd72c3.png)

Also confirmed on neufund.platform.net so I'd say it is not node issue!

**Comment by rudolfix** [comment]
So I now need to use MEW to get paths ;/

**Comment by krzkaczor** [comment]
Might be connected with ledger path validator. Related ticket: https://github.com/Neufund/platform-frontend/issues/70

**Comment by rudolfix** [comment]
I think addresses are obtained correctly. Then we load balances. And this does not end... Library has protection against paths that are not supported (I wrote that ;>)

**Comment by rudolfix** [comment]
PING! I had it again

**Comment by rudolfix** [comment]
@SergejSoft why this thing is not closed yet??
