### ISSUE TITLE
ETO | Category Distribution Component

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#830]
Input field on ETO forms to generate Pie chart for raised capital will be used for:

I suggest: 
Product Development xx%
Marketing xx%
Operations xx%
Bug Bounty Program xx%
ESOP & Founderss xx%
Free entry field xx% - could be added with name of the field and xx%

**Comment by krzkaczor** [comment]
When you open the form there should already a dummy text for these fields (like "Product development", etc.)
