### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by meneramandarin** [Neufund/platform-frontend#902]
I need to change the copy in phraseapp for this section

<img width="154" alt="capture" src="https://user-images.githubusercontent.com/22756141/41475310-bde34e2e-70be-11e8-8efe-8b1adb15d6e2.PNG">

can you please add it in phraseapp for me?

**Comment by Moejoe90** [comment]
@meneramandarin Do you mean the Create Neunfund wallet?

**Comment by meneramandarin** [comment]
yes exactly

**Comment by meneramandarin** [comment]
as far as I can see it got already changed

**Comment by Moejoe90** [comment]
Cool then closing this
