### ISSUE TITLE
[ASAP] 20 requests to get new block are executed in one second

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#968]
This happens when app is used for some time. For example when you register with ledger and set custom path. Same with registration: every time when you load user with /get/me and you are kicked back to registration IMO new web3 is created.

Please fix it ASAP it kills nodes.

**Comment by banciur** [comment]
Some observations that might help in discovery
Visit https://platform.neufund.io/login/ledger without connected ledger. Then you can observe that two requests are being sent to `https://platform.neufund.io/nodes/private`
Both are `eth_getBlockByNumber` they always have monotonic ids without any holes
One has `["latest", true]` parameters second `["0x259c", true]`
