### ISSUE TITLE
make wallet recovery user friendly

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#970]
problem: we force user to put e-mail like new account is registered. instead please do the following

1. when you press "SEND WORDS" please check if you can recover the seed - some word combinations do not work. we should display a proper message. we should stay in the "words" screen
1. when you have a seed, login user with challenge - create and try getting user record
2. if user record is present take activated mail from it or take unverified mail if no mail is activated
3. in registration form put the e-mail from the previous step read only (like we do it on login page). if we do not have e-mail (user wallet does not exist or had no e-mail) then make it editable
4. next we follow normal login process that will create or update user account

related to: #1432

**Comment by pstroinski** [comment]
Related to #1430 #1432

**Comment by andywalton** [comment]
Closing this: It's connected to #3950 and we'll use this as technical input.
