### ISSUE TITLE
issuer dashboard - hide "complete" action links when no KYC and e-mail not verified

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#972]
You are not able to go into form edit if there is no KYC and e-mail is not verified. So disable this possibility. Now how it looks for new user
![image](https://user-images.githubusercontent.com/17202864/42182864-01af22b6-7e40-11e8-8826-e03a1d541c31.png)

**Comment by SergejSoft** [comment]
Nikola pls. test if you can reproduce this.

**Comment by glupiawymowka** [comment]
This is how it looks now. Options are grayed out, but @rudolfix is it correct that some of them say "SHOW"? 
![image](https://user-images.githubusercontent.com/18315589/47371294-d68aa500-d6e7-11e8-88aa-acdad4d50c27.png)

**Comment by rudolfix** [comment]
I have no idea why it's SHOW or COMPLETE? I think we use SHOW when given from is not longer editable after DRAFT state, may be connected to ticket #1626 in DRAFT we should always use COMPLETE everwhere

**Comment by glupiawymowka** [comment]
ok, I'll check it again when connected ticked will be done

**Comment by glupiawymowka** [comment]
6/11, staging, verification not done

 still the same. Some forms changed to COMPLETE, some of them still have SHOW
![image](https://user-images.githubusercontent.com/18315589/48081159-b1ba2580-e1ef-11e8-8ab9-5f20a943a2fb.png)

**Comment by SergejSoft** [comment]
@rudolfix @glupiawymowka We had originally idea to have show button for formst that are 100% filled. So you can still see what you have entered, therefore SHOW and not COMPLETE. 
It's a bug if you see SHOW on not completed forms. 
So the logic. (IF Form filled with required data  100%  >SHOW, else COMPLETE)
