### ISSUE TITLE
[SECURITY ISSUE] when activating e-mail in context of another logged user I land in his dashboard

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#974]
I activated via following link
`https://platform.neufund.net/email-verify?code=629a56e5-d100-42e9-9806-596008103b86&email=rudolfix%2Bissuer%40possij.pl`
However I was logged into following account `rudolfix+reco@possij.pl`:
```
address
:
"0x429123b08df32b0006fd1f3b0ef893a8993802f3"
email
:
"rudolfix+reco@possij.pl"
salt
:
"dt4g+D4qCgT33S+ldVlVROrHGWfmc5MgAZq1m5IIc50="
vault
:
"{"salt":"dt4g+D4qCgT33S+ldVlVROrHGWfmc5MgAZq1m5IIc50=","hdPathString":"m/44'/60'/0'","encSeed":{"encStr":"YmyZvFg0CfiaSC3s1wPiIo/cqHO9pFfIRXoWgn7d/6QVqIU0neYELWwNTpYvvFm0PhNrxHzR6KTwNpVrI6PCk6StGoaZzVKQrTJk1CT741cLovPbBD/d7YFrTKvdhbx6Lzrf7IU6MheZqsaSHCr1mjPLpzEBho6rOu4CQIEMCPflkISYvhWIi97Qjvs8QUNAVyozvx+rBXINp06gIk3DAxG8IcCM92yg85AAv9ffXJ4JQY7caYDHVI9Ea+onigTX97Cs66F2KYHFHC9gsBHkVi8lMUb+J5YCD0zsWdeY+YOSrnjlZyLuZTUOLs3wudb6UkWIGWgZGkTo3utCnHg10A==","nonce":"8JDNnPyPesT5/De++9EM3gPg5OPIgm6t"},"encHdRootPriv":{"encStr":"lug0XEWPBIS2tDDH++msa4XDZ94HMNNcYGBDHuZ/Za+/8/Aj2NrHpKIcbylmLLydFFvv/RIipWCdaW3jhSQajkIktlBjVTihngbco+8VKolB2y6Vca1STqbdphNGxjOcTkg26Mu/jhsWUA06eQ37EMW4U2YPaULiYEmPBxkfdA==","nonce":"a1Vtsubm7DXjqMkRTSg6+xsD1PqKHEso"},"version":3,"hdIndex":1,"encPrivKeys":{"429123b08df32b0006fd1f3b0ef893a8993802f3":{"key":"oAvUeJ+YdHcuEa/1qZlKh7SRAFRASKK0hFNin4AepzWAxRa77elx+osY5pPB5Say","nonce":"YVP+ONi6YYkSy/O5fC/ocPGQjOrzv85N"}},"addresses":["429123b08df32b0006fd1f3b0ef893a8993802f3"]}"
walletType
:
"LIGHT"
```
I clicked in the activation link
Now I still see this account dashboard, instead of activated user dashboard.

**rudolfix+issuer@possij.pl e-mail was not activated**

Steps to reproduce
1. login into account 1
2. close tab
3. click activation link of user 2
4. you are in user 1 dashboard

Fix:
when in route for e-mail activation or login via login link, first erase state as in logout!
OR
if there is login context and you try to activate e-mail from other account say that you should log out first. the same for clicking on login link

**Comment by glupiawymowka** [comment]
*tested on .net*

1. user 1 is correctly logged out
2. User 2 can login by entering a password as his correct email is pre-entered already 

overall the issue is fixed correctly
