### ISSUE TITLE
[SECURITY ISSUE] when logged out and clicking on activation/login link app tries me to log me in into incorrect account

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#975]
1. I click following link belonging to "rudolfix+issuer@neufund.org"
```
```
2. I was previously logged into "rudolfix+reco@neufund.org" and I logged out before clicking
3. I'm forced into logging into wrong account as below
![image](https://user-images.githubusercontent.com/17202864/42183834-916b0ae8-7e43-11e8-9db5-46482fda34e7.png)
btw. rudolfix+issuer has a ledger nano so full confusion!

4. I log in and of course e-mail was not activated

**Comment by Moejoe90** [comment]
@rudolfix 
I tried doing this pr and couldn't reproduce it. 
I will add an E2E test that covers this case

**Comment by Moejoe90** [comment]
@glupiawymowka I moved this to QA 
If you are able to reproduce this bug then please ping me

**Comment by glupiawymowka** [comment]
couldn't reproduce it so far. 
Will be reopened if this happens again
