### ISSUE TITLE
read wallet type from e-mail activation link and set specific wallet type on login

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#976]
I registered with nano, try to verify e-mail
Click on the link and go to login page **of light wallet**. this is super confusing.
we'll add "wallet_type" query parameter to login link from which you can take wallet type
then please set correct tab!

here is backend issue that needs to be solved Neufund/platform-backend/ issue 697

**Comment by rudolfix** [comment]
so we are already sending this in the e-mails. when this is done we can finally do it
https://github.com/Neufund/platform-frontend/issues/1049

**Comment by rudolfix** [comment]
BUMP! why it's not fixed yet? super easy to do now

**Comment by Moejoe90** [comment]
@rudolfix 
I can't do this ticket because i'm not getting the wallet type in the login link i'm only getting it in the activation link
![image](https://user-images.githubusercontent.com/23242822/46817323-30ea4400-cd7f-11e8-86ec-d7c3f6b57cbc.png)
