### ISSUE TITLE
Backoffice - exporting verification reports

### ISSUE THREAD

**Issue by kelexa** [Neufund/platform-frontend#984]
Hey, 

We are missing the option to export KYC verification reports.
We need the users' ETH addresses in order to get an AML report, and also all the information on each customers' file in case of an audit.

![verificationreport1](https://user-images.githubusercontent.com/40295416/42223912-2efa4248-7ed9-11e8-825d-ab9bd75c9c3a.jpg)

And should be exported as a list on an file like this:

![verificationreport2](https://user-images.githubusercontent.com/40295416/42224147-ac489c7c-7ed9-11e8-88cf-0bf7954b5c2f.jpg)

Thanks.

**Comment by kelexa** [comment]
https://docs.google.com/spreadsheets/d/10EHsEpxoO0-3nWRsCZwWqxYvScD9YaBKsoPCiORvuRo/edit?usp=sharing this is the report template, report should have all this information. thanks.

**Comment by SergejSoft** [comment]
@shanile pls. check if this is done. if done, pls. close.

**Comment by kelexa** [comment]
issue solved
